/*
 * Function: Exception_AudioBufferCleanup
 * Address: 004a9e95
 * Category: audio
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void Exception_AudioBufferCleanup(void)

{
  int *piVar1;
  void *this;
  int unaff_EBP;
  int *piVar2;
  
  piVar2 = *(int **)(unaff_EBP + -0x18);
  piVar1 = *(int **)(unaff_EBP + 0xc);
  if (piVar2 != piVar1) {
    this = *(void **)(unaff_EBP + -0x14);
    do {
      STL_Map_EraseNode(this,(uint *)(unaff_EBP + 0xc),*(uint **)(*(int *)(unaff_EBP + 8) + 4));
      piVar2 = (int *)*piVar2;
    } while (piVar2 != piVar1);
  }
  CRuntime_CxxThrowException(0,0);
  ExceptionList = *(void **)(unaff_EBP + -0xc);
  return;
}


