/*
 * Function: Music_SetPosition
 * Address: 004a1210
 * Category: audio
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __thiscall Music_SetPosition(void *this,undefined4 *param_1,undefined4 *param_2)

{
  char cVar1;
  undefined4 *puVar2;
  int iVar3;
  undefined4 *puVar4;
  undefined4 *puVar5;
  bool local_c;
  undefined4 *local_8;
  
  puVar4 = (undefined4 *)(*(undefined4 **)((int)this + 4))[1];
  cVar1 = *(char *)((int)puVar4 + 0x41);
  local_c = true;
  puVar2 = *(undefined4 **)((int)this + 4);
  while (cVar1 == '\0') {
    iVar3 = Debug_LogMessage((int)param_2,(char)*param_2);
    local_c = iVar3 < 0;
    if (local_c) {
      puVar5 = (undefined4 *)*puVar4;
    }
    else {
      puVar5 = (undefined4 *)puVar4[2];
    }
    puVar2 = puVar4;
    puVar4 = puVar5;
    cVar1 = *(char *)((int)puVar5 + 0x41);
  }
  local_8 = puVar2;
  if (local_c) {
    if (puVar2 == (undefined4 *)**(int **)((int)this + 4)) {
      puVar4 = (undefined4 *)Image_DrawLine(this,&param_2,'\x01',puVar2,param_2);
      *param_1 = *puVar4;
      *(undefined1 *)(param_1 + 1) = 1;
      return;
    }
    Vector_Subtract((int *)&local_8);
  }
  puVar4 = local_8;
  iVar3 = Debug_LogMessage(local_8[4],(char)param_2);
  if (iVar3 < 0) {
    puVar4 = (undefined4 *)Image_DrawLine(this,&param_2,local_c,puVar2,param_2);
    *param_1 = *puVar4;
    *(undefined1 *)(param_1 + 1) = 1;
    return;
  }
  *param_1 = puVar4;
  *(undefined1 *)(param_1 + 1) = 0;
  return;
}


