/*
 * Function: Boss_ProcessWreckerWarWrecker
 * Address: 004312e0
 * Category: bosses
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall Boss_ProcessWreckerWarWrecker(int param_1)

{
  int iVar1;
  
  iVar1 = *(int *)(param_1 + 0x34) + -0x18;
  *(int *)(param_1 + 0x34) = iVar1;
  if (iVar1 < 0) {
    *(undefined4 *)(param_1 + 0x34) = 0;
  }
  return;
}


