/*
 * Function: Boss_BattleshipCannonSystem
 * Address: 00431630
 * Category: bosses
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall Boss_BattleshipCannonSystem(int param_1)

{
  Boss_ProcessFinalSecretWeapon((void *)(*(int *)(param_1 + 0x4c) + 500),*(int **)(param_1 + 0x68));
  return;
}


