/*
 * Function: Boss_ProcessHelicopterAttack
 * Address: 00405940
 * Category: bosses
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __thiscall
Boss_ProcessHelicopterAttack(void *this,undefined4 *param_1,uint param_2,undefined4 *param_3)

{
  undefined4 *puVar1;
  undefined4 uVar2;
  int iVar3;
  uint uVar4;
  int extraout_ECX;
  uint uVar5;
  undefined4 *unaff_ESI;
  undefined4 *unaff_EDI;
  undefined4 *puVar6;
  uint unaff_retaddr;
  undefined4 local_34 [7];
  uint local_18;
  undefined1 *local_14;
  void *local_10;
  undefined *puStack_c;
  undefined4 local_8;
  
  local_8 = 0xffffffff;
  puStack_c = &DAT_0050f760;
  local_10 = ExceptionList;
  local_18 = DAT_00569f5c ^ unaff_retaddr;
  local_14 = &stack0xffffffc0;
  puVar1 = param_3;
  puVar6 = local_34;
  for (iVar3 = 7; iVar3 != 0; iVar3 = iVar3 + -1) {
    *puVar6 = *puVar1;
    puVar1 = puVar1 + 1;
    puVar6 = puVar6 + 1;
  }
  iVar3 = *(int *)((int)this + 4);
  if (iVar3 == 0) {
    uVar4 = 0;
  }
  else {
    uVar4 = (*(int *)((int)this + 0xc) - iVar3) / 0x1c;
  }
  if (param_2 != 0) {
    if (iVar3 == 0) {
      iVar3 = 0;
    }
    else {
      iVar3 = (*(int *)((int)this + 8) - *(int *)((int)this + 4)) / 0x1c;
    }
    if (0x9249249U - iVar3 < param_2) {
      ExceptionList = &local_10;
      local_14 = &stack0xffffffc0;
      Level_InitializeVodkavania();
    }
    else {
      if (*(int *)((int)this + 4) == 0) {
        iVar3 = 0;
      }
      else {
        iVar3 = (*(int *)((int)this + 8) - *(int *)((int)this + 4)) / 0x1c;
      }
      if (uVar4 < iVar3 + param_2) {
        if (0x9249249 - (uVar4 >> 1) < uVar4) {
          uVar4 = 0;
        }
        else {
          uVar4 = uVar4 + (uVar4 >> 1);
        }
        if (*(int *)((int)this + 4) == 0) {
          iVar3 = 0;
        }
        else {
          iVar3 = (*(int *)((int)this + 8) - *(int *)((int)this + 4)) / 0x1c;
        }
        ExceptionList = &local_10;
        local_14 = &stack0xffffffc0;
        if (uVar4 < iVar3 + param_2) {
          ExceptionList = &local_10;
          local_14 = &stack0xffffffc0;
          iVar3 = Vector_Size_28ByteObjects((int)this);
          uVar4 = iVar3 + param_2;
        }
        param_3 = (undefined4 *)operator_new(uVar4 * 0x1c);
        local_8 = 0;
        puVar1 = (undefined4 *)
                 MemoryCopy_Forward_28ByteObjects(*(undefined4 **)((int)this + 4),param_1,param_3);
        Vector_Destructor_4ByteObjects(puVar1,param_2,local_34);
        MemoryCopy_Forward_28ByteObjects
                  (param_1,*(undefined4 **)((int)this + 8),puVar1 + param_2 * 7);
        if (*(int *)((int)this + 4) == 0) {
          uVar5 = 0;
          iVar3 = extraout_ECX;
        }
        else {
          iVar3 = *(int *)((int)this + 8) - *(int *)((int)this + 4);
          uVar5 = iVar3 / 0x1c;
        }
        if (*(int *)((int)this + 4) != 0) {
                    /* WARNING: Subroutine does not return */
          System_ShutdownHandler(iVar3,uVar5);
        }
        *(undefined4 **)((int)this + 0xc) = param_3 + uVar4 * 7;
        *(undefined4 **)((int)this + 4) = param_3;
        *(undefined4 **)((int)this + 8) = param_3 + (param_2 + uVar5) * 7;
      }
      else {
        param_3 = *(undefined4 **)((int)this + 8);
        if ((uint)(((int)param_3 - (int)param_1) / 0x1c) < param_2) {
          ExceptionList = &local_10;
          puVar1 = param_3;
          param_3 = (undefined4 *)&stack0xffffffb4;
          local_14 = &stack0xffffffc0;
          Weapon_UpdateCooldown(param_1,puVar1,param_1 + param_2 * 7);
          local_8 = 2;
          Enemy_ProcessTruckLogic
                    (*(undefined4 **)((int)this + 8),
                     param_2 - (*(int *)((int)this + 8) - (int)param_1) / 0x1c,local_34);
          iVar3 = *(int *)((int)this + 8) + param_2 * 0x1c;
          *(int *)((int)this + 8) = iVar3;
          puVar1 = (undefined4 *)(iVar3 + param_2 * -0x1c);
        }
        else {
          puVar6 = param_3 + param_2 * -7;
          ExceptionList = &local_10;
          local_14 = &stack0xffffffc0;
          uVar2 = Weapon_UpdateCooldown(puVar6,param_3,param_3);
          puVar1 = param_3;
          *(undefined4 *)((int)this + 8) = uVar2;
          param_3 = (undefined4 *)&stack0xffffffb4;
          MemoryCopy_Backward_28ByteObjects_Wrapper(&param_3,param_1,puVar6,puVar1);
          param_3 = (undefined4 *)&stack0xffffffb8;
          puVar1 = param_1 + param_2 * 7;
        }
        MemoryFill_28ByteObjects(param_1,puVar1,local_34);
      }
    }
  }
  ExceptionList = local_10;
  Exception_SetMessage((void *)(local_18 ^ unaff_retaddr),unaff_EDI,unaff_ESI);
  return;
}


