/*
 * Function: Collision_FindMTV
 * Address: 00498910
 * Category: physics
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall Collision_FindMTV(int param_1,uint param_2)

{
  if (0xf < *(uint *)(param_1 + 0x2c)) {
                    /* WARNING: Subroutine does not return */
    System_ShutdownHandler(param_1,param_2);
  }
  *(undefined4 *)(param_1 + 0x2c) = 0xf;
  *(undefined4 *)(param_1 + 0x28) = 0;
  *(undefined1 *)(param_1 + 0x18) = 0;
  return;
}


