/*
 * Function: Physics_ProcessFriction
 * Address: 004120b0
 * Category: physics
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


uint __fastcall Physics_ProcessFriction(int *param_1)

{
  int iVar1;
  byte *pbVar2;
  
  iVar1 = (**(code **)(*param_1 + 0x10))();
  if (iVar1 == -1) {
    return 0xffffffff;
  }
  pbVar2 = (byte *)Physics_ProcessBouncing((int)param_1);
  return (uint)*pbVar2;
}


