/*
 * Function: Survival_HandlePlayerCollisionWithMarker
 * Address: 00432930
 * Category: physics
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __fastcall Survival_HandlePlayerCollisionWithMarker(int param_1)

{
  double dVar1;
  int *piVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  int iVar6;
  int iVar7;
  undefined4 uVar8;
  int iVar9;
  uint uVar10;
  ulonglong uVar11;
  int iVar12;
  char cVar13;
  int iVar14;
  char cVar15;
  char cVar16;
  
  Boss_ProcessWreckerWarWrecker(param_1);
  iVar3 = Boss_ProcessApeKommieKong(param_1);
  if ((*(double *)(param_1 + 8) < (double)(-0x140 - iVar3 / 2)) ||
     (iVar3 = Boss_ProcessApeKommieKong(param_1), dVar1 = (double)(iVar3 / 2 + 0x140),
     dVar1 < *(double *)(param_1 + 8) != (NAN(dVar1) || NAN(*(double *)(param_1 + 8)))))
  goto LAB_00432c07;
  if (_DAT_0052a0c0 < *(double *)(param_1 + 0x28)) {
    dVar1 = *(double *)(param_1 + 0x28) + _DAT_0052c590;
    *(double *)(param_1 + 0x28) = dVar1;
    if (_DAT_005302e0 < dVar1) {
      *(undefined4 *)(param_1 + 0x28) = 0;
      *(undefined4 *)(param_1 + 0x2c) = 0x401c0000;
    }
    *(double *)(param_1 + 0x18) =
         (_DAT_005302e0 - *(double *)(param_1 + 0x28)) * _DAT_005302d8 *
         (double)(int)((uint)*(byte *)(param_1 + 0x30) * -2 + 1);
    *(double *)(param_1 + 0x20) = *(double *)(param_1 + 0x28) * _DAT_005302d8;
  }
  if (((NAN(*(double *)(param_1 + 0x28)) || NAN(_DAT_0052a0c0)) !=
       (*(double *)(param_1 + 0x28) == _DAT_0052a0c0)) &&
     (uVar11 = Math_FloatToUInt64(), uVar10 = (int)(uint)uVar11 >> 0x1f,
     (int)(((uint)uVar11 ^ uVar10) - uVar10) < 0x5a)) {
    *(double *)(param_1 + 0x28) = *(double *)(param_1 + 0x28) + _DAT_0052c590;
  }
  iVar3 = Boss_ProcessEyebot(param_1);
  dVar1 = (double)(0x1d6 - iVar3 / 2);
  if (dVar1 < *(double *)(param_1 + 0x10) == (NAN(dVar1) || NAN(*(double *)(param_1 + 0x10)))) {
    iVar3 = *(int *)(param_1 + 0x4c);
    if ((*(int *)(iVar3 + 0x80) == 0) &&
       ((*(int *)(*(int *)(param_1 + 0x50) + 0x96c) != 0 ||
        (_DAT_0052a0c0 < *(double *)(iVar3 + 0x148))))) {
      cVar16 = '\x01';
      cVar15 = '\0';
      iVar14 = 0;
      uVar11 = Math_FloatToUInt64();
      iVar4 = (int)uVar11;
      iVar9 = *(int *)(iVar3 + 0x98) + 2;
      uVar11 = Math_FloatToUInt64();
      iVar5 = (int)uVar11;
      cVar13 = *(char *)(param_1 + 0x30);
      iVar3 = *(int *)(*(int *)(iVar3 + 0x5c) + 0x708);
      iVar12 = 0;
      uVar11 = Math_FloatToUInt64();
      iVar6 = (int)uVar11;
      uVar11 = Math_FloatToUInt64();
      iVar7 = (int)uVar11;
      uVar11 = Math_FloatToUInt64();
      uVar8 = Collision_PixelPerfectDetection
                        (*(void **)(param_1 + 0x60),(int)uVar11,iVar7,iVar6,iVar12,cVar13,iVar3,
                         iVar5,iVar9,iVar4,iVar14,cVar15,cVar16);
      if ((char)uVar8 != '\0') {
        dVar1 = *(double *)(*(int *)(param_1 + 0x4c) + 0x148);
        if (dVar1 < _DAT_0052a0c0 != (dVar1 == _DAT_0052a0c0)) {
          iVar3 = *(int *)(*(int *)(param_1 + 0x4c) + 0x5c);
          *(int *)(iVar3 + 0x96c) = *(int *)(iVar3 + 0x96c) + -1;
          piVar2 = *(int **)(*(int *)(param_1 + 0x4c) + 0x5c);
          if (piVar2[0x25b] == 0) {
            iVar3 = *piVar2;
            uVar11 = Math_FloatToUInt64();
            (**(code **)(iVar3 + 0xb8))(0x59,(int)uVar11);
          }
          iVar3 = *(int *)(param_1 + 0x4c);
          *(undefined4 *)(iVar3 + 0x148) = 0;
          *(undefined4 *)(iVar3 + 0x14c) = 0x40220000;
          iVar3 = **(int **)(*(int *)(param_1 + 0x4c) + 0x5c);
          uVar11 = Math_FloatToUInt64();
          (**(code **)(iVar3 + 0xb8))(0xe,(int)uVar11);
        }
        goto LAB_00432c00;
      }
    }
    iVar3 = *(int *)(param_1 + 0x4c);
    if (*(int *)(iVar3 + 0x80) != 0) {
      return;
    }
    cVar16 = '\x01';
    cVar15 = '\0';
    iVar14 = 0;
    uVar11 = Math_FloatToUInt64();
    iVar5 = (int)uVar11;
    iVar4 = *(int *)(iVar3 + 0x98);
    uVar11 = Math_FloatToUInt64();
    iVar6 = (int)uVar11;
    cVar13 = *(char *)(param_1 + 0x30);
    iVar3 = *(int *)(*(int *)(iVar3 + 0x5c) + 0x6cc);
    iVar12 = 0;
    uVar11 = Math_FloatToUInt64();
    iVar7 = (int)uVar11;
    uVar11 = Math_FloatToUInt64();
    iVar9 = (int)uVar11;
    uVar11 = Math_FloatToUInt64();
    uVar8 = Collision_PixelPerfectDetection
                      (*(void **)(param_1 + 0x60),(int)uVar11,iVar9,iVar7,iVar12,cVar13,iVar3,iVar6,
                       iVar4,iVar5,iVar14,cVar15,cVar16);
    if ((char)uVar8 == '\0') {
      return;
    }
    Particles_UpdateFire(*(void **)(param_1 + 0x4c));
  }
  else {
    *(undefined4 *)(param_1 + 0x20) = 0;
    *(undefined4 *)(param_1 + 0x24) = 0;
    iVar3 = 0;
    uVar11 = Math_FloatToUInt64();
    Enemy_SpawnWaves(*(void **)(param_1 + 0x4c),(int)uVar11,iVar3);
  }
LAB_00432c00:
  Boss_ProcessRobotXBot(param_1);
LAB_00432c07:
  Boss_BattleshipCannonSystem(param_1);
  return;
}


