/*
 * Function: Assembly_ComplexLoopingStructure
 * Address: 00501e20
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Instruction at (ram,0x00501f34) overlaps instruction at (ram,0x00501f32)
    */
/* WARNING: Unable to track spacebase fully for stack */
/* WARNING: Removing unreachable block (ram,0x00501f35) */
/* WARNING: Removing unreachable block (ram,0x00501f3c) */
/* WARNING: Removing unreachable block (ram,0x00501f3f) */
/* WARNING: Removing unreachable block (ram,0x00501f44) */
/* WARNING: Removing unreachable block (ram,0x00501f47) */
/* WARNING: Removing unreachable block (ram,0x00501f66) */
/* WARNING: Removing unreachable block (ram,0x00501f34) */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined8 __fastcall Assembly_ComplexLoopingStructure(undefined4 param_1)

{
  uint uVar1;
  bool bVar2;
  bool bVar3;
  longlong lVar4;
  uint *puVar5;
  ulonglong uVar6;
  int iVar7;
  undefined1 uVar8;
  byte bVar9;
  byte bVar10;
  undefined4 in_EAX;
  int iVar13;
  int iVar15;
  undefined3 uVar17;
  uint uVar16;
  int iVar18;
  uint uVar19;
  uint extraout_ECX;
  int *piVar20;
  int iVar21;
  undefined4 unaff_EBX;
  int *piVar22;
  int *piVar23;
  undefined4 *puVar24;
  int unaff_EBP;
  undefined4 *puVar27;
  byte *unaff_ESI;
  byte *pbVar28;
  undefined1 *unaff_EDI;
  undefined1 *puVar29;
  byte *pbVar30;
  byte *pbVar31;
  byte *pbVar32;
  undefined2 in_CS;
  byte in_AF;
  byte bVar33;
  byte bVar34;
  byte in_TF;
  byte bVar35;
  bool in_OF;
  byte in_NT;
  byte in_AC;
  byte in_VIF;
  byte in_VIP;
  byte in_ID;
  ulonglong uVar36;
  char cVar11;
  undefined4 uVar12;
  uint uVar14;
  undefined4 *puVar25;
  undefined4 *puVar26;
  
  if (!in_OF) {
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  }
  piVar20 = (int *)&DAT_b220ccac;
  puVar29 = unaff_EDI + -1;
  uVar8 = in(0xce);
  uVar12 = CONCAT31((int3)((uint)in_EAX >> 8),uVar8);
  if (CONCAT22((short)((uint)param_1 >> 0x10),CONCAT11(0x37,(char)param_1)) != 0) {
    return CONCAT44(0xb220e4ac,puVar29);
  }
  bVar35 = 1;
  iVar18 = 0;
  if (puVar29 != (undefined1 *)0x0) {
    iVar13 = in(0xccac);
    unaff_EBP = 0x5f3be6ec;
    uVar8 = in(0xccac);
    *puVar29 = uVar8;
    iVar18 = iVar13 + -1;
    if (iVar18 == 0) {
      if (iVar13 != 2) {
        return 0xb220ccac00000000;
      }
      unaff_EDI = unaff_EDI + -1;
      iVar18 = 0;
    }
    uVar12 = 0;
    puVar29 = unaff_EDI;
  }
  bVar33 = 9 < ((byte)uVar12 & 0xf) | in_AF;
  uVar19 = CONCAT31((int3)((uint)uVar12 >> 8),(byte)uVar12 + bVar33 * '\x06') & 0xffffff0f;
  pbVar30 = (byte *)((uint)puVar29 ^ 0xb220ccac);
  bVar9 = (char)uVar19 + ((char)((uint)uVar12 >> 8) + bVar33) * -3;
  uVar14 = CONCAT22((short)(uVar19 >> 0x10),(ushort)bVar9);
  iVar13 = CONCAT22((short)((uint)unaff_EBX >> 0x10),CONCAT11(0xca,(char)unaff_EBX));
  puVar29 = (undefined1 *)(uVar14 - 0x2a);
  *(byte **)(uVar14 - 0x2a) = unaff_ESI;
  uVar19 = iVar18 - 1;
  if (uVar19 == 0 || (bVar9 & 0x1a) == 0) {
    *(char *)(unaff_EBP + 0x6e) = *(char *)(unaff_EBP + 0x6e) + (char)(uVar19 >> 8);
    uVar8 = *(int *)(uVar14 + 0x22) < 0;
    if (!(bool)uVar8) {
      return CONCAT44(&DAT_b220ccac,uVar14);
    }
    do {
      *(undefined2 *)(puVar29 + -4) = in_CS;
      in_CS = 0xfc35;
      *(undefined4 *)(puVar29 + -8) = 0x501eb6;
      uVar36 = func_0x40f6f6b1();
      puVar29 = (undefined1 *)uVar36;
      out(0xef,(char)uVar36);
    } while (!(bool)uVar8);
    lVar4 = (longlong)*(int *)((int)(uVar36 >> 0x20) + -0x52) * -0x7e;
    piVar22 = (int *)lVar4;
    iVar13 = *piVar22;
    piVar23 = piVar22 + 1;
    uVar19 = extraout_ECX;
    if (*(char *)(extraout_ECX - 0x1b) == -0x36 ||
        ((int)piVar22 != lVar4) != (char)(*(char *)(extraout_ECX - 0x1b) + '6') < '\0') {
      bRambf71a7bd = bRambf71a7bd & 199;
                    /* WARNING: Bad instruction - Truncating control flow here */
      halt_baddata();
    }
    do {
      do {
        uVar6 = uVar36;
        bVar34 = bVar33;
        pbVar32 = pbVar30;
        iVar7 = _DAT_89097ad6;
        iVar21 = (int)(uVar6 >> 0x20);
        pbVar30 = pbVar32 + 4;
        iVar13 = CONCAT22((short)((uint)iVar13 >> 0x10),CONCAT11(0x65,(char)iVar13));
        iVar15 = (uint)uVar6 + 0xfb13c7b;
        piVar20 = (int *)(iVar21 + -0x3664e580);
        bVar9 = (byte)uVar19 & 0x1f;
        iVar18 = *piVar20;
        *piVar20 = *piVar20 >> bVar9;
        bVar2 = (uVar19 & 0x1f) != 0;
        bVar10 = (byte)iVar15;
        bVar3 = 9 < (bVar10 & 0xf);
        bVar33 = bVar3 | bVar34;
        uVar17 = (undefined3)((uint)iVar15 >> 8);
        bVar10 = bVar10 + bVar33 * '\x06';
        cVar11 = bVar10 + (0x90 < (bVar10 & 0xf0) |
                          (!bVar2 && (uint)uVar6 < 0xf04ec385 ||
                          bVar2 && (iVar18 >> bVar9 - 1 & 1U) != 0) | bVar33 * (0xf9 < bVar10)) *
                          '`';
        puVar27 = (undefined4 *)(iVar7 - *(int *)(CONCAT31(uVar17,cVar11) + -0x4fa474c9));
        uVar19 = uVar19 - 1;
        uVar36 = CONCAT44(iVar21,CONCAT31(uVar17,cVar11)) | 0xd;
      } while (uVar19 == 0);
      *(byte *)(iVar13 + 0x33) = *(byte *)(iVar13 + 0x33) ^ (byte)(uVar6 >> 0x28);
      uVar16 = *(uint *)((int)piVar23 + 4);
      piVar20 = *(int **)((int)piVar23 + 8);
      pbVar28 = unaff_ESI + -1;
      puVar25 = (undefined4 *)((int)piVar23 + 8);
      puVar26 = (undefined4 *)((int)piVar23 + 8);
      *(undefined4 **)((int)piVar23 + 8) = puVar27;
      cVar11 = '\t';
      do {
        puVar27 = puVar27 + -1;
        puVar25 = puVar25 + -1;
        *puVar25 = *puVar27;
        cVar11 = cVar11 + -1;
      } while ('\0' < cVar11);
      *(undefined1 **)((int)piVar23 + -0x20) = (undefined1 *)((int)piVar23 + 8);
      puVar24 = (undefined4 *)((int)piVar23 + -0xd666);
      pbVar31 = pbVar30;
      if ((POPCOUNT((uint)pbVar28 & 0xff) & 1U) == 0) {
        pbVar31 = pbVar32 + 5;
        *pbVar30 = *pbVar28;
        uVar16 = uVar16 + 1;
        if ((POPCOUNT(uVar16 & 0xff) & 1U) != 0) {
          bVar2 = 9 < ((byte)uVar16 & 0xf);
          uVar8 = in((short)piVar20);
          puVar5 = (uint *)CONCAT31((int3)(uVar16 >> 8),uVar8);
          *unaff_ESI = *unaff_ESI & (byte)piVar20;
          out((short)piVar20,puVar5);
          *puVar5 = *puVar5 | (uint)((int)piVar23 + 8);
          uVar19 = *puVar5;
          uVar14 = *puVar5;
          uVar1 = *puVar5;
          bVar9 = in(2);
          *(undefined4 *)(unaff_ESI + 0x6043a633) = *(undefined4 *)(unaff_ESI + 0x6043a633);
          pbVar32[6] = bVar9;
          *(uint *)((int)piVar23 + -0xd666) =
               (uint)(in_NT & 1) * 0x4000 | (uint)(bVar35 & 1) * 0x200 | (uint)(in_TF & 1) * 0x100 |
               (uint)((int)uVar19 < 0) * 0x80 | (uint)(uVar14 == 0) * 0x40 |
               (uint)(byte)(9 < ((byte)uVar16 + (bVar2 | bVar33) * -6 & 0xf) |
                           bVar2 | bVar3 | bVar34 & 1) * 0x10 |
               (uint)((POPCOUNT(uVar1 & 0xff) & 1U) == 0) * 4 | (uint)(in_ID & 1) * 0x200000 |
               (uint)(in_VIP & 1) * 0x100000 | (uint)(in_VIF & 1) * 0x80000 |
               (uint)(in_AC & 1) * 0x40000;
          DAT_2ab964ea = DAT_2ab964ea - (char)(uVar16 >> 8);
          *(char *)((int)piVar23 + -0x10) = *(char *)((int)piVar23 + -0x10) >> 0x1e;
                    /* WARNING: Bad instruction - Truncating control flow here */
          halt_baddata();
        }
        puVar27 = (undefined4 *)((int)piVar23 + -0xd66a);
        *(undefined1 **)((int)piVar23 + -0xd66a) = (undefined1 *)((int)piVar23 + 8);
        cVar11 = '\x0f';
        do {
          puVar26 = puVar26 + -1;
          puVar27 = puVar27 + -1;
          *puVar27 = *puVar26;
          cVar11 = cVar11 + -1;
        } while ('\0' < cVar11);
        *(undefined1 **)((int)piVar23 + -0xd6aa) = (undefined1 *)((int)piVar23 + -0xd66a);
        puVar24 = (undefined4 *)((int)piVar23 + -0x18b04);
        pbVar28 = unaff_ESI;
      }
LAB_00501ee4:
      piVar23 = puVar24 + 1;
      unaff_ESI = pbVar28;
      pbVar30 = pbVar31;
      uVar36 = CONCAT44(*puVar24,(int)((longlong)(CONCAT44(piVar20,uVar16) | 0x463e092a) /
                                      (longlong)*piVar20)) | 0xc3a98104;
    } while( true );
  }
  uVar16 = uVar14 & 0xbf71a7bd;
  _DAT_b220cc75 = 0x586b4824;
  puVar24 = (undefined4 *)(uVar14 - 0x2e);
  *(byte **)(uVar14 - 0x2e) = unaff_ESI;
  *pbVar30 = *pbVar30 - 1;
  pbVar28 = unaff_ESI + 1;
  pbVar30[-1] = *unaff_ESI;
  pbVar31 = (byte *)((uint)pbVar30 >> 1 | (uint)(*(byte *)(iVar18 + 0x64419902) < 0xca) << 0x1f);
  *(uint *)(uVar16 + 0x4d) = *(uint *)(uVar16 + 0x4d) >> ((byte)uVar19 & 0x1f);
  goto LAB_00501ee4;
}


