/*
 * Function: Assembly_HaltBadInstruction
 * Address: 00502671
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */

void Assembly_HaltBadInstruction(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


