/*
 * Function: Assembly_FloatingPointProcessing
 * Address: 00502d2f
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Instruction at (ram,0x00502dc5) overlaps instruction at (ram,0x00502dc4)
    */
/* WARNING: Unable to track spacebase fully for stack */

float10 __fastcall Assembly_FloatingPointProcessing(int param_1,int param_2,uint *param_3)

{
  char *pcVar1;
  ushort *puVar2;
  double dVar3;
  uint uVar4;
  undefined6 uVar5;
  undefined4 uVar6;
  byte bVar7;
  byte bVar8;
  int iVar10;
  uint uVar11;
  byte *in_EAX;
  int iVar12;
  undefined2 uVar13;
  uint uVar14;
  uint *unaff_EBX;
  int iVar15;
  int unaff_EBP;
  byte *pbVar16;
  byte *unaff_ESI;
  char *unaff_EDI;
  undefined2 in_SS;
  ushort in_DS;
  byte in_CF;
  bool bVar17;
  bool in_PF;
  byte in_AF;
  undefined1 in_ZF;
  bool bVar18;
  char in_SF;
  bool bVar19;
  char in_OF;
  float10 in_ST0;
  undefined8 in_MM7;
  char cVar9;
  
  uVar13 = (undefined2)param_2;
  if (in_PF) {
    in_CF = 0;
    unaff_EBX = (uint *)((uint)unaff_EBX & *(uint *)(unaff_EBP + -0x16));
    in_OF = SCARRY4(unaff_EBP,1);
    unaff_EBP = unaff_EBP + 1;
    in_SF = unaff_EBP < 0;
    in_ZF = unaff_EBP == 0;
    if (!(bool)in_OF) goto LAB_00502d15_4;
code_r0x00502d33:
    if ((bool)in_ZF || in_OF != in_SF) {
      bVar7 = 9 < ((byte)in_EAX & 0xf) | in_AF;
      bVar8 = (byte)in_EAX + bVar7 * '\x06';
      cVar9 = bVar8 + (0x90 < (bVar8 & 0xf0) | in_CF | bVar7 * (0xf9 < bVar8)) * '`';
      iVar10 = CONCAT31((int3)((uint)in_EAX >> 8),cVar9);
      uVar14 = (int)unaff_EBX - 1;
      *unaff_EDI = cVar9;
      pbVar16 = unaff_ESI + 4;
      if ((POPCOUNT(param_1 - 1U & 0xff) & 1U) != 0) {
        *(char *)((int)unaff_EBX + 0x75) = *(char *)((int)unaff_EBX + 0x75) + '\x01';
                    /* WARNING: Bad instruction - Truncating control flow here */
        halt_baddata();
      }
      do {
        uVar11 = CONCAT31((int3)((uint)iVar10 >> 8),DAT_33e0f92e) | 0x1fc58000;
        while( true ) {
          bVar7 = (byte)uVar11;
          uVar11 = CONCAT31((int3)(uVar11 >> 8),bVar7 + 3);
          uVar4 = (uint)(0xfc < bVar7);
          bVar17 = SBORROW4((int)pbVar16,uVar11);
          iVar10 = (int)pbVar16 - uVar11;
          pbVar16 = (byte *)(iVar10 - uVar4);
          if (bVar17 != SBORROW4(iVar10,uVar4)) break;
          uVar14 = uVar14 ^ *param_3;
        }
        iVar10 = (int)*(undefined6 *)((int)param_3 + -0x27);
        *(uint *)(iVar10 + -0x48) = uVar14;
      } while( true );
    }
    if (in_OF == in_SF) {
LAB_00502d15_4:
      uVar6 = in(uVar13);
      *(undefined4 *)unaff_EDI = uVar6;
      return in_ST0;
    }
    in(0x30);
    pcVar1 = unaff_EDI + 0x2fd0dd4f;
    in_OF = SBORROW1(*pcVar1,(char)unaff_EBX);
    *pcVar1 = *pcVar1 - (char)unaff_EBX;
    in(0xa1);
    param_1 = CONCAT22((short)((uint)param_1 >> 0x10),(ushort)(byte)param_1);
    in_CF = 0;
    in_SF = '\0';
    in_ZF = true;
    out(uVar13,&stack0x00000000);
    psubusb(in_MM7,*(undefined8 *)(param_1 + 3));
    in_EAX = (byte *)register0x00000010;
  }
  else if (!in_PF) goto code_r0x00502d33;
  iVar15 = CONCAT22((short)((uint)&stack0x00000000 >> 0x10),in_DS);
  pbVar16 = in_EAX;
  if (!(bool)in_ZF && in_OF == in_SF) {
code_r0x00502d54:
    puVar2 = (ushort *)(unaff_EBP + -0x12eac543);
    *puVar2 = *puVar2 + (ushort)in_CF * (((ushort)pbVar16 & 3) - (*puVar2 & 3));
    puVar2 = (ushort *)((int)unaff_EDI * 9 + -0x5f0fabd0);
    *puVar2 = *puVar2 + (ushort)in_CF * ((in_DS & 3) - (*puVar2 & 3));
    *(int *)(unaff_ESI + 0x5e90594c) = *(int *)(unaff_ESI + 0x5e90594c) << 0x16;
    *(int *)(iVar15 + -4) = param_2;
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  }
  uRamefab60f4 = SUB41(in_EAX,0);
  *(int *)(unaff_EDI + 0x78) = *(int *)(unaff_EDI + 0x78) >> ((byte)param_1 & 0x1f);
  if (param_1 + 1 == 0) {
    in_CF = 0;
    unaff_EBP = -0x4e12eac6;
    pbVar16 = unaff_ESI;
    unaff_ESI = in_EAX;
    goto code_r0x00502d54;
  }
  cVar9 = in(uVar13);
  *unaff_EDI = cVar9;
  iVar10 = *(int *)(param_2 + 0x3d6109bc);
  bVar17 = in_EAX < (byte *)0x56a2e872;
  bVar19 = (int)(in_EAX + -0x56a2e872) < 0;
  bVar18 = in_EAX == (byte *)0x56a2e872;
  *(uint **)(iVar15 + -4) = unaff_EBX;
  iVar12 = CONCAT31((int3)((uint)(unaff_EDI + 1) >> 8),-bVar17);
  *(int *)(iVar15 + -8) = unaff_EBP;
  if (param_1 + 1 + iVar10 == 1) {
    if (!bVar17) {
      uVar14 = -(int)in_EAX;
      bVar17 = (uVar14 & 0x1f) == 0;
      out(*unaff_ESI,uVar13);
      if (uVar14 == 1 ||
          (bVar17 && uVar14 == 0 || !bVar17 && unaff_EBP << ((byte)uVar14 & 0x1f) == 0)) {
                    /* WARNING: Bad instruction - Truncating control flow here */
        halt_baddata();
      }
      *(undefined2 *)(iVar15 + -0xc) = in_SS;
      out(0xbc,unaff_EBX);
                    /* WARNING: Bad instruction - Truncating control flow here */
      halt_baddata();
    }
    uVar5 = *(undefined6 *)unaff_ESI;
    *in_EAX = -bVar17;
    dVar3 = *(double *)((int)unaff_EBX + 0x76);
    unaff_EBX = (uint *)CONCAT31((int3)((uint)unaff_EBX >> 8),0x7e);
    if (-1 < param_2 - *(int *)(unaff_EBP + 0x56)) {
      *(uint *)(iVar12 + 0x77) = *(uint *)(iVar12 + 0x77) ^ (uint)unaff_EBX;
      return (float10)dVar3;
    }
    uVar6 = *(undefined4 *)(iVar15 + -8);
    in_EAX = in_EAX + 5;
    *(undefined4 *)(iVar15 + -8) = uVar6;
    *(int *)(iVar15 + -0xc) = (int)uVar5;
    *(int *)(iVar15 + -0x10) = param_2;
    *(uint **)(iVar15 + -0x14) = unaff_EBX;
    *(int *)(iVar15 + -0x18) = iVar15 + -4;
    *(int *)(iVar15 + -0x1c) = unaff_EBP;
    *(int *)(iVar15 + -0x20) = iVar12 + iVar15;
    *(byte **)(iVar15 + -0x24) = in_EAX;
    param_2 = param_2 + 1;
    cVar9 = (char)uVar6;
    out(0xf2,cVar9);
    bVar19 = (char)(cVar9 + 'w') < '\0';
    bVar18 = cVar9 == -0x77;
  }
  else if (bVar17) {
    in_EAX = in_EAX + 1;
    out(0xd,iVar12);
    if (-1 < (int)(unaff_ESI + -1)) {
                    /* WARNING: Bad instruction - Truncating control flow here */
      halt_baddata();
    }
    goto LAB_00502dc4;
  }
  *unaff_EBX = *unaff_EBX >> 1 | (uint)((*unaff_EBX & 1) != 0) << 0x1f;
  if (bVar18 || (((*unaff_EBX & 0x40000000) != 0) != (int)*unaff_EBX < 0) != bVar19) {
    do {
                    /* WARNING: Do nothing block with infinite loop */
    } while( true );
  }
  iVar12 = in((short)param_2);
LAB_00502dc4:
  out(0x14,-((byte)iVar12 < *in_EAX));
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


