/*
 * Function: BitStream_FlushBuffer
 * Address: 004dc0f0
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void BitStream_FlushBuffer(void)

{
  int in_EAX;
  int iVar1;
  
  if (8 < *(int *)(in_EAX + 0x16b4)) {
    *(undefined1 *)(*(int *)(in_EAX + 8) + *(int *)(in_EAX + 0x14)) =
         *(undefined1 *)(in_EAX + 0x16b0);
    iVar1 = *(int *)(in_EAX + 0x14) + 1;
    *(int *)(in_EAX + 0x14) = iVar1;
    *(undefined1 *)(iVar1 + *(int *)(in_EAX + 8)) = *(undefined1 *)(in_EAX + 0x16b1);
    *(int *)(in_EAX + 0x14) = *(int *)(in_EAX + 0x14) + 1;
    *(undefined2 *)(in_EAX + 0x16b0) = 0;
    *(undefined4 *)(in_EAX + 0x16b4) = 0;
    return;
  }
  if (0 < *(int *)(in_EAX + 0x16b4)) {
    *(undefined1 *)(*(int *)(in_EAX + 8) + *(int *)(in_EAX + 0x14)) =
         *(undefined1 *)(in_EAX + 0x16b0);
    *(int *)(in_EAX + 0x14) = *(int *)(in_EAX + 0x14) + 1;
  }
  *(undefined2 *)(in_EAX + 0x16b0) = 0;
  *(undefined4 *)(in_EAX + 0x16b4) = 0;
  return;
}


