/*
 * Function: ColorSpace_RGBToHSV
 * Address: 004c2ad0
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __cdecl ColorSpace_RGBToHSV(int *param_1,int param_2,char param_3)

{
  PixelFormat_InvertColors(param_1,0,0x537d60,param_2,param_3);
  PixelFormat_InvertColors(param_1,1,0x537e60,param_2,param_3);
  return;
}


