/*
 * Function: Compiler_CrtInit
 * Address: 004f6845
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void Compiler_CrtInit(void)

{
  bool bVar1;
  bool bVar2;
  wint_t wVar3;
  int iVar4;
  undefined4 extraout_ECX;
  uint extraout_EDX;
  uint extraout_EDX_00;
  uint extraout_EDX_01;
  uint extraout_EDX_02;
  int unaff_EBP;
  undefined4 *unaff_ESI;
  int iVar5;
  undefined4 *unaff_EDI;
  _String_base a_Stack_7c [8];
  undefined4 uStack_74;
  
  Assembly_BitShiftLocking();
  bVar1 = NAN(_DAT_0052a0c0);
  bVar2 = *(double *)(unaff_EBP + 0x20) < _DAT_0052a0c0;
  *(uint *)(unaff_EBP + -0x10) = DAT_00569f5c ^ *(uint *)(unaff_EBP + 4);
  *(undefined4 *)(unaff_EBP + -0x1c) = extraout_ECX;
  *(undefined1 *)(unaff_EBP + -0x18) = 0;
  if (bVar2 != (NAN(*(double *)(unaff_EBP + 0x20)) || bVar1)) {
    *(undefined1 *)(unaff_EBP + -0x18) = 1;
    *(double *)(unaff_EBP + 0x20) = -*(double *)(unaff_EBP + 0x20);
  }
  *(undefined4 *)(unaff_EBP + -0x14) = 0;
  while ((_DAT_0052c808 < *(double *)(unaff_EBP + 0x20) !=
          (_DAT_0052c808 == *(double *)(unaff_EBP + 0x20)) && (*(uint *)(unaff_EBP + -0x14) < 5000))
        ) {
    *(int *)(unaff_EBP + -0x14) = *(int *)(unaff_EBP + -0x14) + 10;
    *(double *)(unaff_EBP + 0x20) = *(double *)(unaff_EBP + 0x20) * _DAT_0052c800;
  }
  Collision_ClosestPoint(unaff_EBP + -0x38,extraout_EDX,'\0');
  *(undefined4 *)(unaff_EBP + -4) = 0;
  uStack_74 = 0x4f68d4;
  iVar4 = Exception_Release((undefined1 *)(unaff_EBP + -0x60),"%.0Lf");
  iVar5 = 0;
  if (0 < iVar4) {
    do {
      wVar3 = _btowc((int)*(char *)(unaff_EBP + -0x60 + iVar5));
      UI_ShowLivesDisplay((void *)(unaff_EBP + -0x38),1,wVar3);
      iVar5 = iVar5 + 1;
    } while (iVar5 < iVar4);
  }
  wVar3 = _btowc(0x30);
  UI_ShowLivesDisplay((void *)(unaff_EBP + -0x38),*(uint *)(unaff_EBP + -0x14),wVar3);
  *(_String_base **)(unaff_EBP + 0x24) = a_Stack_7c;
  Collision_ClosestPoint((int)a_Stack_7c,extraout_EDX_00,'\0');
  UI_ShowWeaponDisplay(a_Stack_7c,extraout_EDX_01,(_String_base *)(unaff_EBP + -0x38),0,0xffffffff);
  Compiler_CrtTerm();
  Collision_ClosestPoint(unaff_EBP + -0x38,extraout_EDX_02,'\x01');
  ExceptionList = *(void **)(unaff_EBP + -0xc);
  Exception_SetMessage
            ((void *)(*(uint *)(unaff_EBP + -0x10) ^ *(uint *)(unaff_EBP + 4)),unaff_EDI,unaff_ESI);
  return;
}


