/*
 * Function: Compression_DecompressData
 * Address: 004be600
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __cdecl Compression_DecompressData(int *param_1,int param_2)

{
  undefined1 *puVar1;
  undefined1 uVar2;
  undefined1 uVar3;
  undefined1 *puVar4;
  undefined1 *puVar5;
  int iVar6;
  
  iVar6 = *param_1;
  if ((char)param_1[2] == '\x06') {
    puVar4 = (undefined1 *)(param_1[1] + param_2);
    if (*(char *)((int)param_1 + 9) == '\b') {
      puVar5 = puVar4;
      if (iVar6 != 0) {
        do {
          uVar2 = puVar4[-1];
          puVar5[-1] = puVar4[-2];
          puVar5[-2] = puVar4[-3];
          puVar1 = puVar4 + -4;
          puVar4 = puVar4 + -4;
          puVar5[-3] = *puVar1;
          iVar6 = iVar6 + -1;
          puVar5[-4] = uVar2;
          puVar5 = puVar5 + -4;
        } while (iVar6 != 0);
        return;
      }
    }
    else {
      puVar5 = puVar4;
      if (iVar6 != 0) {
        do {
          uVar2 = puVar4[-1];
          uVar3 = puVar4[-2];
          puVar5[-1] = puVar4[-3];
          puVar5[-2] = puVar4[-4];
          puVar5[-3] = puVar4[-5];
          puVar5[-4] = puVar4[-6];
          puVar5[-5] = puVar4[-7];
          puVar1 = puVar4 + -8;
          puVar4 = puVar4 + -8;
          puVar5[-6] = *puVar1;
          puVar5[-7] = uVar2;
          iVar6 = iVar6 + -1;
          puVar5[-8] = uVar3;
          puVar5 = puVar5 + -8;
        } while (iVar6 != 0);
        return;
      }
    }
  }
  else if ((char)param_1[2] == '\x04') {
    puVar4 = (undefined1 *)(param_1[1] + param_2);
    puVar5 = puVar4;
    if (*(char *)((int)param_1 + 9) == '\b') {
      if (iVar6 != 0) {
        do {
          uVar2 = puVar4[-1];
          puVar1 = puVar4 + -2;
          puVar4 = puVar4 + -2;
          puVar5[-1] = *puVar1;
          iVar6 = iVar6 + -1;
          puVar5[-2] = uVar2;
          puVar5 = puVar5 + -2;
        } while (iVar6 != 0);
        return;
      }
    }
    else {
      for (; iVar6 != 0; iVar6 = iVar6 + -1) {
        uVar2 = puVar4[-1];
        uVar3 = puVar4[-2];
        puVar5[-1] = puVar4[-3];
        puVar1 = puVar4 + -4;
        puVar4 = puVar4 + -4;
        puVar5[-2] = *puVar1;
        puVar5[-3] = uVar2;
        puVar5[-4] = uVar3;
        puVar5 = puVar5 + -4;
      }
    }
  }
  return;
}


