/*
 * Function: CPU_Instruction50
 * Address: 004caac0
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __cdecl CPU_Instruction50(uint param_1,int param_2,uint param_3)

{
  void *this;
  void *extraout_ECX;
  void *pvVar1;
  byte *extraout_EDX;
  byte *extraout_EDX_00;
  byte *pbVar2;
  
  CPU_Instruction28(param_1,(byte *)(param_1 + 0x11c));
  pvVar1 = this;
  pbVar2 = extraout_EDX;
  if (((*(byte *)(param_1 + 0x11c) & 0x20) == 0) &&
     (CPU_Instruction22(this,param_1,(undefined4 *)"unknown critical chunk"), pvVar1 = extraout_ECX,
     pbVar2 = extraout_EDX_00, param_2 == 0)) {
    return;
  }
  if ((*(uint *)(param_1 + 0x68) & 4) != 0) {
    *(uint *)(param_1 + 0x68) = *(uint *)(param_1 + 0x68) | 8;
  }
  CPU_Instruction33(pvVar1,pbVar2,param_1,param_3);
  return;
}


