/*
 * Function: CPU_Instruction44
 * Address: 004ca0f0
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall CPU_Instruction44(uint param_1,byte *param_2,uint param_3,int param_4,uint param_5)

{
  void *this;
  int iVar1;
  undefined4 uVar2;
  undefined4 uVar3;
  uint extraout_ECX;
  undefined4 extraout_ECX_00;
  undefined4 extraout_ECX_01;
  undefined4 extraout_ECX_02;
  byte *extraout_EDX;
  byte *extraout_EDX_00;
  byte *extraout_EDX_01;
  byte *extraout_EDX_02;
  byte *extraout_EDX_03;
  undefined4 *in_stack_ffffffec;
  undefined4 *in_stack_fffffff0;
  undefined1 local_c;
  
  this = DAT_00569f5c;
  if ((*(uint *)(param_3 + 0x68) & 1) == 0) {
    CPU_Instruction20(param_1,param_2,param_3,"Missing IHDR before pHYS");
    param_1 = extraout_ECX;
    param_2 = extraout_EDX;
  }
  else {
    if ((*(uint *)(param_3 + 0x68) & 4) != 0) {
      CPU_Instruction21(param_1,param_2,param_3,"Invalid pHYS after IDAT");
      CPU_Instruction33(extraout_ECX_01,extraout_EDX_01,param_3,param_5);
      Exception_SetMessage(this,in_stack_ffffffec,in_stack_fffffff0);
      return;
    }
    if ((param_4 != 0) && (*(char *)(param_4 + 8) < '\0')) {
      CPU_Instruction21(param_1,param_2,param_3,"Duplicate pHYS chunk");
      CPU_Instruction33(param_5,extraout_EDX_02,param_3,param_5);
      Exception_SetMessage(this,in_stack_ffffffec,in_stack_fffffff0);
      return;
    }
  }
  if (param_5 != 9) {
    CPU_Instruction21(param_1,param_2,param_3,"Incorrect pHYs chunk length");
    CPU_Instruction33(extraout_ECX_00,extraout_EDX_00,param_3,param_5);
    Exception_SetMessage(this,in_stack_ffffffec,in_stack_fffffff0);
    return;
  }
  CPU_Instruction26(param_1,&stack0xffffffec,param_3,&stack0xffffffec,9);
  iVar1 = CPU_Instruction33(extraout_ECX_02,extraout_EDX_03,param_3,0);
  if (iVar1 == 0) {
    uVar2 = CPU_Instruction24(&stack0xfffffff0);
    uVar3 = CPU_Instruction24(&stack0xffffffec);
    PNG_SetHistogram(param_3,param_4,uVar3,uVar2,local_c);
  }
  Exception_SetMessage(this,in_stack_ffffffec,in_stack_fffffff0);
  return;
}


