/*
 * Function: CPU_InitializeContext
 * Address: 004c5c30
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __thiscall CPU_InitializeContext(void *this,undefined4 *param_1)

{
  undefined4 extraout_ECX;
  
  PNG_GetProgressPtr(this,(int *)param_1[1]);
  PNG_GetProgressPtr(extraout_ECX,(int *)param_1[3]);
  *param_1 = 0;
  param_1[1] = 0;
  param_1[2] = 0;
  param_1[3] = 0;
  param_1[4] = 0;
  param_1[5] = 0;
  param_1[7] = 0xffffffff;
  param_1[8] = 0;
  param_1[9] = 0;
  param_1[10] = 0;
  param_1[0xb] = 0;
  param_1[0xd] = 0;
  param_1[0xc] = 0;
  param_1[0xe] = 0;
  param_1[0xf] = 0;
  param_1[0x10] = 0;
  param_1[0x11] = 0;
  param_1[0x12] = 0;
  return;
}


