/*
 * Function: CPU_ProcessData8
 * Address: 004c6910
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __cdecl CPU_ProcessData8(int param_1,int param_2,undefined4 *param_3)

{
  int iVar1;
  short *psVar2;
  short *psVar3;
  bool bVar4;
  uint unaff_retaddr;
  undefined4 *in_stack_ffffffd4;
  undefined4 *in_stack_ffffffd8;
  short local_14 [4];
  uint local_c;
  uint local_8;
  
  local_8 = DAT_00569f5c ^ unaff_retaddr;
  if (param_3 != (undefined4 *)0x0) {
    GIF_GetLoopCount((undefined4 *)&stack0xffffffd4,(undefined4 *)*param_3);
    local_c = GIF_SetTransparentIndex((uint *)&stack0xffffffd4,8);
    local_14[0] = 0;
    local_14[1] = 0;
    local_14[2] = 0;
    CPU_CopyBytes((undefined1 *)local_14);
    iVar1 = 3;
    bVar4 = true;
    psVar2 = local_14;
    psVar3 = (short *)"vorbis";
    do {
      if (iVar1 == 0) break;
      iVar1 = iVar1 + -1;
      bVar4 = *psVar2 == *psVar3;
      psVar2 = psVar2 + 1;
      psVar3 = psVar3 + 1;
    } while (bVar4);
    if (!bVar4) {
      Exception_SetMessage((void *)(local_8 ^ unaff_retaddr),in_stack_ffffffd4,in_stack_ffffffd8);
      return;
    }
    if (local_c == 1) {
      if ((param_3[2] != 0) && (*(int *)(param_1 + 8) == 0)) {
        CPU_ProcessData5();
        Exception_SetMessage((void *)(local_8 ^ unaff_retaddr),in_stack_ffffffd4,in_stack_ffffffd8);
        return;
      }
    }
    else if (local_c == 3) {
      if (*(int *)(param_1 + 8) != 0) {
        CPU_ProcessData6((uint *)&stack0xffffffd4);
        Exception_SetMessage((void *)(local_8 ^ unaff_retaddr),in_stack_ffffffd4,in_stack_ffffffd8);
        return;
      }
    }
    else if (((local_c == 5) && (*(int *)(param_1 + 8) != 0)) && (*(int *)(param_2 + 0xc) != 0)) {
      CPU_ProcessData7(param_1);
      Exception_SetMessage((void *)(local_8 ^ unaff_retaddr),in_stack_ffffffd4,in_stack_ffffffd8);
      return;
    }
  }
  Exception_SetMessage((void *)(local_8 ^ unaff_retaddr),in_stack_ffffffd4,in_stack_ffffffd8);
  return;
}


