/*
 * Function: CPU_Instruction54
 * Address: 004caf10
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


int __cdecl CPU_Instruction54(int *param_1,int param_2,uint param_3)

{
  int iVar1;
  int *piVar2;
  int *piVar3;
  int *piVar4;
  uint uVar5;
  int iVar6;
  
  piVar2 = param_1;
  iVar1 = param_1[1];
  if (0x3b9ac9f0 < param_3) {
    CPU_Instruction53(1);
  }
  if ((param_3 & 7) != 0) {
    param_3 = param_3 + (8 - (param_3 & 7));
  }
  if ((param_2 < 0) || (1 < param_2)) {
    *(undefined4 *)(*param_1 + 0x14) = 0xe;
    *(int *)(*param_1 + 0x18) = param_2;
    (**(code **)*param_1)(param_1);
  }
  param_1 = (int *)0x0;
  piVar3 = *(int **)(iVar1 + 0x34 + param_2 * 4);
  while (piVar4 = piVar3, piVar4 != (int *)0x0) {
    if (param_3 <= (uint)piVar4[2]) goto LAB_004cb02c;
    param_1 = piVar4;
    piVar3 = (int *)*piVar4;
  }
  iVar6 = param_3 + 0x10;
  if (param_1 == (int *)0x0) {
    uVar5 = *(uint *)(&DAT_0053a5c0 + param_2 * 4);
  }
  else {
    uVar5 = *(uint *)(&DAT_0053a5c8 + param_2 * 4);
  }
  if (1000000000U - iVar6 < uVar5) {
    uVar5 = 1000000000U - iVar6;
  }
  piVar4 = (int *)Math_Clamp(piVar2,uVar5 + iVar6);
  while (piVar4 == (int *)0x0) {
    uVar5 = uVar5 >> 1;
    if (uVar5 < 0x32) {
      CPU_Instruction53(2);
    }
    piVar4 = (int *)Math_Clamp(piVar2,uVar5 + iVar6);
  }
  *(uint *)(iVar1 + 0x4c) = *(int *)(iVar1 + 0x4c) + uVar5 + iVar6;
  *piVar4 = 0;
  piVar4[1] = 0;
  piVar4[2] = uVar5 + param_3;
  if (param_1 == (int *)0x0) {
    *(int **)(iVar1 + 0x34 + param_2 * 4) = piVar4;
  }
  else {
    *param_1 = (int)piVar4;
  }
LAB_004cb02c:
  iVar1 = piVar4[1];
  piVar4[1] = iVar1 + param_3;
  piVar4[2] = piVar4[2] - param_3;
  return iVar1 + 0x10 + (int)piVar4;
}


