/*
 * Function: CPU_ProcessData15
 * Address: 004c6d70
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


undefined4 __cdecl CPU_ProcessData15(int param_1)

{
  int *piVar1;
  undefined4 *puVar2;
  undefined *puVar3;
  void *pvVar4;
  undefined4 uVar5;
  int iVar6;
  int extraout_ECX;
  undefined4 *unaff_EBX;
  uint *puVar7;
  int *piVar8;
  int local_c;
  int local_8;
  
  piVar1 = *(int **)(param_1 + 0x1c);
  puVar2 = unaff_EBX;
  for (iVar6 = 0x14; iVar6 != 0; iVar6 = iVar6 + -1) {
    *puVar2 = 0;
    puVar2 = puVar2 + 1;
  }
  puVar2 = (undefined4 *)Assembly_DecompilationFailed(1,0x18);
  unaff_EBX[1] = param_1;
  unaff_EBX[0x12] = puVar2;
  iVar6 = Process_TerminateProcess(piVar1[2]);
  puVar2[2] = iVar6;
  puVar3 = GIF_ConvertPixelFormat(0,*piVar1 / 2);
  *puVar2 = puVar3;
  puVar3 = GIF_ConvertPixelFormat(0,piVar1[1] / 2);
  puVar2[1] = puVar3;
  if (piVar1[0x308] == 0) {
    iVar6 = Assembly_DecompilationFailed(piVar1[7],0x34);
    piVar1[0x308] = iVar6;
    local_8 = 0;
    if (0 < piVar1[7]) {
      local_c = 0;
      puVar7 = (uint *)(piVar1 + 0x208);
      do {
        GIF_ProcessColorQuantization((uint *)(piVar1[0x308] + local_c),(undefined4 *)*puVar7);
        JPEG_WriteHeader(extraout_ECX,*puVar7,(undefined4 *)*puVar7);
        *puVar7 = 0;
        local_8 = local_8 + 1;
        local_c = local_c + 0x34;
        puVar7 = puVar7 + 1;
      } while (local_8 < piVar1[7]);
    }
  }
  unaff_EBX[4] = piVar1[1];
  pvVar4 = _malloc(*(int *)(param_1 + 4) << 2);
  unaff_EBX[2] = pvVar4;
  pvVar4 = _malloc(*(int *)(param_1 + 4) << 2);
  unaff_EBX[3] = pvVar4;
  iVar6 = 0;
  if (0 < *(int *)(param_1 + 4)) {
    do {
      uVar5 = Assembly_DecompilationFailed(unaff_EBX[4],4);
      *(undefined4 *)(unaff_EBX[2] + iVar6 * 4) = uVar5;
      iVar6 = iVar6 + 1;
    } while (iVar6 < *(int *)(param_1 + 4));
  }
  unaff_EBX[9] = 0;
  unaff_EBX[10] = 0;
  uVar5 = Assembly_DecompilationFailed(piVar1[2],4);
  puVar2[3] = uVar5;
  local_8 = 0;
  if (0 < piVar1[2]) {
    piVar8 = piVar1 + 8;
    do {
      uVar5 = (**(code **)((&PTR_PTR_Process_WaitForExit_005682c8)
                           [piVar1[*(int *)(*piVar8 + 0xc) + 0x48]] + 4))();
      *(undefined4 *)((int)piVar8 + puVar2[3] + (-0x20 - (int)piVar1)) = uVar5;
      local_8 = local_8 + 1;
      piVar8 = piVar8 + 1;
    } while (local_8 < piVar1[2]);
  }
  return 0;
}


