/*
 * Function: CPU_GetAuxCarryFlag
 * Address: 004c57b0
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


byte CPU_GetAuxCarryFlag(void)

{
  byte bVar1;
  undefined4 local_18 [5];
  
  PNG_GetBitDepth(local_18);
  bVar1 = PNG_GetFilterMethod(5);
  return bVar1 & 4;
}


