/*
 * Function: CPU_ReadInstructionBytes
 * Address: 004c5a50
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void CPU_ReadInstructionBytes(void)

{
  int iVar1;
  byte bVar2;
  uint uVar3;
  int unaff_ESI;
  
  *(undefined4 *)(unaff_ESI + 0x48) = 0;
  if (*(int *)(unaff_ESI + 0x44) < *(int *)(unaff_ESI + 0x30)) {
    while( true ) {
      iVar1 = *(int *)(unaff_ESI + 0x44);
      *(int *)(unaff_ESI + 0x44) = iVar1 + 1;
      bVar2 = PNG_GetFilterMethod(iVar1 + 0x1b);
      uVar3 = *(int *)(unaff_ESI + 0x48) + (uint)bVar2;
      *(uint *)(unaff_ESI + 0x48) = uVar3;
      if (bVar2 < 0xff) break;
      if (*(int *)(unaff_ESI + 0x30) <= *(int *)(unaff_ESI + 0x44)) {
        return;
      }
    }
    *(uint *)(unaff_ESI + 0x48) = uVar3 | 0x80000000;
    *(undefined4 *)(unaff_ESI + 0x40) = 1;
  }
  return;
}


