/*
 * Function: Debug_GetRegisterEAX
 * Address: 0050f1c6
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Instruction at (ram,0x0050f1f1) overlaps instruction at (ram,0x0050f1ed)
    */
/* WARNING: Unable to track spacebase fully for stack */

void __fastcall Debug_GetRegisterEAX(uint param_1,int param_2)

{
  uint *puVar1;
  uint uVar2;
  uint uVar3;
  short sVar4;
  ushort uVar5;
  undefined4 in_EAX;
  int iVar6;
  char *pcVar7;
  uint uVar8;
  uint unaff_EBX;
  uint uVar9;
  int iVar10;
  int unaff_EBP;
  undefined4 unaff_ESI;
  int unaff_EDI;
  byte in_CF;
  char in_PF;
  char in_AF;
  char in_ZF;
  char in_SF;
  bool bVar11;
  undefined4 auStack_8 [2];
  
  sVar4 = CONCAT11(in_SF << 7 | in_ZF << 6 | in_AF << 4 | in_PF << 2 | 2U | in_CF,(char)in_EAX);
  out(8,(char)in_EAX);
  if (param_1 == 0) {
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  }
  *(char *)CONCAT22((short)((uint)in_EAX >> 0x10),sVar4) = (char)unaff_EBX;
  uVar5 = CONCAT11((char)(sVar4 % (short)(char)param_2),(char)(sVar4 / (short)(char)param_2));
  do {
    while( true ) {
      uVar8 = param_1;
      param_1 = uVar8 + 1;
      bVar11 = (uVar5 & 0x8000) == 0;
      if (bVar11) break;
      if (bVar11) {
        do {
                    /* WARNING: Do nothing block with infinite loop */
        } while( true );
      }
      iVar6 = in((short)param_2);
      *(char *)(uVar8 + 0x56) = *(char *)(uVar8 + 0x56) - (char)((uint)iVar6 >> 8);
      unaff_EBP = unaff_EBP + -1;
      bVar11 = unaff_EBX < *(uint *)(unaff_EDI + 0x32);
      unaff_EBX = unaff_EBX - *(uint *)(unaff_EDI + 0x32);
      *(char *)(iVar6 + -0x18) = *(char *)(iVar6 + -0x18) + -1;
      puVar1 = (uint *)(param_2 + -0xc64ae6f);
      uVar9 = (uint)bVar11;
      uVar2 = *puVar1;
      uVar3 = *puVar1 - param_1;
      bVar11 = *puVar1 < param_1 || uVar3 < uVar9;
      *puVar1 = uVar3 - uVar9;
      uVar5 = 0xa09f;
      if (*puVar1 != 0 && (SBORROW4(uVar2,param_1) != SBORROW4(uVar3,uVar9)) == (int)*puVar1 < 0)
      goto Debug_GetRegisterECX;
    }
    bVar11 = false;
  } while ((uVar5 & 0xf2) == 0 || (char)uVar5 < '\0');
Debug_GetRegisterECX:
  uVar9 = CONCAT22((short)(unaff_EBX >> 0x10),
                   CONCAT11((char)(unaff_EBX >> 8) + *(char *)(unaff_EBP + -0x7dbaa620) + bVar11,
                            (char)unaff_EBX));
  iVar6 = *(int *)(unaff_EDI * 9 + -0x35);
  *(byte *)(unaff_EDI + -0x1e) = *(byte *)(unaff_EDI + -0x1e) & (byte)uVar5;
  pcVar7 = (char *)in(0xe4);
  uVar2 = *(uint *)(unaff_EBP + -0x2c209b90);
  iVar10 = uVar9 + *(uint *)(unaff_EBP + -0x2c209b90);
  if (iVar10 < 0) {
    *(undefined4 *)((int)auStack_8 - iVar6) = unaff_ESI;
    puVar1 = (uint *)(iVar10 + 0x48e6af16);
    *puVar1 = *puVar1 | (uint)CARRY4(uVar9,uVar2) << 8;
    *pcVar7 = *pcVar7 + (char)(uVar8 + 2 >> 8);
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  }
  *(char **)(unaff_EDI + -0x205a6fe8) = pcVar7;
  return;
}


