/*
 * Function: ExceptionHandler_VectorDestructorIterator
 * Address: 004fb89d
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* Library Function - Single Match
    void __stdcall `eh vector destructor iterator'(void *,unsigned int,int,void (__thiscall*)(void
   *))
   
   Library: Visual Studio 2003 Release */

void ExceptionHandler_VectorDestructorIterator
               (void *param_1,uint param_2,int param_3,_func_void_void_ptr *param_4)

{
  int *piVar1;
  int iVar2;
  undefined4 in_ECX;
  uint in_EDX;
  int unaff_EBP;
  int unaff_retaddr;
  
  Runtime_CheckBounds(in_ECX,in_EDX,0x547040,(undefined4 *)0xc,unaff_retaddr,(undefined4 *)param_1,
                      (undefined4 *)param_2);
  *(undefined4 *)(unaff_EBP + -0x1c) = 0;
  iVar2 = *(int *)(unaff_EBP + 0xc);
  *(int *)(unaff_EBP + 8) = *(int *)(unaff_EBP + 8) + iVar2 * *(int *)(unaff_EBP + 0x10);
  *(undefined4 *)(unaff_EBP + -4) = 0;
  while( true ) {
    piVar1 = (int *)(unaff_EBP + 0x10);
    *piVar1 = *piVar1 + -1;
    if (*piVar1 < 0) break;
    *(int *)(unaff_EBP + 8) = *(int *)(unaff_EBP + 8) - iVar2;
    (**(code **)(unaff_EBP + 0x14))();
  }
  *(undefined4 *)(unaff_EBP + -0x1c) = 1;
  *(undefined4 *)(unaff_EBP + -4) = 0xffffffff;
  Exception_MessageBuffer();
  func_0x00503463();
  return;
}


