/*
 * Function: Exception_VectorInsert40Error
 * Address: 0040937b
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void Exception_VectorInsert40Error(void)

{
  undefined4 *puVar1;
  int iVar2;
  undefined4 uVar3;
  undefined4 *extraout_ECX;
  int extraout_ECX_00;
  uint extraout_EDX;
  undefined4 *unaff_EBX;
  int unaff_EBP;
  int unaff_ESI;
  int unaff_EDI;
  
  iVar2 = *(int *)(unaff_EBP + 0xc) * 0x28;
  ArrayDestroy_40ByteObjects
            (*(int *)(unaff_EBP + -0x14),*(uint *)(unaff_EBP + 8),iVar2 + *(uint *)(unaff_EBP + 8),
             *(int *)(*(int *)(unaff_EBP + -0x14) + 8) + iVar2);
  CRuntime_CxxThrowException(0,0);
  *(undefined1 **)(unaff_EBP + 8) = &stack0xfffffff8;
  *(undefined1 **)(unaff_EBP + 8) = &stack0xfffffff4;
  *(undefined4 **)(unaff_EBP + 8) = extraout_ECX + unaff_EDI * -10;
  uVar3 = WeaponBomb_ProcessLaserGuidedBomb
                    (extraout_ECX + unaff_EDI * -10,extraout_ECX,extraout_ECX);
  iVar2 = *(int *)(unaff_EBP + 8);
  puVar1 = *(undefined4 **)(unaff_EBP + 0x10);
  *(undefined4 *)(unaff_ESI + 8) = uVar3;
  *(undefined1 **)(unaff_EBP + 0xc) = &stack0xfffffffc;
  *(undefined1 **)(unaff_EBP + 0xc) = &stack0xfffffff8;
  *(undefined1 **)(unaff_EBP + 8) = &stack0xfffffff4;
  Craft_ProcessStrafer((undefined4 *)(unaff_EBP + 8),(int)unaff_EBX,iVar2,puVar1);
  *(undefined1 **)(unaff_EBP + 8) = &stack0xfffffff8;
  *(undefined1 **)(unaff_EBP + 8) = &stack0xfffffff4;
  Craft_ProcessSatellite(unaff_EBX,unaff_EBX + unaff_EDI * 10,(undefined4 *)(unaff_EBP + -0x40));
  if (*(int *)(unaff_EBP + -0x24) != 0) {
                    /* WARNING: Subroutine does not return */
    System_ShutdownHandler(extraout_ECX_00,extraout_EDX);
  }
  *(undefined4 *)(unaff_EBP + -0x24) = 0;
  *(undefined4 *)(unaff_EBP + -0x20) = 0;
  *(undefined4 *)(unaff_EBP + -0x1c) = 0;
  if (*(int *)(unaff_EBP + -0x34) != 0) {
                    /* WARNING: Subroutine does not return */
    System_ShutdownHandler(0,extraout_EDX);
  }
  ExceptionList = *(void **)(unaff_EBP + -0xc);
  return;
}


