/*
 * Function: Exception_LocaleBufferCleanup
 * Address: 004eff2f
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


undefined * Exception_LocaleBufferCleanup(void)

{
  void *pvVar1;
  int unaff_EBP;
  
  *(int *)(unaff_EBP + -0x18) = *(int *)(unaff_EBP + 8);
  *(BADSPACEBASE **)(unaff_EBP + -0x10) = register0x00000010;
  *(undefined1 *)(unaff_EBP + -4) = 2;
  pvVar1 = operator_new(*(int *)(unaff_EBP + 8) * 2 + 2);
  *(void **)(unaff_EBP + 8) = pvVar1;
  return &DAT_004eff50;
}


