/*
 * Function: Exception_CleanupResources
 * Address: 00492dc0
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __thiscall Exception_CleanupResources(void *this,int param_1,void *param_2)

{
  int iVar1;
  char cVar2;
  _String_base *p_Var3;
  int extraout_ECX;
  undefined4 extraout_ECX_00;
  undefined4 extraout_ECX_01;
  int extraout_ECX_02;
  int extraout_ECX_03;
  uint extraout_EDX;
  uint extraout_EDX_00;
  uint extraout_EDX_01;
  uint extraout_EDX_02;
  undefined4 extraout_EDX_03;
  uint extraout_EDX_04;
  uint uVar4;
  int iVar5;
  uint uVar6;
  undefined8 uVar7;
  uint unaff_retaddr;
  undefined4 *in_stack_ffffff80;
  undefined4 *in_stack_ffffff84;
  uint local_68;
  undefined1 local_64 [4];
  uint local_60;
  undefined4 local_50;
  uint local_4c;
  _String_base local_48 [4];
  uint local_44;
  undefined4 local_34;
  uint local_30;
  undefined4 local_2c [6];
  uint local_14;
  void *local_10;
  undefined4 uStack_c;
  int local_8;
  
  local_8 = 0xffffffff;
  uStack_c = 0x5150d0;
  local_10 = ExceptionList;
  local_14 = DAT_00569f5c ^ unaff_retaddr;
  uVar6 = 0;
  if (*(int *)((int)param_2 + 4) != 0) {
    ExceptionList = &local_10;
    Background_ProcessGroundLayer
              (*(int *)((int)param_2 + 8),(uint)param_2,*(int *)((int)param_2 + 4),
               *(int *)((int)param_2 + 8));
                    /* WARNING: Subroutine does not return */
    System_ShutdownHandler(extraout_ECX,extraout_EDX);
  }
  ExceptionList = &local_10;
  *(undefined4 *)((int)param_2 + 4) = 0;
  *(undefined4 *)((int)param_2 + 8) = 0;
  *(undefined4 *)((int)param_2 + 0xc) = 0;
  Registry_QueryValue(local_2c);
  local_8 = 0;
  if (*(char *)(param_1 + 4) == '\0') {
    local_30 = 0xf;
    local_34 = 0;
    local_44 = local_44 & 0xffffff00;
    PowerUp_ProcessThunderstrike
              (local_48,extraout_EDX_00,(_String_base *)(param_1 + 8),0,0xffffffff);
    local_8._0_1_ = 1;
    uVar7 = Database_CommitTransaction((int)this,(byte *)local_48,(int)local_48);
    uVar4 = (uint)((ulonglong)uVar7 >> 0x20);
    if ((int)uVar7 == 0) {
      p_Var3 = Survival_LoadConfiguration
                         ((_String_base *)&stack0xffffff80,
                          (_String_base *)"Unable to Dereference \"",(int)local_48);
      local_8._0_1_ = 2;
      p_Var3 = Intel_DisplayPopulationData
                         (extraout_ECX_01,(uint)local_64,(_String_base *)local_64,p_Var3,
                          (_String_base *)&DAT_005339dc);
      local_8 = CONCAT31(local_8._1_3_,3);
      D3D_SetViewport(this,(int)p_Var3);
      if (0xf < local_4c) {
                    /* WARNING: Subroutine does not return */
        System_ShutdownHandler(extraout_ECX_02,extraout_EDX_02);
      }
      local_4c = 0xf;
      local_50 = 0;
      local_60 = local_60 & 0xffffff00;
      if (0xf < local_68) {
                    /* WARNING: Subroutine does not return */
        System_ShutdownHandler((int)in_stack_ffffff84,extraout_EDX_02);
      }
      in_stack_ffffff84 = (undefined4 *)((uint)in_stack_ffffff84 & 0xffffff00);
      if (0xf < local_30) {
                    /* WARNING: Subroutine does not return */
        System_ShutdownHandler(extraout_ECX_02,local_44);
      }
      local_30 = 0xf;
      local_34 = 0;
      local_44 = local_44 & 0xffffff00;
      uVar4 = extraout_EDX_02;
    }
    else {
      cVar2 = *(char *)((int)uVar7 + 4);
      if (cVar2 != '\0') {
        local_8 = (uint)local_8._1_3_ << 8;
        if (0xf < local_30) {
                    /* WARNING: Subroutine does not return */
          System_ShutdownHandler(local_44,uVar4);
        }
        local_30 = 0xf;
        local_34 = 0;
        local_44 = (uint)local_44._1_3_ << 8;
        goto LAB_00492f68;
      }
      if (0xf < local_30) {
                    /* WARNING: Subroutine does not return */
        System_ShutdownHandler(CONCAT31((int3)((uint)extraout_ECX_00 >> 8),cVar2),uVar4);
      }
      local_30 = 0xf;
      local_34 = 0;
      local_44 = (uint)local_44._1_3_ << 8;
    }
  }
  else {
    cVar2 = PowerUp_SpawnRapidFire(this,extraout_EDX_00,param_1,(uint)local_2c);
    uVar4 = extraout_EDX_01;
    if (cVar2 != '\0') {
      uVar7 = CONCAT44(extraout_EDX_01,local_2c);
LAB_00492f68:
      for (; (iVar5 = (int)uVar7, iVar1 = *(int *)(iVar5 + 0xc), iVar1 != 0 &&
             (uVar6 < (uint)(*(int *)(iVar5 + 0x10) - iVar1 >> 2))); uVar6 = uVar6 + 1) {
        uVar4 = *(uint *)(iVar1 + uVar6 * 4);
        if (*(char *)(uVar4 + 4) != '\0') {
          if (*(int *)((int)param_2 + 4) != 0) {
            Background_ProcessGroundLayer
                      (*(int *)((int)param_2 + 8),(uint)param_2,*(int *)((int)param_2 + 4),
                       *(int *)((int)param_2 + 8));
                    /* WARNING: Subroutine does not return */
            System_ShutdownHandler(extraout_ECX_03,extraout_EDX_04);
          }
          *(undefined4 *)((int)param_2 + 4) = 0;
          *(undefined4 *)((int)param_2 + 8) = 0;
          *(undefined4 *)((int)param_2 + 0xc) = 0;
          goto LAB_00492fc4;
        }
        Craft_ProcessCruise(param_2,uVar4 + 8);
        uVar7 = CONCAT44(extraout_EDX_03,iVar5);
      }
      local_8 = 0xffffffff;
      D3D_Clear(local_2c,(uint)((ulonglong)uVar7 >> 0x20));
      goto LAB_00492fe8;
    }
  }
LAB_00492fc4:
  local_8 = 0xffffffff;
  D3D_Clear(local_2c,uVar4);
LAB_00492fe8:
  ExceptionList = local_10;
  Exception_SetMessage((void *)(local_14 ^ unaff_retaddr),in_stack_ffffff80,in_stack_ffffff84);
  return;
}


