/*
 * Function: Exception_Handler5
 * Address: 004f3de2
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void * __fastcall Exception_Handler5(int param_1,uint param_2,void *param_3)

{
  undefined4 *puVar1;
  undefined4 extraout_ECX;
  undefined8 uVar2;
  
  puVar1 = *(undefined4 **)(param_1 + 0x18);
  Resource_LoadResource((int)param_3,param_2,'\0');
  uVar2 = Assembly_ComplexLoopingStructure(extraout_ECX);
  FID_conflict_assign(param_3,puVar1,(uint)uVar2);
  return param_3;
}


