/*
 * Function: Exception_InputProcessingCleanup
 * Address: 004a2f50
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall Exception_InputProcessingCleanup(undefined4 param_1,uint param_2)

{
  code *pcVar1;
  int unaff_EBP;
  
  Animation_ProcessNukeEffects(*(int *)(unaff_EBP + -0x14),param_2);
  CRuntime_CxxThrowException(0,0);
  pcVar1 = (code *)swi(3);
  (*pcVar1)();
  return;
}


