/*
 * Function: Exception_InitializeHandler
 * Address: 004fb60f
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall Exception_InitializeHandler(undefined4 *param_1,uint param_2)

{
  *param_1 = &PTR_Locale_InitCategory_00546fd4;
  if (param_1[2] != 0) {
                    /* WARNING: Subroutine does not return */
    System_ShutdownHandler((int)param_1,param_2);
  }
  return;
}


