/*
 * Function: Exception_STLStringCleanup
 * Address: 00457084
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall Exception_STLStringCleanup(undefined4 param_1,uint param_2)

{
  int unaff_EBP;
  
                    /* WARNING: Subroutine does not return */
  System_ShutdownHandler(*(int *)(unaff_EBP + -0x14),param_2);
}


