/*
 * Function: Font_Destructor
 * Address: 004756e0
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall Font_Destructor(undefined4 *param_1)

{
  *param_1 = &PTR_Memory_ResizeImageBuffer_00532fdc;
  DeleteObject((HGDIOBJ)param_1[5]);
  Graphics_SetColorMode(param_1);
  return;
}


