/*
 * Function: HTTP_SetRequestParams
 * Address: 004a8db0
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


undefined4 __fastcall
HTTP_SetRequestParams(void *param_1,uint param_2,_String_base *param_3,_String_base *param_4)

{
  _String_base *p_Var1;
  uint extraout_EDX;
  ulonglong uVar2;
  _String_base local_2c [4];
  int local_28;
  uint local_14;
  void *local_10;
  undefined4 uStack_c;
  undefined4 local_8;
  
  local_8 = 0xffffffff;
  uStack_c = 0x516088;
  local_10 = ExceptionList;
  ExceptionList = &local_10;
  PowerUp_ProcessThunderstrike((_String_base *)((int)param_1 + 0x28),param_2,param_3,0,0xffffffff);
  PowerUp_ProcessThunderstrike
            ((_String_base *)((int)param_1 + 0x44),extraout_EDX,param_4,0,0xffffffff);
  p_Var1 = (_String_base *)Image_CopyConstructor(local_2c,param_3,param_4);
  local_8 = 0;
  uVar2 = HTTP_SendRequest(param_1,p_Var1);
  if (0xf < local_14) {
                    /* WARNING: Subroutine does not return */
    System_ShutdownHandler(local_28,(uint)(uVar2 >> 0x20));
  }
  ExceptionList = local_10;
  return (int)uVar2;
}


