/*
 * Function: ImageFormat_ReadHeader
 * Address: 004bcf80
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __cdecl
ImageFormat_ReadHeader(void *param_1,undefined4 param_2,undefined4 *param_3,uint param_4)

{
  ImageFormat_FlipHorizontal
            (param_1,param_2,param_3,param_4,0x4fcb28,ImageFormat_ConvertRGBAToRGB,0x4fc3fd,0x4fccd6
            );
  return;
}


