/*
 * Function: Image_GetPitch
 * Address: 0049d150
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Removing unreachable block (ram,0x0049d1e1) */

void __thiscall
Image_GetPitch(void *this,uint param_1,int param_2,_String_base *param_3,_String_base *param_4)

{
  void *this_00;
  uint uVar1;
  int iVar2;
  undefined4 *unaff_ESI;
  undefined4 *in_stack_ffffffd0;
  void *local_10;
  undefined4 uStack_c;
  undefined4 local_8;
  
  this_00 = DAT_00569f5c;
  local_8 = 0xffffffff;
  uStack_c = 0x516558;
  local_10 = ExceptionList;
  ExceptionList = &local_10;
  UI_ShowProgressBar(&stack0xffffffd0,param_3,param_4);
  local_8 = 0;
  if (param_2 == 0) {
    uVar1 = 0;
  }
  else {
    uVar1 = param_2 - param_1;
  }
  if (*(uint *)((int)this + 0x18) < 0x10) {
    iVar2 = (int)this + 4;
  }
  else {
    iVar2 = *(int *)((int)this + 4);
  }
  if (param_1 != 0) {
    param_1 = param_1 - iVar2;
  }
  List_GetFirst(this,param_1,uVar1,(_String_base *)&stack0xffffffd0,0,0xffffffff);
  ExceptionList = local_10;
  Exception_SetMessage(this_00,unaff_ESI,in_stack_ffffffd0);
  return;
}


