/*
 * Function: ImageDecoder_ConvertColorSpace
 * Address: 004cdd90
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall
ImageDecoder_ConvertColorSpace
          (undefined4 param_1,undefined4 param_2,uint param_3,byte *param_4,uint param_5)

{
  void *this;
  undefined4 *in_stack_fffffff0;
  undefined4 *puVar1;
  undefined4 *in_stack_fffffff4;
  
  this = DAT_00569f5c;
  if (param_5 != 3) {
    if ((param_5 & 2) != 0) {
      Renderer_ClearBuffers(&stack0xfffffff0,(uint)*(ushort *)(param_4 + 2));
      Renderer_ClearBuffers(&stack0xfffffff2,(uint)*(ushort *)(param_4 + 4));
      Renderer_ClearBuffers(&stack0xfffffff4,(uint)*(ushort *)(param_4 + 6));
      ImageDecoder_ProcessHeader(param_3,(byte *)&DAT_00567cfc,&stack0xfffffff0,6);
      Exception_SetMessage(this,in_stack_fffffff0,in_stack_fffffff4);
      return;
    }
    Renderer_ClearBuffers(&stack0xfffffff0,(uint)*(ushort *)(param_4 + 8));
    ImageDecoder_ProcessHeader(param_3,(byte *)&DAT_00567cfc,&stack0xfffffff0,2);
    Exception_SetMessage(this,in_stack_fffffff0,in_stack_fffffff4);
    return;
  }
  if (((*(char *)(param_3 + 0x218) == '\0') || (*(short *)(param_3 + 0x118) != 0)) &&
     (*(ushort *)(param_3 + 0x118) < (ushort)*param_4)) {
    CPU_Instruction21(param_4,(byte *)CONCAT22((short)((uint)param_2 >> 0x10),(ushort)*param_4),
                      param_3,"Invalid background palette index");
    Exception_SetMessage(this,in_stack_fffffff0,in_stack_fffffff4);
    return;
  }
  puVar1 = (undefined4 *)CONCAT31((int3)((uint)in_stack_fffffff0 >> 8),*param_4);
  ImageDecoder_ProcessHeader(param_3,(byte *)&DAT_00567cfc,&stack0xfffffff0,1);
  Exception_SetMessage(this,puVar1,in_stack_fffffff4);
  return;
}


