/*
 * Function: Image_Clone
 * Address: 0049de80
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __cdecl Image_Clone(void *param_1,int param_2)

{
  void *this;
  char *pcVar1;
  char *pcVar2;
  undefined4 *in_stack_ffffffc0;
  undefined4 *in_stack_ffffffc4;
  
  this = DAT_00569f5c;
  if (-0x7789fdb4 < param_2) {
    if (param_2 < -0x7789fd93) {
      if (param_2 == -0x7789fd94) {
        pcVar2 = "DDERR_DCALREADYCREATED";
        goto LAB_0049e873;
      }
      switch(param_2) {
      case -0x7789fdb3:
        pcVar2 = "DDERR_NOTPALETTIZED";
        break;
      case -0x7789fdb2:
        pcVar2 = "DDERR_UNSUPPORTEDMODE";
        break;
      case -0x7789fdb1:
        pcVar2 = "DDERR_NOMIPMAPHW";
        break;
      case -0x7789fdb0:
        pcVar2 = "DDERR_INVALIDSURFACETYPE";
        break;
      default:
        goto switchD_0049df79_caseD_88760006;
      case -0x7789fda8:
        pcVar2 = "DDERR_NOOPTIMIZEHW";
        break;
      case -0x7789fda7:
        pcVar2 = "DDERR_NOTLOADED";
        break;
      case -0x7789fda6:
        pcVar2 = "DDERR_NOFOCUSWINDOW";
      }
      goto LAB_0049e873;
    }
    if (param_2 < -0x7789fd07) {
      if (param_2 == -0x7789fd08) {
        pcVar2 = "D3DERR_SCENE_IN_SCENE";
        goto LAB_0049e873;
      }
      switch(param_2) {
      case -0x7789fd8a:
        pcVar2 = "DDERR_NONONLOCALVIDMEM";
        break;
      default:
        goto switchD_0049df79_caseD_88760006;
      case -0x7789fd80:
        pcVar2 = "DDERR_CANTPAGELOCK";
        break;
      case -0x7789fd6c:
        pcVar2 = "DDERR_CANTPAGEUNLOCK";
        break;
      case -0x7789fd58:
        pcVar2 = "DDERR_NOTPAGELOCKED";
        break;
      case -0x7789fd4e:
        pcVar2 = "DDERR_MOREDATA";
        break;
      case -0x7789fd4d:
        pcVar2 = "DDERR_EXPIRED";
        break;
      case -0x7789fd49:
        pcVar2 = "DDERR_VIDEONOTACTIVE";
        break;
      case -0x7789fd45:
        pcVar2 = "DDERR_DEVICEDOESNTOWNSURFACE";
        break;
      case -0x7789fd44:
        pcVar2 = "D3DERR_BADMAJORVERSION";
        break;
      case -0x7789fd43:
        pcVar2 = "D3DERR_BADMINORVERSION";
        break;
      case -0x7789fd3f:
        pcVar2 = "D3DERR_INVALID_DEVICE";
        break;
      case -0x7789fd3e:
        pcVar2 = "D3DERR_INITFAILED";
        break;
      case -0x7789fd3d:
        pcVar2 = "D3DERR_DEVICEAGGREGATED";
        break;
      case -0x7789fd30:
        pcVar2 = "D3DERR_TEXTURE_NO_SUPPORT";
        break;
      case -0x7789fd2f:
        pcVar2 = "D3DERR_TEXTURE_CREATE_FAILED";
        break;
      case -0x7789fd2e:
        pcVar2 = "D3DERR_TEXTURE_DESTROY_FAILED";
        break;
      case -0x7789fd2d:
        pcVar2 = "D3DERR_TEXTURE_LOCK_FAILED";
        break;
      case -0x7789fd2c:
        pcVar2 = "D3DERR_TEXTURE_UNLOCK_FAILED";
        break;
      case -0x7789fd2b:
        pcVar2 = "D3DERR_TEXTURE_LOAD_FAILED";
        break;
      case -0x7789fd2a:
        pcVar2 = "D3DERR_TEXTURE_SWAP_FAILED";
        break;
      case -0x7789fd29:
        pcVar2 = "D3DERR_TEXTURE_LOCKED";
        break;
      case -0x7789fd28:
        pcVar2 = "D3DERR_TEXTURE_NOT_LOCKED";
        break;
      case -0x7789fd27:
        pcVar2 = "D3DERR_TEXTURE_GETSURF_FAILED";
        break;
      case -0x7789fd26:
        pcVar2 = "D3DERR_MATRIX_CREATE_FAILED";
        break;
      case -0x7789fd25:
        pcVar2 = "D3DERR_MATRIX_DESTROY_FAILED";
        break;
      case -0x7789fd24:
        pcVar2 = "D3DERR_MATRIX_SETDATA_FAILED";
        break;
      case -0x7789fd23:
        pcVar2 = "D3DERR_MATRIX_GETDATA_FAILED";
        break;
      case -0x7789fd22:
        pcVar2 = "D3DERR_SETVIEWPORTDATA_FAILED";
        break;
      case -0x7789fd21:
        pcVar2 = "D3DERR_INVALIDCURRENTVIEWPORT";
        break;
      case -0x7789fd20:
        pcVar2 = "D3DERR_INVALIDPRIMITIVETYPE";
        break;
      case -0x7789fd1f:
        pcVar2 = "D3DERR_INVALIDVERTEXTYPE";
        break;
      case -0x7789fd1e:
        pcVar2 = "D3DERR_TEXTURE_BADSIZE";
        break;
      case -0x7789fd1d:
        pcVar2 = "D3DERR_INVALIDRAMPTEXTURE";
        break;
      case -0x7789fd1c:
        pcVar2 = "D3DERR_MATERIAL_CREATE_FAILED";
        break;
      case -0x7789fd1b:
        pcVar2 = "D3DERR_MATERIAL_DESTROY_FAILED";
        break;
      case -0x7789fd1a:
        pcVar2 = "D3DERR_MATERIAL_SETDATA_FAILED";
        break;
      case -0x7789fd19:
        pcVar2 = "D3DERR_MATERIAL_GETDATA_FAILED";
        break;
      case -0x7789fd18:
        pcVar2 = "D3DERR_INVALIDPALETTE";
        break;
      case -0x7789fd17:
        pcVar2 = "D3DERR_ZBUFF_NEEDS_SYSTEMMEMORY";
        break;
      case -0x7789fd16:
        pcVar2 = "D3DERR_ZBUFF_NEEDS_VIDEOMEMORY";
        break;
      case -0x7789fd15:
        pcVar2 = "D3DERR_SURFACENOTINVIDMEM";
        break;
      case -0x7789fd12:
        pcVar2 = "D3DERR_LIGHT_SET_FAILED";
        break;
      case -0x7789fd11:
        pcVar2 = "D3DERR_LIGHTHASVIEWPORT";
        break;
      case -0x7789fd10:
        pcVar2 = "D3DERR_LIGHTNOTINTHISVIEWPORT";
      }
      goto LAB_0049e873;
    }
    if (-0x7789f7e4 < param_2) {
      if (param_2 < -0x7787fff5) {
        if (param_2 == -0x7787fff6) {
          pcVar2 = "DSERR_ALLOCATED";
          goto LAB_0049e873;
        }
        switch(param_2) {
        case -0x7789f7e3:
          pcVar2 = "D3DERR_TOOMANYOPERATIONS";
          break;
        case -0x7789f7e2:
          pcVar2 = "D3DERR_CONFLICTINGTEXTUREFILTER";
          break;
        case -0x7789f7e1:
          pcVar2 = "D3DERR_UNSUPPORTEDFACTORVALUE";
          break;
        default:
          goto switchD_0049df79_caseD_88760006;
        case -0x7789f7df:
          pcVar2 = "D3DERR_CONFLICTINGRENDERSTATE";
          break;
        case -0x7789f7de:
          pcVar2 = "D3DERR_UNSUPPORTEDTEXTUREFILTER";
          break;
        case -0x7789f7dd:
          pcVar2 = "D3DERR_TOOMANYPRIMITIVES";
          break;
        case -0x7789f7dc:
          pcVar2 = "D3DERR_INVALIDMATRIX";
          break;
        case -0x7789f7da:
          pcVar2 = "D3DERR_CONFLICTINGTEXTUREPALETTE";
          break;
        case -0x7789f7cc:
          pcVar2 = "D3DERR_INVALIDSTATEBLOCK";
          break;
        case -0x7789f7cb:
          pcVar2 = "D3DERR_INBEGINSTATEBLOCK";
          break;
        case -0x7789f7ca:
          pcVar2 = "D3DERR_NOTINBEGINSTATEBLOCK";
        }
        goto LAB_0049e873;
      }
      switch(param_2) {
      case -0x7787ffe2:
        pcVar2 = "DSERR_CONTROLUNAVAIL";
        break;
      default:
        goto switchD_0049df79_caseD_88760006;
      case -0x7787ffce:
        pcVar2 = "DSERR_INVALIDCALL";
        break;
      case -0x7787ffba:
        pcVar2 = "DSERR_PRIOLEVELNEEDED";
        break;
      case -0x7787ff9c:
        pcVar2 = "DSERR_BADFORMAT";
        break;
      case -0x7787ff88:
        pcVar2 = "DSERR_NODRIVER";
        break;
      case -0x7787ff7e:
        pcVar2 = "DSERR_ALREADYINITIALIZED";
        break;
      case -0x7787ff6a:
        pcVar2 = "DSERR_BUFFERLOST";
        break;
      case -0x7787ff60:
        pcVar2 = "DSERR_OTHERAPPHASPRIO";
        break;
      case -0x7787ff56:
        pcVar2 = "DSERR_UNINITIALIZED";
      }
      goto LAB_0049e873;
    }
    if (param_2 == -0x7789f7e4) {
      pcVar2 = "D3DERR_UNSUPPORTEDALPHAARG";
      goto LAB_0049e873;
    }
    if (-0x7789f7fe < param_2) {
      switch(param_2) {
      case -0x7789f7f4:
        pcVar2 = "D3DERR_VERTEXBUFFEROPTIMIZED";
        break;
      case -0x7789f7f3:
        pcVar2 = "D3DERR_VBUF_CREATE_FAILED";
        break;
      case -0x7789f7f2:
        pcVar2 = "D3DERR_VERTEXBUFFERLOCKED";
        break;
      case -0x7789f7f1:
        pcVar2 = "D3DERR_VERTEXBUFFERUNLOCKFAILED";
        break;
      default:
        goto switchD_0049df79_caseD_88760006;
      case -0x7789f7ea:
        pcVar2 = "D3DERR_ZBUFFER_NOTPRESENT";
        break;
      case -0x7789f7e9:
        pcVar2 = "D3DERR_STENCILBUFFER_NOTPRESENT";
        break;
      case -0x7789f7e8:
        pcVar2 = "D3DERR_WRONGTEXTUREFORMAT";
        break;
      case -0x7789f7e7:
        pcVar2 = "D3DERR_UNSUPPORTEDCOLOROPERATION";
        break;
      case -0x7789f7e6:
        pcVar2 = "D3DERR_UNSUPPORTEDCOLORARG";
        break;
      case -0x7789f7e5:
        pcVar2 = "D3DERR_UNSUPPORTEDALPHAOPERATION";
      }
      goto LAB_0049e873;
    }
    if (param_2 == -0x7789f7fe) {
      pcVar2 = "D3DERR_COLORKEYATTACHED";
      goto LAB_0049e873;
    }
    if (param_2 < -0x7789fcfb) {
      if (param_2 == -0x7789fcfc) {
        pcVar2 = "D3DERR_NOVIEWPORTS";
        goto LAB_0049e873;
      }
      switch(param_2) {
      case -0x7789fd07:
        pcVar2 = "D3DERR_SCENE_NOT_IN_SCENE";
        break;
      case -0x7789fd06:
        pcVar2 = "D3DERR_SCENE_BEGIN_FAILED";
        break;
      case -0x7789fd05:
        pcVar2 = "D3DERR_SCENE_END_FAILED";
        break;
      default:
        goto switchD_0049df79_caseD_88760006;
      case -0x7789fcfe:
        pcVar2 = "D3DERR_INBEGIN";
        break;
      case -0x7789fcfd:
        pcVar2 = "D3DERR_NOTINBEGIN";
      }
      goto LAB_0049e873;
    }
    if (param_2 < -0x7789fcf8) {
      if (param_2 == -0x7789fcf9) {
        pcVar2 = "D3DERR_NOCURRENTVIEWPORT";
        goto LAB_0049e873;
      }
      if (param_2 == -0x7789fcfb) {
        pcVar2 = "D3DERR_VIEWPORTDATANOTSET";
        goto LAB_0049e873;
      }
      if (param_2 == -0x7789fcfa) {
        pcVar2 = "D3DERR_VIEWPORTHASNODEVICE";
        goto LAB_0049e873;
      }
    }
    else if (param_2 == -0x7789f800) {
      pcVar2 = "D3DERR_INVALIDVERTEXFORMAT";
      goto LAB_0049e873;
    }
    goto switchD_0049df79_caseD_88760006;
  }
  if (param_2 == -0x7789fdb4) {
    *(undefined4 *)((int)param_1 + 0x18) = 0xf;
    *(undefined4 *)((int)param_1 + 0x14) = 0;
    *(undefined1 *)((int)param_1 + 4) = 0;
    pcVar2 = "DDERR_IMPLICITLYCREATED";
    do {
      pcVar1 = pcVar2;
      pcVar2 = pcVar1 + 1;
    } while (*pcVar1 != '\0');
    String_Assign(param_1,(_String_base *)"DDERR_IMPLICITLYCREATED",(uint)(pcVar1 + -0x534e70));
    Exception_SetMessage(this,in_stack_ffffffc0,in_stack_ffffffc4);
    return;
  }
  if (-0x7789fe98 < param_2) {
    switch(param_2) {
    case -0x7789fe84:
      pcVar2 = "DDERR_OUTOFVIDEOMEMORY";
      break;
    default:
      goto switchD_0049df79_caseD_88760006;
    case -0x7789fe82:
      pcVar2 = "DDERR_OVERLAYCANTCLIP";
      break;
    case -0x7789fe80:
      pcVar2 = "DDERR_OVERLAYCOLORKEYONLYONEACTIVE";
      break;
    case -0x7789fe7d:
      pcVar2 = "DDERR_PALETTEBUSY";
      break;
    case -0x7789fe70:
      pcVar2 = "DDERR_COLORKEYNOTSET";
      break;
    case -0x7789fe66:
      pcVar2 = "DDERR_SURFACEALREADYATTACHED";
      break;
    case -0x7789fe5c:
      pcVar2 = "DDERR_SURFACEALREADYDEPENDENT";
      break;
    case -0x7789fe52:
      pcVar2 = "DDERR_SURFACEBUSY";
      break;
    case -0x7789fe4d:
      pcVar2 = "DDERR_CANTLOCKSURFACE";
      break;
    case -0x7789fe48:
      pcVar2 = "DDERR_SURFACEISOBSCURED";
      break;
    case -0x7789fe3e:
      pcVar2 = "DDERR_SURFACELOST";
      break;
    case -0x7789fe34:
      pcVar2 = "DDERR_SURFACENOTATTACHED";
      break;
    case -0x7789fe2a:
      pcVar2 = "DDERR_TOOBIGHEIGHT";
      break;
    case -0x7789fe20:
      pcVar2 = "DDERR_TOOBIGSIZE";
      break;
    case -0x7789fe16:
      pcVar2 = "DDERR_TOOBIGWIDTH";
      break;
    case -0x7789fe02:
      pcVar2 = "DDERR_UNSUPPORTEDFORMAT";
      break;
    case -0x7789fdf8:
      pcVar2 = "DDERR_UNSUPPORTEDMASK";
      break;
    case -0x7789fdf7:
      pcVar2 = "DDERR_INVALIDSTREAM";
      break;
    case -0x7789fde7:
      pcVar2 = "DDERR_VERTICALBLANKINPROGRESS";
      break;
    case -0x7789fde4:
      pcVar2 = "DDERR_WASSTILLDRAWING";
      break;
    case -0x7789fdd0:
      pcVar2 = "DDERR_XALIGN";
      break;
    case -0x7789fdcf:
      pcVar2 = "DDERR_INVALIDDIRECTDRAWGUID";
      break;
    case -0x7789fdce:
      pcVar2 = "DDERR_DIRECTDRAWALREADYCREATED";
      break;
    case -0x7789fdcd:
      pcVar2 = "DDERR_NODIRECTDRAWHW";
      break;
    case -0x7789fdcc:
      pcVar2 = "DDERR_PRIMARYSURFACEALREADYEXISTS";
      break;
    case -0x7789fdcb:
      pcVar2 = "DDERR_NOEMULATION";
      break;
    case -0x7789fdca:
      pcVar2 = "DDERR_REGIONTOOSMALL";
      break;
    case -0x7789fdc9:
      pcVar2 = "DDERR_CLIPPERISUSINGHWND";
      break;
    case -0x7789fdc8:
      pcVar2 = "DDERR_NOCLIPPERATTACHED";
      break;
    case -0x7789fdc7:
      pcVar2 = "DDERR_NOHWND";
      break;
    case -0x7789fdc6:
      pcVar2 = "DDERR_HWNDSUBCLASSED";
      break;
    case -0x7789fdc5:
      pcVar2 = "DDERR_HWNDALREADYSET";
      break;
    case -0x7789fdc4:
      pcVar2 = "DDERR_NOPALETTEATTACHED";
      break;
    case -0x7789fdc3:
      pcVar2 = "DDERR_NOPALETTEHW";
      break;
    case -0x7789fdc2:
      pcVar2 = "DDERR_BLTFASTCANTCLIP";
      break;
    case -0x7789fdc1:
      pcVar2 = "DDERR_NOBLTHW";
      break;
    case -0x7789fdc0:
      pcVar2 = "DDERR_NODDROPSHW";
      break;
    case -0x7789fdbf:
      pcVar2 = "DDERR_OVERLAYNOTVISIBLE";
      break;
    case -0x7789fdbd:
      pcVar2 = "DDERR_INVALIDPOSITION";
      break;
    case -0x7789fdbc:
      pcVar2 = "DDERR_NOTAOVERLAYSURFACE";
      break;
    case -0x7789fdbb:
      pcVar2 = "DDERR_EXCLUSIVEMODEALREADYSET";
      break;
    case -0x7789fdba:
      pcVar2 = "DDERR_NOTFLIPPABLE";
      break;
    case -0x7789fdb9:
      pcVar2 = "DDERR_CANTDUPLICATE";
      break;
    case -0x7789fdb8:
      pcVar2 = "DDERR_NOTLOCKED";
      break;
    case -0x7789fdb7:
      pcVar2 = "DDERR_CANTCREATEDC";
      break;
    case -0x7789fdb6:
      pcVar2 = "DDERR_NODC";
      break;
    case -0x7789fdb5:
      pcVar2 = "DDERR_WRONGMODE";
    }
    goto LAB_0049e873;
  }
  if (param_2 == -0x7789fe98) {
    pcVar2 = "DDERR_OUTOFCAPS";
    goto LAB_0049e873;
  }
  if (-0x7789ff4a < param_2) {
    switch(param_2) {
    case -0x7789ff33:
      pcVar2 = "DDERR_NOCLIPLIST";
      break;
    default:
      goto switchD_0049df79_caseD_88760006;
    case -0x7789ff2e:
      pcVar2 = "DDERR_NOCOLORCONVHW";
      break;
    case -0x7789ff2c:
      pcVar2 = "DDERR_NOCOOPERATIVELEVELSET";
      break;
    case -0x7789ff29:
      pcVar2 = "DDERR_NOCOLORKEY";
      break;
    case -0x7789ff24:
      pcVar2 = "DDERR_NOCOLORKEYHW";
      break;
    case -0x7789ff22:
      pcVar2 = "DDERR_NODIRECTDRAWSUPPORT";
      break;
    case -0x7789ff1f:
      pcVar2 = "DDERR_NOEXCLUSIVEMODE";
      break;
    case -0x7789ff1a:
      pcVar2 = "DDERR_NOFLIPHW";
      break;
    case -0x7789ff10:
      pcVar2 = "DDERR_NOGDI";
      break;
    case -0x7789ff06:
      pcVar2 = "DDERR_NOMIRRORHW";
      break;
    case -0x7789ff01:
      pcVar2 = "DDERR_NOTFOUND";
      break;
    case -0x7789fefc:
      pcVar2 = "DDERR_NOOVERLAYHW";
      break;
    case -0x7789fef2:
      pcVar2 = "DDERR_OVERLAPPINGRECTS";
      break;
    case -0x7789fee8:
      pcVar2 = "DDERR_NORASTEROPHW";
      break;
    case -0x7789fede:
      pcVar2 = "DDERR_NOROTATIONHW";
      break;
    case -0x7789feca:
      pcVar2 = "DDERR_NOSTRETCHHW";
      break;
    case -0x7789fec4:
      pcVar2 = "DDERR_NOT4BITCOLOR";
      break;
    case -0x7789fec3:
      pcVar2 = "DDERR_NOT4BITCOLORINDEX";
      break;
    case -0x7789fec0:
      pcVar2 = "DDERR_NOT8BITCOLOR";
      break;
    case -0x7789feb6:
      pcVar2 = "DDERR_NOTEXTUREHW";
      break;
    case -0x7789feb1:
      pcVar2 = "DDERR_NOVSYNCHW";
      break;
    case -0x7789feac:
      pcVar2 = "DDERR_NOZBUFFERHW";
      break;
    case -0x7789fea2:
      pcVar2 = "DDERR_NOZOVERLAYHW";
    }
    goto LAB_0049e873;
  }
  if (param_2 == -0x7789ff4a) {
    pcVar2 = "DDERR_NOSURFACELEFT";
    goto LAB_0049e873;
  }
  if (-0x7789ffa6 < param_2) {
    switch(param_2) {
    case -0x7789ffa1:
      pcVar2 = "DDERR_INCOMPATIBLEPRIMARY";
      break;
    default:
      goto switchD_0049df79_caseD_88760006;
    case -0x7789ff9c:
      pcVar2 = "DDERR_INVALIDCAPS";
      break;
    case -0x7789ff92:
      pcVar2 = "DDERR_INVALIDCLIPLIST";
      break;
    case -0x7789ff88:
      pcVar2 = "DDERR_INVALIDMODE";
      break;
    case -0x7789ff7e:
      pcVar2 = "DDERR_INVALIDOBJECT";
      break;
    case -0x7789ff6f:
      pcVar2 = "DDERR_INVALIDPIXELFORMAT";
      break;
    case -0x7789ff6a:
      pcVar2 = "DDERR_INVALIDRECT";
      break;
    case -0x7789ff60:
      pcVar2 = "DDERR_LOCKEDSURFACES";
      break;
    case -0x7789ff56:
      pcVar2 = "DDERR_NO3D";
      break;
    case -0x7789ff4c:
      pcVar2 = "DDERR_NOALPHAHW";
      break;
    case -0x7789ff4b:
      pcVar2 = "DDERR_NOSTEREOHARDWARE";
    }
    goto LAB_0049e873;
  }
  if (param_2 == -0x7789ffa6) {
    pcVar2 = "DDERR_HEIGHTALIGN";
    goto LAB_0049e873;
  }
  if (param_2 < -0x7ff8ffa8) {
    if (param_2 == -0x7ff8ffa9) {
      pcVar2 = "DDERR_INVALIDPARAMS";
      goto LAB_0049e873;
    }
    if (param_2 < -0x7ffbfeef) {
      if (param_2 == -0x7ffbfef0) {
        pcVar2 = "DSERR_NOAGGREGATION";
        goto LAB_0049e873;
      }
      if (param_2 == -0x7fffbfff) {
        pcVar2 = "DDERR_UNSUPPORTED";
        goto LAB_0049e873;
      }
      if (param_2 == -0x7fffbffe) {
        pcVar2 = "DSERR_NOINTERFACE";
        goto LAB_0049e873;
      }
      if (param_2 == -0x7fffbffb) {
        pcVar2 = "DSERR_GENERIC";
        goto LAB_0049e873;
      }
    }
    else {
      if (param_2 == -0x7ffbfe10) {
        pcVar2 = "DDERR_NOTINITIALIZED";
        goto LAB_0049e873;
      }
      if (param_2 == -0x7ff8fff2) {
        pcVar2 = "E_OUTOFMEMORY";
        goto LAB_0049e873;
      }
    }
switchD_0049df79_caseD_88760006:
    Exception_Release(&stack0xffffffc0,&DAT_0053447c);
    pcVar2 = &stack0xffffffc0;
  }
  else {
    switch(param_2) {
    case -0x7789fffb:
      pcVar2 = "DDERR_ALREADYINITIALIZED";
      break;
    default:
      goto switchD_0049df79_caseD_88760006;
    case -0x7789fff6:
      pcVar2 = "DDERR_CANNOTATTACHSURFACE";
      break;
    case -0x7789ffec:
      pcVar2 = "DDERR_CANNOTDETACHSURFACE";
      break;
    case -0x7789ffd8:
      pcVar2 = "DDERR_CURRENTLYNOTAVAIL";
      break;
    case -0x7789ffc9:
      pcVar2 = "DDERR_EXCEPTION";
    }
  }
LAB_0049e873:
  Level_InitializeDictastroika(param_1,pcVar2);
  Exception_SetMessage(this,in_stack_ffffffc0,in_stack_ffffffc4);
  return;
}


