/*
 * Function: Image_CopyDirectPixels
 * Address: 004d95e0
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __cdecl Image_CopyDirectPixels(int param_1,int param_2,int param_3,int param_4)

{
  Math_RoundUpToPowerOf2(param_3,0,param_4,0,*(int *)(param_1 + 0xdc),*(uint *)(param_1 + 0x1c));
  Image_FillPixelBoundaries
            ((void *)(*(int *)(param_2 + 0x1c) << 3),param_4,*(int *)(param_1 + 0xdc),
             *(int *)(param_1 + 0x1c));
  return;
}


