/*
 * Function: LinkedList_Destructor
 * Address: 004027f0
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall LinkedList_Destructor(int param_1,uint param_2)

{
  if (0xf < *(uint *)(param_1 + 0x50)) {
                    /* WARNING: Subroutine does not return */
    System_ShutdownHandler(param_1,param_2);
  }
  *(undefined4 *)(param_1 + 0x50) = 0xf;
  *(undefined4 *)(param_1 + 0x4c) = 0;
  *(undefined1 *)(param_1 + 0x3c) = 0;
  if (0xf < *(uint *)(param_1 + 0x34)) {
                    /* WARNING: Subroutine does not return */
    System_ShutdownHandler(param_1,param_2);
  }
  *(undefined4 *)(param_1 + 0x34) = 0xf;
  *(undefined4 *)(param_1 + 0x30) = 0;
  *(undefined1 *)(param_1 + 0x20) = 0;
  if (0xf < *(uint *)(param_1 + 0x18)) {
                    /* WARNING: Subroutine does not return */
    System_ShutdownHandler(param_1,param_2);
  }
  *(undefined4 *)(param_1 + 0x18) = 0xf;
  *(undefined4 *)(param_1 + 0x14) = 0;
  *(undefined1 *)(param_1 + 4) = 0;
  return;
}


