/*
 * Function: Locale_GetWCharNumericFacet
 * Address: 004ee4b9
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


facet * Locale_GetWCharNumericFacet(void)

{
  uint uVar1;
  facet *this;
  int iVar2;
  int unaff_EBP;
  
  Assembly_BitShiftLocking();
  Threading_LockSectorByIndex((void *)(unaff_EBP + -0x10),0);
  *(undefined4 *)(unaff_EBP + -4) = 0;
  uVar1 = std::locale::id::Operator_CastToUnsignedInt((id *)&DAT_005a4994);
  this = std::locale::_Getfacet(*(locale **)(unaff_EBP + 8),uVar1);
  if ((this == (facet *)0x0) && (this = DAT_005a48f8, DAT_005a48f8 == (facet *)0x0)) {
    iVar2 = Getcat();
    if (iVar2 == -1) {
      Exception_Constructor((exception *)(unaff_EBP + -0x1c));
      CRuntime_CxxThrowException(unaff_EBP + -0x1c,&DAT_005511f0);
    }
    this = DAT_005a48f8;
    RefCount_Increment((int)DAT_005a48f8);
    std::locale::facet::_Register(this);
  }
  *(undefined4 *)(unaff_EBP + -4) = 0xffffffff;
  Threading_UnlockSectorByIndex((int *)(unaff_EBP + -0x10));
  ExceptionList = *(void **)(unaff_EBP + -0xc);
  return this;
}


