/*
 * Function: Locale_ToLower
 * Address: 00475d70
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __thiscall Locale_ToLower(void *this,byte param_1)

{
  Locale_ToUpperCase((uint)param_1,(int *)((int)this + 8));
  return;
}


