/*
 * Function: Log_WriteInfo
 * Address: 0044f759
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


INT_PTR Log_WriteInfo(void)

{
  LPWSTR pWVar1;
  undefined4 *puVar2;
  int iVar3;
  INT_PTR IVar4;
  DWORD DVar5;
  LPCDLGTEMPLATEA unaff_EDI;
  
  puVar2 = (undefined4 *)GlobalLock(unaff_EDI);
  *(undefined2 *)((int)puVar2 + 10) = 10;
  *(undefined2 *)(puVar2 + 3) = 10;
  *puVar2 = 0x80c800c0;
  *(undefined2 *)(puVar2 + 2) = 1;
  *(undefined2 *)((int)puVar2 + 0xe) = 200;
  *(undefined2 *)(puVar2 + 4) = 200;
  *(undefined2 *)((int)puVar2 + 0x12) = 0;
  *(undefined2 *)(puVar2 + 5) = 0;
  iVar3 = MultiByteToWideChar(0,0,"Marker List",-1,(LPWSTR)((int)puVar2 + 0x16),0x32);
  pWVar1 = (LPWSTR)((int)puVar2 + 0x16) + iVar3;
  *pWVar1 = L'\b';
  MultiByteToWideChar(0,0,"Tahoma",-1,pWVar1 + 1,0x32);
  puVar2 = (undefined4 *)System_Sleep();
  *(undefined2 *)(puVar2 + 3) = 0xbe;
  *(undefined2 *)((int)puVar2 + 0xe) = 0xc3;
  *(undefined2 *)(puVar2 + 4) = 100;
  *puVar2 = 0x50300001;
  puVar2[1] = 0x200;
  *(undefined2 *)(puVar2 + 2) = 5;
  *(undefined2 *)((int)puVar2 + 10) = 5;
  *(undefined2 *)((int)puVar2 + 0x12) = 0xffff;
  *(undefined2 *)(puVar2 + 5) = 0x83;
  *(undefined2 *)((int)puVar2 + 0x16) = 0;
  *(undefined2 *)(puVar2 + 6) = 0;
  GlobalUnlock(unaff_EDI);
  IVar4 = DialogBoxIndirectParamA
                    (DAT_005a33c0,unaff_EDI,*(HWND *)(DAT_0056da10 + 0x30c),Log_WriteError,0);
  GlobalFree(unaff_EDI);
  DVar5 = timeGetTime();
  *(DWORD *)(DAT_0056da10 + 0x404) = DVar5;
  return IVar4;
}


