/*
 * Function: Math_MatrixMultiply
 * Address: 004f082d
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void Math_MatrixMultiply(void)

{
  void *this;
  undefined4 *puVar1;
  int *piVar2;
  undefined4 uVar3;
  undefined4 uVar4;
  uint *puVar5;
  int unaff_EBP;
  undefined8 uVar6;
  int iVar7;
  int iVar8;
  int iVar9;
  undefined4 *in_stack_ffffffd8;
  undefined4 *in_stack_ffffffdc;
  
  Assembly_BitShiftLocking();
  *(uint *)(unaff_EBP + -0x10) = DAT_00569f5c ^ *(uint *)(unaff_EBP + 4);
  puVar1 = (undefined4 *)System_GetSystemInfo();
  *puVar1 = 0;
  this = *(void **)(unaff_EBP + 0x1c);
  piVar2 = SexyWidget_ProcessInput(this,(int *)(unaff_EBP + 0x1c));
  uVar4 = *(undefined4 *)((int)this + 0xc);
  *(undefined4 *)(unaff_EBP + -4) = 0;
  iVar9 = unaff_EBP + 0x14;
  iVar8 = unaff_EBP + 0xc;
  iVar7 = unaff_EBP + -0x34;
  uVar3 = Math_RandomFloat();
  uVar6 = func_0x004fe4d6(unaff_EBP + -0x34,unaff_EBP + -0x14,uVar3,iVar7,iVar8,iVar9,uVar4,piVar2);
  *(undefined4 *)(unaff_EBP + -4) = 0xffffffff;
  SmartPointer_Destructor((uint *)(unaff_EBP + 0x1c));
  uVar4 = equal((void *)(unaff_EBP + 0xc),(int *)(unaff_EBP + 0x14));
  puVar5 = *(uint **)(unaff_EBP + 0x20);
  if ((char)uVar4 != '\0') {
    *puVar5 = *puVar5 | 1;
  }
  if (*(int *)(unaff_EBP + -0x14) != unaff_EBP + -0x34) {
    piVar2 = (int *)System_GetSystemInfo();
    if (*piVar2 == 0) {
      **(undefined8 **)(unaff_EBP + 0x24) = uVar6;
      goto LAB_004f08d0;
    }
    puVar5 = *(uint **)(unaff_EBP + 0x20);
  }
  *puVar5 = *puVar5 | 2;
LAB_004f08d0:
  puVar1 = *(undefined4 **)(unaff_EBP + 8);
  *puVar1 = *(undefined4 *)(unaff_EBP + 0xc);
  puVar1[1] = *(undefined4 *)(unaff_EBP + 0x10);
  ExceptionList = *(void **)(unaff_EBP + -0xc);
  Exception_SetMessage
            ((void *)(*(uint *)(unaff_EBP + -0x10) ^ *(uint *)(unaff_EBP + 4)),in_stack_ffffffd8,
             in_stack_ffffffdc);
  return;
}


