/*
 * Function: Mutex_Destroy
 * Address: 004e0c80
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __cdecl Mutex_Destroy(int param_1)

{
  int iVar1;
  
  iVar1 = *(int *)(param_1 + 0x1a0);
  *(undefined1 *)(iVar1 + 0x24) = 0;
  *(undefined4 *)(iVar1 + 0x2c) = *(undefined4 *)(param_1 + 0x60);
  return;
}


