/*
 * Function: PixelFormat_ConvertBGRToRGB
 * Address: 004c1c00
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __cdecl PixelFormat_ConvertBGRToRGB(uint param_1)

{
  int iVar1;
  void *this;
  byte bVar2;
  int iVar3;
  uint extraout_ECX;
  uint extraout_ECX_00;
  uint extraout_ECX_01;
  uint uVar4;
  uint extraout_ECX_02;
  byte *extraout_EDX;
  byte *extraout_EDX_00;
  byte *extraout_EDX_01;
  byte *pbVar5;
  byte *extraout_EDX_02;
  undefined4 *in_stack_ffffffc4;
  undefined4 *in_stack_ffffffc8;
  
  this = DAT_00569f5c;
  if (*(int *)(param_1 + 0xec) == 0) {
    Exception_Release(&stack0xffffffc4,"NULL row buffer for row %ld, pass %d");
    CPU_Instruction20(extraout_ECX,extraout_EDX,param_1,&stack0xffffffc4);
  }
  if ((*(uint *)(param_1 + 0x70) & 0x1000) != 0) {
    if (*(char *)(param_1 + 0x108) == '\x03') {
      PixelFormat_GetPixelSize
                ((uint *)(param_1 + 0x100),*(int *)(param_1 + 0xec) + 1,*(int *)(param_1 + 0x114),
                 *(int *)(param_1 + 0x188),(uint)*(ushort *)(param_1 + 0x11a));
    }
    else {
      if (*(short *)(param_1 + 0x11a) == 0) {
        iVar1 = *(int *)(param_1 + 0xec);
        iVar3 = 0;
      }
      else {
        iVar1 = *(int *)(param_1 + 0xec);
        iVar3 = param_1 + 0x18c;
      }
      PixelFormat_GetChannelMask((int *)(param_1 + 0x100),iVar1 + 1,iVar3);
    }
  }
  if ((*(uint *)(param_1 + 0x70) & 0x40000) != 0) {
    ImageFormat_OptimizePalette
              ((uint *)(param_1 + 0x100),(undefined1 *)(*(int *)(param_1 + 0xec) + 1),-0x80);
  }
  if ((*(uint *)(param_1 + 0x70) & 0x600000) != 0) {
    iVar3 = Compression_ValidateData
                      (param_1,(int *)(param_1 + 0x100),(byte *)(*(int *)(param_1 + 0xec) + 1));
    if (iVar3 != 0) {
      *(undefined1 *)(param_1 + 0x214) = 1;
      uVar4 = extraout_ECX_00;
      pbVar5 = extraout_EDX_00;
      if (*(int *)(param_1 + 0x70) == 0x400000) {
        CPU_Instruction21(extraout_ECX_00,extraout_EDX_00,param_1,
                          "png_do_rgb_to_gray found nongray pixel");
        uVar4 = extraout_ECX_01;
        pbVar5 = extraout_EDX_01;
      }
      if (*(int *)(param_1 + 0x70) == 0x200000) {
        CPU_Instruction20(uVar4,pbVar5,param_1,"png_do_rgb_to_gray found nongray pixel");
      }
    }
  }
  if (((*(uint *)(param_1 + 0x70) & 0x4000) != 0) && ((*(uint *)(param_1 + 0x6c) & 0x20000) == 0)) {
    Compression_GetLevel((int *)(param_1 + 0x100),*(int *)(param_1 + 0xec) + 1);
  }
  if ((*(char *)(param_1 + 0x70) < '\0') &&
     ((*(short *)(param_1 + 0x11a) != 0 || ((*(byte *)(param_1 + 0x126) & 4) != 0)))) {
    Compression_GetCompressionType
              ((int *)(param_1 + 0x100),(byte *)(*(int *)(param_1 + 0xec) + 1),param_1 + 0x18c,
               param_1 + 0x138,param_1 + 0x142,*(int *)(param_1 + 0x164),*(int *)(param_1 + 0x168),
               *(int *)(param_1 + 0x16c),*(int *)(param_1 + 0x170),*(int *)(param_1 + 0x174),
               *(int *)(param_1 + 0x178),(byte)*(undefined4 *)(param_1 + 0x158));
  }
  if (((*(uint *)(param_1 + 0x70) & 0x2000) != 0) &&
     (((-1 < (char)*(uint *)(param_1 + 0x70) ||
       ((*(short *)(param_1 + 0x11a) == 0 && ((*(byte *)(param_1 + 0x126) & 4) == 0)))) &&
      (*(char *)(param_1 + 0x126) != '\x03')))) {
    PixelFormat_ConvertPixels
              ((int *)(param_1 + 0x100),(byte *)(*(int *)(param_1 + 0xec) + 1),
               *(int *)(param_1 + 0x164),*(int *)(param_1 + 0x170),
               (byte)*(undefined4 *)(param_1 + 0x158));
  }
  if ((*(uint *)(param_1 + 0x70) & 0x400) != 0) {
    Compression_CompressData((int *)(param_1 + 0x100),(undefined1 *)(*(int *)(param_1 + 0xec) + 1));
  }
  if ((*(byte *)(param_1 + 0x70) & 0x40) != 0) {
    PixelFormat_GetChannelShift
              ((int *)(param_1 + 0x100),(byte *)(*(int *)(param_1 + 0xec) + 1),
               *(int *)(param_1 + 0x1ec),*(int *)(param_1 + 0x1f0));
    if (*(int *)(param_1 + 0x104) == 0) {
      CPU_Instruction20(extraout_ECX_02,extraout_EDX_02,param_1,"png_do_dither returned rowbytes=0")
      ;
    }
  }
  if ((*(byte *)(param_1 + 0x70) & 0x20) != 0) {
    ImageFormat_GetFrameDelay(param_1 + 0x100,(byte *)(*(int *)(param_1 + 0xec) + 1));
  }
  if ((*(byte *)(param_1 + 0x70) & 8) != 0) {
    Compression_Initialize
              ((int *)(param_1 + 0x100),(byte *)(*(int *)(param_1 + 0xec) + 1),
               (byte *)(param_1 + 0x181));
  }
  if ((*(byte *)(param_1 + 0x70) & 4) != 0) {
    ImageFormat_GetColorCount((int *)(param_1 + 0x100),*(int *)(param_1 + 0xec) + 1);
  }
  if ((*(byte *)(param_1 + 0x70) & 1) != 0) {
    ImageFormat_QuantizeColors
              ((int *)(param_1 + 0x100),(undefined1 *)(*(int *)(param_1 + 0xec) + 1));
  }
  if ((*(uint *)(param_1 + 0x70) & 0x10000) != 0) {
    ImageFormat_CreateAnimation(param_1 + 0x100,(byte *)(*(int *)(param_1 + 0xec) + 1));
  }
  if (((*(uint *)(param_1 + 0x70) & 0x4000) != 0) && ((*(uint *)(param_1 + 0x6c) & 0x20000) != 0)) {
    Compression_GetLevel((int *)(param_1 + 0x100),*(int *)(param_1 + 0xec) + 1);
  }
  if ((char)((uint)*(undefined4 *)(param_1 + 0x70) >> 8) < '\0') {
    Compression_SetLevel
              ((uint *)(param_1 + 0x100),*(int *)(param_1 + 0xec) + 1,
               (uint)*(ushort *)(param_1 + 0x12e),(char)*(undefined4 *)(param_1 + 0x6c));
  }
  if ((*(uint *)(param_1 + 0x70) & 0x80000) != 0) {
    Compression_GetRatio((int *)(param_1 + 0x100),*(int *)(param_1 + 0xec) + 1);
  }
  if ((*(uint *)(param_1 + 0x70) & 0x20000) != 0) {
    Compression_DecompressData((int *)(param_1 + 0x100),*(int *)(param_1 + 0xec) + 1);
  }
  if ((*(byte *)(param_1 + 0x70) & 0x10) != 0) {
    ImageFormat_ExtractFrame((int *)(param_1 + 0x100),(undefined1 *)(*(int *)(param_1 + 0xec) + 1));
  }
  if ((*(uint *)(param_1 + 0x70) & 0x100000) != 0) {
    if (*(code **)(param_1 + 0x58) != (code *)0x0) {
      (**(code **)(param_1 + 0x58))(param_1,param_1 + 0x100,*(int *)(param_1 + 0xec) + 1);
    }
    if (*(char *)(param_1 + 100) != '\0') {
      *(char *)(param_1 + 0x109) = *(char *)(param_1 + 100);
    }
    if (*(char *)(param_1 + 0x65) != '\0') {
      *(char *)(param_1 + 0x10a) = *(char *)(param_1 + 0x65);
    }
    bVar2 = *(char *)(param_1 + 0x10a) * *(char *)(param_1 + 0x109);
    *(byte *)(param_1 + 0x10b) = bVar2;
    *(uint *)(param_1 + 0x104) = *(int *)(param_1 + 0x100) * (uint)bVar2 + 7 >> 3;
  }
  Exception_SetMessage(this,in_stack_ffffffc4,in_stack_ffffffc8);
  return;
}


