/*
 * Function: PixelFormat_SetAlphaComponent
 * Address: 004c22d0
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __cdecl PixelFormat_SetAlphaComponent(int *param_1,int param_2,int param_3)

{
  int iVar1;
  int *piVar2;
  int iVar3;
  int iVar4;
  
  param_1[1] = 0;
  if (param_2 != 0x3e) {
    *(undefined4 *)(*param_1 + 0x14) = 0xc;
    *(undefined4 *)(*param_1 + 0x18) = 0x3e;
    *(int *)(*param_1 + 0x1c) = param_2;
    (**(code **)*param_1)(param_1);
  }
  if (param_3 != 0x168) {
    *(undefined4 *)(*param_1 + 0x14) = 0x15;
    *(undefined4 *)(*param_1 + 0x18) = 0x168;
    *(int *)(*param_1 + 0x1c) = param_3;
    (**(code **)*param_1)(param_1);
  }
  iVar4 = param_1[3];
  iVar1 = *param_1;
  piVar2 = param_1;
  for (iVar3 = 0x5a; iVar3 != 0; iVar3 = iVar3 + -1) {
    *piVar2 = 0;
    piVar2 = piVar2 + 1;
  }
  *param_1 = iVar1;
  param_1[3] = iVar4;
  *(undefined1 *)(param_1 + 4) = 0;
  ZLIB_DeflateParams(param_1);
  param_1[2] = 0;
  param_1[6] = 0;
  param_1[0x11] = 0;
  param_1[0x12] = 0;
  param_1[0x13] = 0;
  param_1[0x14] = 0;
  param_1[0x15] = 0;
  piVar2 = param_1 + 0x1a;
  iVar4 = 4;
  do {
    piVar2[-4] = 0;
    *piVar2 = 0;
    piVar2 = piVar2 + 1;
    iVar4 = iVar4 + -1;
  } while (iVar4 != 0);
  param_1[0x58] = 0;
  param_1[0xc] = 0;
  param_1[0xd] = 0x3ff00000;
  param_1[5] = 100;
  return;
}


