/*
 * Function: PNG_WriteImageData
 * Address: 004c4e10
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


int __cdecl PNG_WriteImageData(int *param_1,undefined4 param_2,undefined4 param_3)

{
  int *piVar1;
  
  piVar1 = param_1;
  if (param_1[5] != 0xcd) {
    *(undefined4 *)(*param_1 + 0x14) = 0x14;
    *(int *)(*param_1 + 0x18) = param_1[5];
    (**(code **)*param_1)(param_1);
  }
  if ((uint)piVar1[0x18] <= (uint)piVar1[0x1e]) {
    *(undefined4 *)(*piVar1 + 0x14) = 0x7b;
    (**(code **)(*piVar1 + 4))(piVar1,0xffffffff);
    return 0;
  }
  if (piVar1[2] != 0) {
    *(int *)(piVar1[2] + 4) = piVar1[0x1e];
    *(int *)(piVar1[2] + 8) = piVar1[0x18];
    (**(code **)piVar1[2])(piVar1);
  }
  param_1 = (int *)0x0;
  (**(code **)(piVar1[0x61] + 4))(piVar1,param_2,&param_1,param_3);
  piVar1[0x1e] = piVar1[0x1e] + (int)param_1;
  return (int)param_1;
}


