/*
 * Function: PNG_FilterScanline
 * Address: 004cff40
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


byte __cdecl PNG_FilterScanline(int *param_1,int param_2)

{
  int *piVar1;
  int iVar2;
  short sVar3;
  ushort uVar4;
  char *pcVar5;
  undefined1 *puVar6;
  byte bVar7;
  uint uVar8;
  byte *pbVar9;
  uint uVar10;
  bool bVar11;
  
  uVar10 = 0;
  do {
    uVar8 = param_1[0x1b];
    if (uVar8 < 0x106) {
      PNG_ReadtEXt();
      uVar8 = param_1[0x1b];
      if ((uVar8 < 0x106) && (param_2 == 0)) {
        return 0;
      }
      if (uVar8 == 0) {
        iVar2 = param_1[0x15];
        if (iVar2 < 0) {
          puVar6 = (undefined1 *)0x0;
        }
        else {
          puVar6 = (undefined1 *)(param_1[0xc] + iVar2);
        }
        Compression_CompressBlock((int)param_1,puVar6,param_1[0x19] - iVar2,(uint)(param_2 == 4));
        param_1[0x15] = param_1[0x19];
        PNG_ReadIEND();
        if (*(int *)(*param_1 + 0x10) == 0) {
          return (param_2 != 4) - 1U & 2;
        }
        return (param_2 == 4) * '\x02' + 1;
      }
    }
    if (2 < uVar8) {
      uVar10 = (param_1[0x10] << ((byte)param_1[0x14] & 0x1f) ^
               (uint)*(byte *)(param_1[0xc] + 2 + param_1[0x19])) & param_1[0x13];
      param_1[0x10] = uVar10;
      uVar4 = *(ushort *)(param_1[0xf] + uVar10 * 2);
      uVar10 = (uint)uVar4;
      *(ushort *)(param_1[0xe] + (param_1[0xb] & param_1[0x19]) * 2) = uVar4;
      *(short *)(param_1[0xf] + param_1[0x10] * 2) = (short)param_1[0x19];
    }
    if (((uVar10 != 0) && (param_1[0x19] - uVar10 <= param_1[9] - 0x106U)) && (param_1[0x20] != 2))
    {
      pcVar5 = PNG_WritegAMA(uVar10);
      param_1[0x16] = (int)pcVar5;
    }
    if ((uint)param_1[0x16] < 3) {
      bVar7 = *(byte *)(param_1[0x19] + param_1[0xc]);
      *(undefined2 *)(param_1[0x5a7] + param_1[0x5a6] * 2) = 0;
      *(byte *)(param_1[0x5a4] + param_1[0x5a6]) = bVar7;
      param_1[0x5a6] = param_1[0x5a6] + 1;
      *(short *)(param_1 + bVar7 + 0x23) = (short)param_1[bVar7 + 0x23] + 1;
      bVar11 = param_1[0x5a6] == param_1[0x5a5] + -1;
      param_1[0x1b] = param_1[0x1b] + -1;
LAB_004d017f:
      param_1[0x19] = param_1[0x19] + 1;
    }
    else {
      sVar3 = (short)param_1[0x19] - (short)param_1[0x1a];
      bVar7 = (char)param_1[0x16] - 3;
      *(short *)(param_1[0x5a7] + param_1[0x5a6] * 2) = sVar3;
      *(byte *)(param_1[0x5a4] + param_1[0x5a6]) = bVar7;
      param_1[0x5a6] = param_1[0x5a6] + 1;
      uVar4 = sVar3 - 1;
      *(short *)(param_1 + (byte)(&DAT_00543680)[bVar7] + 0x124) =
           (short)param_1[(byte)(&DAT_00543680)[bVar7] + 0x124] + 1;
      if (uVar4 < 0x100) {
        bVar7 = (&UNK_00543480)[uVar4];
      }
      else {
        bVar7 = (&DAT_00543580)[uVar4 >> 7];
      }
      *(short *)(param_1 + bVar7 + 0x260) = (short)param_1[bVar7 + 0x260] + 1;
      iVar2 = param_1[0x1b];
      bVar11 = param_1[0x5a6] == param_1[0x5a5] + -1;
      uVar8 = param_1[0x16];
      param_1[0x1b] = iVar2 - uVar8;
      if ((uVar8 <= (uint)param_1[0x1e]) && (2 < iVar2 - uVar8)) {
        param_1[0x16] = uVar8 - 1;
        do {
          iVar2 = param_1[0x19];
          uVar8 = iVar2 + 1;
          param_1[0x19] = uVar8;
          uVar10 = ((uint)*(byte *)(iVar2 + 3 + param_1[0xc]) ^
                   param_1[0x10] << ((byte)param_1[0x14] & 0x1f)) & param_1[0x13];
          param_1[0x10] = uVar10;
          uVar4 = *(ushort *)(param_1[0xf] + uVar10 * 2);
          uVar10 = (uint)uVar4;
          *(ushort *)(param_1[0xe] + (uVar8 & param_1[0xb]) * 2) = uVar4;
          *(short *)(param_1[0xf] + param_1[0x10] * 2) = (short)param_1[0x19];
          piVar1 = param_1 + 0x16;
          *piVar1 = *piVar1 + -1;
        } while (*piVar1 != 0);
        goto LAB_004d017f;
      }
      pbVar9 = (byte *)(param_1[0xc] + param_1[0x19] + uVar8);
      param_1[0x19] = param_1[0x19] + uVar8;
      param_1[0x16] = 0;
      uVar8 = (uint)*pbVar9;
      param_1[0x10] = uVar8;
      param_1[0x10] = (uVar8 << ((byte)param_1[0x14] & 0x1f) ^ (uint)pbVar9[1]) & param_1[0x13];
    }
    if (bVar11) {
      iVar2 = param_1[0x15];
      if (iVar2 < 0) {
        puVar6 = (undefined1 *)0x0;
      }
      else {
        puVar6 = (undefined1 *)(param_1[0xc] + iVar2);
      }
      Compression_CompressBlock((int)param_1,puVar6,param_1[0x19] - iVar2,0);
      param_1[0x15] = param_1[0x19];
      PNG_ReadIEND();
      if (*(int *)(*param_1 + 0x10) == 0) {
        return 0;
      }
    }
  } while( true );
}


