/*
 * Function: PNG_SetupFilterHeuristics
 * Address: 004c3a70
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __fastcall
PNG_SetupFilterHeuristics
          (undefined4 param_1,byte *param_2,uint param_3,int param_4,size_t param_5,int param_6,
          double *param_7)

{
  double dVar1;
  void *pvVar2;
  int iVar3;
  double *pdVar4;
  ulonglong uVar5;
  
  if (2 < param_4) {
    CPU_Instruction21(param_1,param_2,param_3,"Unknown filter heuristic method");
    return;
  }
  if (param_4 == 0) {
    param_4 = 1;
  }
  if ((((int)param_5 < 0) || (param_6 == 0)) || (param_4 == 1)) {
    param_5 = 0;
  }
  *(char *)(param_3 + 0x1f9) = (char)param_5;
  *(char *)(param_3 + 0x1f8) = (char)param_4;
  if (0 < (int)param_5) {
    if (*(int *)(param_3 + 0x1fc) == 0) {
      pvVar2 = CPU_Instruction12(param_3,param_5);
      *(void **)(param_3 + 0x1fc) = pvVar2;
      iVar3 = 0;
      if (0 < (int)param_5) {
        do {
          *(undefined1 *)(iVar3 + *(int *)(param_3 + 0x1fc)) = 0xff;
          iVar3 = iVar3 + 1;
        } while (iVar3 < (int)param_5);
      }
    }
    if (*(int *)(param_3 + 0x200) == 0) {
      pvVar2 = CPU_Instruction12(param_3,param_5 * 2);
      *(void **)(param_3 + 0x200) = pvVar2;
      pvVar2 = CPU_Instruction12(param_3,param_5 * 2);
      *(void **)(param_3 + 0x204) = pvVar2;
      iVar3 = 0;
      if (0 < (int)param_5) {
        do {
          *(undefined2 *)(*(int *)(param_3 + 0x200) + iVar3 * 2) = 0x100;
          *(undefined2 *)(*(int *)(param_3 + 0x204) + iVar3 * 2) = 0x100;
          iVar3 = iVar3 + 1;
        } while (iVar3 < (int)param_5);
      }
    }
    iVar3 = 0;
    if (3 < (int)param_5) {
      param_4 = 3;
      pdVar4 = (double *)(param_6 + 0x10);
      do {
        if (pdVar4[-2] < _DAT_0052a0c0 == (NAN(pdVar4[-2]) || NAN(_DAT_0052a0c0))) {
          uVar5 = Math_FloatToUInt64();
          *(short *)(*(int *)(param_3 + 0x204) + iVar3 * 2) = (short)uVar5;
          uVar5 = Math_FloatToUInt64();
          *(short *)(*(int *)(param_3 + 0x200) + iVar3 * 2) = (short)uVar5;
        }
        else {
          *(undefined2 *)(*(int *)(param_3 + 0x200) + iVar3 * 2) = 0x100;
          *(undefined2 *)(*(int *)(param_3 + 0x204) + iVar3 * 2) = 0x100;
        }
        if (pdVar4[-1] < _DAT_0052a0c0 == (NAN(pdVar4[-1]) || NAN(_DAT_0052a0c0))) {
          uVar5 = Math_FloatToUInt64();
          *(short *)(*(int *)(param_3 + 0x204) + 2 + iVar3 * 2) = (short)uVar5;
          uVar5 = Math_FloatToUInt64();
          *(short *)(*(int *)(param_3 + 0x200) + 2 + iVar3 * 2) = (short)uVar5;
        }
        else {
          *(undefined2 *)(*(int *)(param_3 + 0x200) + 2 + iVar3 * 2) = 0x100;
          *(undefined2 *)(*(int *)(param_3 + 0x204) + 2 + iVar3 * 2) = 0x100;
        }
        if (*pdVar4 < _DAT_0052a0c0 == (NAN(*pdVar4) || NAN(_DAT_0052a0c0))) {
          uVar5 = Math_FloatToUInt64();
          *(short *)(*(int *)(param_3 + 0x204) + 4 + iVar3 * 2) = (short)uVar5;
          uVar5 = Math_FloatToUInt64();
          *(short *)(*(int *)(param_3 + 0x200) + 4 + iVar3 * 2) = (short)uVar5;
        }
        else {
          *(undefined2 *)(*(int *)(param_3 + 0x200) + 4 + iVar3 * 2) = 0x100;
          *(undefined2 *)(*(int *)(param_3 + 0x204) + 4 + iVar3 * 2) = 0x100;
        }
        if (pdVar4[1] < _DAT_0052a0c0 == (NAN(pdVar4[1]) || NAN(_DAT_0052a0c0))) {
          uVar5 = Math_FloatToUInt64();
          *(short *)(*(int *)(param_3 + 0x204) + 6 + iVar3 * 2) = (short)uVar5;
          uVar5 = Math_FloatToUInt64();
          *(short *)(*(int *)(param_3 + 0x200) + 6 + iVar3 * 2) = (short)uVar5;
        }
        else {
          *(undefined2 *)(*(int *)(param_3 + 0x200) + 6 + iVar3 * 2) = 0x100;
          *(undefined2 *)(*(int *)(param_3 + 0x204) + 6 + iVar3 * 2) = 0x100;
        }
        param_4 = param_4 + 4;
        iVar3 = iVar3 + 4;
        pdVar4 = pdVar4 + 4;
      } while (param_4 < (int)param_5);
    }
    for (; iVar3 < (int)param_5; iVar3 = iVar3 + 1) {
      dVar1 = *(double *)(param_6 + iVar3 * 8);
      if (dVar1 < _DAT_0052a0c0 == (NAN(dVar1) || NAN(_DAT_0052a0c0))) {
        uVar5 = Math_FloatToUInt64();
        *(short *)(*(int *)(param_3 + 0x204) + iVar3 * 2) = (short)uVar5;
        uVar5 = Math_FloatToUInt64();
        *(short *)(*(int *)(param_3 + 0x200) + iVar3 * 2) = (short)uVar5;
      }
      else {
        *(undefined2 *)(*(int *)(param_3 + 0x200) + iVar3 * 2) = 0x100;
        *(undefined2 *)(*(int *)(param_3 + 0x204) + iVar3 * 2) = 0x100;
      }
    }
  }
  if (*(int *)(param_3 + 0x208) == 0) {
    pvVar2 = CPU_Instruction12(param_3,10);
    *(void **)(param_3 + 0x208) = pvVar2;
    pvVar2 = CPU_Instruction12(param_3,10);
    *(void **)(param_3 + 0x20c) = pvVar2;
    **(undefined2 **)(param_3 + 0x208) = 8;
    **(undefined2 **)(param_3 + 0x20c) = 8;
    *(undefined2 *)(*(int *)(param_3 + 0x208) + 2) = 8;
    *(undefined2 *)(*(int *)(param_3 + 0x20c) + 2) = 8;
    *(undefined2 *)(*(int *)(param_3 + 0x208) + 4) = 8;
    *(undefined2 *)(*(int *)(param_3 + 0x20c) + 4) = 8;
    *(undefined2 *)(*(int *)(param_3 + 0x208) + 6) = 8;
    *(undefined2 *)(*(int *)(param_3 + 0x20c) + 6) = 8;
    *(undefined2 *)(*(int *)(param_3 + 0x208) + 8) = 8;
    *(undefined2 *)(*(int *)(param_3 + 0x20c) + 8) = 8;
  }
  if ((param_7 == (double *)0x0) ||
     (*param_7 < _DAT_0052a0c0 != (NAN(*param_7) || NAN(_DAT_0052a0c0)))) {
    **(undefined2 **)(param_3 + 0x208) = 8;
    **(undefined2 **)(param_3 + 0x20c) = 8;
  }
  else if (_DAT_0052a0f0 <= *param_7) {
    uVar5 = Math_FloatToUInt64();
    **(undefined2 **)(param_3 + 0x20c) = (short)uVar5;
    uVar5 = Math_FloatToUInt64();
    **(undefined2 **)(param_3 + 0x208) = (short)uVar5;
  }
  if ((param_7 == (double *)0x0) ||
     (param_7[1] < _DAT_0052a0c0 != (NAN(param_7[1]) || NAN(_DAT_0052a0c0)))) {
    *(undefined2 *)(*(int *)(param_3 + 0x208) + 2) = 8;
    *(undefined2 *)(*(int *)(param_3 + 0x20c) + 2) = 8;
  }
  else if (_DAT_0052a0f0 <= param_7[1]) {
    uVar5 = Math_FloatToUInt64();
    *(short *)(*(int *)(param_3 + 0x20c) + 2) = (short)uVar5;
    uVar5 = Math_FloatToUInt64();
    *(short *)(*(int *)(param_3 + 0x208) + 2) = (short)uVar5;
  }
  if ((param_7 == (double *)0x0) ||
     (param_7[2] < _DAT_0052a0c0 != (NAN(param_7[2]) || NAN(_DAT_0052a0c0)))) {
    *(undefined2 *)(*(int *)(param_3 + 0x208) + 4) = 8;
    *(undefined2 *)(*(int *)(param_3 + 0x20c) + 4) = 8;
  }
  else if (_DAT_0052a0f0 <= param_7[2]) {
    uVar5 = Math_FloatToUInt64();
    *(short *)(*(int *)(param_3 + 0x20c) + 4) = (short)uVar5;
    uVar5 = Math_FloatToUInt64();
    *(short *)(*(int *)(param_3 + 0x208) + 4) = (short)uVar5;
  }
  if ((param_7 == (double *)0x0) ||
     (param_7[3] < _DAT_0052a0c0 != (NAN(param_7[3]) || NAN(_DAT_0052a0c0)))) {
    *(undefined2 *)(*(int *)(param_3 + 0x208) + 6) = 8;
    *(undefined2 *)(*(int *)(param_3 + 0x20c) + 6) = 8;
  }
  else if (_DAT_0052a0f0 <= param_7[3]) {
    uVar5 = Math_FloatToUInt64();
    *(short *)(*(int *)(param_3 + 0x20c) + 6) = (short)uVar5;
    uVar5 = Math_FloatToUInt64();
    *(short *)(*(int *)(param_3 + 0x208) + 6) = (short)uVar5;
  }
  if ((param_7 == (double *)0x0) ||
     (param_7[4] < _DAT_0052a0c0 != (NAN(param_7[4]) || NAN(_DAT_0052a0c0)))) {
    *(undefined2 *)(*(int *)(param_3 + 0x208) + 8) = 8;
    *(undefined2 *)(*(int *)(param_3 + 0x20c) + 8) = 8;
  }
  else if (_DAT_0052a0f0 <= param_7[4]) {
    uVar5 = Math_FloatToUInt64();
    *(short *)(*(int *)(param_3 + 0x20c) + 8) = (short)uVar5;
    uVar5 = Math_FloatToUInt64();
    *(short *)(*(int *)(param_3 + 0x208) + 8) = (short)uVar5;
    return;
  }
  return;
}


