/*
 * Function: PNG_SetIOPtr
 * Address: 004c5020
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall PNG_SetIOPtr(undefined4 param_1,undefined2 param_2,int *param_3,int param_4)

{
  int *piVar1;
  undefined4 extraout_ECX;
  undefined2 extraout_DX;
  
  piVar1 = (int *)param_3[6];
  if (0 < param_4) {
    if (piVar1[1] < param_4) {
      do {
        param_4 = param_4 - piVar1[1];
        PNG_DestroyWriteStruct(param_1,param_2,param_3);
        param_1 = extraout_ECX;
        param_2 = extraout_DX;
      } while (piVar1[1] < param_4);
    }
    *piVar1 = *piVar1 + param_4;
    piVar1[1] = piVar1[1] - param_4;
  }
  return;
}


