/*
 * Function: PNG_SetProgressCallback
 * Address: 004c5450
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall PNG_SetProgressCallback(undefined4 param_1,int *param_2)

{
  int *piVar1;
  int iVar2;
  int *piVar3;
  
  iVar2 = *param_2;
  piVar3 = *(int **)(iVar2 + 0xc);
  piVar1 = (int *)(iVar2 + 8);
  *piVar1 = *piVar1 + -1;
  if (*piVar1 == 0) {
    piVar3[2] = piVar3[2] + -1;
    *(int *)(iVar2 + 0xc) = *piVar3;
    *piVar3 = iVar2;
  }
  iVar2 = piVar3[1];
  piVar3[2] = piVar3[2] + -1;
  param_2[3] = iVar2;
  piVar3[1] = (int)param_2;
  PNG_SetWriteCallback(iVar2,(uint)param_2,piVar3);
  return;
}


