/*
 * Function: PNG_ReadChunk
 * Address: 004cee50
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __cdecl PNG_ReadChunk(int *param_1,byte *param_2,int param_3)

{
  byte bVar1;
  int iVar2;
  uint uVar3;
  uint uVar4;
  int iVar5;
  byte *pbVar6;
  
  if ((*(char *)((int)param_1 + 9) == '\b') && (*(char *)((int)param_1 + 10) == '\x01')) {
    if (param_3 == 1) {
      iVar5 = *param_1;
      uVar4 = 0;
      uVar3 = 0x80;
      pbVar6 = param_2;
      if (iVar5 != 0) {
        do {
          if (*param_2 != 0) {
            uVar4 = uVar4 | uVar3;
          }
          param_2 = param_2 + 1;
          if (uVar3 < 2) {
            *pbVar6 = (byte)uVar4;
            pbVar6 = pbVar6 + 1;
            uVar3 = 0x80;
            uVar4 = 0;
          }
          else {
            uVar3 = (int)uVar3 >> 1;
          }
          iVar5 = iVar5 + -1;
        } while (iVar5 != 0);
        if (uVar3 != 0x80) {
          *pbVar6 = (byte)uVar4;
        }
      }
    }
    else if (param_3 == 2) {
      iVar5 = *param_1;
      uVar3 = 0;
      iVar2 = 6;
      pbVar6 = param_2;
      if (iVar5 != 0) {
        do {
          uVar3 = uVar3 | (*param_2 & 3) << ((byte)iVar2 & 0x1f);
          if (iVar2 == 0) {
            *pbVar6 = (byte)uVar3;
            pbVar6 = pbVar6 + 1;
            iVar2 = 6;
            uVar3 = 0;
          }
          else {
            iVar2 = iVar2 + -2;
          }
          param_2 = param_2 + 1;
          iVar5 = iVar5 + -1;
        } while (iVar5 != 0);
        if (iVar2 != 6) {
          *pbVar6 = (byte)uVar3;
        }
      }
    }
    else if (param_3 == 4) {
      iVar5 = *param_1;
      uVar3 = 0;
      iVar2 = 4;
      pbVar6 = param_2;
      if (iVar5 != 0) {
        do {
          uVar3 = uVar3 | (*param_2 & 0xf) << ((byte)iVar2 & 0x1f);
          if (iVar2 == 0) {
            *pbVar6 = (byte)uVar3;
            pbVar6 = pbVar6 + 1;
            iVar2 = 4;
            uVar3 = 0;
          }
          else {
            iVar2 = iVar2 + -4;
          }
          param_2 = param_2 + 1;
          iVar5 = iVar5 + -1;
        } while (iVar5 != 0);
        if (iVar2 != 4) {
          *pbVar6 = (byte)uVar3;
        }
      }
    }
    *(char *)((int)param_1 + 9) = (char)param_3;
    bVar1 = (char)param_3 * *(char *)((int)param_1 + 10);
    *(byte *)((int)param_1 + 0xb) = bVar1;
    param_1[1] = (uint)bVar1 * *param_1 + 7 >> 3;
  }
  return;
}


