/*
 * Function: PNG_ProcessImageTransforms
 * Address: 004c32f0
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __cdecl PNG_ProcessImageTransforms(byte *param_1,int *param_2)

{
  int *piVar1;
  int iVar2;
  int *piVar3;
  int iVar4;
  int iVar5;
  void *extraout_ECX;
  void *extraout_ECX_00;
  void *extraout_ECX_01;
  void *extraout_ECX_02;
  void *extraout_ECX_03;
  void *extraout_ECX_04;
  void *extraout_ECX_05;
  void *extraout_ECX_06;
  void *extraout_ECX_07;
  void *extraout_ECX_08;
  void *extraout_ECX_09;
  void *extraout_ECX_10;
  void *extraout_ECX_11;
  void *this;
  byte *extraout_EDX;
  byte *extraout_EDX_00;
  byte *extraout_EDX_01;
  byte *extraout_EDX_02;
  byte *extraout_EDX_03;
  byte *extraout_EDX_04;
  byte *extraout_EDX_05;
  byte *extraout_EDX_06;
  byte *pbVar6;
  
  piVar3 = param_2;
  Renderer_PushMatrix((int)param_1);
  ImageDecoder_ValidateFormat
            ((uint)*(byte *)(param_2 + 6),(byte *)param_2[1],(uint)param_1,*param_2,
             (byte *)param_2[1],(uint)*(byte *)(param_2 + 6),(uint)*(byte *)((int)param_2 + 0x19),
             (uint)*(byte *)((int)param_2 + 0x1a),(uint)*(byte *)((int)param_2 + 0x1b),
             (uint)*(byte *)(param_2 + 7));
  this = extraout_ECX;
  pbVar6 = extraout_EDX;
  if ((*(byte *)(param_2 + 2) & 1) != 0) {
    ImageDecoder_ApplyFilters((uint)param_1);
    this = extraout_ECX_00;
    pbVar6 = extraout_EDX_00;
  }
  if ((param_2[2] & 0x800U) != 0) {
    ImageDecoder_Deinterlace
              ((uint)*(byte *)(param_2 + 0xb),pbVar6,(uint)param_1,(uint)*(byte *)(param_2 + 0xb));
    this = extraout_ECX_01;
    pbVar6 = extraout_EDX_01;
  }
  if ((*(byte *)(param_2 + 2) & 2) != 0) {
    ImageDecoder_CorrectGamma
              (this,(byte *)(uint)*(byte *)((int)param_2 + 0x19),(uint)param_1,
               (byte *)(param_2 + 0x11),(uint)*(byte *)((int)param_2 + 0x19));
    this = extraout_ECX_02;
    pbVar6 = extraout_EDX_02;
  }
  if ((*(byte *)(param_2 + 2) & 4) != 0) {
    ImageDecoder_ProcessPalette
              (this,pbVar6,param_1,(double)(float)param_2[0x20],(double)(float)param_2[0x21],
               (double)(float)param_2[0x22],(double)(float)param_2[0x23],
               (double)(float)param_2[0x24],(double)(float)param_2[0x25],
               (double)(float)param_2[0x26],(double)(float)param_2[0x27]);
    this = extraout_ECX_03;
    pbVar6 = extraout_EDX_03;
  }
  if ((*(byte *)(param_2 + 2) & 8) == 0) {
    if (*(char *)((int)param_2 + 0x19) == '\x03') {
      CPU_Instruction20((uint)this,pbVar6,(int)param_1,
                        "Valid palette required for paletted images\n");
      this = extraout_ECX_05;
      pbVar6 = extraout_EDX_05;
    }
  }
  else {
    Renderer_PopMatrix((uint)*(ushort *)(param_2 + 5),(byte *)param_2[4],(uint)param_1,param_2[4],
                       (uint)*(ushort *)(param_2 + 5));
    this = extraout_ECX_04;
    pbVar6 = extraout_EDX_04;
  }
  if ((*(byte *)(param_2 + 2) & 0x10) != 0) {
    if ((((*(uint *)(param_1 + 0x70) & 0x80000) != 0) && (*(char *)((int)param_2 + 0x19) == '\x03'))
       && (iVar4 = 0, *(short *)((int)param_2 + 0x16) != 0)) {
      do {
        *(char *)(param_2[0x13] + iVar4) = -1 - *(char *)(param_2[0x13] + iVar4);
        iVar4 = iVar4 + 1;
      } while (iVar4 < (int)(uint)*(ushort *)((int)param_2 + 0x16));
    }
    ImageDecoder_HandleTransparency
              ((byte *)(param_2 + 0x14),(byte *)param_2[0x13],param_1,(byte *)param_2[0x13],
               (int)(param_2 + 0x14),(uint)*(ushort *)((int)param_2 + 0x16),
               (uint)*(byte *)((int)param_2 + 0x19));
    this = extraout_ECX_06;
    pbVar6 = extraout_EDX_06;
  }
  if ((*(byte *)(param_2 + 2) & 0x20) != 0) {
    ImageDecoder_ConvertColorSpace
              ((int)param_2 + 0x5a,pbVar6,(uint)param_1,(byte *)((int)param_2 + 0x5a),
               (uint)*(byte *)((int)param_2 + 0x19));
    this = extraout_ECX_07;
  }
  if ((*(byte *)(param_2 + 2) & 0x40) != 0) {
    Renderer_LoadIdentity
              (this,(byte *)(uint)*(ushort *)(param_2 + 5),(uint)param_1,param_2[0x1f],
               (int)(uint)*(ushort *)(param_2 + 5));
    this = extraout_ECX_08;
  }
  if ((param_2[2] & 0x100U) != 0) {
    ImageDecoder_ScaleImage
              ((uint)*(byte *)(param_2 + 0x1b),(byte *)param_2[0x1a],(uint)param_1,param_2[0x19],
               (byte *)param_2[0x1a],(uint)*(byte *)(param_2 + 0x1b));
    this = extraout_ECX_09;
  }
  if ((param_2[2] & 0x400U) != 0) {
    Renderer_SetRenderState
              (param_2[0x28],(byte *)param_2[0x2a],param_1,(void *)param_2[0x28],param_2[0x29],
               (byte *)param_2[0x2a],(uint)*(byte *)(param_2 + 0x2d),
               (byte *)(uint)*(byte *)((int)param_2 + 0xb5),(byte *)param_2[0x2b],
               (undefined4 *)param_2[0x2c]);
    this = extraout_ECX_10;
  }
  if ((char)param_2[2] < '\0') {
    ImageDecoder_CropImage
              (param_2[0x1c],(byte *)(uint)*(byte *)(param_2 + 0x1e),(uint)param_1,param_2[0x1c],
               param_2[0x1d],(int)(uint)*(byte *)(param_2 + 0x1e));
    this = extraout_ECX_11;
  }
  if ((param_2[2] & 0x200U) != 0) {
    ImageDecoder_FlipImage(this,param_1,(ushort *)(param_2 + 0xf));
    *(uint *)(param_1 + 0x6c) = *(uint *)(param_1 + 0x6c) | 0x10000;
  }
  piVar1 = param_2 + 0xc;
  param_2 = (int *)0x0;
  if (0 < *piVar1) {
    iVar4 = 0;
    do {
      iVar2 = *(int *)(piVar3[0xe] + iVar4);
      iVar5 = piVar3[0xe] + iVar4;
      if (iVar2 < 0) {
        if (iVar2 == -1) {
          Renderer_Rotate(*(undefined4 *)(iVar5 + 8),*(byte **)(iVar5 + 4),param_1,
                          *(byte **)(iVar5 + 4),(byte *)*(undefined4 *)(iVar5 + 8),
                          *(uint *)(iVar5 + 0xc));
          *(undefined4 *)(iVar4 + piVar3[0xe]) = 0xfffffffd;
        }
      }
      else {
        Renderer_Scale(*(int *)(iVar5 + 0xc),*(byte **)(iVar5 + 8),param_1,*(byte **)(iVar5 + 4),
                       *(byte **)(iVar5 + 8),*(int *)(iVar5 + 0xc),iVar2);
        *(undefined4 *)(iVar4 + piVar3[0xe]) = 0xfffffffe;
      }
      param_2 = (int *)((int)param_2 + 1);
      iVar4 = iVar4 + 0x10;
    } while ((int)param_2 < piVar3[0xc]);
  }
  return;
}


