/*
 * Function: PNG_ReadIHDR
 * Address: 004cf560
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall
PNG_ReadIHDR(undefined4 param_1,byte *param_2,uint param_3,undefined4 param_4,undefined4 param_5)

{
  if (*(code **)(param_3 + 0x4c) != (code *)0x0) {
    (**(code **)(param_3 + 0x4c))(param_3,param_4,param_5);
    return;
  }
  CPU_Instruction20(param_3,param_2,param_3,"Call to NULL write function");
  return;
}


