/*
 * Function: RefCounter_Release
 * Address: 00471c70
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall RefCounter_Release(undefined4 *param_1)

{
  int *piVar1;
  
  piVar1 = param_1 + 2;
  *piVar1 = *piVar1 + -1;
  if (*piVar1 == 0) {
    (**(code **)*param_1)(1);
  }
  return;
}


