/*
 * Function: Runtime_CompactHeap
 * Address: 004f8733
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


_String_base * __fastcall Runtime_CompactHeap(undefined4 param_1,uint param_2,_String_base *param_3)

{
  uint extraout_EDX;
  _String_base *in_stack_00000014;
  
  String_Reset((int)param_3,param_2,'\0');
  PowerUp_ProcessThunderstrike(param_3,extraout_EDX,in_stack_00000014,0,0xffffffff);
  return param_3;
}


