/*
 * Function: Runtime_DebugHeapSet
 * Address: 004f9a9a
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall Runtime_DebugHeapSet(undefined4 *param_1,uint param_2)

{
  *param_1 = &PTR_Runtime_DebugHeapCheck_00546f94;
  System_DirectShutdownHandler3((int)param_1,param_2);
  *param_1 = &PTR_SexyWidget_UpdateProperties_0053129c;
  return;
}


