/*
 * Function: Score_ProcessLoadScores
 * Address: 00426140
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Removing unreachable block (ram,0x0042655d) */

void __thiscall Score_ProcessLoadScores(void *this,void *param_1)

{
  _String_base _Var1;
  int iVar2;
  void *this_00;
  undefined4 *puVar3;
  char *pcVar4;
  _String_base *p_Var5;
  char *pcVar6;
  undefined4 uVar7;
  int extraout_ECX;
  int extraout_ECX_00;
  int extraout_ECX_01;
  _String_base *p_Var8;
  int extraout_ECX_02;
  uint extraout_EDX;
  uint extraout_EDX_00;
  uint uVar9;
  ulonglong uVar10;
  uint unaff_retaddr;
  undefined4 *in_stack_ffffff84;
  undefined4 *in_stack_ffffff88;
  uint uVar11;
  undefined1 local_60 [4];
  uint local_5c;
  undefined1 local_54 [8];
  undefined4 local_4c;
  uint local_48;
  undefined1 local_44 [16];
  undefined4 local_34;
  undefined4 local_30;
  undefined4 local_2c;
  undefined4 local_28;
  undefined4 local_24;
  undefined4 local_20;
  undefined4 local_1c;
  undefined4 local_18;
  uint local_14;
  void *local_10;
  undefined4 uStack_c;
  undefined4 local_8;
  
  this_00 = param_1;
  local_8 = 0xffffffff;
  uStack_c = 0x511358;
  local_10 = ExceptionList;
  local_14 = DAT_00569f5c ^ unaff_retaddr;
  if (*(int *)((int)this + 0x84) == 0) {
    ExceptionList = &local_10;
    DrawSprite(*(void **)(*(int *)((int)this + 0x60) + 0x7b0),param_1,0,0,'\0',0,0,'\0');
    SexyWidget_Translate(param_1,0xaa,0);
    Graphics_SetProjection(param_1,*(undefined4 *)(*(int *)((int)this + 0x60) + 0x92c));
    puVar3 = (undefined4 *)SexyWidget_ApplyMatrix(&local_24,0xff,0xff,0xff);
    SexyWidget_SetRectangle(param_1,puVar3);
    iVar2 = *(int *)((int)this + 0x60);
    if ((*(int *)(iVar2 + 0x148c) == 0) ||
       ((*(int *)(iVar2 + 0x1490) - *(int *)(iVar2 + 0x148c)) / 0x60 == 0)) {
      local_48 = 0xf;
      local_4c = 0;
      local_5c = local_5c & 0xffffff00;
      pcVar6 = "NEW USER";
      do {
        pcVar4 = pcVar6;
        pcVar6 = pcVar4 + 1;
      } while (*pcVar4 != '\0');
      String_Assign(local_60,(_String_base *)"NEW USER",(uint)(pcVar4 + -0x52e104));
                    /* WARNING: Load size is inaccurate */
      local_8 = 0;
      (**(code **)(*this + 0x90))(&local_24,param_1,0x37,local_60);
      iVar2 = extraout_ECX;
      uVar9 = local_5c;
    }
    else {
      if (*(char *)(iVar2 + 0xb31) == '\0') {
        Level_InitializeDictastroika(local_60,"Welcome Back,");
                    /* WARNING: Load size is inaccurate */
        local_8 = 1;
        (**(code **)(*this + 0x90))(&local_24,param_1,0x37,local_60);
        iVar2 = extraout_ECX_00;
        uVar9 = extraout_EDX;
      }
      else {
        Level_InitializeDictastroika(local_60,"Welcome,");
                    /* WARNING: Load size is inaccurate */
        local_8 = 2;
        (**(code **)(*this + 0x90))(&local_24,param_1,0x37,local_60);
        iVar2 = extraout_ECX_01;
        uVar9 = local_5c;
      }
      if (0xf < local_48) {
        local_8 = 0xffffffff;
                    /* WARNING: Subroutine does not return */
        System_ShutdownHandler(iVar2,uVar9);
      }
      local_8 = 0xffffffff;
      local_48 = 0xf;
      local_4c = 0;
      local_5c = local_5c & 0xffffff00;
      p_Var8 = (_String_base *)
               (*(int *)(*(int *)((int)this + 0x60) + 0xb40) * 0x60 +
               *(int *)(*(int *)((int)this + 0x60) + 0x148c));
      p_Var5 = p_Var8;
      do {
        _Var1 = *p_Var5;
        p_Var5 = p_Var5 + 1;
      } while (_Var1 != (_String_base)0x0);
      String_Assign(local_60,p_Var8,(int)p_Var5 - (int)(p_Var8 + 1));
                    /* WARNING: Load size is inaccurate */
      local_8 = 3;
      (**(code **)(*this + 0x90))(&local_24,param_1,0x4b,local_60);
      iVar2 = extraout_ECX_02;
      uVar9 = extraout_EDX_00;
    }
    if (0xf < local_48) {
      local_8 = 0xffffffff;
                    /* WARNING: Subroutine does not return */
      System_ShutdownHandler(iVar2,uVar9);
    }
    local_8 = 0xffffffff;
    SexyWidget_Translate(param_1,-0xaa,0);
    PowerUpEffects_Render(*(void **)((int)this + 0x80),param_1);
    SexyWidget_SetColorizeFlag2(param_1,1);
    if (*(int *)((int)this + 0x5c) != 0) {
      puVar3 = (undefined4 *)CreateColor(&local_24,0xff,0xff,0xff,*(int *)((int)this + 0x5c));
      SexyWidget_SetRectangle(param_1,puVar3);
      DrawSprite(*(void **)(*(int *)((int)this + 0x60) + 0x898),param_1,0xed,0x98,'\0',0,0,'\0');
    }
    SexyWidget_SetColorizeFlag2(param_1,0);
    param_1 = (void *)0x0;
    do {
      uVar9 = *(uint *)((int)this + (int)param_1 * 4 + 0x68);
      if (*(int *)(uVar9 + 0xf8) != 0) {
        uVar11 = (uint)in_stack_ffffff88 & 0xffffff00;
        local_8 = 4;
        if ((param_1 == (void *)0x1) &&
           (uVar9 = *(uint *)(*(int *)((int)this + 0x60) + 0x148c),
           *(ushort *)(*(int *)(*(int *)((int)this + 0x60) + 0xb40) * 0x60 + uVar9 + 0x1e) < 3)) {
          pcVar6 = "?You must complete 3 stages in Mission Mode\nin order to unlock\nSurvival Mode!"
          ;
          do {
            pcVar6 = pcVar6 + 1;
          } while (*pcVar6 != '\0');
          String_Assign(&stack0xffffff84,(_String_base *)0x52e098,(uint)(pcVar6 + -0x52e098));
        }
        else {
          PowerUp_ProcessThunderstrike
                    ((_String_base *)&stack0xffffff84,uVar9,
                     (_String_base *)(&DAT_00561550 + (int)param_1 * 0x1c),0,0xffffffff);
        }
        Graphics_SetProjection(this_00,*(undefined4 *)(*(int *)((int)this + 0x60) + 0x934));
        puVar3 = (undefined4 *)
                 CreateColor(local_44,0,0,0,
                             *(undefined4 *)(*(int *)((int)this + (int)param_1 * 4 + 0x68) + 0xf8));
        SexyWidget_SetRectangle(this_00,puVar3);
                    /* WARNING: Load size is inaccurate */
        iVar2 = *this;
        local_24 = 0xd2;
        local_1c = 0xd2;
        local_20 = 0xaf;
        local_18 = 100;
        uVar7 = (**(code **)(**(int **)(*(int *)((int)this + 0x60) + 0x92c) + 0x10))(0);
        (**(code **)(iVar2 + 0x98))(this_00,&local_24,&stack0xffffff84,uVar7);
        Graphics_SetProjection(this_00,*(undefined4 *)(*(int *)((int)this + 0x60) + 0x940));
        uVar10 = Math_FloatToUInt64();
        puVar3 = (undefined4 *)CreateColor(local_54,0xff,0xe0,0x40,(int)uVar10);
        SexyWidget_SetRectangle(this_00,puVar3);
                    /* WARNING: Load size is inaccurate */
        iVar2 = *this;
        local_34 = 0xd2;
        local_2c = 0xd2;
        local_30 = 0xaa;
        local_28 = 100;
        uVar7 = (**(code **)(**(int **)(*(int *)((int)this + 0x60) + 0x92c) + 0x10))(0);
        (**(code **)(iVar2 + 0x98))(this_00,&local_34,&stack0xffffff84,uVar7);
        local_8 = 0xffffffff;
        in_stack_ffffff88 = (undefined4 *)(uVar11 & 0xffffff00);
      }
      param_1 = (void *)((int)param_1 + 1);
    } while ((int)param_1 < 6);
    SexyWidget_SetColorizeFlag2(this_00,0);
  }
  ExceptionList = local_10;
  Exception_SetMessage((void *)(local_14 ^ unaff_retaddr),in_stack_ffffff84,in_stack_ffffff88);
  return;
}


