/*
 * Function: Score_ProcessFinalTally
 * Address: 00425c40
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __thiscall Score_ProcessFinalTally(void *this,int param_1,int param_2,int param_3,int param_4)

{
  int iVar1;
  
  UI_ValidateWidgetLayout(this,param_1,param_2,param_3,param_4);
  iVar1 = (**(code **)(**(int **)(*(int *)((int)this + 0x60) + 0x938) + 0x1c))
                    (*(int *)((int)this + 100) + 0x5c);
  (**(code **)(**(int **)((int)this + 100) + 0x34))(0x1ea - iVar1 / 2,0x4b,iVar1,0x1e);
  (**(code **)(**(int **)((int)this + 0x68) + 0x34))(0x2d,0xc3,0x6e,0x6e);
  (**(code **)(**(int **)((int)this + 0x6c) + 0x34))(0xaf,0x145,0x6e,0x6e);
  (**(code **)(**(int **)((int)this + 0x70) + 0x34))(0x1db,0xc3,0x78,0x28);
  (**(code **)(**(int **)((int)this + 0x74) + 0x34))(0x1bd,0x109,0x78,0x28);
  (**(code **)(**(int **)((int)this + 0x78) + 0x34))(0x1bd,0x14f,0x78,0x28);
  (**(code **)(**(int **)((int)this + 0x7c) + 0x34))(0x1db,0x195,0x78,0x28);
  return;
}


