/*
 * Function: Security_CheckPermissions
 * Address: 004e3910
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


int * __cdecl Security_CheckPermissions(int param_1,int param_2,int param_3)

{
  int iVar1;
  int *piVar2;
  int *piVar3;
  int iVar4;
  undefined4 uVar5;
  void *pvVar6;
  int iVar7;
  int iVar8;
  int local_10;
  int local_c;
  uint *local_8;
  
  piVar2 = (int *)Assembly_DecompilationFailed(1,0x24);
  iVar7 = *(int *)(*(int *)(param_1 + 4) + 0x1c);
  local_c = 0;
  local_10 = 0;
  *piVar2 = param_3;
  piVar2[1] = *(int *)(param_2 + 0xc);
  piVar2[2] = *(int *)(param_3 + 0xc);
  piVar2[4] = *(int *)(iVar7 + 0xc20);
  piVar3 = (int *)(*(int *)(iVar7 + 0xc20) + *(int *)(param_3 + 0x10) * 0x34);
  piVar2[5] = (int)piVar3;
  iVar1 = *piVar3;
  iVar4 = Assembly_DecompilationFailed(piVar2[2],4);
  piVar2[6] = iVar4;
  param_1 = 0;
  if (0 < piVar2[2]) {
    local_8 = (uint *)(param_3 + 0x14);
    param_2 = 0;
    do {
      iVar4 = License_CheckExpiry(*local_8);
      if (iVar4 != 0) {
        if (local_10 < iVar4) {
          local_10 = iVar4;
        }
        uVar5 = Assembly_DecompilationFailed(iVar4,4);
        *(undefined4 *)(param_2 + piVar2[6]) = uVar5;
        iVar8 = 0;
        if (0 < iVar4) {
          piVar3 = (int *)(param_3 + 0x114 + local_c * 4);
          do {
            if ((*local_8 & 1 << ((byte)iVar8 & 0x1f)) != 0) {
              *(int *)(*(int *)(param_2 + piVar2[6]) + iVar8 * 4) =
                   *piVar3 * 0x34 + *(int *)(iVar7 + 0xc20);
              local_c = local_c + 1;
              piVar3 = piVar3 + 1;
            }
            iVar8 = iVar8 + 1;
          } while (iVar8 < iVar4);
        }
      }
      param_2 = param_2 + 4;
      local_8 = local_8 + 1;
      param_1 = param_1 + 1;
    } while (param_1 < piVar2[2]);
  }
  iVar7 = piVar2[2];
  piVar2[7] = iVar7;
  if (1 < iVar1) {
    iVar4 = iVar1 + -1;
    iVar8 = iVar7;
    do {
      iVar8 = iVar8 * iVar7;
      iVar4 = iVar4 + -1;
    } while (iVar4 != 0);
    piVar2[7] = iVar8;
  }
  piVar2[3] = local_10;
  pvVar6 = _malloc(piVar2[7] << 2);
  piVar2[8] = (int)pvVar6;
  param_1 = 0;
  if (0 < piVar2[7]) {
    param_3 = 0;
    do {
      param_2 = param_1;
      iVar7 = piVar2[7] / piVar2[2];
      pvVar6 = _malloc(iVar1 * 4);
      *(void **)(param_3 + piVar2[8]) = pvVar6;
      iVar4 = 0;
      if (0 < iVar1) {
        do {
          iVar8 = param_2 / iVar7;
          param_2 = param_2 - iVar8 * iVar7;
          iVar7 = iVar7 / piVar2[2];
          iVar4 = iVar4 + 1;
          *(int *)(*(int *)(piVar2[8] + param_3) + -4 + iVar4 * 4) = iVar8;
        } while (iVar4 < iVar1);
      }
      param_1 = param_1 + 1;
      param_3 = param_3 + 4;
    } while (param_1 < piVar2[7]);
  }
  return piVar2;
}


