/*
 * Function: Settings_ProcessEffectQuality
 * Address: 00428a50
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __thiscall Settings_ProcessEffectQuality(void *this,int *param_1)

{
  uint uVar1;
  int extraout_ECX;
  void *pvVar2;
  uint extraout_EDX;
  
                    /* WARNING: Load size is inaccurate */
  if (param_1 == *this) {
    return;
  }
  if (*(int **)((int)this + 4) == param_1) {
    *(int *)((int)this + 4) = param_1[2];
  }
  if (*param_1 != 0) {
    Settings_ProcessTextureQuality(*param_1);
                    /* WARNING: Subroutine does not return */
    System_ShutdownHandler(extraout_ECX,extraout_EDX);
  }
  pvVar2 = this;
  if (param_1 == *(int **)((int)this + 8)) {
    pvVar2 = (void *)param_1[2];
    *(void **)((int)this + 8) = pvVar2;
  }
  uVar1 = param_1[2];
  *(int *)(uVar1 + 4) = param_1[1];
  if (param_1[1] != 0) {
    pvVar2 = (void *)param_1[2];
    *(void **)(param_1[1] + 8) = pvVar2;
  }
                    /* WARNING: Subroutine does not return */
  System_ShutdownHandler((int)pvVar2,uVar1);
}


