/*
 * Function: SexyWidget_ProcessColorArray
 * Address: 00469010
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall SexyWidget_ProcessColorArray(int *param_1,uint param_2,int param_3,int param_4)

{
  undefined4 *puVar1;
  undefined4 *puVar2;
  undefined1 local_18 [16];
  int *local_8;
  
  local_8 = param_1;
  if (param_1[0xb] == 0) {
    param_1[0xb] = 0;
    param_1[0xc] = 0;
    param_1[0xd] = 0;
    if (0 < param_4) {
      puVar2 = (undefined4 *)(param_3 + 8);
      do {
        puVar1 = (undefined4 *)CreateColor(local_18,puVar2[-2],puVar2[-1],*puVar2,puVar2[1]);
        SexyWidget_ProcessColor(param_1 + 10,puVar1);
        puVar2 = puVar2 + 4;
        param_4 = param_4 + -1;
      } while (param_4 != 0);
    }
    (**(code **)(*local_8 + 0xbc))();
    return;
  }
                    /* WARNING: Subroutine does not return */
  System_ShutdownHandler((int)param_1,param_2);
}


