/*
 * Function: SexyWidget_ResetColors
 * Address: 00469120
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


int __thiscall SexyWidget_ResetColors(void *this,int param_1)

{
  int iVar1;
  undefined4 local_14 [4];
  
  if (*(int *)((int)this + 0x2c) == 0) {
    iVar1 = 0;
  }
  else {
    iVar1 = *(int *)((int)this + 0x30) - *(int *)((int)this + 0x2c) >> 4;
  }
  if (iVar1 <= param_1) {
    SexyWidget_SetMatrix(local_14);
    UI_ProcessChildBinding((void *)((int)this + 0x28),param_1 + 1);
  }
  return param_1 * 0x10 + *(int *)((int)this + 0x2c);
}


