/*
 * Function: SexyWidget_ProcessEvents
 * Address: 00468720
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __thiscall SexyWidget_ProcessEvents(void *this,int param_1)

{
  undefined4 *puVar1;
  _String_base *p_Var2;
  undefined4 *puVar3;
  double dVar4;
  int *piVar5;
  int *piVar6;
  int iVar7;
  undefined4 *puVar8;
  undefined4 *puVar9;
  uint extraout_EDX;
  uint uVar10;
  uint extraout_EDX_00;
  _String_base *p_Var11;
  int *piVar12;
  
  if (param_1 != -1) {
    piVar6 = *(int **)((int)this + 0xac);
    piVar12 = (int *)this;
    while (piVar5 = piVar6, piVar5 != (int *)0x0) {
      piVar12 = piVar5;
      piVar6 = (int *)piVar5[0x2b];
    }
    uVar10 = param_1 * 0x10;
    do {
      iVar7 = piVar12[0x1c] + param_1 * 0x1c;
      p_Var2 = (_String_base *)piVar12[0x1d];
      p_Var11 = (_String_base *)(iVar7 + 0x1c);
      if (p_Var11 != p_Var2) {
        iVar7 = iVar7 - (int)p_Var11;
        do {
          PowerUp_ProcessThunderstrike(p_Var11 + iVar7,uVar10,p_Var11,0,0xffffffff);
          p_Var11 = p_Var11 + 0x1c;
          uVar10 = extraout_EDX;
        } while (p_Var11 != p_Var2);
      }
      Background_ProcessGroundLayer(param_1 * 0x1c,uVar10,piVar12[0x1d] + -0x1c,piVar12[0x1d]);
      piVar12[0x1d] = piVar12[0x1d] + -0x1c;
      puVar3 = (undefined4 *)piVar12[0x21];
      iVar7 = piVar12[0x20] + param_1 * 0x10;
      puVar8 = (undefined4 *)(iVar7 + 0x10);
      if (puVar8 != puVar3) {
        iVar7 = iVar7 - (int)puVar8;
        do {
          puVar9 = (undefined4 *)(iVar7 + (int)puVar8);
          *puVar9 = *puVar8;
          puVar9[1] = puVar8[1];
          puVar9[2] = puVar8[2];
          puVar1 = puVar8 + 3;
          puVar8 = puVar8 + 4;
          puVar9[3] = *puVar1;
        } while (puVar8 != puVar3);
      }
      piVar12[0x21] = piVar12[0x21] + -0x10;
      (**(code **)(*piVar12 + 0xbc))();
      piVar12 = (int *)piVar12[0x2c];
      uVar10 = extraout_EDX_00;
    } while (piVar12 != (int *)0x0);
  }
  if (*(int **)((int)this + 100) != (int *)0x0) {
    if (*(int *)((int)this + 0x70) == 0) {
      iVar7 = 0;
    }
    else {
      iVar7 = (*(int *)((int)this + 0x74) - *(int *)((int)this + 0x70)) / 0x1c;
    }
    dVar4 = (double)iVar7;
    if (iVar7 < 0) {
      dVar4 = dVar4 + _DAT_00531540;
    }
    (**(code **)(**(int **)((int)this + 100) + 0xc4))(dVar4);
  }
  return;
}


