/*
 * Function: SexyWidget_ValidateMatrix
 * Address: 0046a5b0
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


uint __fastcall SexyWidget_ValidateMatrix(uint *param_1)

{
  return ((param_1[3] << 8 | *param_1) << 8 | param_1[1]) << 8 | param_1[2];
}


