/*
 * Function: SexyWidget_EnsureTexture
 * Address: 0046bd00
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


int __fastcall SexyWidget_EnsureTexture(int *param_1)

{
  if (param_1[0x13] == 0) {
    Texture_ConvertAndUpload(param_1);
  }
  return param_1[0x13];
}


