/*
 * Function: Socket_Create
 * Address: 004e1d30
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __cdecl Socket_Create(int param_1,int param_2,int *param_3,int param_4)

{
  byte *pbVar1;
  byte *pbVar2;
  short *psVar3;
  int iVar4;
  byte bVar5;
  int iVar6;
  int iVar7;
  char *pcVar8;
  byte *pbVar9;
  int local_10;
  int *local_c;
  
  iVar6 = *(int *)(*(int *)(param_1 + 0x1a8) + 0x18);
  iVar7 = *(int *)(param_1 + 0x5c);
  if (0 < param_4) {
    local_c = param_3;
    local_10 = param_4;
    do {
      pcVar8 = (char *)*local_c;
      pbVar9 = *(byte **)((param_2 - (int)param_3) + (int)local_c);
      for (iVar4 = iVar7; iVar4 != 0; iVar4 = iVar4 + -1) {
        bVar5 = *pbVar9;
        pbVar1 = pbVar9 + 1;
        pbVar2 = pbVar9 + 2;
        psVar3 = (short *)(*(int *)(iVar6 + (uint)(bVar5 >> 3) * 4) +
                          ((int)(uint)(*pbVar1 >> 2) * 0x20 + (uint)(*pbVar2 >> 3)) * 2);
        pbVar9 = pbVar9 + 3;
        if (*psVar3 == 0) {
          HTTP_CloseConnection
                    ((void *)(uint)(*pbVar1 >> 2),param_1,(uint)(bVar5 >> 3),(uint)(*pbVar2 >> 3));
        }
        *pcVar8 = (char)*psVar3 + -1;
        pcVar8 = pcVar8 + 1;
      }
      local_c = local_c + 1;
      local_10 = local_10 + -1;
    } while (local_10 != 0);
  }
  return;
}


