/*
 * Function: String_ToLower
 * Address: 004d6070
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __cdecl String_ToLower(int param_1,undefined4 *param_2)

{
  undefined2 uVar1;
  int iVar2;
  uint uVar3;
  uint uVar4;
  int iVar5;
  uint uVar6;
  undefined4 *puVar7;
  uint uVar8;
  uint uVar9;
  uint uVar10;
  undefined4 *puVar11;
  int iVar12;
  int iVar13;
  int local_2c;
  undefined4 *local_20;
  undefined4 *local_1c;
  uint local_c;
  uint local_8;
  
  uVar8 = *(int *)(param_1 + 0xe0) - 1;
  iVar12 = *(int *)(param_1 + 0x44);
  iVar2 = *(int *)(param_1 + 0x148);
  local_2c = 0;
  if (0 < *(int *)(param_1 + 0x3c)) {
    local_1c = (undefined4 *)(iVar2 + 0x40);
    local_20 = param_2;
    do {
      iVar5 = (**(code **)(*(int *)(param_1 + 4) + 0x20))
                        (param_1,*local_1c,*(int *)(iVar2 + 8) * *(int *)(iVar12 + 0xc),
                         *(int *)(iVar12 + 0xc),1);
      if (*(uint *)(iVar2 + 8) < uVar8) {
        local_c = *(uint *)(iVar12 + 0xc);
      }
      else {
        local_c = *(uint *)(iVar12 + 0x20) % *(uint *)(iVar12 + 0xc);
        if (local_c == 0) {
          local_c = *(uint *)(iVar12 + 0xc);
        }
      }
      uVar3 = *(uint *)(iVar12 + 0x1c);
      uVar4 = *(uint *)(iVar12 + 8);
      uVar9 = uVar3 % uVar4;
      if (0 < (int)uVar9) {
        uVar9 = uVar4 - uVar9;
      }
      local_8 = 0;
      if (0 < (int)local_c) {
        do {
          iVar13 = *(int *)(iVar5 + local_8 * 4);
          (**(code **)(*(int *)(param_1 + 0x158) + 4))
                    (param_1,iVar12,*local_20,iVar13,local_8 << 3,0,uVar3);
          if (0 < (int)uVar9) {
            puVar11 = (undefined4 *)(iVar13 + uVar3 * 0x80);
            Memory_ZeroFill(puVar11,uVar9 << 7);
            uVar1 = *(undefined2 *)(puVar11 + -0x20);
            uVar6 = uVar9;
            if (0 < (int)uVar9) {
              do {
                *(undefined2 *)puVar11 = uVar1;
                puVar11 = puVar11 + 0x20;
                uVar6 = uVar6 - 1;
              } while (uVar6 != 0);
            }
          }
          local_8 = local_8 + 1;
        } while ((int)local_8 < (int)local_c);
      }
      if (*(uint *)(iVar2 + 8) == uVar8) {
        uVar6 = (uVar3 + uVar9) / uVar4;
        local_8 = local_c;
        if ((int)local_c < *(int *)(iVar12 + 0xc)) {
          do {
            puVar11 = *(undefined4 **)(iVar5 + local_8 * 4);
            iVar13 = *(int *)(iVar5 + -4 + local_8 * 4);
            Memory_ZeroFill(puVar11,(uVar3 + uVar9) * 0x80);
            if (uVar6 != 0) {
              local_c = uVar6;
              do {
                uVar1 = *(undefined2 *)(uVar4 * 0x80 + -0x80 + iVar13);
                puVar7 = puVar11;
                uVar10 = uVar4;
                if (0 < (int)uVar4) {
                  do {
                    *(undefined2 *)puVar7 = uVar1;
                    uVar10 = uVar10 - 1;
                    puVar7 = puVar7 + 0x20;
                  } while (uVar10 != 0);
                }
                puVar11 = puVar11 + uVar4 * 0x20;
                iVar13 = iVar13 + uVar4 * 0x80;
                local_c = local_c - 1;
              } while (local_c != 0);
            }
            local_8 = local_8 + 1;
          } while ((int)local_8 < *(int *)(iVar12 + 0xc));
        }
      }
      local_1c = local_1c + 1;
      local_20 = local_20 + 1;
      local_2c = local_2c + 1;
      iVar12 = iVar12 + 0x54;
    } while (local_2c < *(int *)(param_1 + 0x3c));
  }
  String_ToUpper(param_1);
  return;
}


