/*
 * Function: String_WideCharFormatOutput
 * Address: 004ed0d8
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __thiscall
String_WideCharFormatOutput(void *this,undefined4 *param_1,int param_2,int param_3,int *param_4)

{
  undefined4 uVar1;
  undefined4 *puVar2;
  int iVar3;
  undefined4 *unaff_EBP;
  uint unaff_retaddr;
  CHAR local_10 [4];
  undefined4 uStack_c;
  
  puVar2 = (undefined4 *)(DAT_00569f5c ^ unaff_retaddr);
  *param_4 = param_2;
  uVar1 = *param_1;
  iVar3 = String_WideCharToMultiByteConvert(local_10,L'\0',param_1,(int *)((int)this + 8));
  if (0 < iVar3) {
    iVar3 = iVar3 + -1;
    if (param_3 - *param_4 < iVar3) {
      *param_1 = uVar1;
    }
    else if (0 < iVar3) {
      Assembly_MemoryCopy((undefined4 *)*param_4,(int)local_10);
      *param_4 = *param_4 + iVar3;
    }
  }
  uStack_c = 0x4ed161;
  Exception_SetMessage((void *)((uint)puVar2 ^ unaff_retaddr),puVar2,unaff_EBP);
  return;
}


