/*
 * Function: String_Concatenate
 * Address: 00498ee0
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall String_Concatenate(undefined4 *param_1)

{
  char cVar1;
  int iVar2;
  uint uVar3;
  int extraout_ECX;
  int extraout_ECX_00;
  uint extraout_EDX;
  uint extraout_EDX_00;
  
  *param_1 = &PTR_List_Clear_005342c0;
  Scoring_SetHighScore((int)param_1);
  cVar1 = *(char *)((int)param_1 + 0xf1);
  iVar2 = extraout_ECX;
  uVar3 = extraout_EDX;
  while (cVar1 != '\0') {
    Sleep(0x14);
    iVar2 = extraout_ECX_00;
    uVar3 = extraout_EDX_00;
    cVar1 = *(char *)((int)param_1 + 0xf1);
  }
  if (0xf < (uint)param_1[0x3b]) {
                    /* WARNING: Subroutine does not return */
    System_ShutdownHandler(iVar2,uVar3);
  }
  param_1[0x3b] = 0xf;
  param_1[0x3a] = 0;
  *(undefined1 *)(param_1 + 0x36) = 0;
  if (0xf < (uint)param_1[0x34]) {
                    /* WARNING: Subroutine does not return */
    System_ShutdownHandler(iVar2,uVar3);
  }
  param_1[0x34] = 0xf;
  param_1[0x33] = 0;
  *(undefined1 *)(param_1 + 0x2f) = 0;
  if (0xf < (uint)param_1[0x2c]) {
                    /* WARNING: Subroutine does not return */
    System_ShutdownHandler(iVar2,uVar3);
  }
  param_1[0x2c] = 0xf;
  param_1[0x2b] = 0;
  *(undefined1 *)(param_1 + 0x27) = 0;
  if (0xf < (uint)param_1[0x25]) {
                    /* WARNING: Subroutine does not return */
    System_ShutdownHandler(iVar2,uVar3);
  }
  param_1[0x25] = 0xf;
  param_1[0x24] = 0;
  *(undefined1 *)(param_1 + 0x20) = 0;
  if (0xf < (uint)param_1[0x1e]) {
                    /* WARNING: Subroutine does not return */
    System_ShutdownHandler(iVar2,uVar3);
  }
  param_1[0x1e] = 0xf;
  param_1[0x1d] = 0;
  *(undefined1 *)(param_1 + 0x19) = 0;
  if (0xf < (uint)param_1[0x17]) {
                    /* WARNING: Subroutine does not return */
    System_ShutdownHandler(iVar2,uVar3);
  }
  param_1[0x17] = 0xf;
  param_1[0x16] = 0;
  *(undefined1 *)(param_1 + 0x12) = 0;
  if (0xf < (uint)param_1[0x10]) {
                    /* WARNING: Subroutine does not return */
    System_ShutdownHandler(iVar2,uVar3);
  }
  param_1[0x10] = 0xf;
  param_1[0xf] = 0;
  *(undefined1 *)(param_1 + 0xb) = 0;
  if (0xf < (uint)param_1[9]) {
                    /* WARNING: Subroutine does not return */
    System_ShutdownHandler(iVar2,uVar3);
  }
  param_1[9] = 0xf;
  param_1[8] = 0;
  *(undefined1 *)(param_1 + 4) = 0;
  return;
}


