/*
 * Function: Survival_InitializeInsaneMode
 * Address: 00432770
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall Survival_InitializeInsaneMode(int param_1)

{
  int iVar1;
  ulonglong uVar2;
  
  Boss_ProcessWormMechworm(param_1);
  Boss_ProcessRobotXBot(param_1);
  uVar2 = Math_FloatToUInt64();
  iVar1 = (int)uVar2;
  uVar2 = Math_FloatToUInt64();
  Game_DisplayScoreChange
            (*(void **)(param_1 + 0x4c),*(int *)(*(int *)(param_1 + 0x50) + 0xcd4),(int)uVar2,iVar1)
  ;
  return;
}


