/*
 * Function: Texture_GetID
 * Address: 004b9890
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


byte __fastcall Texture_GetID(int param_1)

{
  if (*(int *)(param_1 + 0xc) == 0) {
    return 0;
  }
  return **(byte **)(param_1 + 8) & 1;
}


