/*
 * Function: Texture_SetWrapMode
 * Address: 004b8140
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


int __fastcall Texture_SetWrapMode(undefined4 param_1,undefined2 param_2)

{
  int iVar1;
  void *pvVar2;
  undefined4 *puVar3;
  int extraout_ECX;
  int extraout_ECX_00;
  int extraout_ECX_01;
  int extraout_ECX_02;
  int extraout_ECX_03;
  int extraout_ECX_04;
  int extraout_EDX;
  int extraout_EDX_00;
  uint extraout_EDX_01;
  int extraout_EDX_02;
  byte *extraout_EDX_03;
  byte *extraout_EDX_04;
  byte *extraout_EDX_05;
  byte *pbVar4;
  int extraout_EDX_06;
  uint uVar5;
  uint local_28;
  uint local_24;
  uint local_20;
  void *local_1c;
  uint local_18;
  int local_14;
  uint local_10;
  uint *local_c;
  byte *local_8;
  
  local_14 = String_AllocateBuffer(param_1,param_2);
  if (local_14 != 0) {
    local_8 = (byte *)ImageFormat_WriteHeader("1.0.5",0,0,0);
    if (local_8 == (byte *)0x0) {
      Memory_AllocateBlock(extraout_ECX,extraout_EDX);
      return 0;
    }
    local_c = PixelFormat_SetBlueComponent((int)local_8);
    if (local_c == (uint *)0x0) {
      Memory_AllocateBlock(extraout_ECX_00,extraout_EDX_00);
      ImageFormat_GetFileExtension
                (extraout_ECX_01,extraout_EDX_01,&local_8,(undefined4 *)0x0,(undefined4 *)0x0);
      return 0;
    }
    iVar1 = Assembly_LoopingConstruct((undefined4 *)local_8,extraout_EDX_00);
    if (iVar1 == 0) {
      PixelFormat_SetGreenComponent((int)local_8,local_14);
      ImageFormat_ValidateHeader((uint)local_8,extraout_EDX_03,local_8,local_c);
      ImageFormat_HasTransparency
                (local_8,local_c,&local_18,&local_10,&local_28,&local_24,&local_20,(uint *)0x0,
                 (uint *)0x0);
      ImageFormat_DitherImage((int)local_8);
      ImageFormat_GetFrameCount((int)local_8,0xff,1);
      ImageFormat_DitherImage((int)local_8);
      ImageFormat_ReduceColors((int)local_8);
      ImageFormat_SupportsAnimation((int)local_8);
      iVar1 = ImageFormat_GetMimeType((int)local_8,(int)local_c);
      pvVar2 = operator_new(iVar1 * local_10 * 4);
      uVar5 = 0;
      pbVar4 = extraout_EDX_04;
      if (local_10 != 0) {
        do {
          local_1c = (void *)((int)pvVar2 + uVar5 * local_18 * 4);
          ImageFormat_GetStride
                    ((byte *)&local_1c,local_8,(uint *)local_8,&local_1c,(undefined4 *)0x0,1);
          uVar5 = uVar5 + 1;
          pbVar4 = extraout_EDX_05;
        } while (uVar5 < local_10);
      }
      ImageFormat_GetPadding(local_8,pbVar4,local_8,local_c);
      ImageFormat_GetFileExtension
                (extraout_ECX_03,(uint)&local_c,&local_8,&local_c,(undefined4 *)0x0);
      Memory_AllocateBlock(extraout_ECX_04,extraout_EDX_06);
      puVar3 = (undefined4 *)operator_new(0x10);
      if (puVar3 == (undefined4 *)0x0) {
        iVar1 = 0;
      }
      else {
        iVar1 = Texture_GetFormat(puVar3);
      }
      *(uint *)(iVar1 + 4) = local_18;
      *(void **)(iVar1 + 0xc) = pvVar2;
      *(uint *)(iVar1 + 8) = local_10;
      return iVar1;
    }
    ImageFormat_GetFileExtension(extraout_ECX_02,(uint)&local_c,&local_8,&local_c,(undefined4 *)0x0)
    ;
    Memory_AllocateBlock(local_14,extraout_EDX_02);
  }
  return 0;
}


