/*
 * Function: TextureManager_Initialize
 * Address: 004ba5c0
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


undefined4 * __thiscall TextureManager_Initialize(void *this,int param_1)

{
  undefined2 *puVar1;
  
  *(undefined ***)this = &PTR_TextureManager_Destructor_00537b00;
  puVar1 = (undefined2 *)operator_new(0x10);
  *(undefined2 **)((int)this + 8) = puVar1;
  *(undefined4 *)((int)this + 0x10) = 8;
  *(undefined4 *)((int)this + 0xc) = 2;
  if (param_1 < 0) {
    *(undefined1 *)((int)this + 4) = 1;
    param_1 = -param_1;
  }
  else {
    *(undefined1 *)((int)this + 4) = 0;
  }
  *puVar1 = (short)param_1;
  *(short *)(*(int *)((int)this + 8) + 2) = (short)((uint)param_1 >> 0x10);
  Texture_Release((int)this);
  return (undefined4 *)this;
}


