/*
 * Function: TextureManager_OptimizeTextures
 * Address: 004baf90
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void * __thiscall TextureManager_OptimizeTextures(void *this,void *param_1,void *param_2)

{
  char cVar1;
  ushort uVar2;
  void *pvVar3;
  int iVar4;
  void *this_00;
  void *extraout_ECX;
  uint extraout_EDX;
  uint extraout_EDX_00;
  int extraout_EDX_01;
  int extraout_EDX_02;
  uint extraout_EDX_03;
  uint uVar5;
  int iVar6;
  undefined4 local_40 [5];
  undefined4 local_2c [5];
  uint local_18;
  int local_14;
  void *local_10;
  undefined *puStack_c;
  undefined4 local_8;
  
  local_8 = 0xffffffff;
  puStack_c = &DAT_00517288;
  local_10 = ExceptionList;
  iVar6 = 0;
  local_18 = 0;
  ExceptionList = &local_10;
  cVar1 = Texture_SetID((int)param_2);
  if (cVar1 == '\0') {
    cVar1 = Texture_SetID((int)this);
    if (cVar1 != '\0') {
      pvVar3 = TextureManager_GetTexture(this,local_40);
      local_8 = 1;
      TextureManager_CreateTexture(param_2,param_1,pvVar3);
      Texture_Constructor(local_40,extraout_EDX_00);
      ExceptionList = local_10;
      return param_1;
    }
    Texture_CopyToBuffer(local_2c);
    local_8 = 2;
    Graphics_SetTransform((int)param_2);
    iVar4 = Graphics_SetTransform((int)this);
    pvVar3 = extraout_ECX;
    if (iVar4 <= extraout_EDX_01) {
      pvVar3 = param_2;
    }
    local_14 = Graphics_SetTransform((int)pvVar3);
    if (0 < local_14) {
      do {
        uVar2 = Texture_SetTarget(param_2,iVar6);
        local_18 = (uint)uVar2;
        uVar2 = Texture_SetTarget(this,iVar6);
        iVar4 = (uint)uVar2 + extraout_EDX_02 + local_18;
        Texture_GetInternalFormat(local_2c,iVar6,(short)iVar4);
        iVar6 = iVar6 + 1;
      } while (iVar6 < local_14);
      if (0 < iVar4 >> 0x10) {
        Texture_GetInternalFormat(local_2c,local_14,(short)((uint)iVar4 >> 0x10));
      }
    }
    TextureManager_Shutdown(param_1,(int)local_2c);
    uVar5 = extraout_EDX_03;
  }
  else {
    pvVar3 = TextureManager_GetTexture(this_00,local_2c);
    local_8 = 0;
    TextureManager_CreateTexture(this,param_1,pvVar3);
    uVar5 = extraout_EDX;
  }
  Texture_Constructor(local_2c,uVar5);
  ExceptionList = local_10;
  return param_1;
}


