/*
 * Function: TextureManager_LoadTexture
 * Address: 004ba650
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


int __fastcall TextureManager_LoadTexture(int param_1)

{
  uint uVar1;
  int iVar2;
  int extraout_EDX;
  
  uVar1 = Texture_GetTarget(param_1);
  iVar2 = 0xf;
  do {
    if ((uVar1 & 0xffff & 1 << ((byte)iVar2 & 0x1f)) != 0) {
      return *(int *)(extraout_EDX + 0xc) * 0x10 + -0xf + iVar2;
    }
    iVar2 = iVar2 + -1;
  } while (-1 < iVar2);
  return 0;
}


