/*
 * Function: TextEffect_Constructor
 * Address: 0042c170
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


int * __thiscall TextEffect_Constructor(void *this,int param_1)

{
  undefined4 *puVar1;
  
  puVar1 = (undefined4 *)operator_new(0xc);
  *(undefined4 **)((int)this + 8) = puVar1;
  *(undefined4 **)((int)this + 0xc) = puVar1;
  *(undefined4 **)((int)this + 0x10) = puVar1;
  *(undefined4 *)((int)this + 0x14) = 0;
  puVar1[2] = 0;
  puVar1[1] = 0;
  *puVar1 = 0;
  *(int *)this = param_1;
  *(undefined4 *)((int)this + 4) = *(undefined4 *)(param_1 + 0x5c);
  return (int *)this;
}


