/*
 * Function: Texture_Destructor
 * Address: 004b97d0
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __thiscall Texture_Destructor(void *this,int param_1)

{
  undefined4 *puVar1;
  uint uVar2;
  int iVar3;
  uint extraout_EDX;
  uint uVar4;
  undefined4 *puVar5;
  
  *(int *)((int)this + 0x10) = param_1;
  puVar1 = (undefined4 *)operator_new(param_1 * 2);
  iVar3 = *(int *)((int)this + 0xc);
  uVar4 = extraout_EDX;
  if (0 < iVar3) {
    uVar4 = iVar3 * 2;
    puVar5 = *(undefined4 **)((int)this + 8);
    for (uVar2 = uVar4 >> 2; uVar2 != 0; uVar2 = uVar2 - 1) {
      *puVar1 = *puVar5;
      puVar5 = puVar5 + 1;
      puVar1 = puVar1 + 1;
    }
    for (uVar2 = uVar4 & 3; uVar2 != 0; uVar2 = uVar2 - 1) {
      *(undefined1 *)puVar1 = *(undefined1 *)puVar5;
      puVar5 = (undefined4 *)((int)puVar5 + 1);
      puVar1 = (undefined4 *)((int)puVar1 + 1);
    }
    iVar3 = 0;
  }
                    /* WARNING: Subroutine does not return */
  System_ShutdownHandler(iVar3,uVar4);
}


