/*
 * Function: Timer_Pause
 * Address: 00440a20
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


undefined4 * __thiscall Timer_Pause(void *this,int param_1,int param_2)

{
  undefined8 uVar1;
  undefined4 uVar2;
  
  Boss_HelicopterTurretSystem(this,param_1);
  *(undefined ***)this = &PTR_Config_LoadDefaultSettings_00530c54;
  *(int *)((int)this + 0x70) = param_2;
  uVar1 = *(undefined8 *)(param_2 + 0x90);
  *(undefined8 *)((int)this + 0x58) = uVar1;
  *(undefined8 *)((int)this + 0x40) = uVar1;
  uVar2 = *(undefined4 *)(param_2 + 0x74);
  *(undefined4 *)((int)this + 0x2c) = 0x40240000;
  *(undefined4 *)((int)this + 0x60) = uVar2;
  *(undefined4 *)((int)this + 0x28) = 0;
  *(undefined4 *)((int)this + 100) = 0;
  *(undefined4 *)((int)this + 0x90) = *(undefined4 *)(param_2 + 0xa0);
  *(undefined1 *)((int)this + 0x48) = 0;
  *(int *)(*(int *)((int)this + 0x50) + 0xb0c) = *(int *)(*(int *)((int)this + 0x50) + 0xb0c) + -1;
  *(int *)(*(int *)((int)this + 0x4c) + 0x32c) = *(int *)(*(int *)((int)this + 0x4c) + 0x32c) + -1;
  return (undefined4 *)this;
}


