/*
 * Function: Timer_Initialize
 * Address: 00440810
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall Timer_Initialize(undefined4 *param_1)

{
  *param_1 = &PTR_Timer_GetTotalTime_00530c30;
  Boss_ProcessBattleship(param_1);
  return;
}


