/*
 * Function: Unwind@00515980
 * Address: 00515980
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Instruction at (ram,0x005159ab) overlaps instruction at (ram,0x005159aa)
    */
/* WARNING: Unable to track spacebase fully for stack */

short __fastcall Unwind_00515980(byte *param_1,uint param_2)

{
  byte *pbVar1;
  int *piVar2;
  uint *puVar3;
  uint *puVar4;
  char cVar5;
  undefined4 uVar6;
  byte bVar7;
  byte bVar8;
  byte bVar9;
  byte bVar10;
  int iVar11;
  undefined4 in_EAX;
  undefined3 uVar12;
  int unaff_EBX;
  int *piVar13;
  int *unaff_EBP;
  int iVar14;
  char *unaff_ESI;
  char *unaff_EDI;
  char *pcVar15;
  int *piVar16;
  undefined2 in_CS;
  undefined2 in_DS;
  bool bVar17;
  byte in_AF;
  undefined4 *local_4;
  
  puVar3 = (uint *)(param_1 + (int)unaff_ESI * 8 + 0x378090ca);
  *puVar3 = *puVar3 ^ param_2;
  puVar4 = (uint *)(unaff_ESI + 1);
  cVar5 = *unaff_ESI;
  uVar12 = (undefined3)((uint)in_EAX >> 8);
  iVar11 = CONCAT31(uVar12,cVar5);
  if ((int)*puVar3 < 0) {
    unaff_EDI[iVar11] = unaff_EDI[iVar11] + '\x01';
    pcVar15 = unaff_EDI + 5;
    uVar6 = in((short)param_2);
    *(undefined4 *)(unaff_EDI + 1) = uVar6;
    *(uint *)(param_2 + 0x35ef9d5e) = *(uint *)(param_2 + 0x35ef9d5e) | 0xffffffbb;
    bVar17 = CARRY4((uint)puVar4,*puVar4);
    iVar14 = *(int *)((int)unaff_EBP + 1);
    piVar13 = (int *)((int)unaff_EBP + 5);
  }
  else {
    *unaff_EDI = cVar5;
    local_4 = (undefined4 *)CONCAT22(local_4._2_2_,in_DS);
    param_2 = CONCAT22((short)(param_2 >> 0x10),CONCAT11(0xbf,(char)param_2));
    iVar11 = CONCAT31(uVar12,cVar5 + 'm');
    pcVar15 = (char *)*local_4;
    iVar14 = *(int *)(unaff_EBX + 0x41);
    if (iVar14 <= (int)puVar4) {
      *local_4 = 0x5158d3;
      bVar9 = func_0x74e9d57c();
      return (ushort)bVar9 * (ushort)*(byte *)((int)puVar4 + (0x21 - iVar14));
    }
    bVar17 = (bool)(*param_1 & 1);
    *param_1 = *param_1 >> 1 | bVar17 << 7;
    param_1 = param_1 + -1;
    if (param_1 == (byte *)0x0) {
                    /* WARNING: Bad instruction - Truncating control flow here */
      halt_baddata();
    }
    iVar14 = *unaff_EBP;
    piVar13 = unaff_EBP + 1;
  }
  *(int *)((int)piVar13 + -4) = unaff_EBX;
  pbVar1 = (byte *)(iVar14 + -0x52);
  bVar9 = *pbVar1;
  bVar7 = *pbVar1 + (byte)param_2;
  *pbVar1 = bVar7 + bVar17;
  bVar8 = 9 < ((byte)iVar11 & 0xf) | in_AF;
  uVar12 = (undefined3)((uint)iVar11 >> 8);
  bVar10 = (byte)iVar11 + bVar8 * '\x06';
  piVar16 = (int *)(pcVar15 + 1);
  piVar2 = (int *)(CONCAT31(uVar12,bVar10 + (0x90 < (bVar10 & 0xf0) |
                                            (CARRY1(bVar9,(byte)param_2) || CARRY1(bVar7,bVar17)) |
                                            bVar8 * (0xf9 < bVar10)) * '`') + 0x78 + unaff_EBX * 4);
  *piVar2 = *piVar2 + unaff_EBX;
  *(uint *)(((uint)((int)piVar13 + -4) ^ (uint)param_1) - 4) = param_2;
  iVar11 = CONCAT31(uVar12,DAT_57321f61);
  *(char *)(iVar14 + -0xd0588d3 + (int)piVar16 * 4) = (char)unaff_EBX;
  *(undefined2 *)(iVar11 + -4) = in_CS;
  *piVar16 = *piVar16 << ((byte)param_1 & 0x1f);
  *(char *)piVar16 = (char)((uint)((int)piVar13 + -4) ^ (uint)param_1);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


