/*
 * Function: Unwind@00515199
 * Address: 00515199
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */

void Unwind_00515199(void)

{
  undefined4 in_EAX;
  uint *puVar1;
  uint unaff_EBX;
  
  puVar1 = (uint *)CONCAT31((int3)((uint)in_EAX >> 8),(char)in_EAX + '\x18');
  *puVar1 = *puVar1 & unaff_EBX;
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


