/*
 * Function: Unwind@00517534
 * Address: 00517534
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void Unwind_00517534(void)

{
  undefined4 *unaff_EBX;
  undefined4 unaff_ESI;
  
  *unaff_EBX = unaff_ESI;
  do {
                    /* WARNING: Do nothing block with infinite loop */
  } while( true );
}


