/*
 * Function: Unwind@005177fa
 * Address: 005177fa
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __fastcall Unwind_005177fa(int param_1,undefined4 param_2)

{
  uint *puVar1;
  undefined1 uVar2;
  undefined4 in_EAX;
  short sVar3;
  byte in_CF;
  
  out((short)param_2,in_EAX);
  sVar3 = ((short)in_EAX + -0x45d8) - (ushort)in_CF;
  uVar2 = in(sVar3);
  out(*_DAT_e536e065,sVar3);
  puVar1 = (uint *)(CONCAT31((int3)((uint)param_2 >> 8),uVar2) + param_1 * 4);
  *puVar1 = *puVar1 ^ 0xf;
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


