/*
 * Function: Unwind@0051763a
 * Address: 0051763a
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __fastcall Unwind_0051763a(undefined4 param_1,ushort param_2)

{
  byte *pbVar1;
  uint uVar2;
  uint *puVar3;
  int unaff_EBX;
  int unaff_EBP;
  uint unaff_ESI;
  int *unaff_EDI;
  
  pbVar1 = (byte *)(unaff_EBP + 0x4c);
  *pbVar1 = *pbVar1 >> 7 | *pbVar1 << 1;
  out(param_2 | (ushort)&stack0x00000000,(char)unaff_EBX);
  puVar3 = (uint *)(unaff_EBX >> 0x1f);
  uVar2 = *puVar3;
  *puVar3 = *puVar3 + unaff_ESI;
  _DAT_b0a8bce4 = (_DAT_b0a8bce4 + -0x3d) - (uint)CARRY4(uVar2,unaff_ESI);
  *unaff_EDI = unaff_EBX;
  *(char *)((int)unaff_EDI + -0x5bda7da9) = *(char *)((int)unaff_EDI + -0x5bda7da9) + '\x01';
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


