/*
 * Function: Unwind@00510e30
 * Address: 00510e30
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


float10 __fastcall Unwind_00510e30(undefined4 param_1,int *param_2)

{
  int iVar1;
  ushort *unaff_EBX;
  ushort unaff_DI;
  byte in_CF;
  float10 in_ST0;
  
  iVar1 = *param_2;
  *unaff_EBX = *unaff_EBX + (ushort)in_CF * ((unaff_DI & 3) - (*unaff_EBX & 3));
  return (float10)iVar1 / in_ST0;
}


