/*
 * Function: Unwind@005131c0
 * Address: 005131c0
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall Unwind_005131c0(int param_1)

{
  uint *puVar1;
  uint unaff_ESI;
  int unaff_EDI;
  byte in_CF;
  
  puVar1 = (uint *)(param_1 + unaff_EDI + (uint)in_CF);
  *puVar1 = *puVar1 | unaff_ESI;
  LOCK();
  UNLOCK();
  do {
                    /* WARNING: Do nothing block with infinite loop */
  } while( true );
}


