/*
 * Function: Unwind@00511ba0
 * Address: 00511ba0
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Instruction at (ram,0x00511c0e) overlaps instruction at (ram,0x00511c0d)
    */
/* WARNING: Unable to track spacebase fully for stack */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined8 __fastcall Unwind_00511ba0(int param_1,uint param_2,char *param_3)

{
  int iVar1;
  byte *pbVar2;
  bool bVar3;
  byte bVar4;
  byte bVar5;
  char cVar6;
  undefined4 in_EAX;
  uint uVar7;
  ushort extraout_var;
  undefined4 uVar8;
  uint uVar9;
  undefined2 *puVar10;
  undefined2 uVar11;
  byte bVar13;
  int *extraout_EDX;
  int iVar12;
  uint unaff_EBX;
  int unaff_EBP;
  char *unaff_ESI;
  char *pcVar14;
  uint *unaff_EDI;
  undefined2 in_ES;
  undefined1 in_CF;
  byte in_AF;
  bool in_ZF;
  bool in_SF;
  byte in_TF;
  byte in_IF;
  byte in_NT;
  byte in_AC;
  byte in_VIF;
  byte in_VIP;
  byte in_ID;
  undefined2 in_FPUControlWord;
  undefined2 in_FPUStatusWord;
  undefined2 in_FPUTagWord;
  undefined2 in_FPULastInstructionOpcode;
  undefined4 in_FPUDataPointer;
  undefined4 in_FPUInstructionPointer;
  uint unaff_retaddr;
  
  if (in_SF) {
    if (!(bool)in_CF && !in_ZF) {
                    /* WARNING: Bad instruction - Truncating control flow here */
      halt_baddata();
    }
    return CONCAT44(unaff_retaddr,in_EAX);
  }
  uVar7 = (uint)(short)in_EAX;
  bVar4 = (byte)param_1;
  if (param_1 == 0) {
    uVar9 = (uint)CONCAT11(0x7f,bVar4);
    do {
      uVar9 = uVar9 - 1;
    } while (uVar9 != 0 && in_ZF == false);
LAB_00511c2b:
    do {
      cVar6 = *unaff_ESI;
      *unaff_ESI = *unaff_ESI + '\x01';
      uVar9 = *(uint *)(unaff_ESI + -0x500e4f83);
      *(uint *)(unaff_ESI + -0x500e4f83) = uVar9 << 0x1a | (uint)(CONCAT14(in_CF,uVar9) >> 7);
      bVar4 = (byte)unaff_EBX;
      unaff_EBX = param_2 >> 8 & 0xff;
      param_2 = CONCAT22((short)(param_2 >> 0x10),CONCAT11(bVar4,(char)param_2));
      if (*unaff_ESI != '\0' && SCARRY1(cVar6,'\x01') == *unaff_ESI < '\0') {
        iVar1 = param_2 - 0x4c;
        *unaff_EDI = *unaff_EDI >> 1 | (uint)((*unaff_EDI & 1) != 0) << 0x1f;
        iVar12 = param_2 + 1;
        out((short)iVar12,(char)uVar7 + '\x01');
        puVar10 = (undefined2 *)
                  CONCAT22((short)((uint)iVar1 >> 0x10),
                           CONCAT11((char)((uint)iVar1 >> 8) - *(char *)(unaff_EBP + -0x1d),
                                    (char)iVar1));
        out(*(undefined4 *)unaff_ESI,(short)iVar12);
        *puVar10 = in_FPUControlWord;
        puVar10[2] = in_FPUStatusWord;
        puVar10[4] = in_FPUTagWord;
        *(undefined4 *)(puVar10 + 10) = in_FPUDataPointer;
        *(undefined4 *)(puVar10 + 6) = in_FPUInstructionPointer;
        puVar10[9] = in_FPULastInstructionOpcode;
        uVar11 = CONCAT11((byte)((uint)iVar12 >> 8) | (byte)unaff_EDI,(char)iVar12);
        out(*(undefined4 *)(unaff_ESI + 8),uVar11);
        out(99,unaff_EDI);
        return CONCAT44(CONCAT22((short)((uint)iVar12 >> 0x10),uVar11),unaff_EDI);
      }
      in_CF = 0;
    } while (((byte)unaff_EDI[param_2 * 2 + -0x1a] & bVar4) != 0);
    func_0xb49e298f();
    uVar11 = SUB42(extraout_EDX,0);
    out(*unaff_ESI,uVar11);
    cVar6 = in(uVar11);
    bVar3 = 9 < (cVar6 + 0x86U & 0xf);
    bVar4 = bVar3 | in_AF;
    uVar7 = CONCAT31((int3)(((uint)extraout_var << 0x10) >> 8),cVar6 + 0x86U + bVar4 * '\x06') &
            0xffffff0f;
    *(byte *)((int)extraout_EDX + -0xe) = *(byte *)((int)extraout_EDX + -0xe) | bVar4;
    uVar7 = CONCAT22((short)(uVar7 >> 0x10),CONCAT11(bVar4,(char)uVar7)) | 0xe2123b14;
    pcVar14 = unaff_ESI + 2;
    if ((int)pcVar14 >= 0) {
      *(uint *)(uVar7 - 4) =
           (uint)(in_NT & 1) * 0x4000 | (uint)SCARRY4((int)(unaff_ESI + 1),1) * 0x800 |
           (uint)(in_IF & 1) * 0x200 | (uint)(in_TF & 1) * 0x100 | (uint)((int)pcVar14 < 0) * 0x80 |
           (uint)(pcVar14 == (char *)0x0) * 0x40 | (uint)(bVar3 | in_AF & 1) * 0x10 |
           (uint)((POPCOUNT((uint)pcVar14 & 0xff) & 1U) == 0) * 4 | (uint)(in_ID & 1) * 0x200000 |
           (uint)(in_VIP & 1) * 0x100000 | (uint)(in_VIF & 1) * 0x80000 |
           (uint)(in_AC & 1) * 0x40000;
      *(int *)(uVar7 - 8) = (int)unaff_EDI + *extraout_EDX;
      uVar8 = in(uVar11);
      out(uVar11,uVar8);
      return CONCAT44(extraout_EDX,uVar8);
    }
  }
  else {
    while( true ) {
      unaff_EDI = (uint *)((uint)unaff_EDI | _DAT_cdda229c);
      if ((int)unaff_EDI < 1) {
                    /* WARNING: Bad instruction - Truncating control flow here */
        halt_baddata();
      }
      if (0 < (int)unaff_EDI) break;
      bVar13 = (byte)(param_2 >> 8);
      in_CF = bVar13 < bVar4;
      bVar5 = bVar13 - bVar4;
      param_2 = CONCAT31(CONCAT21((short)(param_2 >> 0x10),bVar5),0x7e);
      if (param_1 == 0) {
        while( true ) {
          unaff_EBP = unaff_EBP + *(int *)(param_2 + 0x28) + (uint)(byte)in_CF;
          bVar4 = *(byte *)(unaff_EBX + 0xb005eebc);
          pbVar2 = (byte *)(unaff_EBP + 0x7ba5e181);
          *pbVar2 = *pbVar2 >> 1 | *pbVar2 << 7;
          param_3 = (char *)CONCAT22(param_3._2_2_,in_ES);
          if (param_1 + -1 == 0 || ((byte)(unaff_retaddr + 0x2123c4e5 >> 8) & bVar4) == 0) break;
          param_1 = param_1 + -1;
          if (param_1 == 0) {
            *(undefined4 *)(unaff_ESI + 0x5b) = *(undefined4 *)(unaff_ESI + 0x5b);
            in_CF = false;
            unaff_retaddr = (uint)CONCAT11(0x13,(byte)unaff_ESI & 0xd9);
            uRamfffffffc = 0x28;
            unaff_ESI = param_3;
          }
          else {
            bVar4 = in(0xd3);
            param_3 = (char *)0x16d9255b;
            unaff_retaddr = (uint)bVar4;
            in_CF = false;
          }
        }
        pbVar2 = (byte *)(unaff_EBX + 0x4e8527d2);
        bVar4 = (byte)(param_1 + -1) & 7;
        *pbVar2 = *pbVar2 >> bVar4 | *pbVar2 << 8 - bVar4;
        return CONCAT44(param_2,param_3);
      }
      uVar7 = unaff_retaddr;
      if (bVar5 == 0 || SBORROW1(bVar13,bVar4) != (short)((ushort)bVar5 << 8) < 0)
      goto LAB_00511c2b;
      bVar5 = (byte)(unaff_retaddr ^ param_2);
      in_AF = 9 < (bVar5 & 0xf) | in_AF;
      bVar5 = bVar5 + in_AF * '\x06';
      unaff_retaddr =
           CONCAT31((int3)((unaff_retaddr ^ param_2) >> 8),
                    bVar5 + (0x90 < (bVar5 & 0xf0) | in_AF * (0xf9 < bVar5)) * '`');
      *(char *)(unaff_retaddr + 0x586514e3) =
           *(char *)(unaff_retaddr + 0x586514e3) - (char)unaff_EBX;
    }
    *unaff_EDI = CONCAT31((int3)(unaff_retaddr >> 8),3);
    unaff_ESI[-0x6a23df77] = unaff_ESI[-0x6a23df77] - (char)((uint)*(undefined4 *)unaff_ESI >> 8);
    *(short *)(unaff_EDI + 1) = (short)*(undefined4 *)unaff_ESI;
  }
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


