/*
 * Function: Unwind@00510720
 * Address: 00510720
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void Unwind_00510720(void)

{
  int in_EAX;
  
  *(int *)(in_EAX + -0x6f) = *(int *)(in_EAX + -0x6f) >> 2;
  do {
                    /* WARNING: Do nothing block with infinite loop */
  } while( true );
}


