/*
 * Function: Unwind@005116e0
 * Address: 005116e0
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __fastcall Unwind_005116e0(undefined4 param_1,int param_2)

{
  uint uVar1;
  code *pcVar2;
  byte extraout_CL;
  int extraout_EDX;
  int unaff_EDI;
  undefined1 in_CF;
  
  (**(code **)(param_2 + 0x5e))();
  uVar1 = *(uint *)(&stack0x00000000 + extraout_EDX);
  *(uint *)(&stack0x00000000 + extraout_EDX) =
       uVar1 << (extraout_CL & 0x1f) | (uint)(CONCAT14(in_CF,uVar1) >> 0x21 - (extraout_CL & 0x1f));
  _DAT_e7deede8 = _DAT_e7deede8 - unaff_EDI;
  pcVar2 = (code *)swi(1);
  (*pcVar2)();
  return;
}


