/*
 * Function: Unwind@005100f8
 * Address: 005100f8
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void Unwind_005100f8(void)

{
  do {
                    /* WARNING: Do nothing block with infinite loop */
  } while( true );
}


