/*
 * Function: Unwind@00515e60
 * Address: 00515e60
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Instruction at (ram,0x00515e7b) overlaps instruction at (ram,0x00515e7a)
    */
/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unable to track spacebase fully for stack */
/* WARNING: Removing unreachable block (ram,0x00515e7b) */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined8 __fastcall Unwind_00515e60(undefined *param_1,undefined1 *param_2,undefined3 param_3)

{
  char *pcVar1;
  undefined1 uVar2;
  uint in_EAX;
  uint uVar3;
  int iVar4;
  uint uVar5;
  code *extraout_ECX;
  int extraout_ECX_00;
  char cVar7;
  undefined1 *puVar6;
  undefined1 *extraout_EDX;
  byte bVar8;
  undefined4 unaff_EBX;
  int unaff_EBP;
  byte *pbVar9;
  byte *unaff_ESI;
  uint *unaff_EDI;
  undefined2 in_FS;
  byte in_CF;
  char in_ZF;
  bool bVar10;
  undefined1 in_OF;
  uint *puVar11;
  
  puVar11 = (uint *)0x0;
  while( true ) {
    bVar8 = (byte)((uint)unaff_EBX >> 8);
    if ((code *)param_1 != (code *)0x1 && in_ZF == '\0') {
      *(int *)(unaff_EBP + -0x19) = (*(int *)(unaff_EBP + -0x19) - (int)unaff_ESI) - (uint)in_CF;
      cVar7 = (char)((uint)param_2 >> 8);
      *(char *)(in_EAX + 0xe69145b6) = cVar7;
      pcVar1 = (char *)(unaff_EBP + -0x409e9179 + (int)unaff_ESI * 8);
      *pcVar1 = *pcVar1 - cVar7;
      *(byte *)unaff_EDI = (byte)*unaff_EDI ^ bVar8;
                    /* WARNING: Bad instruction - Truncating control flow here */
      halt_baddata();
    }
    if (!(bool)in_OF) break;
    uVar3 = func_0x37171244(unaff_EBP);
    *(byte *)((int)unaff_EDI + -0x51f8ea) = *(byte *)((int)unaff_EDI + -0x51f8ea) + 1;
    iVar4 = uVar3 + 0xe4c34b84;
    param_1 = (undefined *)(extraout_ECX_00 + -1);
    if ((code *)param_1 == (code *)0x0 || iVar4 == 0) {
      uVar3 = CONCAT31((int3)((uint)iVar4 >> 8),(char)iVar4 + '5');
      uVar5 = uVar3 & 0xffffffc8;
      *(uint *)(uVar3 * -0x4f + -4) = uVar5;
      *unaff_EDI = uVar5;
      return CONCAT44(CONCAT31(param_3,(char)((uint)puVar11 >> 0x18)),
                      CONCAT22((short)(uVar5 >> 0x10),
                               (ushort)(byte)((char)uVar5 + (char)(uVar5 >> 8) * -0x66)));
    }
    puVar6 = &DAT_3f82a1e2;
    bVar10 = SCARRY1(DAT_b6d0933c,bVar8);
    cVar7 = DAT_b6d0933c + bVar8;
    DAT_b6d0933c = cVar7 + (uVar3 < 0x1b3cb47c);
    if ((bVar10 != SCARRY1(cVar7,uVar3 < 0x1b3cb47c)) == DAT_b6d0933c < '\0') {
      (*(code *)param_1)();
      *(undefined2 *)((int)unaff_EDI + 0x13) = in_FS;
      param_1 = extraout_ECX;
      puVar6 = extraout_EDX;
      pbVar9 = unaff_ESI;
    }
    else {
      puVar11 = (uint *)((int)unaff_EDI + -0x4bd0e0ed);
      *puVar11 = *puVar11 >> 1 | (uint)((*puVar11 & 1) != 0) << 0x1f;
      *unaff_ESI = *unaff_ESI ^ 0x43;
      unaff_EDI = (uint *)((int)unaff_EDI + 3);
      pbVar9 = unaff_ESI + 4;
    }
    while( true ) {
      iVar4 = in((short)puVar6);
      param_2 = puVar6 + 1;
      uVar3 = iVar4 + 0x7241d100;
      *(uint *)(unaff_EBP + 0x208e88fa) = *(uint *)(unaff_EBP + 0x208e88fa) ^ (uint)param_1;
      ((code *)param_1)[0x79] = (code)((char)((code *)param_1)[0x79] - bVar8);
      unaff_EBP = 0x4490d72b;
      unaff_ESI = pbVar9 + 1;
      *(byte *)((int)unaff_EDI + -1) = *pbVar9;
      uVar2 = in((short)param_2);
      uVar3 = CONCAT22((short)(uVar3 >> 0x10),
                       CONCAT11(((char)(uVar3 >> 8) - DAT_4490d762) - (uVar3 < 0xf420135f),uVar2)) ^
              0x4ef3d5d5;
      if ((POPCOUNT(uVar3 & 0xff) & 1U) != 0) break;
      puVar6 = puVar6 + 2;
      pbVar9 = unaff_ESI;
    }
    ((code *)param_1)[0x247226f1] = (code)((byte)((code *)param_1)[0x247226f1] & (byte)(uVar3 >> 8))
    ;
    in_CF = 0;
    in_OF = false;
    in_EAX = uVar3 | 0x9d70de1c;
    in_ZF = in_EAX == 0;
    puVar11 = unaff_EDI;
  }
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


