/*
 * Function: Unwind@00513140
 * Address: 00513140
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"

// Decompilation failed for Unwind@00513140
void Unwind@00513140(void) {
    // Implementation unavailable
}
