/*
 * Function: Unwind@00516f98
 * Address: 00516f98
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */

void __fastcall Unwind_00516f98(undefined4 param_1,undefined4 param_2)

{
  undefined2 uVar1;
  int unaff_EBX;
  char *unaff_ESI;
  undefined1 *unaff_EDI;
  
  *unaff_ESI = (*unaff_ESI + -0x51) - (&stack0x00000000 < unaff_EDI);
  uVar1 = CONCAT11((byte)((uint)param_2 >> 8) & *(byte *)(unaff_EBX + 0x5dd7870b),(char)param_2);
  out(*unaff_ESI,uVar1);
  *(int *)(unaff_EBX + -0x150a70bb) =
       *(int *)(unaff_EBX + -0x150a70bb) - CONCAT22((short)((uint)param_2 >> 0x10),uVar1);
  unaff_EDI[0x16b5707d] = unaff_EDI[0x16b5707d] + '\x01';
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


