/*
 * Function: Unwind@00517668
 * Address: 00517668
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */

void Unwind_00517668(void)

{
  int unaff_EDI;
  
  *(char *)(unaff_EDI + -0x5bda7dae) = *(char *)(unaff_EDI + -0x5bda7dae) + '\x01';
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


