/*
 * Function: Unwind@00514b98
 * Address: 00514b98
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Instruction at (ram,0x00514dd2) overlaps instruction at (ram,0x00514dce)
    */
/* WARNING: Unable to track spacebase fully for stack */
/* WARNING: Removing unreachable block (ram,0x00514d0a) */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __fastcall Unwind_00514b98(char *param_1,int *param_2)

{
  byte *pbVar1;
  undefined1 uVar2;
  undefined1 *puVar3;
  char cVar4;
  code cVar5;
  uint uVar6;
  bool bVar7;
  code *pcVar8;
  undefined6 uVar9;
  byte bVar10;
  ushort uVar11;
  undefined4 in_EAX;
  char *pcVar12;
  char *pcVar13;
  uint uVar14;
  uint uVar15;
  undefined1 *puVar17;
  uint *extraout_ECX;
  int extraout_ECX_00;
  int extraout_ECX_01;
  int extraout_ECX_02;
  int iVar19;
  undefined2 uVar20;
  int *extraout_EDX;
  undefined2 *puVar21;
  int unaff_EBX;
  int *piVar22;
  undefined4 *puVar23;
  undefined4 *puVar24;
  code **ppcVar25;
  undefined1 *puVar26;
  code **unaff_EBP;
  code **ppcVar27;
  code *pcVar28;
  char *unaff_ESI;
  int *piVar29;
  int *piVar30;
  byte *pbVar31;
  char *unaff_EDI;
  int *piVar32;
  int *piVar33;
  byte *pbVar34;
  uint *puVar35;
  uint *puVar36;
  undefined2 uVar37;
  undefined2 in_SS;
  byte bVar38;
  bool bVar39;
  byte in_AF;
  bool bVar40;
  bool bVar41;
  byte in_TF;
  byte in_IF;
  byte bVar42;
  bool bVar43;
  byte in_NT;
  byte in_AC;
  byte in_VIF;
  byte in_VIP;
  byte in_ID;
  unkbyte10 in_ST7;
  undefined4 in_XMM1_Da;
  undefined4 in_XMM1_Db;
  undefined4 in_XMM1_Dc;
  undefined4 in_XMM1_Dd;
  undefined8 uVar44;
  int *unaff_retaddr;
  undefined1 auStack_5efb [17498];
  char *pcStack_1aa1;
  char acStack_4d [21];
  undefined1 *puStack_38;
  int *piStack_24;
  int *piStack_20;
  code *pcStack_1c;
  undefined1 *puStack_18;
  int *piStack_14;
  int *piStack_10;
  char *pcStack_c;
  char *pcStack_8;
  code *local_4;
  char *pcVar16;
  undefined3 uVar18;
  
  bVar42 = 0;
  while (param_1 = param_1 + -1, param_1 != (char *)0x0) {
    *(int *)(param_1 + unaff_EBX + 0x434bc6d1) = -*(int *)(param_1 + unaff_EBX + 0x434bc6d1);
  }
  do {
    cVar4 = *param_1;
    puVar35 = (uint *)((int)param_2 + -0x15);
    uVar15 = *puVar35;
    *puVar35 = (int)*puVar35 >> 1;
    uVar6 = *puVar35;
    *(int **)(unaff_EDI + -4) = param_2;
    bVar10 = (byte)param_2;
    param_2 = (int *)CONCAT22((short)((uint)param_2 >> 0x10),CONCAT11(0x6d,bVar10));
    uVar14 = (uint)bVar42;
    *unaff_EDI = *unaff_ESI;
    bVar42 = 1;
    puVar17 = *(undefined1 **)(unaff_EDI + -4);
    if ((POPCOUNT(uVar6 & 0xff) & 1U) != 0) {
      DAT_28bdda20 = DAT_28bdda20 & bVar10;
      pbVar31 = puVar17 + 0x1c33280f;
      bVar42 = (byte)puVar17;
      cVar4 = bVar42 + *pbVar31;
      pcRamf775c62f = param_1;
      *(uint *)(unaff_EDI + -3) =
           (uint)(in_NT & 1) * 0x4000 |
           (uint)(SCARRY1(bVar42,*pbVar31) != SCARRY1(cVar4,'\0')) * 0x800 | 0x400 |
           (uint)(in_IF & 1) * 0x200 | (uint)(in_TF & 1) * 0x100 | (uint)(cVar4 < '\0') * 0x80 |
           (uint)(cVar4 == '\0') * 0x40 | (uint)(in_AF & 1) * 0x10 |
           (uint)((POPCOUNT(cVar4) & 1U) == 0) * 4 | (uint)CARRY1(bVar42,*pbVar31) |
           (uint)(in_ID & 1) * 0x200000 | (uint)(in_VIP & 1) * 0x100000 |
           (uint)(in_VIF & 1) * 0x80000 | (uint)(in_AC & 1) * 0x40000;
                    /* WARNING: Bad instruction - Truncating control flow here */
      halt_baddata();
    }
    LOCK();
    uVar2 = *puVar17;
    *puVar17 = (char)((uint)param_1 >> 8);
    param_1 = (char *)CONCAT22((short)((uint)param_1 >> 0x10),CONCAT11(uVar2,(char)param_1));
    UNLOCK();
    piVar22 = (int *)(puVar17 + -1);
    pcVar12 = (char *)((CONCAT22((short)((uint)in_EAX >> 0x10),
                                 (ushort)(byte)((char)in_EAX + cVar4 +
                                               (char)((uint)in_EAX >> 8) * -0x5c)) + 0x762820d6) -
                      (uint)((uVar15 & 1) != 0));
    *(int *)(param_1 + 0x4108dc58) = *(int *)(param_1 + 0x4108dc58) + 0x5f;
    piVar30 = (int *)0x9cea6bd8;
    piVar33 = (int *)(unaff_EDI + uVar14 * -2 + 1);
    while( true ) {
      piVar32 = piVar33;
      piVar29 = (int *)((int)piVar30 + -1);
      bVar10 = (byte)pcVar12;
      uVar37 = (undefined2)((uint)pcVar12 >> 0x10);
      uVar18 = (undefined3)(CONCAT22(uVar37,CONCAT11(bVar10 / 0x66,bVar10)) >> 8);
      uVar11 = (ushort)CONCAT31(uVar18,bVar10 % 0x66);
      local_4 = (code *)CONCAT31(uVar18,0x26);
      if (uVar11 != 0) break;
      piVar33 = piVar32 + -1;
      *piVar32 = (int)local_4;
      pcVar12 = (char *)(CONCAT31((int3)(CONCAT22(uVar37,0x9026) >> 8),0x26) | 0x25);
      *(uint *)((int)piVar22 + -0xf) = *(uint *)((int)piVar22 + -0xf) | (uint)pcVar12;
      pcStack_8 = pcVar12;
      pcStack_c = param_1;
      piStack_10 = param_2;
      piStack_14 = piVar22;
      puStack_18 = (undefined1 *)&local_4;
      pcStack_1c = (code *)unaff_EBP;
      piStack_20 = piVar29;
      piStack_24 = piVar33;
      uVar14 = (int)piVar33 - (int)piVar22;
      bVar39 = (POPCOUNT(uVar14 & 0xff) & 1U) == 0;
      if (bVar39) {
        pcVar28 = (code *)swi(0x53);
        (*pcVar28)();
                    /* WARNING: Bad instruction - Truncating control flow here */
        halt_baddata();
      }
      pcVar28 = (code *)((int)unaff_EBP + 0x7bc92438);
      bVar10 = (byte)param_1 & 0x1f;
      cVar5 = *pcVar28;
      *pcVar28 = (code)((char)*pcVar28 << bVar10);
      bVar7 = ((uint)param_1 & 0x1f) != 0;
      bVar38 = !bVar7 && piVar33 < piVar22 || bVar7 && (char)((char)cVar5 << bVar10 - 1) < '\0';
      bVar43 = bVar10 != 1 && SBORROW4((int)piVar33,(int)piVar22) ||
               bVar10 == 1 && (bool)bVar38 != (char)*pcVar28 < '\0';
      bVar7 = ((uint)param_1 & 0x1f) != 0;
      bVar41 = !bVar7 && (int)uVar14 < 0 || bVar7 && (char)*pcVar28 < '\0';
      bVar40 = !bVar7 && uVar14 == 0 || bVar7 && *pcVar28 == (code)0x0;
      bVar39 = !bVar7 && bVar39 || bVar7 && (POPCOUNT(*pcVar28) & 1U) == 0;
      param_2 = piVar33;
code_r0x00514c19:
      piVar30 = piVar29;
      if (!bVar40 && bVar43 == bVar41) {
        ppcVar27 = unaff_EBP;
        if (bVar43) {
          piVar30 = (int *)CONCAT22((short)((uint)pcVar12 >> 0x10),CONCAT11(0xa3,(char)pcVar12));
          if (!bVar40 && bVar43 == bVar41) {
            *piVar30 = *piVar30 >> 1;
            return;
          }
          *(int *)((int)piVar32 + -0x2e) = *(int *)((int)piVar32 + -0x2e) - (int)param_1;
                    /* WARNING: Bad instruction - Truncating control flow here */
          halt_baddata();
        }
        do {
          pcVar16 = param_1;
          pcVar13 = pcVar12;
          if (!bVar39) {
            piVar29 = (int *)*(undefined6 *)((int)param_2 + 0x7b);
            goto code_r0x00514c8f;
          }
          puVar35 = (uint *)(pcVar13 + 0x5b25e658);
          uVar14 = *puVar35;
          uVar15 = *puVar35;
          *puVar35 = (uint)(&stack0x00000000 + uVar15 + bVar38);
          *pcVar13 = *pcVar13 + -0x42 +
                     (CARRY4(uVar14,(uint)&stack0x00000000) ||
                     CARRY4((uint)(&stack0x00000000 + uVar15),(uint)bVar38));
          param_2 = (int *)(*(int *)(pcVar16 + 0x12) * -0x32);
          ppcVar25 = &local_4;
          unaff_EBP = &local_4;
          local_4 = (code *)ppcVar27;
          cVar4 = '\f';
          do {
            ppcVar27 = (code **)((int)ppcVar27 + -4);
            ppcVar25 = ppcVar25 + -1;
            *ppcVar25 = *ppcVar27;
            cVar4 = cVar4 + -1;
          } while ('\0' < cVar4);
          puStack_38 = (undefined1 *)&local_4;
          piVar22 = (int *)CONCAT31((int3)((uint)piVar22 >> 8),
                                    (char)piVar22 - acStack_4d[(int)param_2]);
          param_1 = (char *)CONCAT22((short)((uint)pcVar16 >> 0x10),CONCAT11(0x38,(char)pcVar16));
          bVar38 = false;
          bVar43 = false;
          pcVar12 = (char *)((uint)pcVar13 & 0xffffffc9);
          bVar41 = false;
          bVar40 = ((uint)pcVar13 & 0xc9) == 0;
          bVar39 = (POPCOUNT((byte)pcVar13 & 0xc9) & 1U) == 0;
          do {
            pcStack_1aa1 = pcVar13;
            if (bVar39) goto code_r0x00514c19;
            param_1 = param_1 + -1;
            piVar30 = piVar29;
            if (param_1 == (char *)0x0) {
              out(*piVar29,(short)param_2);
              piVar30 = unaff_retaddr;
            }
            piVar29 = (int *)((int)piVar30 + -1);
            out((char)*piVar30,(short)param_2);
          } while (!bVar40);
          uVar14 = (uint)pcVar13 & 0x27f02f00;
          bVar39 = true;
          uVar15 = CONCAT31((int3)(uVar14 >> 8),in_AF * '\x06') & 0xffffff0f;
          pcVar16 = (char *)CONCAT22((short)(uVar15 >> 0x10),
                                     CONCAT11((char)(uVar14 >> 8) + in_AF,(char)uVar15));
          pcVar12 = pcVar16;
          ppcVar27 = &local_4;
          bVar38 = in_AF;
          unaff_retaddr = piVar33;
        } while (uVar14 == 0);
        ppcVar27 = (code **)((uint)&local_4 | (uint)pcVar16);
code_r0x00514c8f:
        uVar9 = *(undefined6 *)(pcVar16 + 0x1b5c9807);
        uVar37 = (undefined2)((uint6)uVar9 >> 0x20);
        out(0xec,pcVar16);
        pcVar12 = (char *)((int)piVar29 + 0x325f871d);
        cVar4 = *pcVar12;
        *pcVar12 = *pcVar12 - (char)param_2;
        piVar30 = (int *)((int)piVar29 + -1);
        out((char)*piVar29,(short)param_2);
        pcVar28 = (code *)swi(4);
        if (SBORROW1(cVar4,(char)param_2)) {
          (*pcVar28)();
          param_2 = extraout_EDX;
        }
        pcVar28 = *ppcVar27;
        local_4 = Unwind_00514d1b;
        uVar44 = (*(code *)((int)param_2 + 0x1d))();
        pcVar12 = (char *)((int)piVar32 + -5);
        bVar10 = (byte)uVar44;
        if (SBORROW1(bVar10,(char)*piVar33)) {
          uVar14 = CONCAT22((short)((uint6)uVar9 >> 0x10),
                            CONCAT11((char)((uint6)uVar9 >> 8) +
                                     *(char *)((ulonglong)uVar44 >> 0x20),(char)uVar9));
          pbVar34 = (byte *)((int)piVar32 + -10);
          *(int *)((int)piVar32 + -6) = *piVar30;
          pbVar31 = (byte *)(uVar14 - 0x2e);
          *pbVar31 = *pbVar31 << 1 | *pbVar31 >> 7;
          bVar42 = *pbVar31;
          cVar4 = *(char *)((int)uVar44 + -0x2a0e4518);
          *extraout_ECX = *extraout_ECX ^ uVar14;
          local_4 = (code *)CONCAT22(local_4._2_2_,in_SS);
          bVar42 = 0xf < (byte)(bVar10 + cVar4 + ((bVar42 & 1) != 0));
          *pbVar34 = *pbVar34 - 1;
          ffree(in_ST7);
          pcStack_8 = (char *)0x514d44;
          uVar44 = func_0x11b54bd3();
          puVar21 = (undefined2 *)((ulonglong)uVar44 >> 0x20);
          uVar14 = (uint)bVar42;
          pcVar12 = (char *)((int)piVar29 + 0x29f53f8d);
          pbVar31 = (byte *)(pcVar12 + uVar14);
          uVar20 = (undefined2)((ulonglong)uVar44 >> 0x20);
          if ((SCARRY4((int)piVar29 + -6,0x29f53f93) != SCARRY4((int)pcVar12,uVar14)) !=
              (int)pbVar31 < 0) {
            bVar42 = 9 < ((byte)uVar44 & 0xf) | in_AF;
            bVar10 = (byte)uVar44 + bVar42 * -6;
            *(uint *)(puVar21 + -0x3fbcdc63) =
                 *(uint *)(puVar21 + -0x3fbcdc63) ^
                 CONCAT31((int3)((ulonglong)uVar44 >> 8),
                          bVar10 + (0x9f < bVar10 |
                                   ((char *)0xd60ac06c < (char *)((int)piVar29 + -6) ||
                                   CARRY4((uint)pcVar12,uVar14)) | bVar42 * (bVar10 < 6)) * -0x60 +
                          (char)((ulonglong)uVar44 >> 8) * '~' + 'P') & 0xffff00ff;
            _DAT_a21d64f1 = in(uVar20);
                    /* WARNING: Bad instruction - Truncating control flow here */
            halt_baddata();
          }
          pbVar1 = (byte *)((int)puVar21 + 0x1b);
          bVar42 = (byte)extraout_ECX_00 & 7;
          *pbVar1 = *pbVar1 << bVar42 | *pbVar1 >> 8 - bVar42;
          out(0xfe,(int)uVar44);
          if (*pbVar31 >= *pbVar34) {
            out(uVar20,(char)*(undefined4 *)pbVar31);
            *(uint *)(pbVar31 + (int)&pcStack_8 + (*pbVar31 < *pbVar34)) =
                 *(uint *)(pbVar31 + (int)&pcStack_8 + (*pbVar31 < *pbVar34)) ^ (uint)&local_4;
                    /* WARNING: Bad instruction - Truncating control flow here */
            halt_baddata();
          }
          if (extraout_ECX_00 == 0) {
            cVar4 = in(uVar20);
            *(char *)((int)piVar32 + -0xb) = cVar4;
            halt_baddata();
          }
        }
        else {
          bVar10 = 9 < (bVar10 & 0xf) | in_AF;
          ppcVar27 = &local_4;
          pcVar8 = (code *)swi(0x43);
          local_4 = pcVar28;
          uVar44 = (*pcVar8)();
          puVar21 = (undefined2 *)((ulonglong)uVar44 >> 0x20);
          puVar35 = (uint *)((int)pcVar12 * 0x200000);
          puVar23 = (undefined4 *)
                    *(undefined6 *)(extraout_ECX_01 + 0x14d442a4 + (int)pcVar12 * 0x800000);
          uVar14 = (uint)((int)pcVar12 * 0x100000 < 0);
          puVar17 = &stack0xa5aa28f2 + uVar14;
          iVar19 = *(int *)uVar44;
          puVar26 = (undefined1 *)(iVar19 + -4);
          *(undefined2 *)(iVar19 + -4) = uVar37;
          if (auStack_5efb < (undefined1 *)0x5a557813 && !CARRY4((uint)&stack0xa5aa28f2,uVar14)) {
            if ((int)((uint)puVar23 & (uint)puVar35) < 1) {
              bVar42 = 0;
              iVar19 = extraout_ECX_01;
              puVar24 = puVar23;
            }
            else {
              bVar39 = *(uint *)(extraout_ECX_01 + 0x19) < 0x6383ea3e;
              puVar26 = (undefined1 *)(iVar19 + -8);
              *(undefined4 *)(iVar19 + -8) = 0x514db1;
              uVar44 = func_0x8f4910b7();
              puVar21 = (undefined2 *)((ulonglong)uVar44 >> 0x20);
              if (bVar39) {
                puVar24 = (undefined4 *)(puVar26 + -4);
                *(undefined4 **)(puVar26 + -4) = puVar23;
                cVar4 = '\x1d';
                do {
                  puVar23 = puVar23 + -1;
                  puVar24 = puVar24 + -1;
                  *puVar24 = *puVar23;
                  cVar4 = cVar4 + -1;
                } while ('\0' < cVar4);
                *(undefined1 **)(puVar26 + -0x7c) = puVar26 + -4;
                    /* WARNING: Bad instruction - Truncating control flow here */
                halt_baddata();
              }
              *piVar30 = (*piVar30 - (int)piVar30) - (uint)bVar39;
              bVar10 = 9 < ((byte)uVar44 & 0xf) | bVar10;
              uVar18 = (undefined3)((ulonglong)uVar44 >> 8);
              bVar38 = (byte)uVar44 + bVar10 * '\x06';
              puVar24 = (undefined4 *)
                        (puVar17 +
                        (-(uint)(CONCAT31(uVar18,bVar38 + (0x90 < (bVar38 & 0xf0) |
                                                          puVar23 < *(undefined4 **)
                                                                     (puVar21 + (int)puVar17 * 4) |
                                                          bVar10 * (0xf9 < bVar38)) * '`') <
                                0xb79e35cb) - *(int *)((int)piVar29 + 0xe)));
              puVar17 = (undefined1 *)CONCAT31(uVar18,uRamf0a18cd1);
              puVar36 = puVar35 + -1;
              puVar3 = (undefined1 *)*puVar35;
              iVar19 = extraout_ECX_02;
              do {
                iVar19 = iVar19 + -1;
                ppcVar27 = (code **)puVar23;
                puVar35 = puVar36;
              } while (iVar19 != 0 && puVar17 == puVar3);
            }
            *(undefined4 *)((int)ppcVar27 + -0x3f3251b) = in_XMM1_Da;
            *(undefined4 *)((int)ppcVar27 + -0x3f32517) = in_XMM1_Db;
            *(undefined4 *)((int)ppcVar27 + -0x3f32513) = in_XMM1_Dc;
            *(undefined4 *)((int)ppcVar27 + -0x3f3250f) = in_XMM1_Dd;
            *(uint *)(puVar26 + -4) = (uint)puVar17 | 0xee99e10d;
            *(int *)(puVar26 + -8) = iVar19;
            *(undefined2 **)(puVar26 + -0xc) = puVar21;
            *(undefined4 **)(puVar26 + -0x10) = puVar24;
            *(undefined1 **)(puVar26 + -0x14) = puVar26;
            *(int *)(puVar26 + -0x18) = (int)ppcVar27 + 1;
            *(int **)(puVar26 + -0x1c) = piVar30;
            *(uint **)(puVar26 + -0x20) = puVar35;
            while (iVar19 != 0) {
              iVar19 = iVar19 + -1;
              uVar2 = in((short)puVar21);
              *(undefined1 *)puVar35 = uVar2;
              puVar35 = (uint *)((int)puVar35 + (uint)bVar42 * -2 + 1);
            }
                    /* WARNING: Bad instruction - Truncating control flow here */
            halt_baddata();
          }
        }
        *puVar21 = uVar37;
                    /* WARNING: Bad instruction - Truncating control flow here */
        halt_baddata();
      }
    }
    in_EAX = in(0x5a);
    if ((POPCOUNT(uVar11 & 0xff) & 1U) != 0) {
                    /* WARNING: Bad instruction - Truncating control flow here */
      halt_baddata();
    }
    unaff_EDI = (char *)((int)piVar32 + -1);
    unaff_ESI = (char *)((int)piVar30 + -2);
    *(char *)piVar32 = *(char *)piVar29;
  } while( true );
}


