/*
 * Function: Unwind@00512667
 * Address: 00512667
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */

void Unwind_00512667(void)

{
  int in_EAX;
  undefined4 unaff_EBP;
  int unaff_ESI;
  undefined4 *unaff_EDI;
  byte in_CF;
  
  *unaff_EDI = unaff_EBP;
  *(int *)(unaff_ESI + -0x23) = *(int *)(unaff_ESI + -0x23) + in_EAX + (uint)in_CF;
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


