/*
 * Function: Unwind@0050fd73
 * Address: 0050fd73
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */

undefined8 __fastcall Unwind_0050fd73(undefined4 param_1,int param_2)

{
  byte *pbVar1;
  char in_AL;
  int iVar2;
  int unaff_EBX;
  int unaff_ESI;
  char in_CF;
  bool bVar3;
  undefined4 in_stack_00000014;
  undefined4 in_stack_0000001c;
  
  iVar2 = CONCAT22((short)((uint)param_1 >> 0x10),CONCAT11(0xd,(char)param_1));
  bVar3 = (char)(in_AL + -0x4c) != in_CF;
  if (iVar2 == 1 || bVar3) {
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  }
  if (iVar2 == 2 || bVar3) {
    pbVar1 = (byte *)(param_2 + -0x6f + unaff_EBX);
    *pbVar1 = *pbVar1 | 0x44;
    *(int *)(unaff_ESI + 0x1a) = *(int *)(unaff_ESI + 0x1a) << 1;
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  }
  return CONCAT44(in_stack_00000014,in_stack_0000001c);
}


