/*
 * Function: Unwind@00510e68
 * Address: 00510e68
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void Unwind_00510e68(void)

{
  do {
                    /* WARNING: Do nothing block with infinite loop */
  } while( true );
}


