/*
 * Function: Unwind@00515d70
 * Address: 00515d70
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */

void __fastcall Unwind_00515d70(int param_1,char param_2)

{
  char *pcVar1;
  byte bVar2;
  ulonglong uVar3;
  uint5 uVar4;
  undefined4 unaff_EBP;
  int unaff_ESI;
  uint unaff_EDI;
  byte in_CF;
  
  bVar2 = (byte)param_1 & 0x1f;
  uVar4 = CONCAT14(unaff_EDI < *(uint *)(param_1 + -0x75959ad0) ||
                   unaff_EDI - *(uint *)(param_1 + -0x75959ad0) < (uint)in_CF,unaff_EBP);
  uVar3 = (ulonglong)uVar4 << bVar2 | (ulonglong)(uVar4 >> 0x21 - bVar2);
  pcVar1 = (char *)((int)uVar3 + -0x33 + unaff_ESI * 4);
  *pcVar1 = (*pcVar1 - param_2) - ((uVar3 & 0x100000000) != 0);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


