/*
 * Function: Unwind@005137c7
 * Address: 005137c7
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unable to track spacebase fully for stack */

void __fastcall Unwind_005137c7(int param_1,undefined4 param_2)

{
  uint *puVar1;
  uint uVar2;
  longlong lVar3;
  code *pcVar4;
  undefined4 in_EAX;
  undefined1 *puVar5;
  uint3 uVar6;
  undefined1 *puVar7;
  uint unaff_ESI;
  undefined1 *unaff_EDI;
  undefined2 in_GS;
  int in_GS_OFFSET;
  bool bVar8;
  undefined8 uVar9;
  int unaff_retaddr;
  
  uVar6 = (uint3)((uint)param_2 >> 8) ^ (uint3)((uint)*(undefined4 *)(unaff_ESI + 0x78eb58b5) >> 8);
  puVar5 = (undefined1 *)CONCAT22((short)((uint)in_EAX >> 0x10),in_GS);
  if (param_1 == 0) {
    puVar5 = &DAT_72650b0e;
  }
  else {
    unaff_ESI = unaff_ESI | *(uint *)(param_1 + 0x2c);
    if ((int)unaff_ESI < 1) {
      lVar3 = (longlong)*(int *)(unaff_ESI + 0x35) * -0x16;
      puVar7 = puVar5 + -4;
      *(uint *)(puVar5 + -4) = unaff_ESI;
      if (SBORROW4(CONCAT31(uVar6,0x7b),1)) {
        pcVar4 = (code *)swi(0x94);
        uVar9 = (*pcVar4)();
        puVar1 = (uint *)(in_GS_OFFSET + (int)((ulonglong)uVar9 >> 0x20) + 0x1b);
        *puVar1 = *puVar1 & (uint)uVar9;
        return;
      }
      puVar5 = (undefined1 *)CONCAT31((int3)((uint)&stack0x00000000 >> 8),-((int)lVar3 != lVar3));
      bVar8 = *(undefined1 **)(puVar5 + unaff_retaddr + -0xd) < puVar7;
      goto code_r0x00513845;
    }
  }
  puVar1 = (uint *)(CONCAT31(uVar6,'{' - *(byte *)(unaff_ESI + 0xc5a212bf)) + -0x2a);
  uVar2 = (uint)(0x7b < *(byte *)(unaff_ESI + 0xc5a212bf));
  bVar8 = 0xcd79bc6 < *puVar1 || CARRY4(*puVar1 + 0xf3286439,uVar2);
  *puVar1 = *puVar1 + 0xf3286439 + uVar2;
code_r0x00513845:
  uVar2 = *(uint *)(puVar5 + -0x79);
  *(uint *)(puVar5 + -0x79) = uVar2 << 5 | (uint)(CONCAT14(bVar8,uVar2) >> 0x1c);
  *unaff_EDI = (char)puVar5;
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


