/*
 * Function: Unwind@0051621a
 * Address: 0051621a
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Instruction at (ram,0x00516234) overlaps instruction at (ram,0x00516231)
    */
/* WARNING: Stack frame is not setup normally: Input value of stackpointer is not used */
/* WARNING: This function may have set the stack pointer */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 * __fastcall Unwind_0051621a(int param_1,int param_2)

{
  int *piVar1;
  uint *puVar2;
  char cVar3;
  uint uVar4;
  byte in_AL;
  char cVar6;
  char *pcVar5;
  int extraout_ECX;
  uint *puVar7;
  byte bVar8;
  int unaff_EBX;
  undefined1 *puVar9;
  int unaff_EBP;
  undefined4 *unaff_ESI;
  char *unaff_EDI;
  undefined2 in_CS;
  undefined2 in_SS;
  byte in_CF;
  bool bVar10;
  undefined2 in_FPUControlWord;
  undefined2 in_FPUStatusWord;
  undefined2 in_FPUTagWord;
  undefined2 in_FPULastInstructionOpcode;
  undefined4 in_FPUDataPointer;
  undefined4 in_FPUInstructionPointer;
  unkbyte10 extraout_ST0;
  unkbyte10 extraout_ST1;
  unkbyte10 in_ST2;
  unkbyte10 in_ST3;
  unkbyte10 in_ST4;
  unkbyte10 in_ST5;
  unkbyte10 in_ST6;
  unkbyte10 in_ST7;
  undefined8 uVar11;
  
  while( true ) {
    bVar8 = ((char)unaff_EBX - *(char *)(param_1 + -0x49)) -
            (0xbf < in_AL || CARRY1(in_AL + 0x40,in_CF));
    _DAT_56b7aa01 = _DAT_56b7aa01 - (int)unaff_EDI;
    piVar1 = (int *)(CONCAT31((int3)((uint)unaff_EBX >> 8),bVar8) + -0x5a);
    *piVar1 = *piVar1 << 1;
    unaff_EBX = CONCAT22((short)((uint)unaff_EBX >> 0x10),
                         CONCAT11((byte)((uint)unaff_EBX >> 8) | unaff_EDI[-0x3985275b],bVar8));
    in_AL = (byte)_DAT_5a388d95 & 0x7d;
    bVar10 = (int)unaff_ESI < 0;
    unaff_ESI = (undefined4 *)((int)unaff_ESI << 1);
    *(undefined2 *)(unaff_EBP + 0x7cb5ee24) = in_CS;
    if (bVar10) break;
    in_CF = *(byte *)(param_2 + 10) < bVar8;
    unaff_EDI = (char *)0xc67ad8a5;
  }
  puVar9 = &DAT_325d583b;
  _DAT_325d583b = 0x51625b;
  _DAT_325d583f = in_CS;
  DAT_aa51a6e6 = in_AL;
  uVar11 = func_0xb30410a1();
  puVar7 = (uint *)((ulonglong)uVar11 >> 0x20);
  pcVar5 = (char *)uVar11;
  *(undefined2 *)(unaff_EBX + 1) = in_FPUControlWord;
  *(undefined2 *)(unaff_EBX + 5) = in_FPUStatusWord;
  *(undefined2 *)(unaff_EBX + 9) = in_FPUTagWord;
  *(undefined4 *)(unaff_EBX + 0x15) = in_FPUDataPointer;
  *(undefined4 *)(unaff_EBX + 0xd) = in_FPUInstructionPointer;
  *(undefined2 *)(unaff_EBX + 0x13) = in_FPULastInstructionOpcode;
  *(unkbyte10 *)(unaff_EBX + 0x1d) = extraout_ST0;
  *(unkbyte10 *)(unaff_EBX + 0x27) = extraout_ST1;
  *(unkbyte10 *)(unaff_EBX + 0x31) = in_ST2;
  *(unkbyte10 *)(unaff_EBX + 0x3b) = in_ST3;
  *(unkbyte10 *)(unaff_EBX + 0x45) = in_ST4;
  *(unkbyte10 *)(unaff_EBX + 0x4f) = in_ST5;
  *(unkbyte10 *)(unaff_EBX + 0x59) = in_ST6;
  *(unkbyte10 *)(unaff_EBX + 99) = in_ST7;
  *(undefined4 *)(unaff_EBP + -0x51) = *(undefined4 *)(unaff_EBP + -0x51);
  *(char **)(puVar9 + -4) = pcVar5;
  if (extraout_ECX == 0) {
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  }
  puVar2 = (uint *)(unaff_EBP + 0x56);
  bVar10 = (*puVar2 & 1) != 0;
  *puVar2 = *puVar2 >> 1;
  uVar4 = *puVar7;
  cVar6 = (char)((ulonglong)uVar11 >> 8);
  cVar3 = (char)*puVar7 - cVar6;
  *(char *)puVar7 = cVar3 - bVar10;
  if ((SBORROW1((char)uVar4,cVar6) != SBORROW1(cVar3,bVar10)) != (char)*puVar7 < '\0') {
    *(undefined2 *)(puVar9 + -8) = in_SS;
    *pcVar5 = *pcVar5 + 'B';
    *(undefined4 *)(puVar9 + -8) = 0xc2c55ec8;
    do {
    } while ((*(byte *)((int)puVar7 + 0xade5d8f) & 0xf) != 0);
    *(undefined4 *)(unaff_EDI + 4) = *unaff_ESI;
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  }
  *puVar7 = *puVar7 ^ (uint)puVar7;
  *unaff_EDI = *unaff_EDI - (char)extraout_ECX;
  return unaff_ESI;
}


