/*
 * Function: Unwind@00512898
 * Address: 00512898
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void Unwind_00512898(void)

{
  int unaff_EBX;
  int unaff_ESI;
  int *unaff_EDI;
  
  *(uint *)(unaff_ESI + -0x378a0dd3) = *(uint *)(unaff_ESI + -0x378a0dd3) & 0xffffffb2;
  _DAT_6a746135 = _DAT_6a746135 + 0x6a74616c;
  *unaff_EDI = *unaff_EDI + unaff_EBX;
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


