/*
 * Function: Unwind@00512be2
 * Address: 00512be2
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Instruction at (ram,0x00512c0d) overlaps instruction at (ram,0x00512c0c)
    */
/* WARNING: Unable to track spacebase fully for stack */
/* WARNING: Removing unreachable block (ram,0x00512cb0) */
/* WARNING: Removing unreachable block (ram,0x00512d0d) */

ulonglong __fastcall
Unwind_00512be2(uint param_1,int *param_2,int *param_3,undefined4 param_4,undefined4 param_5,
               int *param_6,uint param_7,undefined4 param_8)

{
  uint *puVar1;
  byte *pbVar2;
  undefined4 uVar3;
  longlong lVar4;
  code *pcVar5;
  int iVar6;
  undefined1 uVar7;
  byte bVar8;
  undefined4 in_EAX;
  undefined1 *puVar10;
  undefined1 *puVar11;
  undefined2 uVar13;
  byte bVar14;
  int *unaff_EBX;
  undefined4 *puVar15;
  int unaff_EBP;
  undefined4 *puVar16;
  undefined1 *unaff_ESI;
  undefined4 *unaff_EDI;
  bool bVar17;
  byte in_AF;
  byte bVar18;
  bool in_ZF;
  bool bVar19;
  bool bVar20;
  bool bVar21;
  uint uVar22;
  undefined2 in_FPUControlWord;
  float10 in_ST0;
  float10 in_ST1;
  float10 in_ST2;
  float10 in_ST3;
  float10 in_ST4;
  float10 in_ST5;
  float10 in_ST6;
  float10 in_ST7;
  undefined8 uVar23;
  ulonglong uVar24;
  undefined1 *unaff_retaddr;
  char cVar9;
  uint uVar12;
  
  bVar21 = false;
  bVar18 = 9 < ((byte)in_EAX & 0xf) | in_AF;
  uVar22 = CONCAT31((int3)((uint)in_EAX >> 8),(byte)in_EAX + bVar18 * '\x06') & 0xffffff0f;
  uVar22 = CONCAT22((short)(uVar22 >> 0x10),
                    CONCAT11((char)((uint)in_EAX >> 8) + bVar18,(char)uVar22));
  if (!in_ZF) {
    return CONCAT44((int)param_2 + 1,(int)(short)((short)unaff_EDI + -0xf8c));
  }
  while( true ) {
    DAT_d6429279 = (undefined1)uVar22;
    uVar7 = *(undefined1 *)((int)unaff_EBX + (uVar22 & 0xff));
    uVar12 = CONCAT31((int3)(uVar22 >> 8),uVar7);
    bVar14 = (byte)param_2 & (byte)(uVar22 >> 8);
    param_2 = (int *)CONCAT31((int3)((uint)param_2 >> 8),bVar14);
    bVar20 = (char)bVar14 < '\0';
    bVar19 = bVar14 == 0;
    if (bVar20) {
      uVar13 = (undefined2)(uVar22 >> 0x10);
      puVar11 = (undefined1 *)
                (CONCAT22(uVar13,CONCAT11(bVar20 << 7 | bVar19 << 6 | bVar18 << 4 |
                                          ((POPCOUNT(bVar14) & 1U) == 0) << 2,uVar7)) | 0x200);
      if (bVar20) {
        while( true ) {
          puVar10 = puVar11;
          uVar24 = CONCAT44(param_2,unaff_ESI) / (longlong)*(int *)((int)unaff_EBX + -0x5f8c3cf6);
          lVar4 = CONCAT44(param_2,unaff_ESI) % (longlong)*(int *)((int)unaff_EBX + -0x5f8c3cf6);
          param_2 = (int *)lVar4;
          if (bVar19 || bVar20) break;
          *(int *)(unaff_EBP + 0x34ca79c7) = *(int *)(unaff_EBP + 0x34ca79c7) - (int)unaff_EDI;
          unaff_EDI = (undefined4 *)((int)unaff_EDI + (-1 - *param_2));
          bVar20 = (int)uVar24 < 0;
          bVar19 = (uVar24 & 0x8a96dd47) == 0;
          puVar11 = (undefined1 *)in((short)lVar4);
          unaff_ESI = puVar10;
        }
        in(0xd2);
                    /* WARNING: Bad instruction - Truncating control flow here */
        halt_baddata();
      }
      bVar14 = (byte)param_1 & bVar14;
      puVar1 = (uint *)(CONCAT22((short)(param_1 >> 0x10),CONCAT11(0x8a,bVar14)) + -0x3e);
      *puVar1 = *puVar1 >> 1 | (uint)((*puVar1 & 1) != 0) << 0x1f;
      uVar3 = in((short)param_2);
      *unaff_EDI = uVar3;
      out(0x4a,uVar7);
      return CONCAT44(param_2,CONCAT22(uVar13,CONCAT11(((char)bVar14 < '\0') << 7 |
                                                       (bVar14 == 0) << 6 | bVar18 << 4 |
                                                       ((POPCOUNT(bVar14) & 1U) == 0) << 2,uVar7)))
             | 0x200;
    }
    bVar20 = CARRY4((uint)unaff_ESI,*(uint *)(param_1 + 0x3b3098d2));
    unaff_ESI = unaff_ESI + *(uint *)(param_1 + 0x3b3098d2);
    if (!SBORROW4((int)unaff_EDI,1)) break;
    unaff_EDI = (undefined4 *)*(undefined6 *)(param_1 + 0x7589021);
    unaff_EBX = (int *)0x2695e442;
    in_ST0 = in_ST0 * (float10)*(float *)((int)unaff_EDI + 0x2695e463);
    uVar22 = param_1;
    param_1 = (int)param_2 + bVar20 + uVar12;
  }
  bVar20 = false;
  *(byte *)(unaff_EBP + 0x1c8cb6e2) = *(byte *)(unaff_EBP + 0x1c8cb6e2) | (byte)param_1;
  do {
    puVar11 = (undefined1 *)(uVar12 + 1);
    bVar19 = puVar11 == (undefined1 *)0x0;
    if (puVar11 == (undefined1 *)0x1) {
      uVar23 = func_0x0b74aefc();
      *(undefined2 *)((int)((ulonglong)uVar23 >> 0x20) + -0x25) = in_FPUControlWord;
      out(0x5d,CONCAT22((short)((ulonglong)uVar23 >> 0x10),
                        (ushort)(byte)((char)uVar23 + (char)((ulonglong)uVar23 >> 8) * -0x73)));
      pcVar5 = (code *)swi(3);
      uVar24 = (*pcVar5)();
      return uVar24;
    }
    while( true ) {
      bVar17 = (POPCOUNT((uint)puVar11 & 0xff) & 1U) == 0;
      uVar22 = param_1 >> 0x10;
      uVar7 = (undefined1)param_1;
      bVar14 = ((int)puVar11 < 0) << 7 | bVar19 << 6 | bVar18 << 4 | bVar17 << 2 | 2 | bVar20;
      if (!bVar20) break;
      bVar8 = (byte)unaff_ESI;
      if (!bVar17) {
        puVar11 = (undefined1 *)0x49bae597;
        out((short)param_2,bVar8);
        param_2 = (int *)((int)unaff_ESI >> 0x1f);
        *(longlong *)(param_2 + -0x1b) = (longlong)ROUND(in_ST0);
LAB_00512d7c:
        do {
          DAT_c3527061 = DAT_c3527061 ^ (byte)((uint)unaff_EBX >> 8);
          uVar3 = *(undefined4 *)(puVar11 + -0x52);
        } while ((POPCOUNT(DAT_c3527061) & 1U) == 0);
        *(uint *)((int)param_2 + -0x35) = *(uint *)((int)param_2 + -0x35) ^ (uint)&stack0x00000000;
        puVar1 = (uint *)((int)*(undefined6 *)((int)unaff_EBX + -0x52) + 0x35);
        *puVar1 = *puVar1 >> ((char)uVar3 * -0x6b & 0x1fU);
        pcVar5 = (code *)swi(1);
        uVar24 = (*pcVar5)();
        return uVar24;
      }
      bVar18 = 9 < (bVar8 & 0xf) | bVar18;
      bVar8 = bVar8 + bVar18 * -6;
      cVar9 = bVar8 + (0x9f < bVar8 | bVar20 | bVar18 * (bVar8 < 6)) * -0x60;
      param_1 = CONCAT31((int3)((uint)unaff_ESI >> 8),cVar9);
      bVar20 = false;
      puVar11 = (undefined1 *)(CONCAT22((short)uVar22,CONCAT11(bVar14,uVar7)) & (uint)param_2);
      bVar19 = puVar11 == (undefined1 *)0x0;
      if (bVar19) goto LAB_00512d7c;
      out((short)param_2,cVar9);
      unaff_EBX = param_3;
      unaff_ESI = puVar11;
    }
    iVar6 = param_3[1];
    puVar16 = (undefined4 *)(*param_3 + -1);
    unaff_ESI = unaff_retaddr + (uint)bVar21 * -2 + 1;
    param_1 = CONCAT31((int3)((uint)param_8 >> 8),*unaff_retaddr);
    puVar15 = (undefined4 *)(iVar6 + -4);
    *(undefined4 **)(iVar6 + -4) = puVar16;
    cVar9 = '\a';
    do {
      puVar16 = puVar16 + -1;
      puVar15 = puVar15 + -1;
      *puVar15 = *puVar16;
      cVar9 = cVar9 + -1;
    } while ('\0' < cVar9);
    *(int *)(iVar6 + -0x24) = iVar6 + -4;
    *(undefined4 *)(iVar6 + -0xa0d) = 0xffffffd4;
    uVar22 = *(uint *)(iVar6 + -0xa0d);
    bVar21 = (uVar22 & 0x400) != 0;
    bVar18 = (uVar22 & 0x10) != 0;
    bVar14 = (byte)param_7 & 0x1f;
    cVar9 = (char)((uint)param_5 >> 8);
    bVar8 = (byte)param_5;
    unaff_EBX = (int *)CONCAT22((short)((uint)param_5 >> 0x10),CONCAT11(cVar9 << bVar14,bVar8));
    bVar20 = (param_7 & 0x1f) != 0;
    bVar19 = !bVar20 && (uVar22 & 1) != 0 || bVar20 && (char)(cVar9 << bVar14 - 1) < '\0';
    pbVar2 = (byte *)(unaff_EBX + 0x19);
    bVar20 = *pbVar2 < bVar8 || (byte)(*pbVar2 - bVar8) < bVar19;
    *pbVar2 = (*pbVar2 - bVar8) - bVar19;
    uVar12 = param_7;
    param_2 = param_6;
    in_ST0 = in_ST1;
    in_ST1 = in_ST2;
    in_ST2 = in_ST3;
    in_ST3 = in_ST4;
    in_ST4 = in_ST5;
    in_ST5 = in_ST6;
    in_ST6 = in_ST7;
  } while( true );
}


