/*
 * Function: Unwind@00510ab0
 * Address: 00510ab0
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */

void Unwind_00510ab0(void)

{
  int in_EAX;
  int unaff_EBX;
  int unaff_EBP;
  byte *unaff_EDI;
  
  *(char *)(unaff_EBX + -0x16ac5e5a) = *(char *)(unaff_EBX + -0x16ac5e5a) >> 7;
  *unaff_EDI = *unaff_EDI & (byte)((uint)(unaff_EBP + 1) >> 8);
  *(char *)(in_EAX + -0x3b) = *(char *)(in_EAX + -0x3b) - (char)((uint)unaff_EBX >> 8);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


