/*
 * Function: Unwind@00516663
 * Address: 00516663
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Instruction at (ram,0x00516667) overlaps instruction at (ram,0x00516666)
    */
/* WARNING: Control flow encountered bad instruction data */

void __fastcall Unwind_00516663(byte *param_1)

{
  int *piVar1;
  uint *puVar2;
  uint uVar3;
  int in_EAX;
  undefined4 unaff_EBX;
  int iVar6;
  undefined4 *unaff_ESI;
  byte in_CF;
  char in_AF;
  unkbyte10 in_ST2;
  uint uVar4;
  uint uVar5;
  
  iVar6 = CONCAT22((short)((uint)unaff_EBX >> 0x10),
                   CONCAT11(*(undefined1 *)(in_EAX + -0x74),(char)unaff_EBX));
  puVar2 = (uint *)(iVar6 + 0x52ae9195);
  *puVar2 = *puVar2 + 1;
  uVar3 = *puVar2;
  uVar4 = *puVar2;
  uVar5 = *puVar2;
  *param_1 = *param_1 ^ (byte)((uint)param_1 >> 8);
  out(*unaff_ESI,0x7923);
  piVar1 = (int *)(CONCAT22((short)((uint)in_EAX >> 0x10),
                            CONCAT11(((int)uVar3 < 0) << 7 | (uVar4 == 0) << 6 | in_AF << 4 |
                                     ((POPCOUNT(uVar5 & 0xff) & 1U) == 0) << 2 | 2U | in_CF,
                                     (char)in_EAX)) + 0x43);
  *piVar1 = *piVar1 + iVar6;
  in(0x7923);
  ffree(in_ST2);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


