/*
 * Function: Unwind@0051554e
 * Address: 0051554e
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"

// Decompilation failed for Unwind@0051554e
void Unwind@0051554e(void) {
    // Implementation unavailable
}
