/*
 * Function: Unwind@005140c0
 * Address: 005140c0
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Instruction at (ram,0x005140db) overlaps instruction at (ram,0x005140da)
    */
/* WARNING: Stack frame is not setup normally: Input value of stackpointer is not used */

void __fastcall Unwind_005140c0(int param_1,short param_2)

{
  uint uVar1;
  undefined1 uVar2;
  undefined2 uVar3;
  uint uVar4;
  int iVar5;
  undefined1 *puVar6;
  undefined1 *puVar7;
  undefined4 *puVar8;
  undefined4 *unaff_ESI;
  undefined1 *unaff_EDI;
  byte in_CF;
  
  while( true ) {
    puVar6 = (undefined1 *)0x957b7c94;
    uVar4 = in(param_2);
    param_2 = param_2 + -1;
    if (param_1 != 0) {
      uVar1 = (uint)in_CF;
      in_CF = uVar4 < 0x248b162f || uVar4 + 0xdb74e9d1 < uVar1;
      iVar5 = (uVar4 + 0xdb74e9d1) - uVar1;
      uVar2 = (undefined1)iVar5;
      puVar7 = &DAT_957b7c90;
      uVar3 = CONCAT11(0xa6,uVar2);
      puVar8 = unaff_ESI;
      if (iVar5 == 0) goto code_r0x005140d8;
      *unaff_EDI = uVar2;
      puVar6 = (undefined1 *)0x957b7c98;
      unaff_EDI = (undefined1 *)0xf14d5afc;
      uVar4 = 0xa05d5950;
      param_1 = iRam957b7c94;
    }
    uVar3 = (undefined2)uVar4;
    puVar8 = (undefined4 *)((int)unaff_ESI + -1);
    in_CF = in_CF == 0;
    if (puVar8 == (undefined4 *)0x0 || (int)unaff_ESI < 1) break;
    unaff_EDI = (undefined1 *)0x85aa36de;
    unaff_ESI = puVar8;
  }
  puVar7 = puVar6 + -4;
  *(undefined1 **)(puVar6 + -4) = unaff_EDI;
code_r0x005140d8:
  out(*puVar8,uVar3);
  out(0x29,(char)param_2);
  *(int *)(puVar7 + -4) = param_1;
  do {
                    /* WARNING: Do nothing block with infinite loop */
  } while( true );
}


