/*
 * Function: Unwind@00517be9
 * Address: 00517be9
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Instruction at (ram,0x00517c43) overlaps instruction at (ram,0x00517c42)
    */
/* WARNING: Stack frame is not setup normally: Input value of stackpointer is not used */

void __fastcall Unwind_00517be9(undefined4 param_1,undefined2 param_2)

{
  undefined1 *puVar1;
  undefined4 uVar2;
  undefined1 *puVar3;
  int in_EAX;
  uint *puVar4;
  int unaff_EBX;
  int iVar5;
  int *unaff_EBP;
  int iVar6;
  undefined1 *unaff_ESI;
  undefined1 *unaff_EDI;
  undefined2 in_CS;
  undefined2 in_SS;
  byte in_CF;
  undefined2 in_FPUControlWord;
  undefined2 in_FPUStatusWord;
  undefined2 in_FPUTagWord;
  undefined2 in_FPULastInstructionOpcode;
  undefined4 in_FPUDataPointer;
  undefined4 in_FPUInstructionPointer;
  
  out(0xd2,(char)in_EAX);
  *(char *)(unaff_EBP + 0xd) = (char)param_2;
  iVar6 = *unaff_EBP;
  puVar1 = unaff_ESI + 1;
  *unaff_EDI = *unaff_ESI;
  uVar2 = in(param_2);
  *(undefined4 *)(unaff_EDI + 1) = uVar2;
  puVar4 = (uint *)((in_EAX + -0x7c228393 + (uint)in_CF | 0x10) + 0x7ae9d67b);
  *(undefined1 **)((int)unaff_EBP + 1) = puVar1;
  *puVar4 = *puVar4 ^ (uint)puVar1;
  puVar3 = *(undefined1 **)((int)unaff_EBP + 1);
  iVar5 = CONCAT31((int3)((uint)(puVar1 + unaff_EBX + (((uint)puVar4 & 0x100) != 0)) >> 8),
                   puVar3[0x33f143ac]);
  *(undefined2 *)(iVar5 + 0x5b5463ef) = in_FPUControlWord;
  *(undefined2 *)(iVar5 + 0x5b5463f3) = in_FPUStatusWord;
  *(undefined2 *)(iVar5 + 0x5b5463f7) = in_FPUTagWord;
  *(undefined4 *)(iVar5 + 0x5b546403) = in_FPUDataPointer;
  *(undefined4 *)(iVar5 + 0x5b5463fb) = in_FPUInstructionPointer;
  *(undefined2 *)(iVar5 + 0x5b546401) = in_FPULastInstructionOpcode;
  LOCK();
  *(char *)(iVar6 + -0x431fbbb0) = (char)puVar4;
  UNLOCK();
  *(undefined2 *)((int)unaff_EBP + 1) = in_CS;
  *(undefined1 *)(iVar5 + 0x1b7cacfa) =
       (char)(CONCAT11(puVar1 < puVar3,*(undefined1 *)(iVar5 + 0x1b7cacfa)) >> 1);
  *(undefined2 *)(*(int *)((int)unaff_EBP + 1) + -4) = in_SS;
  do {
                    /* WARNING: Do nothing block with infinite loop */
  } while( true );
}


