/*
 * Function: Unwind@00515d50
 * Address: 00515d50
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Instruction at (ram,0x00515d51) overlaps instruction at (ram,0x00515d50)
    */
/* WARNING: Unable to track spacebase fully for stack */
/* WARNING: Removing unreachable block (ram,0x00515c53) */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __fastcall Unwind_00515d50(int param_1,short param_2)

{
  byte bVar1;
  byte bVar2;
  uint uVar3;
  uint in_EAX;
  int iVar4;
  int iVar5;
  uint *unaff_EBX;
  int unaff_EBP;
  uint unaff_ESI;
  byte *unaff_EDI;
  byte *pbVar6;
  undefined2 in_SS;
  byte in_AF;
  char in_ZF;
  float10 in_ST0;
  
  iVar4 = param_1 + -1;
  pbVar6 = unaff_EDI;
  _DAT_7609ed49 = in_EAX;
  if (iVar4 != 0 && in_ZF != '\0') goto LAB_00515d44;
  while( true ) {
    bVar2 = (byte)in_EAX ^ 0x54;
    unaff_EDI = (byte *)(in_EAX ^ 0x54);
    param_2 = param_2 + 1;
    iVar5 = iVar4 + -1;
    if (iVar5 == 0) {
      iVar4 = *(int *)unaff_EDI;
      out(0x58,(char)unaff_EDI);
      bVar2 = in(param_2);
      *pbVar6 = bVar2;
      *(undefined4 *)(pbVar6 + 1) =
           *(undefined4 *)CONCAT22((short)(unaff_ESI >> 0x10),(short)unaff_EDI);
      *(char *)(unaff_EBP + -0x7c) = *(char *)(unaff_EBP + -0x7c) + (char)unaff_EBX + (iVar4 != 0);
                    /* WARNING: Bad instruction - Truncating control flow here */
      halt_baddata();
    }
    iVar4 = CONCAT22((short)((uint)iVar5 >> 0x10),CONCAT11(0x95,(byte)iVar5));
    *unaff_EBX = *unaff_EBX ^ (uint)unaff_EBX;
    if (-1 < (int)*unaff_EBX) break;
    *(int *)pbVar6 = *(int *)pbVar6 << 1;
    *(double *)(unaff_EDI + 0x62) = (double)in_ST0;
    pbVar6[0x71c55f10] = pbVar6[0x71c55f10] + 1;
LAB_00515d44:
    in_ST0 = (float10)*(short *)((int)unaff_EBX + -0x5d);
    iVar4 = iVar4 + -1;
    in(param_2);
    *(uint *)(unaff_ESI - 0x1f) = *(uint *)(unaff_ESI - 0x1f) | unaff_ESI;
    in_EAX = in(param_2);
    pbVar6 = unaff_EDI;
  }
  bVar1 = 9 < (bVar2 & 0xf) | in_AF;
  bVar2 = bVar2 + bVar1 * -6;
  *pbVar6 = *pbVar6 & (byte)iVar5;
  uVar3 = CONCAT31((int3)(in_EAX >> 8),bVar2 + (0x9f < bVar2 | bVar1 * (bVar2 < 6)) * -0x60) ^
          0x162a6309;
  if (uVar3 != 0) {
    uVar3 = uVar3 - 1;
    *pbVar6 = (byte)uVar3;
    if ((POPCOUNT(uVar3 & 0xff) & 1U) == 0) {
                    /* WARNING: Bad instruction - Truncating control flow here */
      halt_baddata();
    }
    bVar2 = *(byte *)((int)unaff_EBX + (uVar3 & 0xff));
    *(byte *)(unaff_ESI + 0x5301ddb7) = *(byte *)(unaff_ESI + 0x5301ddb7) & bVar2;
    out(1,bVar2);
    do {
                    /* WARNING: Do nothing block with infinite loop */
    } while( true );
  }
  if (iVar4 != 1 && ((uint)unaff_EBX & unaff_ESI - 1) == 0) {
    *(undefined2 *)(unaff_EBX + -1) = in_SS;
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  }
  out(*(undefined1 *)(unaff_ESI - 1),param_2);
  *(int *)(iVar4 + 0x79) = unaff_EBP;
  return;
}


