/*
 * Function: Unwind@00513a98
 * Address: 00513a98
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */

void __fastcall Unwind_00513a98(byte param_1,undefined4 param_2)

{
  undefined4 in_EAX;
  uint uVar1;
  byte bVar2;
  int iVar3;
  
  iVar3 = CONCAT22((short)((uint)param_2 >> 0x10),
                   CONCAT11((byte)((uint)param_2 >> 8) ^ param_1,(byte)param_2));
  uVar1 = CONCAT22((short)((uint)in_EAX >> 0x10),
                   CONCAT11((byte)((uint)in_EAX >> 8) | (byte)in_EAX,(byte)in_EAX)) ^ 0xfe420199;
  bVar2 = (byte)param_2 & *(byte *)(iVar3 + -0x61dfc95e);
  if ((POPCOUNT(bVar2) & 1U) != 0) {
    do {
                    /* WARNING: Do nothing block with infinite loop */
    } while( true );
  }
  out((short)CONCAT31((int3)((uint)iVar3 >> 8),bVar2),
      CONCAT31((int3)(uVar1 >> 8),(char)uVar1 + -0xc));
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


