/*
 * Function: Unwind@0050fe22
 * Address: 0050fe22
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Instruction at (ram,0x0050fe36) overlaps instruction at (ram,0x0050fe31)
    */
/* WARNING: Removing unreachable block (ram,0x0050fe3c) */

float10 __fastcall Unwind_0050fe22(undefined1 *param_1,uint param_2)

{
  uint *puVar1;
  int *piVar2;
  byte *pbVar3;
  char *pcVar4;
  uint uVar5;
  double dVar6;
  byte bVar7;
  byte bVar8;
  bool bVar9;
  code *pcVar10;
  int in_EAX;
  byte bVar11;
  undefined1 *extraout_ECX;
  int iVar12;
  int unaff_EBX;
  int unaff_EBP;
  int unaff_ESI;
  
  if (param_1 == (undefined1 *)0x0) {
    in_EAX = (int)(short)in_EAX;
  }
  *(uint *)(param_2 + 0x65) = *(uint *)(param_2 + 0x65) ^ param_2;
  bVar7 = *(byte *)(param_2 + 0x812bc94f);
  *param_1 = (char)((uint)param_1 >> 8);
  swi(4);
  iVar12 = CONCAT22((short)(param_2 >> 0x10),
                    CONCAT11((byte)(param_2 >> 8) | *(byte *)(unaff_EBX + -0x48),(char)param_2));
  dVar6 = *(double *)(unaff_EBP * 2 + -0x1282d39a);
  pcVar4 = (char *)((CONCAT31((int3)((uint)in_EAX >> 8),(byte)in_EAX & bVar7) | 0x822e770a) +
                    0x3a96258e + unaff_ESI);
  *pcVar4 = *pcVar4 >> 1;
  puVar1 = (uint *)(iVar12 + 0x34);
  uVar5 = *puVar1;
  *puVar1 = *puVar1 + 0x24;
  pbVar3 = (byte *)(unaff_EBX * 4 + 0x7652140c);
  bVar7 = *pbVar3;
  bVar11 = (byte)param_1;
  bVar8 = *pbVar3 + bVar11;
  bVar9 = CARRY1(bVar8,uVar5 < 0xffffffdc);
  *pbVar3 = bVar8 + (uVar5 < 0xffffffdc);
  if ((CARRY1(bVar7,bVar11) || bVar9) || *pbVar3 == 0) {
    piVar2 = (int *)(iVar12 + -0x6533024f);
    *piVar2 = *piVar2 + -0x5b866ee0 + (uint)(CARRY1(bVar7,bVar11) || bVar9);
    return (float10)dVar6;
  }
  pcVar10 = (code *)swi(4);
  if (SCARRY4(unaff_EBX,1)) {
    (*pcVar10)();
    param_1 = extraout_ECX;
  }
  *(byte *)(unaff_EBX + -0x715d9116) = *(byte *)(unaff_EBX + -0x715d9116) >> ((byte)param_1 & 0x1f);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


