/*
 * Function: Unwind@00510a90
 * Address: 00510a90
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */

void Unwind_00510a90(void)

{
  undefined4 uVar1;
  undefined4 in_EAX;
  int unaff_EDI;
  bool in_ZF;
  char in_SF;
  char in_OF;
  
  if (in_ZF || in_OF != in_SF) {
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  }
  uVar1 = in((short)((int)in_EAX >> 0x1f));
  *(undefined4 *)(unaff_EDI + *(int *)(unaff_EDI + 0x4a)) = uVar1;
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


