/*
 * Function: Unwind@00511730
 * Address: 00511730
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */

void Unwind_00511730(void)

{
  uint uVar1;
  char cVar2;
  undefined4 **ppuVar3;
  undefined4 **unaff_EBP;
  uint *unaff_EDI;
  byte in_CF;
  undefined4 *apuStack_8 [2];
  
  do {
    uVar1 = (uint)in_CF;
    in_CF = CARRY4(*unaff_EDI,(uint)unaff_EDI) || CARRY4(*unaff_EDI + (int)unaff_EDI,uVar1);
    *unaff_EDI = *unaff_EDI + (int)unaff_EDI + uVar1;
    uVar1 = *unaff_EDI;
    ppuVar3 = apuStack_8 + 1;
    apuStack_8[1] = unaff_EBP;
    cVar2 = '\t';
    do {
      unaff_EBP = unaff_EBP + -1;
      ppuVar3 = ppuVar3 + -1;
      *ppuVar3 = *unaff_EBP;
      cVar2 = cVar2 + -1;
    } while ('\0' < cVar2);
    unaff_EBP = apuStack_8 + 1;
  } while ((int)uVar1 < 0);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


