/*
 * Function: Unwind@00516680
 * Address: 00516680
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unable to track spacebase fully for stack */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

int __fastcall Unwind_00516680(int param_1)

{
  ushort *puVar1;
  byte *pbVar2;
  int *piVar3;
  undefined4 uVar4;
  char cVar5;
  code *pcVar6;
  int iVar7;
  uint *in_EAX;
  uint uVar8;
  uint *puVar9;
  int iVar10;
  char *pcVar11;
  byte *extraout_ECX;
  byte *extraout_ECX_00;
  byte *pbVar12;
  undefined2 uVar13;
  byte bVar15;
  int iVar14;
  char *unaff_EBX;
  uint uVar16;
  undefined1 *puVar17;
  undefined1 *puVar18;
  undefined1 *puVar19;
  undefined1 *puVar20;
  undefined4 *unaff_EBP;
  undefined4 *unaff_ESI;
  undefined4 *puVar21;
  undefined4 *unaff_EDI;
  undefined2 in_CS;
  undefined2 in_SS;
  ushort uVar22;
  byte in_CF;
  byte bVar23;
  bool bVar24;
  bool in_PF;
  char in_AF;
  undefined2 in_FPUStatusWord;
  undefined8 uVar25;
  char in_stack_a7a8a1da;
  ushort auStack_b1a1 [2];
  undefined4 uStack_c;
  undefined1 auStack_4 [4];
  
  if (in_PF) {
    *unaff_EDI = *unaff_ESI;
    uVar16 = (uint)auStack_4 | *(uint *)((int)unaff_EDI + 0x12d2d689);
    uVar8 = ((uint)in_EAX ^ 0x89634616) & 0xffffff8d;
    bVar23 = (char)uVar8 - 0x2f;
    _DAT_f919c526 =
         CONCAT31((int3)(CONCAT22((short)(uVar8 >> 0x10),CONCAT11(bVar23 / 0x10,bVar23)) >> 8),
                  bVar23 % 0x10);
    puVar17 = (undefined1 *)(uVar16 - 4);
    *(undefined4 *)(uVar16 - 4) = 0xe38069fe;
    *unaff_EBX = *unaff_EBX + '\x01';
    in(0xe0);
    pcVar6 = (code *)swi(0xd5);
    iVar7 = (*pcVar6)();
    *(undefined4 **)(puVar17 + -4) = unaff_ESI + 2;
    return iVar7 + 0x509fce9a;
  }
  puVar1 = (ushort *)((int)unaff_EBP + 6);
  *puVar1 = *puVar1 + (ushort)in_CF * (((ushort)in_EAX & 3) - (*puVar1 & 3));
  uVar4 = *(undefined4 *)(param_1 + -0x672462c0);
  puVar21 = (undefined4 *)&stack0xfffffff8;
  cVar5 = '\n';
  do {
    unaff_EBP = unaff_EBP + -1;
    puVar21 = puVar21 + -1;
    *puVar21 = *unaff_EBP;
    cVar5 = cVar5 + -1;
  } while ('\0' < cVar5);
  auStack_b1a1[0] =
       ((short)unaff_EDI - (short)uVar4) - (ushort)in_CF |
       (ushort)*(undefined4 *)(unaff_EBX + -0x1e);
  uVar22 = auStack_b1a1[0];
  bVar23 = 0;
  *in_EAX = *in_EAX ^ (uint)&stack0xfffffff8;
  auStack_b1a1[0] = 0x66a5;
  auStack_b1a1[1] = 0x51;
  uVar8 = func_0x9ab2179e();
  iVar7 = *(int *)(extraout_ECX + 0x62448715);
  puVar19 = &stack0xffff4e63 + -(uint)bVar23 + (-0xb19d - iVar7) + 0xb19d;
  puVar9 = (uint *)(uVar8 & 0x8bfd3566);
  bVar24 = (*puVar9 & 1) != 0;
  *puVar9 = *puVar9 >> 1 | (uint)bVar24 << 0x1f;
  iVar14 = (int)*(undefined6 *)(&stack0x00000054 + (int)in_EAX * 2);
  iVar10 = (int)((int)unaff_ESI + 1U) + (uint)bVar24 + CONCAT31((int3)((uint)puVar9 >> 8),0xf2);
  bVar24 = in_stack_a7a8a1da < '\0';
  if (!bVar24) {
    *(undefined2 *)(iVar10 + 0x33f38ce8) = in_FPUStatusWord;
    pbVar12 = extraout_ECX;
    puVar21 = (undefined4 *)((int)unaff_ESI + 1U);
    if ((bVar24 != (char)(in_stack_a7a8a1da << 1 | bVar24) < '\0') != iVar10 < 0) {
      unaff_ESI[0x1f] = unaff_ESI[0x1f] + -0x731b7a66;
      *(char *)((int)in_EAX + 0x6f4d4ec6) = *(char *)((int)in_EAX + 0x6f4d4ec6) + '\x01';
      *(ushort *)((int)auStack_b1a1 + -(uint)bVar23 + (-0xb19d - iVar7) + 0xb19d) = uVar22;
                    /* WARNING: Bad instruction - Truncating control flow here */
      halt_baddata();
    }
    while( true ) {
      bVar15 = (byte)((uint)iVar14 >> 8);
      bVar23 = in_AF * -6 + 0x42;
      pbVar2 = (byte *)((CONCAT31(0xa9365b,bVar23 + (0x9f < bVar23 |
                                                    (bVar15 < (byte)pbVar12 ||
                                                    (byte)(bVar15 - (byte)pbVar12) < bVar24) |
                                                    in_AF * (bVar23 < 6)) * -0x60) & 0x8912e6ee) -
                       0x37);
      *pbVar2 = *pbVar2 | (byte)unaff_EBX;
      bVar23 = (byte)((uint)unaff_EBX >> 8) | *pbVar12;
      unaff_EBX = (char *)CONCAT22((short)((uint)unaff_EBX >> 0x10),CONCAT11(bVar23,(byte)unaff_EBX)
                                  );
      bVar24 = bVar23 == 0;
      *(undefined2 *)(puVar19 + -4) = in_CS;
      in_CS = 45000;
      puVar20 = puVar19 + -8;
      *(undefined4 *)(puVar19 + -8) = 0x516750;
      uVar25 = func_0xa356fd09();
      pbVar12 = (byte *)((ulonglong)uVar25 >> 0x20);
      bVar23 = (byte)((ulonglong)uVar25 >> 0x28);
      if (bVar24) break;
      *pbVar12 = *pbVar12 | bVar23;
      puVar18 = puVar20 + -4;
      *(undefined4 *)(puVar20 + -4) = 0x516716;
      _DAT_e6f26b02 = (int)uVar25;
      uVar25 = func_0x323ebac9();
      uVar13 = (undefined2)((ulonglong)uVar25 >> 0x20);
      out(*puVar21,uVar13);
      *(undefined2 *)(puVar18 + -4) = in_SS;
      uVar8 = in(uVar13);
      *in_EAX = uVar8;
      iVar14 = (int)((ulonglong)uVar25 >> 0x20) + 1;
      pcVar11 = (char *)((int)uVar25 - 1U ^ 8);
      *pcVar11 = *pcVar11 + (char)pcVar11;
      out((short)iVar14,_DAT_903738e0);
      in(0x4b);
      bVar24 = puVar21 + 1 < (undefined4 *)in_EAX[0x19a84e25];
      puVar19 = puVar18 + -3;
      pbVar12 = extraout_ECX_00;
      puVar21 = puVar21 + 1;
      in_EAX = in_EAX + 1;
    }
    *(undefined1 **)(unaff_EBX + -0x31) = &stack0xfffffff8 + *(int *)(unaff_EBX + -0x31);
    iVar7 = CONCAT31((int3)((ulonglong)uVar25 >> 8),(char)uVar25 + -0x23);
    *(undefined1 **)(puVar20 + -3) = &stack0xfffffff8;
    _DAT_de5bd56d = (undefined2)iVar7;
    uVar8 = *(uint *)(pbVar12 + (int)&stack0xfffffff8);
    bVar15 = **(byte **)(puVar20 + -3);
    piVar3 = (int *)(iVar7 + (uint)CARRY4((uint)(puVar20 + 1),
                                          *(uint *)(pbVar12 + (int)&stack0xfffffff8)) + 0x21f44153);
    *piVar3 = *piVar3 << 1;
    in(CONCAT11(bVar23 ^ bVar15,(char)((ulonglong)uVar25 >> 0x20)));
    *(undefined4 *)(puVar20 + uVar8 + 1) = *(undefined4 *)(puVar20 + uVar8 + 1);
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  }
  pcVar6 = (code *)swi(1);
  iVar7 = (*pcVar6)();
  return iVar7;
}


