/*
 * Function: Unwind@005166b1
 * Address: 005166b1
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"

// Decompilation failed for Unwind@005166b1
void Unwind@005166b1(void) {
    // Implementation unavailable
}
