/*
 * Function: Unwind@00517340
 * Address: 00517340
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Instruction at (ram,0x00517352) overlaps instruction at (ram,0x00517350)
    */
/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __fastcall Unwind_00517340(int param_1,undefined4 param_2,undefined4 param_3,ushort param_4)

{
  byte *pbVar1;
  undefined4 uVar2;
  ulonglong uVar3;
  uint5 uVar4;
  char cVar5;
  undefined1 *in_EAX;
  byte bVar6;
  int extraout_ECX;
  int extraout_ECX_00;
  undefined2 extraout_DX;
  undefined4 extraout_EDX;
  undefined4 unaff_EBX;
  uint *puVar7;
  uint unaff_ESI;
  undefined4 *puVar8;
  undefined1 *unaff_EDI;
  undefined4 *puVar9;
  undefined4 *puVar10;
  ushort in_CS;
  ushort uVar11;
  bool bVar12;
  bool bVar13;
  undefined2 in_FPUControlWord;
  
  puVar8 = (undefined4 *)(in_EAX + 1);
  *unaff_EDI = *in_EAX;
  puVar7 = (uint *)CONCAT31((int3)((uint)unaff_EBX >> 8),0x2d);
  _DAT_17553176 = _DAT_17553176 ^ (uint)puVar8;
  bVar6 = (byte)param_1 & 0x1f;
  uVar4 = CONCAT14(unaff_ESI < 0xedc7b4c1,*(undefined4 *)((int)puVar7 + -0x66));
  uVar3 = (ulonglong)uVar4 << bVar6 | (ulonglong)(uVar4 >> 0x21 - bVar6);
  *(undefined4 *)((int)puVar7 + -0x66) = (int)uVar3;
  cVar5 = in(0x7c);
  puVar9 = (undefined4 *)(unaff_EDI + 2);
  unaff_EDI[1] = cVar5 + -0x30 + ((uVar3 & 0x100000000) != 0);
  while( true ) {
    uVar11 = in_CS;
    bVar13 = (param_4 & 0x400) != 0;
    bVar6 = (byte)param_1;
    bVar12 = bVar6 < *(byte *)(param_1 + 0x552391a5);
    cVar5 = bVar6 - *(byte *)(param_1 + 0x552391a5);
    if (bVar12 || cVar5 == '\0') {
      *puVar7 = *puVar7 | CONCAT31((int3)((uint)param_1 >> 8),cVar5);
      *(undefined1 *)puVar9 = *(undefined1 *)puVar8;
      _DAT_e1e9905b = in_FPUControlWord;
                    /* WARNING: Bad instruction - Truncating control flow here */
      halt_baddata();
    }
    if (!bVar12) break;
    puVar10 = puVar9 + (uint)bVar13 * -2 + 1;
    puVar8 = puVar8 + (uint)bVar13 * -2 + 1;
    pbVar1 = (byte *)((int)puVar8 + 0x3bbf6e8f);
    *pbVar1 = *pbVar1 ^ (byte)((uint)(puVar9[-0xf] * -0x554f828) >> 8);
    bVar6 = *pbVar1;
    puVar9 = puVar10 + (uint)bVar13 * -2 + 1;
    uVar2 = in((short)param_2);
    *puVar10 = uVar2;
    if (bVar6 != 0) {
      func_0xce005445();
      out(*puVar8,extraout_DX);
      *(char *)(puVar9 + extraout_ECX_00) =
           *(char *)(puVar9 + extraout_ECX_00) << ((byte)extraout_ECX_00 & 0x1f);
      return;
    }
    in_CS = 0;
    func_0x14177ce4();
    param_1 = extraout_ECX;
    param_2 = extraout_EDX;
    param_4 = uVar11;
  }
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


