/*
 * Function: Unwind@005149b0
 * Address: 005149b0
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void Unwind_005149b0(void)

{
  code *pcVar1;
  
  pcVar1 = (code *)swi(0xb5);
  _DAT_feff68ec = (*pcVar1)();
  return;
}


