/*
 * Function: Unwind@00511cf6
 * Address: 00511cf6
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Instruction at (ram,0x00511d3c) overlaps instruction at (ram,0x00511d3b)
    */
/* WARNING (jumptable): Unable to track spacebase fully for stack */
/* WARNING: Unable to track spacebase fully for stack */
/* WARNING: Removing unreachable block (ram,0x00511cfd) */
/* WARNING: Removing unreachable block (ram,0x00511ca7) */
/* WARNING: Removing unreachable block (ram,0x00511d07) */
/* WARNING: Removing unreachable block (ram,0x00511d09) */
/* WARNING: Removing unreachable block (ram,0x00511cf4) */

uint * __fastcall Unwind_00511cf6(int param_1,int param_2,undefined1 param_3)

{
  char *pcVar1;
  byte *pbVar2;
  byte bVar3;
  byte bVar4;
  char cVar5;
  longlong lVar6;
  code *pcVar7;
  undefined4 uVar8;
  byte bVar9;
  int in_EAX;
  int iVar10;
  uint *puVar11;
  undefined1 *puVar12;
  undefined2 uVar13;
  byte bVar14;
  undefined4 unaff_EBX;
  undefined4 *unaff_EBP;
  undefined4 *unaff_ESI;
  undefined4 *puVar15;
  undefined1 *unaff_EDI;
  undefined2 in_ES;
  undefined2 in_CS;
  bool bVar16;
  byte in_AF;
  bool bVar17;
  byte in_TF;
  byte in_IF;
  byte in_NT;
  byte in_AC;
  byte in_VIF;
  byte in_VIP;
  byte in_ID;
  undefined8 uVar18;
  undefined1 unaff_retaddr;
  undefined2 unaff_retaddr_00;
  
  while( true ) {
    param_1 = CONCAT22((short)((uint)param_1 >> 0x10),
                       CONCAT11((byte)((uint)param_1 >> 8) | (byte)((uint)param_2 >> 8),
                                (char)param_1));
    iVar10 = CONCAT13(param_3,CONCAT21(unaff_retaddr_00,unaff_retaddr));
    unaff_retaddr = (undefined1)((ushort)in_ES >> 8);
    bVar17 = (in_EAX - 1U & 0x42b206aa) == 0;
    bVar16 = (POPCOUNT(in_EAX - 1U & 0xaa) & 1U) == 0;
    if (bVar16) break;
    in_EAX = in(0x3c);
  }
  *(uint *)(iVar10 + -8) =
       (uint)(in_NT & 1) * 0x4000 | (uint)(in_IF & 1) * 0x200 | (uint)(in_TF & 1) * 0x100 |
       (uint)bVar17 * 0x40 | (uint)(in_AF & 1) * 0x10 | (uint)bVar16 * 4 |
       (uint)(in_ID & 1) * 0x200000 | (uint)(in_VIP & 1) * 0x100000 | (uint)(in_VIF & 1) * 0x80000 |
       (uint)(in_AC & 1) * 0x40000;
  puVar12 = unaff_EDI;
  if (!bVar17) {
    uVar8 = *(undefined4 *)(iVar10 + -8);
    uVar13 = (undefined2)uVar8;
    in(uVar13);
    if (bVar17) {
      pcVar7 = (code *)swi(0xed);
      uVar18 = (*pcVar7)();
      puVar11 = (uint *)((int)uVar18 + -0x27);
      *puVar11 = *puVar11 >> 1;
      pcVar1 = (char *)((int)((ulonglong)uVar18 >> 0x20) + -3);
      *pcVar1 = *pcVar1 - (char)((ulonglong)uVar18 >> 0x20);
      cVar5 = '\x11';
      do {
        unaff_EBP = unaff_EBP + -1;
        register0x00000010 = (BADSPACEBASE *)((int)register0x00000010 + -4);
        *(undefined4 *)register0x00000010 = *unaff_EBP;
        cVar5 = cVar5 + -1;
      } while ('\0' < cVar5);
                    /* WARNING: Bad instruction - Truncating control flow here */
      halt_baddata();
    }
    puVar12 = (undefined1 *)in(uVar13);
    bVar9 = (byte)puVar12;
    DAT_2f25b79e = bVar9;
    *(undefined2 *)(iVar10 + -8) = in_CS;
    puVar15 = unaff_ESI + 1;
    out(*unaff_ESI,uVar13);
    pbVar2 = (byte *)(param_1 + 0x6ca3fc09);
    bVar3 = *pbVar2;
    bVar14 = (byte)((uint)uVar8 >> 8);
    bVar4 = *pbVar2 + bVar14;
    bVar16 = CARRY1(bVar4,unaff_EDI + 5 < unaff_ESI);
    *pbVar2 = bVar4 + (unaff_EDI + 5 < unaff_ESI);
    if ((CARRY1(bVar3,bVar14) || bVar16) || *pbVar2 == 0) goto LAB_00511db0;
    bVar4 = 9 < (bVar9 & 0xf) | in_AF;
    bVar9 = bVar9 + bVar4 * -6;
    *(uint *)(iVar10 + -0xc) =
         CONCAT31((int3)((uint)puVar12 >> 8),
                  bVar9 + (0x9f < bVar9 | (CARRY1(bVar3,bVar14) || bVar16) | bVar4 * (bVar9 < 6)) *
                          -0x60);
    *(int *)(iVar10 + -0x10) = param_1;
    *(undefined4 *)(iVar10 + -0x14) = uVar8;
    *(undefined4 *)(iVar10 + -0x18) = unaff_EBX;
    *(int *)(iVar10 + -0x1c) = iVar10 + -8;
    *(undefined4 **)(iVar10 + -0x20) = unaff_EBP;
    *(undefined4 **)(iVar10 + -0x24) = puVar15;
    *(undefined1 **)(iVar10 + -0x28) = unaff_EDI + 6;
    param_2 = 0x779c532c;
    puVar12 = unaff_EDI + 6;
  }
  iVar10 = in((short)param_2);
  lVar6 = (longlong)*(int *)(iVar10 + 0x1202757) * -0x3e;
  puVar15 = (undefined4 *)lVar6;
  if (((int)puVar15 != lVar6) != param_2 + 1 < 0) {
                    /* WARNING: Could not recover jumptable at 0x00511d52. Too many branches */
                    /* WARNING: Treating indirect jump as call */
    puVar11 = (uint *)(**(code **)(param_1 + -0x2c))();
    return puVar11;
  }
LAB_00511db0:
  in(0x88);
  *puVar12 = *(undefined1 *)puVar15;
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


