/*
 * Function: Unwind@005111c0
 * Address: 005111c0
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Instruction at (ram,0x0051126f) overlaps instruction at (ram,0x0051126e)
    */
/* WARNING: Unable to track spacebase fully for stack */
/* WARNING: Removing unreachable block (ram,0x00511201) */
/* WARNING: Removing unreachable block (ram,0x005112ea) */
/* WARNING: Removing unreachable block (ram,0x005111e7) */

void __fastcall Unwind_005111c0(uint param_1,int param_2)

{
  ushort *puVar1;
  uint uVar2;
  undefined1 *puVar3;
  char cVar4;
  longlong lVar5;
  int in_EAX;
  int iVar6;
  char *pcVar7;
  uint uVar8;
  uint uVar9;
  undefined4 uVar10;
  uint extraout_ECX;
  uint *puVar11;
  undefined2 uVar12;
  int iVar13;
  int extraout_EDX;
  byte bVar14;
  int *unaff_EBX;
  undefined3 uVar15;
  undefined4 *puVar16;
  byte *unaff_EBP;
  byte *unaff_ESI;
  byte *pbVar17;
  undefined4 *unaff_EDI;
  uint *puVar18;
  undefined4 *puVar19;
  undefined2 in_CS;
  bool bVar20;
  byte bVar21;
  char in_AF;
  undefined4 in_stack_00000001;
  int aiStack_2f [7];
  undefined1 auStack_13 [4];
  int aiStack_f [3];
  
  iVar6 = in_EAX + 1;
  while( true ) {
    bVar20 = unaff_EBP < unaff_ESI;
    unaff_EBP = unaff_EBP + -(int)unaff_ESI;
    lVar5 = (longlong)*(int *)((int)unaff_ESI * 8 + -0x3d5219a2);
    puVar1 = (ushort *)(unaff_ESI + 0x6f88d90d);
    *puVar1 = *puVar1 + (ushort)bVar20 * (((ushort)unaff_ESI & 3) - (*puVar1 & 3));
    pcVar7 = (char *)((uint)(CONCAT44(param_2,iVar6) / lVar5) ^ 0xae18ecf5);
    *pcVar7 = *pcVar7 - (char)pcVar7;
    param_1 = CONCAT31((int3)(param_1 >> 8),(byte)param_1 & *(byte *)((int)unaff_EBX + param_1 * 2))
    ;
                    /* WARNING: Bad instruction - Truncating control flow here */
    uVar15 = (undefined3)((uint)unaff_EBX >> 8);
    bVar14 = (byte)unaff_EBX | *unaff_ESI;
    unaff_EBX = (int *)CONCAT31(uVar15,bVar14);
    if (bVar14 == 0) {
                    /* WARNING: Bad instruction - Truncating control flow here */
      halt_baddata();
    }
    pbVar17 = unaff_ESI + 4;
    *unaff_EDI = *(undefined4 *)unaff_ESI;
    puVar18 = unaff_EDI + 2;
    unaff_EDI[1] = 0xf0960900;
    if (&stack0x00000000 != (undefined1 *)0x0) break;
    uVar8 = CONCAT22(0xf096,(ushort)(byte)(((int)&stack0x00000000 < 0) << 7 |
                                           (&stack0x00000000 == (undefined1 *)0x0) << 6 | in_AF << 4
                                          | 4) << 8) | 0x200;
    param_2 = (int)(CONCAT44(param_2,iVar6) % lVar5) + *(int *)(uVar8 + 0x82d3bcfd);
    *unaff_EBX = *unaff_EBX + 0x5345629c;
    iVar6 = uVar8 + 1;
    unaff_EDI = (undefined4 *)0x4ec5071f;
    unaff_ESI = pbVar17;
    iRam40f62b78 = iVar6;
    if (*(byte *)((int)unaff_EBX + -0x71) < 0xe4) {
      param_2 = param_2 + 1;
    }
  }
  iVar13 = -0x666310e0;
  iVar6 = *(int *)((int)unaff_EBX + -0x29);
  uVar8 = iVar6 + 0xf6914e76;
  *puVar18 = *puVar18 | 0xffffffe7;
  if (-1 < (int)*puVar18) {
    unaff_EBX = (int *)CONCAT31(uVar15,bVar14 | (&stack0x2a617259)[param_1]);
    pbVar17 = (byte *)CONCAT22((short)((uint)in_stack_00000001 >> 0x10),in_CS);
    puVar19 = (undefined4 *)((int)unaff_EDI + 9);
    *(char *)puVar18 = (char)uVar8;
    if (param_1 != 1 && (uVar8 & 0xdc) != 0) {
      unaff_EBX = (int *)((int)unaff_EBX + 1);
    }
    puVar18 = (uint *)(iVar6 + 0x68624341);
    puVar16 = (undefined4 *)&stack0xfffffffd;
    cVar4 = '\x13';
    do {
      puVar19 = puVar19 + -1;
      puVar16 = puVar16 + -1;
      *puVar16 = *puVar19;
      cVar4 = cVar4 + -1;
    } while ('\0' < cVar4);
    bVar21 = 1;
    func_0x76848269();
    in(0xbd);
    bVar14 = (byte)extraout_ECX & 0x1f;
    cVar4 = *(char *)puVar18;
    *(char *)puVar18 = *(char *)puVar18 << bVar14;
    bVar20 = (extraout_ECX & 0x1f) != 0;
    *unaff_EBX = (int)unaff_EBX +
                 (uint)(byte)(!bVar20 & bVar21 | (bVar20 && (char)(cVar4 << bVar14 - 1) < '\0')) +
                 *unaff_EBX;
    param_1 = extraout_ECX;
    iVar13 = extraout_EDX;
  }
  uVar12 = (undefined2)iVar13;
  uVar9 = in(uVar12);
  puVar11 = (uint *)CONCAT31((int3)(param_1 >> 8),0x60);
  uVar10 = in(uVar12);
  uVar2 = (uint)((uVar9 & 0x100) != 0);
  uVar8 = *puVar11;
  puVar3 = &stack0x00000005 + *puVar11;
  *(undefined4 *)(puVar3 + (uVar2 - 4)) = uVar10;
  *(undefined4 *)(puVar3 + (uVar2 - 8)) = uVar10;
  *(uint **)(puVar3 + (uVar2 - 0xc)) = puVar11;
  *(int *)(puVar3 + (uVar2 - 0x10)) = iVar13;
  *(int **)(puVar3 + (uVar2 - 0x14)) = unaff_EBX;
  *(undefined1 **)(puVar3 + (uVar2 - 0x18)) = puVar3 + (uVar2 - 4);
  *(uint *)(puVar3 + (uVar2 - 0x1c)) = uVar9;
  *(byte **)(puVar3 + (uVar2 - 0x20)) = pbVar17;
  *(uint **)(puVar3 + (uVar2 - 0x24)) = puVar18;
  puVar19 = (undefined4 *)((uint)puVar18 ^ *(uint *)((int)puVar18 + 1));
  *(uint *)(puVar3 + (uVar2 - 0x28)) =
       CONCAT22((short)((uint)uVar10 >> 0x10),
                CONCAT11(((int)(puVar3 + uVar2) < 0) << 7 |
                         (puVar3 + uVar2 == (undefined1 *)0x0) << 6 | ((uVar9 & 0x1000) != 0) << 4 |
                         ((POPCOUNT((uint)(puVar3 + uVar2) & 0xff) & 1U) == 0) << 2 | 2U |
                         (CARRY4((uint)&stack0x00000005,uVar8) || CARRY4((uint)puVar3,uVar2)),
                         (char)uVar10));
  *(char *)(unaff_EBX + -0xf) = (char)unaff_EBX[-0xf] - (char)((uint)iVar13 >> 8);
  *(undefined4 *)(puVar3 + (uVar2 - 0x2c)) = 0xffffffaf;
  uVar10 = in(0xa6);
  *(char *)(iVar13 + -0x66) = *(char *)(iVar13 + -0x66) - (char)((uint)uVar10 >> 8);
  out(uVar12,(char)uVar10);
  DAT_af3c70c7 = DAT_af3c70c7 | (byte)iVar13;
  uVar10 = in((short)(iVar13 + 1));
  DAT_10984e34 = DAT_10984e34 + '\x01';
  DAT_09247a77 = (undefined1)uVar10;
  iVar6 = -*(int *)(((iVar13 + 1) - (int)puVar19) + -0x5d914a3a);
  *(undefined4 *)(puVar3 + uVar2 + iVar6 + -0x30) = 0xb5d7fe81;
  *(byte **)(puVar3 + uVar2 + iVar6 + -0x34) = pbVar17;
  *puVar19 = *(undefined4 *)pbVar17;
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


