/*
 * Function: Unwind@00510108
 * Address: 00510108
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */

void Unwind_00510108(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


