/*
 * Function: Unwind@00513060
 * Address: 00513060
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unable to track spacebase fully for stack */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __fastcall Unwind_00513060(undefined4 param_1,undefined4 param_2)

{
  ushort *puVar1;
  int *piVar2;
  int iVar3;
  bool bVar4;
  code *pcVar5;
  byte bVar6;
  char cVar7;
  undefined4 uVar8;
  undefined4 in_EAX;
  undefined2 uVar9;
  undefined2 *puVar10;
  int unaff_EBX;
  int unaff_EBP;
  int unaff_ESI;
  int unaff_EDI;
  bool bVar11;
  char in_AF;
  char in_SF;
  char in_OF;
  undefined2 in_FPUControlWord;
  undefined2 in_FPUStatusWord;
  undefined2 in_FPUTagWord;
  undefined2 in_FPULastInstructionOpcode;
  undefined4 in_FPUDataPointer;
  undefined4 in_FPUInstructionPointer;
  unkbyte10 extraout_ST0;
  unkbyte10 extraout_ST0_00;
  unkbyte10 in_ST0;
  unkbyte10 extraout_ST1;
  unkbyte10 extraout_ST1_00;
  unkbyte10 in_ST1;
  unkbyte10 in_ST2;
  unkbyte10 in_ST3;
  unkbyte10 in_ST4;
  unkbyte10 in_ST5;
  unkbyte10 in_ST6;
  unkbyte10 in_ST7;
  undefined8 uVar12;
  
  if (in_OF == in_SF) {
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  }
  bVar6 = in((short)param_2);
  uVar8 = CONCAT31((int3)((uint)in_EAX >> 8),*(undefined1 *)(unaff_EBX + (uint)bVar6));
  pcVar5 = (code *)swi(4);
  if (in_OF == '\x01') {
    uVar12 = (*pcVar5)();
    param_2 = (undefined4)((ulonglong)uVar12 >> 0x20);
    uVar8 = (undefined4)uVar12;
    in_ST0 = extraout_ST0;
    in_ST1 = extraout_ST1;
  }
  uVar12 = CONCAT44(param_2,uVar8);
  pcVar5 = (code *)swi(4);
  if (SBORROW4(unaff_EDI,1)) {
    uVar12 = (*pcVar5)();
    in_ST0 = extraout_ST0_00;
    in_ST1 = extraout_ST1_00;
  }
  puVar10 = (undefined2 *)((ulonglong)uVar12 >> 0x20);
  *puVar10 = in_FPUControlWord;
  puVar10[2] = in_FPUStatusWord;
  puVar10[4] = in_FPUTagWord;
  *(undefined4 *)(puVar10 + 10) = in_FPUDataPointer;
  *(undefined4 *)(puVar10 + 6) = in_FPUInstructionPointer;
  puVar10[9] = in_FPULastInstructionOpcode;
  *(unkbyte10 *)(puVar10 + 0xe) = in_ST0;
  *(unkbyte10 *)(puVar10 + 0x13) = in_ST1;
  *(unkbyte10 *)(puVar10 + 0x18) = in_ST2;
  *(unkbyte10 *)(puVar10 + 0x1d) = in_ST3;
  *(unkbyte10 *)(puVar10 + 0x22) = in_ST4;
  *(unkbyte10 *)(puVar10 + 0x27) = in_ST5;
  *(unkbyte10 *)(puVar10 + 0x2c) = in_ST6;
  *(unkbyte10 *)(puVar10 + 0x31) = in_ST7;
  piVar2 = (int *)(unaff_EBP + -0x350cc55c);
  iVar3 = *piVar2;
  *piVar2 = -*piVar2;
  bVar6 = (byte)unaff_EBP;
  bVar11 = bVar6 < *(byte *)(unaff_EDI + -0x48);
  bVar6 = bVar6 - *(byte *)(unaff_EDI + -0x48);
  bVar4 = bVar6 < (iVar3 != 0);
  cVar7 = bVar6 - (iVar3 != 0);
  if ((!bVar11 && !bVar4) && cVar7 != '\0') {
    DAT_35434cac = cVar7 + ((cVar7 == '\0') << 6 | in_AF << 4 | ((POPCOUNT(cVar7) & 1U) == 0) << 2 |
                            2U | (bVar11 || bVar4)) * '.';
    *(byte *)(unaff_ESI + 0x65) =
         *(byte *)(unaff_ESI + 0x65) ^ (byte)*(undefined4 *)((int)uVar12 + 0x50);
    uVar9 = (undefined2)((ulonglong)uVar12 >> 0x20);
    out(uVar9,DAT_35434cac);
    uVar8 = in(uVar9);
    _DAT_55f22b5b = CONCAT31((int3)((uint)uVar8 >> 8),(byte)uVar8 - 0x38);
    puVar1 = (ushort *)(unaff_ESI + 0x95);
    _DAT_dc3b0d8e = _DAT_55f22b5b;
    *puVar1 = *puVar1 + (ushort)((byte)uVar8 < 0x38) *
                        (((ushort)(undefined1 *)(unaff_EDI + -2) & 3) - (*puVar1 & 3));
    *(undefined1 *)(unaff_EDI + -2) = *(undefined1 *)(unaff_ESI + 4);
    pcVar5 = (code *)swi(3);
    (*pcVar5)();
    return;
  }
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


