/*
 * Function: Unwind@0050faf0
 * Address: 0050faf0
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void Unwind_0050faf0(void)

{
  if (_DAT_a993ebcf == -0x33b9f804) {
    _DAT_530dc9f2 = _DAT_530dc9f2 + 1;
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  }
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


