/*
 * Function: Unwind@00512641
 * Address: 00512641
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */

longlong Unwind_00512641(undefined4 *param_1,undefined4 param_2,undefined4 param_3,int param_4,
                        undefined1 param_5,int param_6,undefined1 *param_7)

{
  uint *puVar1;
  uint uVar2;
  uint in_EAX;
  int unaff_EBX;
  byte in_CF;
  char *unaff_retaddr;
  uint uVar3;
  
  puVar1 = (uint *)(unaff_EBX + 0x7324b5ee);
  uVar2 = *puVar1;
  uVar3 = *puVar1;
  *puVar1 = (uVar3 - in_EAX) - (uint)in_CF;
  *unaff_retaddr =
       *unaff_retaddr + (char)((uint)param_7 >> 8) +
       (uVar2 < in_EAX || uVar3 - in_EAX < (uint)in_CF);
  if (*unaff_retaddr != '\0') {
    return (longlong)(int)param_7 * (longlong)param_4;
  }
  LOCK();
  *param_7 = (char)param_7;
  UNLOCK();
  if ((char)((byte)param_6 + 0x85) < '\0') {
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  }
  if (0x7a < (byte)param_6) {
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  }
  out(*param_1,CONCAT11(0xe1,param_5));
  out(0x6f,(char)*(undefined4 *)(param_6 + -0x7d7426c4));
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


