/*
 * Function: Unwind@00515900
 * Address: 00515900
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */

void Unwind_00515900(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


