/*
 * Function: Unwind@0051265f
 * Address: 0051265f
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Control flow encountered bad instruction data */

void Unwind_0051265f(void)

{
  int in_EAX;
  undefined4 unaff_EBP;
  int unaff_ESI;
  undefined4 *unaff_EDI;
  char in_CF;
  
  *unaff_EDI = unaff_EBP;
  *(int *)(unaff_ESI + -0x23) = *(int *)(unaff_ESI + -0x23) + in_EAX + (uint)(in_CF == '\0');
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


