/*
 * Function: Vector_PushBack_28ByteObjects
 * Address: 00407970
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __thiscall Vector_PushBack_28ByteObjects(void *this,undefined4 *param_1)

{
  int iVar1;
  undefined4 *puVar2;
  
  iVar1 = *(int *)((int)this + 4);
  if ((iVar1 != 0) &&
     ((uint)((*(int *)((int)this + 8) - iVar1) / 0x1c) <
      (uint)((*(int *)((int)this + 0xc) - iVar1) / 0x1c))) {
    puVar2 = *(undefined4 **)((int)this + 8);
    Vector_Destructor_4ByteObjects(puVar2,1,param_1);
    *(undefined4 **)((int)this + 8) = puVar2 + 7;
    return;
  }
  Vector_InsertSingle_28ByteObjects(this,(int *)&param_1,*(undefined4 **)((int)this + 8),param_1);
  return;
}


