/*
 * Function: Widget_GetFont
 * Address: 004b3710
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __thiscall Widget_GetFont(void *this,undefined4 param_1)

{
  *(undefined4 *)((int)this + 0x14) = param_1;
  Widget_SetColors((int)this);
  return;
}


