/*
 * Function: ZLIB_GZSeek
 * Address: 004cc230
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __cdecl ZLIB_GZSeek(int param_1)

{
  int iVar1;
  
  iVar1 = *(int *)(param_1 + 0x14c);
  ZLIB_GZDOpen(0xd8);
  *(undefined4 *)(iVar1 + 0x1c) = 0;
  if (*(char *)(param_1 + 0xc4) != '\0') {
    ZLIB_GZPutc();
  }
  if (*(char *)(param_1 + 0xcc) != '\0') {
    ZLIB_GZGetc();
    return;
  }
  return;
}


