/*
 * Function: ZLIB_GZPutc
 * Address: 004cc0a0
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void ZLIB_GZPutc(void)

{
  int in_EAX;
  
  ZLIB_GZDOpen(0xe0);
  ZLIB_GZSetParams();
  ZLIB_GZOpen(0x4a);
  ZLIB_GZOpen(0x46);
  ZLIB_GZOpen(0x49);
  ZLIB_GZOpen(0x46);
  ZLIB_GZOpen(0);
  ZLIB_GZOpen(*(undefined1 *)(in_EAX + 0xc5));
  ZLIB_GZOpen(*(undefined1 *)(in_EAX + 0xc6));
  ZLIB_GZOpen(*(undefined1 *)(in_EAX + 199));
  ZLIB_GZSetParams();
  ZLIB_GZSetParams();
  ZLIB_GZOpen(0);
  ZLIB_GZOpen(0);
  return;
}


