/*
 * Function: ZLIB_GZPrintf
 * Address: 004cbec0
 * Category: misc
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void ZLIB_GZPrintf(void)

{
  ZLIB_GZDOpen(0xdd);
  ZLIB_GZSetParams();
  ZLIB_GZSetParams();
  return;
}


