/*
 * Function: Config_LoadPropertiesFile
 * Address: 004ab9b0
 * Category: system
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall Config_LoadPropertiesFile(void *param_1)

{
  char *pcVar1;
  char cVar2;
  char *pcVar3;
  uint uVar4;
  _String_base *p_Var5;
  undefined4 extraout_ECX;
  int extraout_ECX_00;
  int extraout_ECX_01;
  int extraout_ECX_02;
  int extraout_ECX_03;
  uint extraout_EDX;
  uint extraout_EDX_00;
  uint extraout_EDX_01;
  uint extraout_EDX_02;
  uint extraout_EDX_03;
  uint unaff_retaddr;
  undefined4 *in_stack_ffffff44;
  undefined4 *in_stack_ffffff48;
  undefined1 local_9c [20];
  uint local_88;
  _String_base local_4c [4];
  int local_48;
  uint local_34;
  undefined1 local_30 [4];
  uint local_2c;
  undefined4 local_1c;
  uint local_18;
  uint local_14;
  void *local_10;
  undefined *puStack_c;
  undefined4 local_8;
  
  local_8 = 0xffffffff;
  puStack_c = &DAT_00516493;
  local_10 = ExceptionList;
  local_14 = DAT_00569f5c ^ unaff_retaddr;
  ExceptionList = &local_10;
  cVar2 = Font_GetTextHeight(*(int *)((int)param_1 + 8));
  if (cVar2 == '\0') {
    WeaponBomb_ProcessBurstingRocket((int)&stack0xffffff44);
    local_8 = 0;
    cVar2 = XML_ParseDocument(*(int *)((int)param_1 + 8),extraout_EDX,(int *)&stack0xffffff44);
    while (cVar2 != '\0') {
      if (in_stack_ffffff44 == (undefined4 *)0x1) {
        pcVar1 = "Properties";
        do {
          pcVar3 = pcVar1;
          pcVar1 = pcVar3 + 1;
        } while (*pcVar3 != '\0');
        uVar4 = String_Compare(local_9c,0,local_88,(_String_base *)"Properties",
                               (uint)(pcVar3 + -0x536238));
        if (uVar4 != 0) {
          p_Var5 = Survival_LoadConfiguration
                             (local_4c,(_String_base *)"Invalid Section \'",(int)local_9c);
          local_8._0_1_ = 1;
          p_Var5 = Intel_DisplayPopulationData
                             (extraout_ECX,(uint)local_30,(_String_base *)local_30,p_Var5,
                              (_String_base *)&DAT_00531760);
          local_8 = CONCAT31(local_8._1_3_,2);
          Image_Destructor(param_1,p_Var5);
          uVar4 = extraout_EDX_00;
          if (0xf < local_18) {
                    /* WARNING: Subroutine does not return */
            System_ShutdownHandler(extraout_ECX_00,extraout_EDX_00);
          }
joined_r0x004abb67:
          local_2c = local_2c & 0xffffff00;
          local_1c = 0;
          local_18 = 0xf;
          if (0xf < local_34) {
            local_18 = 0xf;
            local_1c = 0;
                    /* WARNING: Subroutine does not return */
            System_ShutdownHandler(local_48,uVar4);
          }
          break;
        }
        cVar2 = Config_ParsePropertiesXML(param_1);
        if (cVar2 == '\0') break;
      }
      else if (in_stack_ffffff44 == (undefined4 *)0x3) {
        p_Var5 = Survival_LoadConfiguration
                           (local_4c,(_String_base *)"Element Not Expected \'",(int)local_9c);
        local_8._0_1_ = 3;
        p_Var5 = Intel_DisplayPopulationData
                           (local_30,extraout_EDX_01,(_String_base *)local_30,p_Var5,
                            (_String_base *)&DAT_00531760);
        local_8 = CONCAT31(local_8._1_3_,4);
        Image_Destructor(param_1,p_Var5);
        local_48 = extraout_ECX_01;
        uVar4 = extraout_EDX_02;
        if (0xf < local_18) {
                    /* WARNING: Subroutine does not return */
          System_ShutdownHandler(extraout_ECX_01,local_2c);
        }
        goto joined_r0x004abb67;
      }
      local_8 = 0xffffffff;
      PowerUp_ProcessNuke((int)&stack0xffffff44);
      WeaponBomb_ProcessBurstingRocket((int)&stack0xffffff44);
      local_8 = 0;
      cVar2 = XML_ParseDocument(*(int *)((int)param_1 + 8),(uint)&stack0xffffff44,
                                (int *)&stack0xffffff44);
    }
    local_8 = 0xffffffff;
    PowerUp_ProcessNuke((int)&stack0xffffff44);
  }
  cVar2 = Font_GetTextHeight(*(int *)((int)param_1 + 8));
  if (cVar2 != '\0') {
    p_Var5 = Config_SaveSettings(extraout_ECX_02,(uint)local_30,(_String_base *)local_30);
    local_8 = 5;
    Image_Destructor(param_1,p_Var5);
    local_8 = 0xffffffff;
    if (0xf < local_18) {
                    /* WARNING: Subroutine does not return */
      System_ShutdownHandler(extraout_ECX_03,extraout_EDX_03);
    }
    local_18 = 0xf;
    local_1c = 0;
    local_2c = local_2c & 0xffffff00;
  }
  if (*(undefined4 **)((int)param_1 + 8) != (undefined4 *)0x0) {
    (**(code **)**(undefined4 **)((int)param_1 + 8))(1);
  }
  *(undefined4 *)((int)param_1 + 8) = 0;
  ExceptionList = local_10;
  Exception_SetMessage((void *)(local_14 ^ unaff_retaddr),in_stack_ffffff44,in_stack_ffffff48);
  return;
}


