/*
 * Function: CreditsSystem_LoadCreditsXML
 * Address: 0041e970
 * Category: system
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void CreditsSystem_LoadCreditsXML(void)

{
  char cVar1;
  char *pcVar2;
  uint uVar3;
  char *pcVar4;
  undefined2 extraout_DX;
  uint extraout_EDX;
  uint extraout_EDX_00;
  uint extraout_EDX_01;
  uint uVar5;
  uint extraout_EDX_02;
  uint extraout_EDX_03;
  uint extraout_EDX_04;
  uint extraout_EDX_05;
  uint extraout_EDX_06;
  uint extraout_EDX_07;
  uint extraout_EDX_08;
  byte *****pppppbVar6;
  undefined4 *puVar7;
  byte *pbVar8;
  bool bVar9;
  bool bVar10;
  uint unaff_retaddr;
  undefined4 *in_stack_ffffff38;
  undefined4 *in_stack_ffffff3c;
  _String_base local_a8 [4];
  byte ****local_a4 [4];
  char *local_94;
  uint local_90;
  undefined1 local_58 [4];
  uint local_54;
  undefined4 local_44;
  uint local_40;
  _String_base local_3c [4];
  uint local_38;
  undefined4 local_28;
  uint local_24;
  undefined4 local_20;
  int local_1c;
  undefined4 *local_18;
  uint local_14;
  void *local_10;
  undefined4 uStack_c;
  undefined4 local_8;
  
  local_8 = 0xffffffff;
  uStack_c = 0x510c66;
  local_10 = ExceptionList;
  local_14 = DAT_00569f5c ^ unaff_retaddr;
  ExceptionList = &local_10;
  local_18 = (undefined4 *)operator_new(0x74);
  local_8 = 0;
  if (local_18 == (undefined4 *)0x0) {
    local_18 = (undefined4 *)0x0;
  }
  else {
    local_18 = (undefined4 *)ObjectType1_Constructor(local_18);
  }
  puVar7 = local_18;
  local_40 = 0xf;
  local_8 = 0xffffffff;
  local_44 = 0;
  local_54 = local_54 & 0xffffff00;
  pcVar4 = "data\\credits.xml";
  do {
    pcVar2 = pcVar4;
    pcVar4 = pcVar2 + 1;
  } while (*pcVar2 != '\0');
  String_Assign(local_58,(_String_base *)"data\\credits.xml",(uint)(pcVar2 + -0x52ce48));
  local_8 = 1;
  Image_UpdateTexture((int)puVar7,extraout_DX,(int)local_58);
  local_8 = 0xffffffff;
  if (0xf < local_40) {
                    /* WARNING: Subroutine does not return */
    System_ShutdownHandler(local_54,extraout_EDX);
  }
  local_40 = 0xf;
  local_44 = 0;
  local_54 = local_54 & 0xffffff00;
  WeaponBomb_ProcessBurstingRocket((int)&stack0xffffff38);
  local_24 = 0xf;
  local_28 = 0;
  local_38 = local_38 & 0xffffff00;
  local_8 = 3;
  cVar1 = Font_GetTextHeight((int)puVar7);
  uVar5 = extraout_EDX_00;
  do {
    if ((cVar1 != '\0') ||
       (cVar1 = XML_ParseDocument((int)puVar7,(uint)&stack0xffffff38,(int *)&stack0xffffff38),
       uVar5 = extraout_EDX_01, cVar1 == '\0')) goto LAB_0041ec22;
    if (in_stack_ffffff38 == (undefined4 *)0x1) {
      pcVar4 = "h";
      do {
        pcVar2 = pcVar4;
        pcVar4 = pcVar2 + 1;
      } while (*pcVar2 != '\0');
      pcVar2 = pcVar2 + -0x52ce44;
      if (local_94 == (char *)0x0) {
LAB_0041eae3:
        if (pcVar2 <= local_94) {
          uVar5 = (uint)(local_94 != pcVar2);
          goto LAB_0041eaee;
        }
LAB_0041eafa:
        pcVar4 = "t";
        do {
          pcVar2 = pcVar4;
          pcVar4 = pcVar2 + 1;
        } while (*pcVar2 != '\0');
        uVar5 = String_Compare(local_a8,0,(uint)local_94,(_String_base *)&DAT_0052ce40,
                               (uint)(pcVar2 + -0x52ce40));
        if (uVar5 == 0) {
          local_20 = 1;
          uVar5 = extraout_EDX_02;
        }
        else {
          pcVar4 = "l";
          do {
            pcVar2 = pcVar4;
            pcVar4 = pcVar2 + 1;
          } while (*pcVar2 != '\0');
          uVar5 = String_Compare(local_a8,0,(uint)local_94,(_String_base *)&DAT_0052ce3c,
                                 (uint)(pcVar2 + -0x52ce3c));
          if (uVar5 == 0) {
            local_20 = 2;
            uVar5 = extraout_EDX_03;
          }
          else {
            pcVar4 = "b";
            do {
              pcVar2 = pcVar4;
              pcVar4 = pcVar2 + 1;
            } while (*pcVar2 != '\0');
            uVar3 = String_Compare(local_a8,0,(uint)local_94,(_String_base *)&DAT_0052ce38,
                                   (uint)(pcVar2 + -0x52ce38));
            uVar5 = extraout_EDX_04;
            if (uVar3 == 0) {
              local_20 = 3;
              pcVar4 = "";
              do {
                pcVar2 = pcVar4;
                pcVar4 = pcVar2 + 1;
              } while (*pcVar2 != '\0');
              String_Assign(local_3c,(_String_base *)&DAT_0052c7cf,(uint)(pcVar2 + -0x52c7cf));
              Vector_PushBack32Byte((void *)(local_1c + 0xf0),local_3c);
              uVar5 = extraout_EDX_05;
            }
          }
        }
      }
      else {
        pcVar4 = local_94;
        if (pcVar2 <= local_94) {
          pcVar4 = pcVar2;
        }
        pppppbVar6 = (byte *****)local_a4[0];
        if (local_90 < 0x10) {
          pppppbVar6 = local_a4;
        }
        bVar9 = false;
        uVar5 = 0;
        bVar10 = true;
        pbVar8 = &DAT_0052ce44;
        do {
          if (pcVar4 == (char *)0x0) break;
          pcVar4 = pcVar4 + -1;
          bVar9 = *(byte *)pppppbVar6 < *pbVar8;
          bVar10 = *(byte *)pppppbVar6 == *pbVar8;
          pppppbVar6 = (byte *****)((int)pppppbVar6 + 1);
          pbVar8 = pbVar8 + 1;
        } while (bVar10);
        if (!bVar10) {
          uVar5 = (1 - (uint)bVar9) - (uint)(bVar9 != 0);
        }
        if (uVar5 == 0) goto LAB_0041eae3;
LAB_0041eaee:
        if (uVar5 != 0) goto LAB_0041eafa;
        local_20 = 0;
        uVar5 = 0;
      }
      cVar1 = XML_ParseDocument((int)local_18,uVar5,(int *)&stack0xffffff38);
      uVar5 = extraout_EDX_06;
      puVar7 = local_18;
      if (cVar1 == '\0') {
LAB_0041ec22:
        if (puVar7 != (undefined4 *)0x0) {
          (**(code **)*puVar7)(1);
          uVar5 = extraout_EDX_08;
        }
        if (local_24 < 0x10) {
          local_24 = 0xf;
          local_28 = 0;
          local_38 = local_38 & 0xffffff00;
          local_8 = 0xffffffff;
          PowerUp_ProcessNuke((int)&stack0xffffff38);
          ExceptionList = local_10;
          Exception_SetMessage
                    ((void *)(local_14 ^ unaff_retaddr),in_stack_ffffff38,in_stack_ffffff3c);
          return;
        }
                    /* WARNING: Subroutine does not return */
        System_ShutdownHandler(local_38,uVar5);
      }
      if (in_stack_ffffff38 == (undefined4 *)0x3) {
        PowerUp_ProcessThunderstrike(local_3c,extraout_EDX_06,local_a8,0,0xffffffff);
        Vector_PushBack32Byte((void *)(local_1c + 0xf0),local_3c);
        puVar7 = local_18;
      }
    }
    cVar1 = Font_GetTextHeight((int)puVar7);
    uVar5 = extraout_EDX_07;
  } while( true );
}


