/*
 * Function: Exception_LocaleSystemCleanup
 * Address: 004ee8fa
 * Category: system
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall Exception_LocaleSystemCleanup(undefined4 param_1,uint param_2)

{
  code *pcVar1;
  int unaff_EBP;
  
  System_DirectShutdownHandler(*(int *)(unaff_EBP + -0x14),param_2);
  CRuntime_CxxThrowException(0,0);
  pcVar1 = (code *)swi(3);
  (*pcVar1)();
  return;
}


