/*
 * Function: File_WriteData
 * Address: 0051251b
 * Category: system
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall File_WriteData(undefined4 param_1,int param_2)

{
  uint *puVar1;
  undefined2 *puVar2;
  char cVar3;
  byte bVar4;
  code *pcVar5;
  uint unaff_EBX;
  uint uVar6;
  int unaff_ESI;
  uint unaff_EDI;
  int in_GS_OFFSET;
  bool in_CF;
  byte *unaff_retaddr;
  undefined4 uStack00000004;
  
  if (in_CF) {
    uVar6 = unaff_EBX ^ unaff_EDI;
    cVar3 = *(char *)(param_2 + -0x79020287);
    bVar4 = *unaff_retaddr;
    puVar2 = (undefined2 *)(in_GS_OFFSET + unaff_ESI + 0x3cf6510b);
    *puVar2 = *puVar2;
    puVar1 = (uint *)(CONCAT22((short)(uVar6 >> 0x10),
                               CONCAT11((char)(uVar6 >> 8) - cVar3 ^ bVar4,(char)uVar6)) +
                     -0x2ff87db9);
    *puVar1 = *puVar1 | unaff_EDI;
    uStack00000004 = *(undefined4 *)param_2;
    File_WriteData(param_1,param_2);
    return;
  }
  pcVar5 = (code *)swi(3);
  (*pcVar5)();
  return;
}


