/*
 * Function: File_Exists
 * Address: 004d6c30
 * Category: system
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


undefined4 __cdecl File_Exists(int *param_1,int param_2)

{
  int iVar1;
  int *piVar2;
  int iVar3;
  undefined4 *puVar4;
  int iVar5;
  
  piVar2 = param_1;
  iVar1 = param_1[0x57];
  if (param_1[0x2f] != 0) {
    if (*(int *)(iVar1 + 0x24) == 0) {
      iVar3 = 0;
      if (0 < param_1[0x39]) {
        puVar4 = (undefined4 *)(iVar1 + 0x14);
        do {
          *puVar4 = 0;
          iVar3 = iVar3 + 1;
          puVar4 = puVar4 + 1;
        } while (iVar3 < param_1[0x39]);
      }
      *(int *)(iVar1 + 0x24) = param_1[0x2f];
    }
    *(int *)(iVar1 + 0x24) = *(int *)(iVar1 + 0x24) + -1;
  }
  iVar3 = param_1[0x40];
  iVar5 = 0;
  if (0 < iVar3) {
    param_1 = param_1 + 0x41;
    do {
      iVar3 = *param_1;
      String_Format(*(void **)(iVar1 + 0x14 + iVar3 * 4),piVar2,*(short **)(param_2 + iVar5 * 4),
                    *(int **)(iVar1 + 0x5c + *(int *)(piVar2[iVar3 + 0x3a] + 0x18) * 4));
      *(int *)(iVar1 + 0x14 + iVar3 * 4) = (int)**(short **)(param_2 + iVar5 * 4);
      iVar3 = piVar2[0x40];
      iVar5 = iVar5 + 1;
      param_1 = param_1 + 1;
    } while (iVar5 < iVar3);
  }
  return CONCAT31((int3)((uint)iVar3 >> 8),1);
}


