/*
 * Function: FileIO_GetFileSize
 * Address: 004825a0
 * Category: system
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __thiscall
FileIO_GetFileSize(void *this,int param_1,int param_2,int param_3,uint *param_4,int param_5,
                  int param_6,int param_7)

{
  uint uVar1;
  uint uVar2;
  int iVar3;
  float *pfVar4;
  int extraout_ECX;
  int extraout_ECX_00;
  float *pfVar5;
  _String_base *p_Var6;
  char *pcVar7;
  undefined1 local_cd4 [3200];
  undefined1 *local_54;
  int local_50;
  int local_4c;
  float local_48 [3];
  float local_3c [4];
  uint local_2c;
  uint local_28;
  uint local_24;
  undefined4 local_20;
  float local_1c;
  float local_18;
  float local_14;
  void *local_10;
  undefined4 uStack_c;
  undefined4 local_8;
  
  local_8 = 0xffffffff;
  uStack_c = 0x5149bb;
  local_10 = ExceptionList;
  if ((2 < param_2) &&
     (ExceptionList = &local_10, uVar2 = SexyWidget_UpdateVertices((int)this), (char)uVar2 != '\0'))
  {
    uVar2 = *param_4;
    local_28 = param_4[1];
    local_24 = param_4[2];
    uVar1 = param_4[3];
    DirectX_SetRenderState(this,param_5);
    p_Var6 = *(_String_base **)((int)this + 0x20);
    uVar2 = ((uVar1 << 8 | uVar2) << 8 | local_28) << 8 | local_24;
    iVar3 = (**(code **)(*(int *)p_Var6 + 0x8c))(p_Var6,0,0,"SetTexture NULL");
    Threading_LockMutex(iVar3,p_Var6);
    local_54 = local_cd4;
    local_50 = 0;
    local_4c = 100;
    local_8 = 0;
    param_4 = (uint *)0x0;
    if (0 < param_2) {
      local_3c[2] = 0.0;
      local_3c[3] = 1.0;
      local_2c = uVar2;
      local_28 = 0;
      local_24 = 0;
      local_20 = 0;
      do {
        local_3c[0] = (float)(*(int *)(param_1 + (int)param_4 * 8) + param_6);
        local_3c[1] = (float)(*(int *)(param_1 + 4 + (int)param_4 * 8) + param_7);
        if (*(int *)((int)this + 0x54) != 0) {
          local_14 = 1.0;
          local_1c = local_3c[0];
          local_18 = local_3c[1];
          pfVar4 = (float *)Font_GetDescent((void *)(*(int *)(*(int *)((int)this + 0x50) + 4) + 8),
                                            local_48,&local_1c);
          local_1c = *pfVar4;
          local_18 = pfVar4[1];
          local_14 = pfVar4[2];
          local_3c[0] = *pfVar4;
          local_3c[1] = pfVar4[1];
        }
        if (local_50 == local_4c) {
          SexyWidget_ValidateGeometry(local_cd4,local_4c * 2);
        }
        pfVar4 = local_3c;
        pfVar5 = (float *)(local_54 + local_50 * 0x20);
        for (iVar3 = 8; iVar3 != 0; iVar3 = iVar3 + -1) {
          *pfVar5 = *pfVar4;
          pfVar4 = pfVar4 + 1;
          pfVar5 = pfVar5 + 1;
        }
        local_50 = local_50 + 1;
        param_4 = (uint *)((int)param_4 + 1);
      } while ((int)param_4 < param_2);
    }
    if (param_3 == 0) {
      pcVar7 = "DrawPrimitive (FillPoly)";
      iVar3 = (**(code **)(**(int **)((int)this + 0x20) + 100))
                        (*(int **)((int)this + 0x20),6,0x1c4,local_54,local_50,0);
      Threading_LockMutex(iVar3,(_String_base *)pcVar7);
      iVar3 = extraout_ECX_00;
    }
    else {
      FileIO_ReadFile(local_cd4,*(int **)((int)this + 0x20));
      iVar3 = extraout_ECX;
    }
    if (local_54 != local_cd4) {
                    /* WARNING: Subroutine does not return */
      System_ShutdownHandler(iVar3,(uint)local_cd4);
    }
  }
  ExceptionList = local_10;
  return;
}


