/*
 * Function: Font_LoadFromFile
 * Address: 00496160
 * Category: system
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


undefined4 * __thiscall Font_LoadFromFile(void *this,undefined4 param_1,_String_base *param_2)

{
  undefined4 uVar1;
  undefined4 *puVar2;
  void *local_10;
  undefined4 uStack_c;
  undefined4 local_8;
  
  local_8 = 0xffffffff;
  uStack_c = 0x515559;
  local_10 = ExceptionList;
  ExceptionList = &local_10;
  Graphics_SetRenderState((undefined4 *)this);
  *(undefined ***)this = &PTR_Registry_CloseKey_00533844;
  *(undefined4 *)((int)this + 0x20) = 0;
  *(undefined4 *)((int)this + 0x24) = 0;
  *(undefined4 *)((int)this + 0x28) = 0;
  local_8._0_1_ = 1;
  local_8._1_3_ = 0;
  uVar1 = Exception_ReportError();
  *(undefined4 *)((int)this + 0x34) = uVar1;
  *(undefined4 *)((int)this + 0x38) = 0;
  local_8._0_1_ = 2;
  *(undefined4 *)((int)this + 0x40) = 0;
  *(undefined4 *)((int)this + 0x44) = 0x3ff00000;
  puVar2 = (undefined4 *)operator_new(0x198);
  local_8._0_1_ = 3;
  if (puVar2 == (undefined4 *)0x0) {
    puVar2 = (undefined4 *)0x0;
  }
  else {
    puVar2 = Font_Constructor(puVar2);
  }
  local_8 = CONCAT31(local_8._1_3_,2);
  *(undefined4 **)((int)this + 0x14) = puVar2;
  RefCounter_AddRef((int)puVar2);
  Font_LoadDescriptor(*(void **)((int)this + 0x14),param_1,param_2);
  *(undefined4 *)((int)this + 0x18) = *(undefined4 *)(*(int *)((int)this + 0x14) + 0x10);
  PowerUp_UpdateSystem(this);
  *(undefined1 *)((int)this + 0x48) = 0;
  *(undefined1 *)((int)this + 0x2c) = 1;
  ExceptionList = local_10;
  return (undefined4 *)this;
}


