/*
 * Function: ImageFormat_GetFileExtension
 * Address: 004bdcf0
 * Category: system
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall
ImageFormat_GetFileExtension
          (int param_1,uint param_2,undefined4 *param_3,undefined4 *param_4,undefined4 *param_5)

{
  undefined4 *extraout_ECX;
  int extraout_ECX_00;
  int extraout_ECX_01;
  undefined4 *extraout_ECX_02;
  undefined4 *puVar1;
  uint extraout_EDX;
  uint extraout_EDX_00;
  uint extraout_EDX_01;
  uint extraout_EDX_02;
  uint extraout_EDX_03;
  uint uVar2;
  undefined4 *puVar3;
  undefined4 *puVar4;
  undefined4 *puVar5;
  
  puVar5 = (undefined4 *)0x0;
  puVar4 = (undefined4 *)0x0;
  puVar3 = (undefined4 *)0x0;
  if (param_3 != (undefined4 *)0x0) {
    puVar5 = (undefined4 *)*param_3;
  }
  if (param_4 != (undefined4 *)0x0) {
    puVar4 = (undefined4 *)*param_4;
  }
  if (param_5 != (undefined4 *)0x0) {
    puVar3 = (undefined4 *)*param_5;
  }
  ImageFormat_IsSupported(param_1,param_2,puVar5,puVar4,puVar3);
  puVar1 = extraout_ECX;
  uVar2 = extraout_EDX;
  if (puVar4 != (undefined4 *)0x0) {
    CPU_Instruction13((int)extraout_ECX,extraout_EDX,(int)puVar5,puVar4[0xe]);
    CPU_Instruction11(extraout_ECX_00,extraout_EDX_00,(int)puVar4);
    *param_4 = 0;
    puVar1 = param_4;
    uVar2 = extraout_EDX_01;
  }
  if (puVar3 != (undefined4 *)0x0) {
    CPU_Instruction13((int)puVar1,puVar3[0xe],(int)puVar5,puVar3[0xe]);
    CPU_Instruction11(extraout_ECX_01,extraout_EDX_02,(int)puVar3);
    *param_5 = 0;
    puVar1 = extraout_ECX_02;
    uVar2 = extraout_EDX_03;
  }
  if (puVar5 != (undefined4 *)0x0) {
    CPU_Instruction11((int)puVar1,uVar2,(int)puVar5);
    *param_3 = 0;
  }
  return;
}


