/*
 * Function: Log_RotateFiles
 * Address: 0044faf0
 * Category: system
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


int __thiscall Log_RotateFiles(void *this,int param_1,int param_2)

{
  undefined4 uVar1;
  int iVar2;
  
  if (*(int *)((int)this + 0x5c) != 0) {
    if ((param_1 == 0) && (param_2 == 0)) {
      uVar1 = 4;
    }
    else {
      uVar1 = 0;
    }
    iVar2 = String_CompareData(*(int *)((int)this + 0x5c),param_1,uVar1,param_2);
    if (iVar2 == 0) {
      return (int)this;
    }
  }
  return 0;
}


