/*
 * Function: Log_RotateFile
 * Address: 004ef563
 * Category: system
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void Log_RotateFile(void)

{
  undefined4 *puVar1;
  uint uVar2;
  int iVar3;
  undefined4 extraout_ECX;
  undefined2 extraout_DX;
  uint extraout_EDX;
  uint extraout_EDX_00;
  uint uVar4;
  int unaff_EBP;
  int iVar5;
  undefined8 uVar6;
  undefined4 *in_stack_ffffffd0;
  undefined4 *in_stack_ffffffd4;
  
  Assembly_BitShiftLocking();
  uVar2 = DAT_00569f5c ^ *(uint *)(unaff_EBP + 4);
  *(undefined4 *)(unaff_EBP + -0x20) = DAT_00546d84;
  *(undefined4 *)(unaff_EBP + -0x14) = extraout_ECX;
  *(uint *)(unaff_EBP + -0x10) = uVar2;
  *(undefined1 *)(unaff_EBP + -0x1c) = DAT_00546d88;
  String_Initialize(unaff_EBP + -0x3c);
  *(undefined4 *)(unaff_EBP + -4) = 0;
  if (*(char *)(unaff_EBP + 0x24) == '\0') {
    *(undefined1 *)(unaff_EBP + -0x1e) = *(undefined1 *)(unaff_EBP + 0x20);
  }
  else {
    *(char *)(unaff_EBP + -0x1e) = *(char *)(unaff_EBP + 0x24);
    *(undefined1 *)(unaff_EBP + -0x1d) = *(undefined1 *)(unaff_EBP + 0x20);
  }
  uVar2 = 0x10;
  while( true ) {
    Memory_AllocateSound((_String_base *)(unaff_EBP + -0x3c),uVar2,(_String_base)0x0);
    iVar5 = *(int *)(unaff_EBP + -0x38);
    if (*(uint *)(unaff_EBP + -0x24) < 0x10) {
      iVar5 = unaff_EBP + -0x38;
    }
    uVar6 = Assembly_ParityFlagCheck(iVar5,extraout_DX);
    uVar4 = (uint)((ulonglong)uVar6 >> 0x20);
    if ((int)uVar6 != 0) break;
    uVar2 = uVar2 * 2;
  }
  iVar5 = *(int *)(unaff_EBP + -0x38);
  uVar2 = (int)uVar6 - 1;
  *(undefined4 *)(unaff_EBP + -0x18) = 0;
  if (*(uint *)(unaff_EBP + -0x24) < 0x10) {
    iVar5 = unaff_EBP + -0x38;
  }
  iVar5 = iVar5 + 1;
  if (uVar2 != 0) {
    *(int *)(unaff_EBP + 0x20) = *(int *)(unaff_EBP + -0x14) + 0xc;
    do {
      iVar3 = Runtime_DebugCrtMemCheckpoint(unaff_EBP + 0x24,iVar5,uVar2);
      if (-3 < iVar3) {
        uVar4 = extraout_EDX;
        if (iVar3 < 0) break;
        if (iVar3 == 0) {
          iVar3 = Assembly_BadInstruction();
          iVar3 = iVar3 + 1;
        }
      }
      Timer_Create((void *)(unaff_EBP + 0xc),*(undefined4 *)(unaff_EBP + 0x24));
      iVar5 = iVar5 + iVar3;
      uVar2 = uVar2 - iVar3;
      uVar4 = extraout_EDX_00;
    } while (uVar2 != 0);
  }
  puVar1 = *(undefined4 **)(unaff_EBP + 8);
  *puVar1 = *(undefined4 *)(unaff_EBP + 0xc);
  puVar1[1] = *(undefined4 *)(unaff_EBP + 0x10);
  String_Reset(unaff_EBP + -0x3c,uVar4,'\x01');
  ExceptionList = *(void **)(unaff_EBP + -0xc);
  Exception_SetMessage
            ((void *)(*(uint *)(unaff_EBP + -0x10) ^ *(uint *)(unaff_EBP + 4)),in_stack_ffffffd0,
             in_stack_ffffffd4);
  return;
}


