/*
 * Function: PropertiesFile_Load
 * Address: 00456400
 * Category: system
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __thiscall PropertiesFile_Load(void *this,int param_1,char param_2,char param_3)

{
  char cVar1;
  undefined4 uVar2;
  _String_base *p_Var3;
  int extraout_ECX;
  undefined4 extraout_ECX_00;
  int extraout_ECX_01;
  int extraout_ECX_02;
  undefined2 extraout_DX;
  uint extraout_EDX;
  uint extraout_EDX_00;
  uint extraout_EDX_01;
  uint extraout_EDX_02;
  uint extraout_EDX_03;
  uint extraout_EDX_04;
  uint uVar4;
  uint extraout_EDX_05;
  uint unaff_retaddr;
  undefined4 *in_stack_ffffff68;
  undefined4 *in_stack_ffffff6c;
  uint local_80;
  undefined4 local_7c [11];
  undefined4 local_50 [8];
  _String_base local_30 [4];
  uint local_2c;
  undefined4 local_1c;
  uint local_18;
  uint local_14;
  void *local_10;
  undefined4 uStack_c;
  int local_8;
  
  local_8 = 0xffffffff;
  uStack_c = 0x5134e3;
  local_10 = ExceptionList;
  local_14 = DAT_00569f5c ^ unaff_retaddr;
  ExceptionList = &local_10;
  ObjectType2_Constructor(local_50);
  local_8 = 0;
  uVar2 = Math_MaxValue((int)this,extraout_DX,param_1,local_50,'\0');
  if ((char)uVar2 == '\0') {
    uVar4 = extraout_EDX;
    if (param_2 == '\0') {
LAB_00456596:
      local_8 = 0xffffffff;
      Image_ScaleBilinear(local_50,uVar4);
      goto LAB_004565a7;
    }
    p_Var3 = Survival_LoadConfiguration
                       (local_30,(_String_base *)"Unable to open properties file: ",param_1);
                    /* WARNING: Load size is inaccurate */
    local_8 = CONCAT31(local_8._1_3_,1);
    (**(code **)(*this + 0x70))(p_Var3);
    uVar4 = extraout_EDX_00;
    if (0xf < local_18) {
                    /* WARNING: Subroutine does not return */
      System_ShutdownHandler(extraout_ECX,extraout_EDX_00);
    }
  }
  else {
    if (param_3 != '\0') {
                    /* WARNING: Load size is inaccurate */
      cVar1 = (**(code **)(*this + 0x130))(local_50,param_1);
      if (cVar1 == '\0') {
        p_Var3 = Survival_LoadConfiguration
                           ((_String_base *)&stack0xffffff68,
                            (_String_base *)"Signature check failed on \'",param_1);
        local_8._0_1_ = 2;
        p_Var3 = Intel_DisplayPopulationData
                           (extraout_ECX_00,(uint)local_30,local_30,p_Var3,
                            (_String_base *)&DAT_00531760);
                    /* WARNING: Load size is inaccurate */
        local_8 = CONCAT31(local_8._1_3_,3);
        (**(code **)(*this + 0x70))(p_Var3);
        if (0xf < local_18) {
                    /* WARNING: Subroutine does not return */
          System_ShutdownHandler(extraout_ECX_01,extraout_EDX_01);
        }
        local_18 = 0xf;
        local_1c = 0;
        local_2c = local_2c & 0xffffff00;
        uVar4 = extraout_EDX_01;
        if (0xf < local_80) {
                    /* WARNING: Subroutine does not return */
          System_ShutdownHandler((int)in_stack_ffffff6c,extraout_EDX_01);
        }
        goto LAB_0045657b;
      }
    }
    Collision_ApplyFriction(local_7c,this);
    local_8._0_1_ = 4;
    cVar1 = Config_InitializeFromFile(local_7c,(int)local_50);
    if (cVar1 != '\0') {
      local_8 = (uint)local_8._1_3_ << 8;
      Collision_UpdateVelocity(local_7c,extraout_EDX_02);
      uVar4 = extraout_EDX_05;
      goto LAB_00456596;
    }
    p_Var3 = Config_SetSetting((int)local_7c,extraout_EDX_02,local_30);
                    /* WARNING: Load size is inaccurate */
    local_8._0_1_ = 5;
    (**(code **)(*this + 0x70))(p_Var3);
    if (0xf < local_18) {
                    /* WARNING: Subroutine does not return */
      System_ShutdownHandler(extraout_ECX_02,extraout_EDX_03);
    }
    local_18 = 0xf;
    local_1c = 0;
    local_2c = local_2c & 0xffffff00;
    local_8 = (uint)local_8._1_3_ << 8;
    Collision_UpdateVelocity(local_7c,extraout_EDX_03);
    uVar4 = extraout_EDX_04;
  }
LAB_0045657b:
  local_8 = 0xffffffff;
  Image_ScaleBilinear(local_50,uVar4);
LAB_004565a7:
  ExceptionList = local_10;
  Exception_SetMessage((void *)(local_14 ^ unaff_retaddr),in_stack_ffffff68,in_stack_ffffff6c);
  return;
}


