/*
 * Function: System_ScheduleTask
 * Address: 0047dbc0
 * Category: system
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


int __thiscall System_ScheduleTask(void *this,undefined4 *param_1,byte param_2)

{
  int iVar1;
  ulonglong uVar2;
  int local_c;
  int local_8;
  
                    /* WARNING: Load size is inaccurate */
  (**(code **)(*this + 0x58))();
  local_8 = 0;
  if (param_2 != 0) {
    param_2 = *(byte *)(param_2 + 0x14 + *(int *)((int)this + 0x14));
  }
  param_1 = *(undefined4 **)((int)this + 0x34);
  if (param_1 != (undefined4 *)0x0) {
    param_1 = (undefined4 *)*param_1;
  }
  iVar1 = 0;
  if (param_1 != *(undefined4 **)((int)this + 0x34)) {
    do {
      if (*(int *)(param_1[3] + 0x12060) == 0) {
        uVar2 = Math_FloatToUInt64();
        local_c = (int)uVar2;
        if (param_2 == 0) {
LAB_0047dcba:
          iVar1 = 0;
        }
        else {
          uVar2 = Math_FloatToUInt64();
          iVar1 = (int)uVar2;
        }
      }
      else {
        uVar2 = Math_FloatToUInt64();
        local_c = (int)uVar2;
        if (param_2 == 0) goto LAB_0047dcba;
        uVar2 = Math_FloatToUInt64();
        iVar1 = (int)uVar2;
      }
      if (local_8 < iVar1 + local_c) {
        local_8 = iVar1 + local_c;
      }
      param_1 = (undefined4 *)*param_1;
      iVar1 = local_8;
    } while (param_1 != *(undefined4 **)((int)this + 0x34));
  }
  return iVar1;
}


