/*
 * Function: System_ExecuteScheduledTask
 * Address: 0047dcf0
 * Category: system
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


bool __thiscall System_ExecuteScheduledTask(void *this,int param_1)

{
  System_CheckResourceLimits
            (&param_1,*(void **)((int)this + 0x20),*(void **)((int)this + 0x24),param_1);
  return param_1 != *(int *)((int)this + 0x24);
}


