/*
 * Function: System_PrioritizeTask
 * Address: 0047dea0
 * Category: system
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


undefined4 * __thiscall System_PrioritizeTask(void *this,int param_1)

{
  uint uVar1;
  uint uVar2;
  undefined4 *puVar3;
  undefined4 *puVar4;
  uint uVar5;
  uint uVar6;
  byte *pbVar7;
  byte *pbVar8;
  bool bVar9;
  bool bVar10;
  undefined4 *local_8;
  
  local_8 = *(undefined4 **)((int)this + 4);
  if (*(char *)((int)local_8[1] + 0x2d) != '\0') {
    return local_8;
  }
  uVar1 = *(uint *)(param_1 + 0x14);
  puVar3 = (undefined4 *)local_8[1];
  do {
    pbVar8 = (byte *)(param_1 + 4);
    if (0xf < *(uint *)(param_1 + 0x18)) {
      pbVar8 = *(byte **)(param_1 + 4);
    }
    uVar2 = puVar3[8];
    if (uVar2 == 0) {
LAB_0047df20:
      if (uVar1 <= uVar2) {
        uVar6 = (uint)(uVar2 != uVar1);
        goto LAB_0047df2d;
      }
LAB_0047df2f:
      puVar4 = (undefined4 *)puVar3[2];
    }
    else {
      uVar5 = uVar2;
      if (uVar1 <= uVar2) {
        uVar5 = uVar1;
      }
      if ((uint)puVar3[9] < 0x10) {
        pbVar7 = (byte *)(puVar3 + 4);
      }
      else {
        pbVar7 = (byte *)puVar3[4];
      }
      bVar9 = false;
      uVar6 = 0;
      bVar10 = true;
      do {
        if (uVar5 == 0) break;
        uVar5 = uVar5 - 1;
        bVar9 = *pbVar7 < *pbVar8;
        bVar10 = *pbVar7 == *pbVar8;
        pbVar7 = pbVar7 + 1;
        pbVar8 = pbVar8 + 1;
      } while (bVar10);
      if (!bVar10) {
        uVar6 = (1 - (uint)bVar9) - (uint)(bVar9 != 0);
      }
      if (uVar6 == 0) goto LAB_0047df20;
LAB_0047df2d:
      if ((int)uVar6 < 0) goto LAB_0047df2f;
      puVar4 = (undefined4 *)*puVar3;
      local_8 = puVar3;
    }
    puVar3 = puVar4;
    if (*(char *)((int)puVar4 + 0x2d) != '\0') {
      return local_8;
    }
  } while( true );
}


