/*
 * Function: Thread_Sleep
 * Address: 004e0840
 * Category: system
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __cdecl Thread_Sleep(int param_1,int *param_2,int param_3,undefined4 *param_4,int param_5)

{
  undefined1 uVar1;
  uint uVar2;
  int iVar3;
  undefined1 *puVar4;
  uint uVar5;
  int iVar6;
  
  uVar2 = *(uint *)(param_1 + 0x5c);
  if (-1 < param_5 + -1) {
    iVar6 = param_3 << 2;
    param_1 = param_5;
    do {
      iVar3 = *(int *)(iVar6 + *param_2);
      puVar4 = (undefined1 *)*param_4;
      param_4 = param_4 + 1;
      iVar6 = iVar6 + 4;
      uVar5 = 0;
      if (uVar2 != 0) {
        do {
          uVar1 = *(undefined1 *)(uVar5 + iVar3);
          puVar4[2] = uVar1;
          puVar4[1] = uVar1;
          *puVar4 = uVar1;
          puVar4 = puVar4 + 3;
          uVar5 = uVar5 + 1;
        } while (uVar5 < uVar2);
      }
      param_1 = param_1 + -1;
    } while (param_1 != 0);
  }
  return;
}


