/*
 * Function: Dialog_ProcessInput
 * Address: 00445c30
 * Category: ui
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __fastcall Dialog_ProcessInput(int param_1)

{
  double dVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  void *this;
  undefined8 local_1c;
  void *local_10;
  undefined4 uStack_c;
  undefined4 local_8;
  
  local_8 = 0xffffffff;
  uStack_c = 0x512e1b;
  local_10 = ExceptionList;
  if (*(int *)(*(int *)(param_1 + 0x4c) + 0x17c) < *(int *)(*(int *)(param_1 + 0x4c) + 0x184)) {
    return;
  }
  ExceptionList = &local_10;
  Boss_ProcessWreckerWarWrecker(param_1);
  iVar4 = *(int *)(param_1 + 0x70);
  iVar2 = *(int *)(param_1 + 0x74) * 0x50 + iVar4;
  *(double *)(param_1 + 0x18) = *(double *)(iVar2 + 0xd0) - *(double *)(param_1 + 8);
  *(double *)(param_1 + 0x20) = *(double *)(iVar2 + 0x1c0) - *(double *)(param_1 + 0x10);
  *(undefined4 *)(param_1 + 8) = *(undefined4 *)(iVar2 + 0xd0);
  *(undefined4 *)(param_1 + 0xc) = *(undefined4 *)(iVar2 + 0xd4);
  dVar1 = *(double *)(iVar2 + 0x1c0);
  *(double *)(param_1 + 0x10) = dVar1;
  if (dVar1 < _DAT_0052c958 == (NAN(dVar1) || NAN(_DAT_0052c958))) {
    ExceptionList = local_10;
    return;
  }
  iVar2 = *(int *)(param_1 + 0x4c);
  if (*(int *)(iVar2 + 0x80) == 0) {
    iVar3 = *(int *)(param_1 + 0x80) + -1;
  }
  else {
    iVar3 = *(int *)(iVar4 + 0x268);
  }
  *(int *)(param_1 + 0x80) = iVar3;
  if (0 < iVar3) {
    ExceptionList = local_10;
    return;
  }
  if (*(double *)(param_1 + 0x10) < _DAT_005301b8 ==
      (NAN(*(double *)(param_1 + 0x10)) || NAN(_DAT_005301b8))) {
    ExceptionList = local_10;
    return;
  }
  if ((NAN(*(double *)(iVar2 + 0x88)) || NAN(_DAT_0052a0c0)) ==
      (*(double *)(iVar2 + 0x88) == _DAT_0052a0c0)) {
    ExceptionList = local_10;
    return;
  }
  if (*(double *)(param_1 + 0x20) < _DAT_0052a0f0 ==
      (NAN(*(double *)(param_1 + 0x20)) || NAN(_DAT_0052a0f0))) {
    ExceptionList = local_10;
    return;
  }
  if (*(int *)(iVar2 + 0x300) != 0) {
    ExceptionList = local_10;
    return;
  }
  *(undefined4 *)(param_1 + 0x80) = *(undefined4 *)(iVar4 + 0x268);
  local_1c = (*(double *)(iVar2 + 0x90) - *(double *)(param_1 + 8)) * _DAT_00530fe8;
  if (local_1c <= _DAT_0052c560) {
    if (local_1c < _DAT_00530850 == (NAN(local_1c) || NAN(_DAT_00530850))) goto LAB_00445d88;
    local_1c._4_4_ = 0xc0080000;
  }
  else {
    local_1c._4_4_ = 0x40080000;
  }
  local_1c = (double)((ulonglong)local_1c._4_4_ << 0x20);
LAB_00445d88:
  iVar4 = Collision_HandleEnemyHit();
  dVar1 = ((double)(iVar4 % 200) * _DAT_0052c538 - _DAT_0052a0f0) + local_1c;
  this = operator_new(0x68);
  local_8 = 0;
  if (this != (void *)0x0) {
    local_1c._4_4_ = (uint)((ulonglong)dVar1 >> 0x20);
    local_1c._0_4_ = SUB84(dVar1,0);
    Math_RandomInt(this,*(int *)(param_1 + 0x4c),*(undefined4 *)(param_1 + 8),
                   *(undefined4 *)(param_1 + 0xc),*(undefined4 *)(param_1 + 0x10),
                   *(undefined4 *)(param_1 + 0x14),(undefined4)local_1c,local_1c._4_4_,
                   *(undefined4 *)(param_1 + 0x20),*(undefined4 *)(param_1 + 0x24),
                   dVar1 < _DAT_0052a0c0 != (NAN(dVar1) || NAN(_DAT_0052a0c0)));
  }
  ExceptionList = local_10;
  return;
}


