/*
 * Function: Dialog_SetTitle
 * Address: 00446b50
 * Category: ui
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall Dialog_SetTitle(int param_1)

{
  if (*(int **)(param_1 + 0x100) != (int *)0x0) {
    (**(code **)(**(int **)(param_1 + 0x100) + 0x14))(0,0);
  }
  if (*(int **)(param_1 + 0x104) != (int *)0x0) {
    (**(code **)(**(int **)(param_1 + 0x104) + 0x14))(0,0);
  }
  return;
}


