/*
 * Function: ErrorDialog_CreateFatalErrorWindow
 * Address: 004ae1d0
 * Category: ui
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __cdecl ErrorDialog_CreateFatalErrorWindow(uint param_1,_String_base *param_2)

{
  int iVar1;
  HCURSOR hCursor;
  _String_base *lpWindowName;
  HWND hWnd;
  DWORD dwStyle;
  LPCSTR lpWindowName_00;
  uint extraout_EDX;
  int nWidth;
  uint unaff_retaddr;
  undefined4 *puVar2;
  undefined4 *in_stack_ffffff08;
  DWORD local_ec;
  tagMSG local_68;
  WNDCLASSA local_4c;
  tagRECT local_24;
  HWND local_14;
  HFONT local_10;
  HWND local_c;
  uint local_8;
  
  local_8 = DAT_00569f5c ^ unaff_retaddr;
  puVar2 = (undefined4 *)0x94;
  GetVersionExA((LPOSVERSIONINFOA)&stack0xffffff04);
  DAT_00566b8a = local_ec != 2;
  iVar1 = MulDiv(8,0x60,0x48);
  DAT_005a37dc = CreateFontA(-iVar1,0,0,0,400,0,0,0,0,0,0,0,0,"Tahoma");
  iVar1 = MulDiv(10,0x60,0x48);
  DAT_005a37e0 = CreateFontA(-iVar1,0,0,0,700,0,0,0,0,0,0,0,0,"Tahoma");
  hCursor = LoadCursorA((HINSTANCE)0x0,(LPCSTR)0x7f00);
  SetCursor(hCursor);
  PowerUp_ProcessThunderstrike
            ((_String_base *)&DAT_00567600,param_1,(_String_base *)param_1,0,0xffffffff);
  PowerUp_ProcessThunderstrike((_String_base *)&DAT_0056761c,extraout_EDX,param_2,0,0xffffffff);
  local_4c.style = 0;
  local_4c.cbClsExtra = 0;
  local_4c.cbWndExtra = 0;
  local_4c.hbrBackground = GetSysColorBrush(0xf);
  local_4c.hCursor = LoadCursorA((HINSTANCE)0x0,(LPCSTR)0x7f00);
  local_4c.hIcon = LoadIconA((HINSTANCE)0x0,(LPCSTR)0x7f01);
  local_4c.hInstance = DAT_005a33c0;
  local_4c.lpfnWndProc = ErrorDialog_WindowProcedure;
  local_4c.lpszClassName = "SEHWindow";
  local_4c.lpszMenuName = (LPCSTR)0x0;
  RegisterClassA(&local_4c);
  local_24.left = 0;
  local_24.top = 0;
  local_24.right = 400;
  local_24.bottom = 300;
  AdjustWindowRect(&local_24,0x82ca0000,0);
  local_c = CreateWindowExA(0,"SEHWindow","Fatal Error!",0x82ca0000,0x40,0x40,
                            local_24.right - local_24.left,local_24.bottom - local_24.top,(HWND)0x0,
                            (HMENU)0x0,DAT_005a33c0,(LPVOID)0x0);
  lpWindowName_00 = DAT_00567674;
  if (DAT_00567688 < 0x10) {
    lpWindowName_00 = (LPCSTR)&DAT_00567674;
  }
  local_14 = CreateWindowExA(0,"EDIT",lpWindowName_00,0x50000804,8,8,0x180,0x54,local_c,(HMENU)0x0,
                             DAT_005a33c0,(LPVOID)0x0);
  iVar1 = MulDiv(9,0x60,0x48);
  local_10 = CreateFontA(-iVar1,0,0,0,700,0,0,0,0,0,0,0,0,"Arial");
  if (DAT_00566b8a == '\0') {
    SendMessageA(local_14,0x30,(WPARAM)local_10,0);
  }
  if (*(uint *)(param_2 + 0x18) < 0x10) {
    lpWindowName = param_2 + 4;
  }
  else {
    lpWindowName = *(_String_base **)(param_2 + 4);
  }
  hWnd = CreateWindowExA(0,"EDIT",(LPCSTR)lpWindowName,0x50a00804,8,0x5c,0x180,0xa8,local_c,
                         (HMENU)0x0,DAT_005a33c0,(LPVOID)0x0);
  iVar1 = MulDiv(8,0x60,0x48);
  local_14 = (HWND)CreateFontA(-iVar1,0,0,0,400,0,0,0,0,0,0,0,0,"Courier New");
  if (DAT_00566b8a == '\0') {
    SendMessageA(hWnd,0x30,(WPARAM)local_14,0);
  }
  dwStyle = 0x50000001;
  if (DAT_005a37d8 == 0) {
    dwStyle = 0x58000001;
  }
  DAT_005a37e8 = CreateWindowExA(0,"BUTTON","Send Report",dwStyle,8,0x10c,0xbc,0x18,local_c,
                                 (HMENU)0x0,DAT_005a33c0,(LPVOID)0x0);
  if (DAT_00566b8a == '\0') {
    SendMessageA(DAT_005a37e8,0x30,(WPARAM)local_10,0);
  }
  iVar1 = 0xcc;
  nWidth = 0xbc;
  if ((DAT_00566b89 == '\0') || (DAT_005676a0 == 0)) {
    iVar1 = 8;
    nWidth = 0x180;
    ShowWindow(DAT_005a37e8,0);
  }
  DAT_005a37ec = CreateWindowExA(0,"BUTTON","Close Now",0x50000001,iVar1,0x10c,nWidth,0x18,local_c,
                                 (HMENU)0x0,DAT_005a33c0,(LPVOID)0x0);
  if (DAT_00566b8a == '\0') {
    SendMessageA(DAT_005a37ec,0x30,(WPARAM)local_10,0);
  }
  ShowWindow(local_c,1);
  iVar1 = GetMessageA(&local_68,(HWND)0x0,0,0);
  while ((0 < iVar1 && (DAT_005a3818 == '\0'))) {
    TranslateMessage(&local_68);
    DispatchMessageA(&local_68);
    iVar1 = GetMessageA(&local_68,(HWND)0x0,0,0);
  }
  DestroyWindow(local_c);
  DeleteObject(DAT_005a37dc);
  DeleteObject(DAT_005a37e0);
  DeleteObject(local_10);
  DeleteObject(local_14);
  Exception_SetMessage((void *)(local_8 ^ unaff_retaddr),puVar2,in_stack_ffffff08);
  return;
}


