/*
 * Function: HighScore_ButtonClickHandler
 * Address: 00423450
 * Category: ui
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __thiscall HighScore_ButtonClickHandler(void *this,undefined4 param_1)

{
  char cVar1;
  void *pvVar2;
  int *piVar3;
  undefined4 *puVar4;
  undefined4 *puVar5;
  undefined1 *puVar6;
  char *pcVar7;
  uint extraout_EDX;
  uint extraout_EDX_00;
  uint extraout_EDX_01;
  uint uVar8;
  uint extraout_EDX_02;
  uint extraout_EDX_03;
  uint extraout_EDX_04;
  int iVar9;
  char *pcVar10;
  int iVar11;
  undefined1 local_84 [28];
  _String_base local_68 [28];
  undefined1 local_4c [28];
  _String_base local_30 [28];
  undefined4 local_14;
  void *local_10;
  undefined4 uStack_c;
  undefined4 local_8;
  
  local_8 = 0xffffffff;
  uStack_c = 0x511152;
  local_10 = ExceptionList;
  local_14 = 0;
  ExceptionList = &local_10;
  (**(code **)(**(int **)((int)this + 4) + 0xb8))(0x12,0);
  switch(param_1) {
  case 0:
    GameSystem_InitializeObject(*(int **)((int)this + 4));
    UI_ProcessChildAnimation(*(void **)(*(int *)((int)this + 4) + 0x2dc),(int *)((int)this + -0x58))
    ;
    (**(code **)(**(int **)((int)this + 4) + 0x78))((int *)((int)this + -0x58));
    ExceptionList = local_10;
    return;
  case 1:
    *(undefined1 *)((int)this + 0x28) = 0;
    ExceptionList = local_10;
    return;
  case 2:
    *(undefined1 *)((int)this + 0x28) = 1;
    ExceptionList = local_10;
    return;
  case 3:
    break;
  case 4:
    (**(code **)(**(int **)((int)this + 4) + 0x108))(0x20);
    iVar11 = 0;
    do {
      pcVar10 = &DAT_0052d740 + iVar11;
      pcVar7 = (char *)(*(int *)(*(int *)((int)this + 4) + 0x144c) + iVar11);
      do {
        cVar1 = *pcVar10;
        pcVar10 = pcVar10 + 1;
        *pcVar7 = cVar1;
        pcVar7 = pcVar7 + 1;
      } while (cVar1 != '\0');
      iVar9 = iVar11 + 0x1c;
      *(undefined4 *)(*(int *)(*(int *)((int)this + 4) + 0x144c) + -4 + iVar9) =
           *(undefined4 *)((int)&DAT_0052d758 + iVar11);
      iVar11 = iVar9;
    } while (iVar9 < 0x118);
    if (*(char *)((int)this + 0x30) != '\0') {
      *(undefined4 *)((int)this + 0x2c) = 10;
    }
    HighScoreSystem_SaveData(*(void **)((int)this + 4));
    ExceptionList = local_10;
    return;
  case 5:
    (**(code **)(**(int **)((int)this + 4) + 0x108))(0x20);
    iVar11 = 0;
    puVar4 = &DAT_0052d61c;
    do {
      pcVar10 = (char *)(puVar4 + -7);
      pcVar7 = (char *)(*(int *)(*(int *)((int)this + 4) + 0x143c) + iVar11);
      do {
        cVar1 = *pcVar10;
        pcVar10 = pcVar10 + 1;
        *pcVar7 = cVar1;
        pcVar7 = pcVar7 + 1;
      } while (cVar1 != '\0');
      puVar5 = puVar4 + 8;
      iVar11 = iVar11 + 0x24;
      *(undefined4 *)(*(int *)(*(int *)((int)this + 4) + 0x143c) + -0xc + iVar11) = puVar4[-1];
      *(undefined4 *)(*(int *)(*(int *)((int)this + 4) + 0x143c) + -8 + iVar11) = *puVar4;
      *(undefined4 *)(*(int *)(*(int *)((int)this + 4) + 0x143c) + -4 + iVar11) = *puVar4;
      puVar4 = puVar5;
    } while ((int)puVar5 < 0x52d75c);
    if (*(char *)((int)this + 0x30) == '\0') {
      *(undefined4 *)((int)this + 0x2c) = 10;
    }
    HighScoreSystem_SaveData(*(void **)((int)this + 4));
    ExceptionList = local_10;
    return;
  case 6:
  case 7:
  case 8:
  case 9:
  case 10:
  case 0xb:
  case 0xc:
  case 0xd:
  case 0xe:
  case 0xf:
  case 0x10:
  case 0x11:
  case 0x12:
  case 0x13:
  case 0x14:
  case 0x15:
  case 0x16:
  case 0x17:
  case 0x18:
  case 0x19:
  case 0x1a:
  case 0x1b:
  case 0x1c:
  case 0x1d:
  case 0x1e:
  case 0x1f:
  case 0x20:
  case 0x21:
    ExceptionList = local_10;
    return;
  case 0x22:
    (**(code **)(**(int **)((int)this + 4) + 0x108))(0x20);
    ExceptionList = local_10;
    return;
  default:
    ExceptionList = local_10;
    return;
  }
  if (*(char *)((int)this + 0x28) == '\0') {
    pvVar2 = operator_new(0x124);
    local_8 = 5;
    if (pvVar2 == (void *)0x0) {
      piVar3 = (int *)0x0;
      uVar8 = extraout_EDX_02;
    }
    else {
      Level_InitializeDictastroika
                (local_84,
                 "Are you sure you want reset MISSION Mode high scores to their defaults?\n\nThis will reset all scores that have been recorded."
                );
      local_8 = CONCAT31(local_8._1_3_,6);
      local_14 = 4;
      Level_InitializeDictastroika(local_68,"RESET SCORES?");
      local_8 = 7;
      local_14 = 0xc;
      piVar3 = Dialog_YesNoConstructor
                         (pvVar2,*(int *)((int)this + 4),-(uint)(this != (void *)0x58) & (uint)this,
                          local_68,(uint)local_84,0x168,0xfa,5,0);
      String_Destructor((int)local_68,extraout_EDX_03);
      uVar8 = extraout_EDX_04;
    }
    local_8 = 0xffffffff;
    if (pvVar2 == (void *)0x0) goto LAB_00423652;
    puVar6 = local_84;
  }
  else {
    pvVar2 = operator_new(0x124);
    piVar3 = (int *)0x0;
    local_8 = 0;
    uVar8 = extraout_EDX;
    if (pvVar2 != (void *)0x0) {
      Level_InitializeDictastroika
                (local_4c,
                 "Are you sure you want reset SURVIVAL Mode high scores to their defaults?\n\nThis will reset all scores that have been recorded."
                );
      local_8 = CONCAT31(local_8._1_3_,1);
      local_14 = 1;
      Level_InitializeDictastroika(local_30,"RESET SCORES?");
      local_8 = 2;
      local_14 = 3;
      piVar3 = Dialog_YesNoConstructor
                         (pvVar2,*(int *)((int)this + 4),-(uint)(this != (void *)0x58) & (uint)this,
                          local_30,(uint)local_4c,0x168,0xfa,4,0);
      String_Destructor((int)local_30,extraout_EDX_00);
      uVar8 = extraout_EDX_01;
    }
    local_8 = 0xffffffff;
    if (pvVar2 == (void *)0x0) goto LAB_00423652;
    puVar6 = local_4c;
  }
  local_8 = 0xffffffff;
  String_Destructor((int)puVar6,uVar8);
LAB_00423652:
  (**(code **)(**(int **)((int)this + 4) + 0x100))(0x20,piVar3);
  (**(code **)(*piVar3 + 0xd4))(0);
  ExceptionList = local_10;
  return;
}


