/*
 * Function: Input_IsMouseButtonPressed
 * Address: 004a1fd0
 * Category: ui
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void Input_IsMouseButtonPressed(int param_1)

{
  int extraout_ECX;
  uint extraout_EDX;
  uint extraout_EDX_00;
  
  if (*(char *)(param_1 + 0x35) == '\0') {
    Input_IsMouseButtonPressed(*(int *)(param_1 + 8));
    Collision_FindMTV(param_1,extraout_EDX);
                    /* WARNING: Subroutine does not return */
    System_ShutdownHandler(extraout_ECX,extraout_EDX_00);
  }
  return;
}


