/*
 * Function: PauseMenu_Update
 * Address: 0042dfd0
 * Category: ui
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall PauseMenu_Update(int *param_1)

{
  int iVar1;
  
  Algorithm_CopyN((int)param_1);
  iVar1 = param_1[0x18];
  if ((*(int *)(iVar1 + 0x184) < *(int *)(iVar1 + 0x17c)) && (*(char *)(iVar1 + 0x327) == '\0')) {
    (**(code **)(*param_1 + 0x38))(0,*(int *)(iVar1 + 0x184) - *(int *)(iVar1 + 0x17c));
  }
  return;
}


