/*
 * Function: SetupUILayout
 * Address: 0040ef20
 * Category: ui
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __thiscall SetupUILayout(void *this,int param_1,int param_2,int param_3,undefined4 *param_4)

{
  int iVar1;
  
  UI_ValidateWidgetLayout(this,param_1,param_2,param_3,(int)param_4);
  (**(code **)(**(int **)((int)this + 0x60) + 0x34))(0x1fe,0x1ae,0x6e,0x1e);
  (**(code **)(**(int **)((int)this + 100) + 0x34))(0x14,0x1ae,0x6e,0x1e);
  iVar1 = 0;
  if (0 < *(int *)((int)this + 0xa8)) {
    param_4 = (undefined4 *)((int)this + 0x68);
    do {
      (**(code **)(*(int *)*param_4 + 0x34))
                ((iVar1 / 3) * 0x1b8 + 10,(iVar1 % 3) * 100 + 0xf,0xb4,0x5a);
      iVar1 = iVar1 + 1;
      param_4 = param_4 + 1;
    } while (iVar1 < *(int *)((int)this + 0xa8));
  }
  return;
}


