/*
 * Function: UI_DrawChildBorder
 * Address: 00464210
 * Category: ui
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


int UI_DrawChildBorder(int *param_1)

{
  int *piVar1;
  
  piVar1 = param_1 + 2;
  *piVar1 = *piVar1 + -1;
  if (*piVar1 == 0) {
    (**(code **)(*param_1 + 0x78))(1);
  }
  return param_1[2];
}


