/*
 * Function: UI_HandleMenuInput
 * Address: 0049a2c0
 * Category: ui
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __thiscall UI_HandleMenuInput(void *this,int *param_1,int param_2,uint param_3)

{
  int *piVar1;
  int *piVar2;
  uint uVar3;
  
  piVar1 = (int *)((int)this + 4);
  piVar2 = piVar1;
  if (0xf < *(uint *)((int)this + 0x18)) {
    piVar2 = (int *)*piVar1;
  }
  if (param_2 == 0) {
    uVar3 = 0;
  }
  else {
    uVar3 = param_2 - (int)piVar2;
  }
  if (param_3 != 0) {
    param_3 = param_3 - param_2;
  }
  PowerUp_ProcessFlakCannon(this,uVar3,param_3);
  if (*(uint *)((int)this + 0x18) < 0x10) {
    *param_1 = (int)piVar1 + uVar3;
    return;
  }
  *param_1 = *piVar1 + uVar3;
  return;
}


