/*
 * Function: UI_HandleChildFocus
 * Address: 00463f10
 * Category: ui
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


undefined4 __thiscall UI_HandleChildFocus(void *this,int param_1,int param_2,int param_3)

{
  char cVar1;
  uint uVar2;
  int *piVar3;
  
  *(undefined4 *)((int)this + 100) = *(undefined4 *)((int)this + 4);
  if (param_3 < 0) {
    uVar2 = *(uint *)((int)this + 0x60) | 2;
  }
  else if (param_3 == 3) {
    uVar2 = *(uint *)((int)this + 0x60) | 4;
  }
  else {
    uVar2 = *(uint *)((int)this + 0x60) | 1;
  }
  *(uint *)((int)this + 0x60) = uVar2;
  UI_ProcessWidgetUpdates(this,param_1,param_2);
  if (*(int **)((int)this + 0x24) != (int *)0x0) {
    cVar1 = (**(code **)(**(int **)((int)this + 0x24) + 0xa8))(param_1,param_2);
    if (cVar1 == '\0') {
      UI_UpdateChildVisibility(this);
    }
  }
  piVar3 = UI_ValidateWidgetHierarchy(this,param_1,param_2);
  if (*(int **)((int)this + 0x44) != (int *)0x0) {
    piVar3 = *(int **)((int)this + 0x44);
  }
  if (param_3 < 0) {
    uVar2 = *(uint *)((int)this + 0x5c) | 2;
    *(undefined4 *)((int)this + 0x170) = 0xffffffff;
    *(uint *)((int)this + 0x5c) = uVar2;
  }
  else if (param_3 == 3) {
    uVar2 = *(uint *)((int)this + 0x5c) | 4;
    *(undefined4 *)((int)this + 0x170) = 2;
    *(uint *)((int)this + 0x5c) = uVar2;
  }
  else {
    uVar2 = 0;
    *(undefined4 *)((int)this + 0x170) = 1;
    *(uint *)((int)this + 0x5c) = *(uint *)((int)this + 0x5c) | 1;
  }
  *(int **)((int)this + 0x44) = piVar3;
  if (piVar3 != (int *)0x0) {
    cVar1 = (**(code **)(*piVar3 + 0x3c))();
    if (cVar1 != '\0') {
      UI_Widget_ApplyBlending(this,piVar3);
    }
    uVar2 = (**(code **)(*piVar3 + 0x70))(param_1 - piVar3[2],param_2 - piVar3[3],param_3);
  }
  return CONCAT31((int3)(uVar2 >> 8),1);
}


