/*
 * Function: UI_HandleWidgetResize
 * Address: 004631e0
 * Category: ui
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


undefined4 __thiscall UI_HandleWidgetResize(void *this,int param_1,int param_2)

{
  int *piVar1;
  int *piVar2;
  undefined3 uVar3;
  undefined3 extraout_var;
  int local_c;
  int local_8;
  
  piVar1 = *(int **)((int)this + 0x48);
  piVar2 = *(int **)((int)this + 4);
  *(int **)((int)this + 100) = piVar2;
  *(undefined1 *)((int)this + 0x50) = 1;
  *(int *)((int)this + 0x54) = param_1;
  *(int *)((int)this + 0x58) = param_2;
  if ((piVar1 != (int *)0x0) && (piVar1 != *(int **)((int)this + 0x44))) {
    *(undefined4 *)((int)this + 0x48) = 0;
    piVar2 = (int *)(**(code **)(*piVar1 + 100))();
  }
  piVar1 = *(int **)((int)this + 0x44);
  if (piVar1 != (int *)0x0) {
    (**(code **)(*piVar1 + 0x80))(param_1 - piVar1[2],param_2 - piVar1[3]);
    piVar2 = UI_ValidateWidgetHierarchy(this,param_1,param_2);
    piVar1 = *(int **)((int)this + 0x44);
    if (piVar2 == piVar1) {
      piVar2 = *(int **)((int)this + 0x48);
      if (piVar2 == (int *)0x0) {
        *(int **)((int)this + 0x48) = piVar1;
        piVar2 = (int *)(**(code **)(*piVar1 + 0x60))();
      }
    }
    else {
      piVar1 = *(int **)((int)this + 0x48);
      if (piVar1 != (int *)0x0) {
        *(undefined4 *)((int)this + 0x48) = 0;
        piVar2 = (int *)(**(code **)(*piVar1 + 100))();
      }
    }
  }
  uVar3 = (undefined3)((uint)piVar2 >> 8);
  if (*(char *)((int)this + 0x2c) != '\0') {
    UI_Widget_SetClipRegion(*(void **)((int)this + 0x28),&local_c);
    (**(code **)(**(int **)((int)this + 0x28) + 0x38))(param_1 - local_c,param_2 - local_8);
    uVar3 = extraout_var;
  }
  return CONCAT31(uVar3,1);
}


