/*
 * Function: UI_HandleMouseInput
 * Address: 004601b0
 * Category: ui
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __thiscall UI_HandleMouseInput(void *this,int param_1,int param_2)

{
                    /* WARNING: Load size is inaccurate */
  *(int *)((int)this + 0x84) = param_2;
  *(int *)((int)this + 0x80) = param_1;
  (**(code **)(*this + 0xf0))();
  *(undefined1 *)((int)this + 0x18) = 1;
  return;
}


