/*
 * Function: UI_ProcessChildSpacing
 * Address: 004696a0
 * Category: ui
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall UI_ProcessChildSpacing(undefined4 *param_1,uint param_2)

{
  undefined4 *extraout_ECX;
  undefined4 *puVar1;
  uint extraout_EDX;
  void *pvStack_10;
  undefined4 uStack_c;
  undefined4 uStack_8;
  
  uStack_c = 0x514503;
  pvStack_10 = ExceptionList;
  ExceptionList = &pvStack_10;
  *param_1 = &PTR_UI_UpdateChildStacking_0053260c;
  puVar1 = (undefined4 *)param_1[0x1f];
  uStack_8 = 1;
  if (puVar1 != (undefined4 *)0x0) {
    (**(code **)*puVar1)(1);
    puVar1 = extraout_ECX;
    param_2 = extraout_EDX;
  }
  if (0xf < (uint)param_1[0x1d]) {
                    /* WARNING: Subroutine does not return */
    System_ShutdownHandler((int)puVar1,param_2);
  }
  param_1[0x1d] = 0xf;
  param_1[0x1c] = 0;
  *(undefined1 *)(param_1 + 0x18) = 0;
  UI_UpdateChildMargins(param_1,param_2);
  ExceptionList = pvStack_10;
  return;
}


