/*
 * Function: UI_ProcessChildStyle
 * Address: 00464230
 * Category: ui
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


undefined4 UI_ProcessChildStyle(void)

{
  undefined4 *in_stack_00000010;
  
  *in_stack_00000010 = 0;
  return 0x80004001;
}


