/*
 * Function: UI_ProcessFrameUpdate
 * Address: 00460d40
 * Category: ui
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


undefined4 UI_ProcessFrameUpdate(char param_1)

{
  if ((((param_1 < 'A') || ('Z' < param_1)) && ((param_1 < 'a' || ('z' < param_1)))) &&
     (((param_1 < '0' || ('9' < param_1)) && (param_1 != '_')))) {
    return 0;
  }
  return 1;
}


