/*
 * Function: UI_SetChildProperties
 * Address: 00464010
 * Category: ui
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


undefined4 __thiscall UI_SetChildProperties(void *this,int param_1,int param_2)

{
  undefined4 uVar1;
  
  *(undefined4 *)((int)this + 100) = *(undefined4 *)((int)this + 4);
  if (*(int *)((int)this + 0x5c) != 0) {
    uVar1 = UI_HandleWidgetResize(this,param_1,param_2);
    return uVar1;
  }
  *(undefined1 *)((int)this + 0x50) = 1;
  uVar1 = UI_ProcessWidgetUpdates(this,param_1,param_2);
  return CONCAT31((int3)((uint)uVar1 >> 8),1);
}


