/*
 * Function: UI_SetChildAlignment
 * Address: 00464500
 * Category: ui
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall UI_SetChildAlignment(int param_1)

{
  int *piVar1;
  int local_8;
  
  if (*(undefined4 **)(param_1 + 0x9c) == (undefined4 *)0x0) {
    piVar1 = (int *)0x0;
  }
  else {
    piVar1 = (int *)**(undefined4 **)(param_1 + 0x9c);
  }
  local_8 = param_1;
  if (piVar1 != *(int **)(param_1 + 0x9c)) {
    do {
      if ((undefined4 *)piVar1[2] != (undefined4 *)0x0) {
        (*(code *)**(undefined4 **)piVar1[2])(1);
      }
      piVar1 = (int *)*piVar1;
    } while (piVar1 != (int *)*(int *)(param_1 + 0x9c));
  }
  piVar1 = *(int **)(param_1 + 0x9c);
  if (piVar1 == (int *)0x0) {
    System_ClearTaskQueue((void *)(param_1 + 0x98),&local_8,(int *)0x0,(int *)0x0);
    return;
  }
  System_ClearTaskQueue((void *)(param_1 + 0x98),&local_8,(int *)*piVar1,piVar1);
  return;
}


