/*
 * Function: UI_UpdateWidgetProperties
 * Address: 00460be0
 * Category: ui
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __thiscall UI_UpdateWidgetProperties(void *this,int param_1)

{
  int *piVar1;
  
  piVar1 = *(int **)((int)this + 100);
  if (piVar1 != (int *)0x0) {
    if (param_1 < 0) {
      (**(code **)(*piVar1 + 0xcc))(*(double *)(piVar1 + 0x1c) - *(double *)(piVar1 + 0x20));
      *(undefined4 *)(*(int *)((int)this + 100) + 0x98) = 1;
      *(undefined4 *)(*(int *)((int)this + 100) + 0x9c) = 0;
      return;
    }
    if (0 < param_1) {
      (**(code **)(*piVar1 + 0xcc))(*(double *)(piVar1 + 0x20) + *(double *)(piVar1 + 0x1c));
      *(undefined4 *)(*(int *)((int)this + 100) + 0x98) = 2;
      *(undefined4 *)(*(int *)((int)this + 100) + 0x9c) = 0;
    }
  }
  return;
}


