/*
 * Function: UI_UpdateChildCollision
 * Address: 00467ee0
 * Category: ui
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


undefined4 UI_UpdateChildCollision(void *param_1,int param_2)

{
  short *psVar1;
  int *extraout_ECX;
  int *in_stack_00000018;
  int *piVar2;
  int *extraout_var;
  int *piVar3;
  void *local_10;
  undefined4 uStack_c;
  undefined4 local_8;
  
  local_8 = 0xffffffff;
  uStack_c = 0x514438;
  local_10 = ExceptionList;
  if (param_2 != -0x261) {
    if (param_2 == 0x96) {
      if (((in_stack_00000018[2] == 2) && (psVar1 = (short *)*in_stack_00000018, *psVar1 == 8)) &&
         (psVar1[8] == 8)) {
        ExceptionList = &local_10;
        UI_Widget_ApplyTransform(&stack0xffffffe8,*(int *)(psVar1 + 4));
        local_8 = 0;
        piVar2 = extraout_ECX;
        piVar3 = extraout_var;
        UI_Widget_ApplyTransform(&stack0xffffffe4,*(int *)(*in_stack_00000018 + 0x18));
        local_8 = 0xffffffff;
        UI_ValidateChildCollision(param_1,piVar2,piVar3);
      }
    }
    else if (param_2 != 0x7a6) {
      return 0x80020003;
    }
  }
  ExceptionList = local_10;
  return 0;
}


