/*
 * Function: UI_UpdateChildRelation
 * Address: 00468b50
 * Category: ui
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall UI_UpdateChildRelation(int param_1)

{
  if (*(int **)(param_1 + 0x60) != (int *)0x0) {
    UI_ProcessChildRelation(*(void **)(param_1 + 0x24),*(int **)(param_1 + 0x60),param_1);
  }
  if (*(int **)(param_1 + 100) != (int *)0x0) {
    UI_ProcessChildRelation(*(void **)(param_1 + 0x24),*(int **)(param_1 + 100),param_1);
  }
  return;
}


