/*
 * Function: UI_UpdateChildAlignment
 * Address: 004645a0
 * Category: ui
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __thiscall UI_UpdateChildAlignment(void *this,int *param_1)

{
  int *piVar1;
  undefined4 ***pppuVar2;
  int iVar3;
  int extraout_ECX;
  int extraout_ECX_00;
  uint extraout_EDX;
  uint extraout_EDX_00;
  uint extraout_EDX_01;
  uint uVar4;
  undefined4 *unaff_ESI;
  undefined4 *unaff_EDI;
  undefined8 uVar5;
  uint unaff_retaddr;
  undefined1 local_30 [4];
  undefined4 **local_2c [5];
  uint local_18;
  uint local_14;
  void *local_10;
  undefined4 uStack_c;
  undefined4 local_8;
  
  local_8 = 0xffffffff;
  uStack_c = 0x513f90;
  local_10 = ExceptionList;
  local_14 = DAT_00569f5c ^ unaff_retaddr;
  ExceptionList = &local_10;
  Sound_FormatMessage(local_30,(_String_base *)local_30,param_1);
  local_8 = 0;
  pppuVar2 = (undefined4 ***)local_2c[0];
  if (local_18 < 0x10) {
    pppuVar2 = local_2c;
  }
  UI_Widget_ProcessTransform(&param_1,pppuVar2);
  piVar1 = param_1;
  local_8 = CONCAT31(local_8._1_3_,1);
  if (param_1 == (int *)0x0) {
    iVar3 = 0;
  }
  else {
    iVar3 = *param_1;
  }
  (**(code **)(**(int **)((int)this + 0x70) + 0x58))(*(int **)((int)this + 0x70),iVar3);
  uVar4 = extraout_EDX;
  if (*(int *)((int)this + 0x84) == 0) {
    uVar5 = (**(code **)(**(int **)((int)this + 0x70) + 0x70))(*(int **)((int)this + 0x70));
    uVar4 = (uint)((ulonglong)uVar5 >> 0x20);
    if ((int)uVar5 != 0) {
      iVar3 = extraout_ECX;
      if (piVar1 != (int *)0x0) {
        UI_DrawWidgetContents(piVar1);
        iVar3 = extraout_ECX_00;
      }
      if (0xf < local_18) {
                    /* WARNING: Subroutine does not return */
        System_ShutdownHandler(iVar3,(uint)local_2c[0]);
      }
      goto LAB_00464692;
    }
  }
  iVar3 = *(int *)((int)this + 0x24);
  if ((iVar3 != 0) && (*(char *)((int)this + 0x20) != '\0')) {
                    /* WARNING: Load size is inaccurate */
    (**(code **)(*this + 0x68))
              (*(int *)(iVar3 + 0x54) - *(int *)((int)this + 8),
               *(int *)(iVar3 + 0x58) - *(int *)((int)this + 0xc));
    uVar4 = extraout_EDX_00;
  }
  *(undefined4 *)((int)this + 0x58) = 1;
  if (piVar1 != (int *)0x0) {
    UI_DrawWidgetContents(piVar1);
    uVar4 = extraout_EDX_01;
  }
  if (0xf < local_18) {
                    /* WARNING: Subroutine does not return */
    System_ShutdownHandler((int)local_2c[0],uVar4);
  }
LAB_00464692:
  ExceptionList = local_10;
  Exception_SetMessage((void *)(local_14 ^ unaff_retaddr),unaff_EDI,unaff_ESI);
  return;
}


