/*
 * Function: Campaign_ProcessBossEncounter
 * Address: 0040a110
 * Category: enemies
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


_String_base * __fastcall
Campaign_ProcessBossEncounter
          (undefined4 param_1,uint param_2,_String_base *param_3,int param_4,undefined4 param_5)

{
  Wave_ProcessQuantities(param_5,param_2,param_3,param_4,(_String_base *)param_5);
  return param_3 + param_4 * 0x30;
}


