/*
 * Function: Campaign_ProcessLoseCondition
 * Address: 0041e260
 * Category: enemies
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


int * __cdecl
Campaign_ProcessLoseCondition(int *param_1,undefined4 param_2,uint param_3,_String_base *param_4)

{
  Campaign_ProcessRegionUnlock
            (param_2,param_3,param_1,(_String_base *)param_2,(_String_base *)param_3,param_4);
  return param_1;
}


