/*
 * Function: Campaign_ProcessBriefing
 * Address: 0041dcb0
 * Category: enemies
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall Campaign_ProcessBriefing(int *param_1)

{
  if (*(char *)((int)param_1 + 0x1e) != '\0') {
    UI_ProcessChildAnimation(*(void **)(param_1[0x17] + 0x2dc),param_1);
    (**(code **)(*(int *)param_1[0x17] + 0x78))(param_1);
  }
  *(undefined1 *)((int)param_1 + 0x1e) = 1;
  return;
}


