/*
 * Function: Campaign_ProcessIntelBriefing
 * Address: 0041e160
 * Category: enemies
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


_String_base * __fastcall
Campaign_ProcessIntelBriefing
          (undefined4 param_1,uint param_2,_String_base *param_3,_String_base *param_4,
          _String_base *param_5)

{
  uint extraout_EDX;
  void *pvStack_10;
  undefined *puStack_c;
  undefined1 local_8;
  undefined3 uStack_7;
  
  puStack_c = &DAT_00510bb1;
  pvStack_10 = ExceptionList;
  uStack_7 = 0;
  ExceptionList = &pvStack_10;
  for (; param_3 != param_4; param_3 = param_3 + 0x20) {
    local_8 = 1;
    if (param_5 != (_String_base *)0x0) {
      *(undefined4 *)(param_5 + 0x18) = 0xf;
      *(undefined4 *)(param_5 + 0x14) = 0;
      param_5[4] = (_String_base)0x0;
      PowerUp_ProcessThunderstrike(param_5,param_2,param_3,0,0xffffffff);
      *(undefined4 *)(param_5 + 0x1c) = *(undefined4 *)(param_3 + 0x1c);
      param_2 = extraout_EDX;
    }
    param_5 = param_5 + 0x20;
  }
  ExceptionList = pvStack_10;
  return param_5;
}


