/*
 * Function: Craft_ProcessSatellite
 * Address: 00433aa0
 * Category: enemies
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall Craft_ProcessSatellite(undefined4 *param_1)

{
  *param_1 = &PTR_UI_InitializeMainMenu_00530390;
  *(int *)(param_1[0x13] + 0x7c) = *(int *)(param_1[0x13] + 0x7c) - *(int *)(param_1[0x14] + 0x12f0)
  ;
  Boss_ProcessBattleship(param_1);
  return;
}


