/*
 * Function: Craft_ProcessMedCopter
 * Address: 004333e0
 * Category: enemies
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __fastcall Craft_ProcessMedCopter(int param_1)

{
  double dVar1;
  int iVar2;
  ulonglong uVar3;
  undefined4 uVar4;
  undefined4 uVar5;
  undefined4 uVar6;
  undefined4 uVar7;
  undefined1 uVar8;
  
  Boss_ProcessWreckerWarWrecker(param_1);
  if (0 < *(int *)(param_1 + 0x70)) {
    *(int *)(param_1 + 0x70) = *(int *)(param_1 + 0x70) + -1;
  }
  if ((((_DAT_005301f8 < *(double *)(param_1 + 8)) &&
       (*(double *)(param_1 + 8) < _DAT_005301f0 !=
        (NAN(*(double *)(param_1 + 8)) || NAN(_DAT_005301f0)))) &&
      (*(int *)(*(int *)(param_1 + 0x4c) + 0x80) == 0)) &&
     ((iVar2 = Collision_HandleEnemyHit(), iVar2 % 0x28 == 0 && (*(int *)(param_1 + 0x70) == 0)))) {
    uVar8 = *(undefined1 *)(param_1 + 0x30);
    uVar7 = *(undefined4 *)(param_1 + 0x24);
    uVar6 = *(undefined4 *)(param_1 + 0x20);
    uVar5 = *(undefined4 *)(param_1 + 0x1c);
    uVar4 = *(undefined4 *)(param_1 + 0x18);
    Boss_ProcessEyebot(param_1);
    uVar3 = Math_FloatToUInt64();
    iVar2 = (int)uVar3;
    uVar3 = Math_FloatToUInt64();
    SexyAppFramework_ProcessMessages
              (*(void **)(param_1 + 0x4c),(int)uVar3,iVar2,uVar4,uVar5,uVar6,uVar7,uVar8);
    *(undefined4 *)(param_1 + 0x70) = 0x4b;
  }
  iVar2 = Boss_ProcessApeKommieKong(param_1);
  if (((double)(-0x140 - iVar2 / 2) <= *(double *)(param_1 + 8)) &&
     (iVar2 = Boss_ProcessApeKommieKong(param_1), dVar1 = (double)(iVar2 / 2 + 0x140),
     dVar1 < *(double *)(param_1 + 8) == (NAN(dVar1) || NAN(*(double *)(param_1 + 8))))) {
    return;
  }
  Boss_BattleshipCannonSystem(param_1);
  return;
}


