/*
 * Function: Enemy_ProcessHelicopterLogic
 * Address: 00403080
 * Category: enemies
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


undefined4 * Enemy_ProcessHelicopterLogic(undefined4 *param_1,int param_2,undefined4 *param_3)

{
  Vector_Constructor_4ByteObjects(param_1,param_2,param_3);
  return param_1 + param_2 * 9;
}


