/*
 * Function: Enemy_RenderWithEffects
 * Address: 0042da00
 * Category: enemies
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


undefined4 * __thiscall Enemy_RenderWithEffects(void *this,int param_1,int param_2,int param_3)

{
  undefined4 uVar1;
  undefined4 *puVar2;
  int iVar3;
  
  *(int *)((int)this + 4) = param_1;
  *(undefined4 *)this = *(undefined4 *)(param_1 + 0x5c);
  *(double *)((int)this + 0x28) = (double)*(int *)(param_1 + 0x1a8);
  *(double *)((int)this + 8) = (double)param_2;
  iVar3 = (int)((ulonglong)((longlong)param_2 * 0x77777777) >> 0x20) - param_2;
  *(undefined4 *)((int)this + 0x20) = 0;
  *(double *)((int)this + 0x10) = (double)param_3;
  *(undefined4 *)((int)this + 0x24) = 0;
  *(undefined1 *)((int)this + 0x30) = 0;
  *(double *)((int)this + 0x18) = (double)((iVar3 >> 6) - (iVar3 >> 0x1f));
  puVar2 = (undefined4 *)operator_new(0xc);
  uVar1 = *(undefined4 *)(param_1 + 0x27c);
  puVar2[1] = 0;
  puVar2[2] = uVar1;
  *(undefined4 **)(*(int *)(param_1 + 0x27c) + 4) = puVar2;
  *puVar2 = this;
  *(undefined4 **)(param_1 + 0x27c) = puVar2;
  *(int *)(param_1 + 0x280) = *(int *)(param_1 + 0x280) + 1;
  *(undefined4 **)((int)this + 0x34) = puVar2;
  return (undefined4 *)this;
}


