/*
 * Function: Particles_UpdateBulletTrails
 * Address: 0041acd0
 * Category: enemies
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __thiscall
Particles_UpdateBulletTrails(void *this,undefined4 param_1,undefined4 param_2,int param_3)

{
  int iVar1;
  ulonglong uVar2;
  
  if (((*(int *)((int)this + 0x300) == 0) &&
      (*(int *)((int)this + 0x17c) <= *(int *)((int)this + 0x184))) ||
     (*(char *)((int)this + 0x327) != '\0')) {
    *(undefined4 *)((int)this + 0x60) = param_1;
    *(undefined4 *)((int)this + 100) = param_2;
    if (param_3 == 0) {
      *(undefined4 *)((int)this + 0x1d8) = 0;
      *(undefined1 *)((int)this + 0x128) = 1;
      if (*(int *)((int)this + 300) != 0) {
        iVar1 = **(int **)((int)this + 0x5c);
        uVar2 = Math_FloatToUInt64();
        (**(code **)(iVar1 + 0xb8))(0x2f,(int)uVar2);
        return;
      }
    }
    else if (param_3 == 1) {
      if ((((NAN(*(double *)((int)this + 0x88)) || NAN(_DAT_0052a0c0)) !=
            (*(double *)((int)this + 0x88) == _DAT_0052a0c0)) && (*(int *)((int)this + 0x80) == 0))
         && (0 < *(int *)(*(int *)((int)this + 0x5c) + 0x968))) {
        Particles_UpdateExplosions(this);
        return;
      }
      (**(code **)(**(int **)((int)this + 0x5c) + 0xb8))(0x15,0);
      if ((*(int *)(*(int *)((int)this + 0x5c) + 0x968) == 0) && (*(int *)((int)this + 0x80) == 0))
      {
        *(undefined4 *)((int)this + 0x1dc) = 0xfa;
      }
    }
  }
  return;
}


