/*
 * Function: UI_ProcessChildConstraints
 * Address: 004680d0
 * Category: enemies
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


int __thiscall UI_ProcessChildConstraints(void *this,int param_1)

{
  undefined4 *puVar1;
  undefined4 *puVar2;
  uint uVar3;
  int iVar4;
  undefined4 uVar5;
  uint uVar6;
  
  if (this == (void *)param_1) {
    return (int)this;
  }
  puVar1 = *(undefined4 **)(param_1 + 4);
  if ((puVar1 == (undefined4 *)0x0) ||
     (uVar3 = *(int *)(param_1 + 8) - (int)puVar1 >> 4, uVar3 == 0)) {
    if (*(int *)((int)this + 4) != 0) {
                    /* WARNING: Subroutine does not return */
      System_ShutdownHandler((int)this,(uint)puVar1);
    }
    *(undefined4 *)((int)this + 4) = 0;
    *(undefined4 *)((int)this + 8) = 0;
    *(undefined4 *)((int)this + 0xc) = 0;
    return (int)this;
  }
  puVar2 = *(undefined4 **)((int)this + 4);
  if (puVar2 == (undefined4 *)0x0) {
    uVar6 = 0;
  }
  else {
    uVar6 = *(int *)((int)this + 8) - (int)puVar2 >> 4;
  }
  if (uVar3 <= uVar6) {
    UI_InitializeWidgetRenderer(puVar1,*(undefined4 **)(param_1 + 8),puVar2);
    if (*(int *)(param_1 + 4) == 0) {
      *(undefined4 *)((int)this + 8) = *(undefined4 *)((int)this + 4);
      return (int)this;
    }
    *(int *)((int)this + 8) =
         (*(int *)(param_1 + 8) - *(int *)(param_1 + 4) >> 4) * 0x10 + *(int *)((int)this + 4);
    return (int)this;
  }
  if (puVar2 == (undefined4 *)0x0) {
    uVar6 = 0;
  }
  else {
    uVar6 = *(int *)((int)this + 0xc) - (int)puVar2 >> 4;
  }
  if (uVar3 <= uVar6) {
    if (puVar2 == (undefined4 *)0x0) {
      iVar4 = 0;
    }
    else {
      iVar4 = *(int *)((int)this + 8) - (int)puVar2 >> 4;
    }
    UI_ProcessChildEvents(puVar1,puVar1 + iVar4 * 4,puVar2);
    uVar5 = Vector_IsEqual(puVar1 + iVar4 * 4,*(undefined4 **)(param_1 + 8),
                           *(undefined4 **)((int)this + 8));
    *(undefined4 *)((int)this + 8) = uVar5;
    return (int)this;
  }
                    /* WARNING: Subroutine does not return */
  System_ShutdownHandler((int)puVar2,(uint)puVar1);
}


