/*
 * Function: Animation_ProcessBlastnyaExplosions
 * Address: 004305b0
 * Category: animation
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


undefined4 * __fastcall
Animation_ProcessBlastnyaExplosions(undefined4 *param_1,uint param_2,byte param_3)

{
  int extraout_ECX;
  uint extraout_EDX;
  
  Level_InitializeKillingrad(param_1,param_2);
  if ((param_3 & 1) != 0) {
                    /* WARNING: Subroutine does not return */
    System_ShutdownHandler(extraout_ECX,extraout_EDX);
  }
  return param_1;
}


