/*
 * Function: Game_ErrorReporter_Destructor
 * Address: 004ad700
 * Category: core
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall Game_ErrorReporter_Destructor(undefined4 *param_1)

{
  int extraout_ECX;
  undefined4 local_18;
  undefined4 *local_14;
  void *pvStack_10;
  undefined4 uStack_c;
  undefined4 local_8;
  
  uStack_c = 0x516783;
  pvStack_10 = ExceptionList;
  ExceptionList = &pvStack_10;
  *param_1 = &PTR_ErrorReporter_Destructor_005363bc;
  local_8 = 4;
  local_14 = param_1;
  if (param_1[6] != 0) {
    Level_InitializeTankylvania((int)param_1);
    DestroyWindow((HWND)param_1[6]);
    param_1[6] = 0;
  }
  DeleteObject((HGDIOBJ)param_1[2]);
  DeleteObject((HGDIOBJ)param_1[3]);
  DeleteObject((HGDIOBJ)param_1[4]);
  Level_InitializeTankylvania((int)param_1);
  STL_Map_EraseConditional(param_1 + 0x67,&local_18,*(int **)param_1[0x68],(int *)param_1[0x68]);
                    /* WARNING: Subroutine does not return */
  System_ShutdownHandler(extraout_ECX,param_1[0x68]);
}


