/*
 * Function: GameState_CopyConstructor
 * Address: 004a5400
 * Category: core
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


undefined4 * __thiscall GameState_CopyConstructor(void *this,undefined4 *param_1)

{
  uint extraout_EDX;
  void *local_10;
  undefined *puStack_c;
  undefined4 local_8;
  
  local_8 = 0xffffffff;
  puStack_c = &DAT_00515ba6;
  local_10 = ExceptionList;
  ExceptionList = &local_10;
  *(undefined4 *)this = *param_1;
  *(undefined4 *)((int)this + 4) = param_1[1];
  *(undefined4 *)((int)this + 8) = param_1[2];
  List_CopyConstructor((void *)((int)this + 0xc),(int)(param_1 + 3));
  *(undefined1 *)((int)this + 0x18) = *(undefined1 *)(param_1 + 6);
  *(undefined1 *)((int)this + 0x19) = *(undefined1 *)((int)param_1 + 0x19);
  *(undefined1 *)((int)this + 0x1a) = *(undefined1 *)((int)param_1 + 0x1a);
  *(undefined1 *)((int)this + 0x1b) = *(undefined1 *)((int)param_1 + 0x1b);
  *(undefined4 *)((int)this + 0x34) = 0xf;
  *(undefined4 *)((int)this + 0x30) = 0;
  local_8 = 0;
  *(undefined1 *)((int)this + 0x20) = 0;
  PowerUp_ProcessThunderstrike
            ((_String_base *)((int)this + 0x1c),(uint)(param_1 + 7),(_String_base *)(param_1 + 7),0,
             0xffffffff);
  *(undefined4 *)((int)this + 0x50) = 0xf;
  *(undefined4 *)((int)this + 0x4c) = 0;
  local_8 = CONCAT31(local_8._1_3_,1);
  *(undefined1 *)((int)this + 0x3c) = 0;
  PowerUp_ProcessThunderstrike
            ((_String_base *)((int)this + 0x38),extraout_EDX,(_String_base *)(param_1 + 0xe),0,
             0xffffffff);
  ExceptionList = local_10;
  return (undefined4 *)this;
}


