/*
 * Function: Game_MainRenderingSystem
 * Address: 00415530
 * Category: core
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __thiscall Game_MainRenderingSystem(void *this,undefined4 *param_1)

{
  double dVar1;
  _String_base _Var2;
  undefined4 *this_00;
  char *pcVar3;
  undefined4 *puVar4;
  undefined4 uVar5;
  _String_base *p_Var6;
  double *pdVar7;
  char *pcVar8;
  int extraout_ECX;
  int *piVar9;
  int extraout_ECX_00;
  undefined1 *puVar10;
  uint extraout_EDX;
  uint extraout_EDX_00;
  float10 fVar11;
  ulonglong uVar12;
  ulonglong uVar13;
  int iVar14;
  char cVar15;
  int iVar16;
  int iVar17;
  undefined4 uVar18;
  int iVar19;
  undefined4 uVar20;
  char cVar21;
  undefined1 local_c4 [8];
  undefined4 local_bc;
  undefined4 local_b4;
  undefined4 local_ac;
  undefined1 local_a4 [4];
  uint local_a0;
  undefined1 local_98 [8];
  undefined4 local_90;
  uint local_8c;
  undefined4 local_88 [5];
  undefined4 local_74;
  int local_70;
  undefined4 local_6c;
  int local_68;
  undefined4 local_64;
  undefined8 local_60;
  undefined1 local_58 [4];
  uint local_54;
  undefined1 local_4c [8];
  undefined4 local_44;
  uint local_40;
  int local_3c;
  double local_38;
  undefined8 local_30;
  int local_28 [4];
  undefined8 local_18;
  void *local_10;
  undefined *puStack_c;
  undefined4 local_8;
  
  this_00 = param_1;
  local_8 = 0xffffffff;
  puStack_c = &DAT_00510563;
  local_10 = ExceptionList;
  ExceptionList = &local_10;
  if ((NAN(*(double *)((int)this + 0x88)) || NAN(_DAT_0052a0c0)) ==
      (*(double *)((int)this + 0x88) == _DAT_0052a0c0)) {
    ExceptionList = &local_10;
    SexyWidget_SetColorizeFlag2(param_1,1);
    uVar12 = Math_FloatToUInt64();
    puVar4 = (undefined4 *)CreateColor(local_28,0xff,(int)uVar12,(int)uVar12,0xff);
    SexyWidget_SetRectangle(param_1,puVar4);
  }
  uVar5 = Compression_GetCompressedSize(*(int *)((int)this + 0x5c));
  cVar21 = '\0';
  if ((char)uVar5 == '\0') {
    iVar19 = 0;
    iVar16 = 0;
    cVar15 = '\0';
    iVar14 = 0;
    uVar12 = Math_FloatToUInt64();
    DrawSprite(*(void **)(*(int *)((int)this + 0x5c) + 0x6b8),param_1,(int)uVar12,iVar14,cVar15,
               iVar16,iVar19,cVar21);
    cVar15 = '\0';
    iVar19 = 0;
    iVar16 = 0;
    cVar21 = '\0';
    iVar14 = 0;
    uVar12 = Math_FloatToUInt64();
    DrawSprite(*(void **)(*(int *)((int)this + 0x5c) + 0x6b8),param_1,(int)uVar12,iVar14,cVar21,
               iVar16,iVar19,cVar15);
  }
  else {
    Graphics_ProcessImageBlend
              (param_1,*(int *)(*(int *)(*(int *)((int)this + 0x5c) + 0x6b8) + 8),
               *(float *)((int)this + 0x6c),0.0);
    Graphics_ProcessImageBlend
              (param_1,*(int *)(*(int *)(*(int *)((int)this + 0x5c) + 0x6b8) + 8),
               *(float *)((int)this + 0x6c) + _DAT_0052c598,0.0);
  }
  iVar14 = GetBossIndex(*(void **)((int)this + 0x5c),
                        *(int *)((int)*(void **)((int)this + 0x5c) + 0x960));
  if (iVar14 == 5) {
    DrawSprite(*(void **)(*(int *)((int)this + 0x5c) + 0x87c),param_1,200,0xa0,'\x01',0,0,'\0');
  }
  if ((*(int *)((int)this + 800) != 0) &&
     (dVar1 = *(double *)(*(int *)((int)this + 0x5c) + 0xb28),
     (NAN(dVar1) || NAN(_DAT_0052a0c0)) == (dVar1 == _DAT_0052a0c0))) {
    uVar5 = Compression_GetCompressedSize(*(int *)((int)this + 0x5c));
    piVar9 = *(int **)((int)this + 800);
    if ((char)uVar5 == '\0') {
      cVar15 = '\0';
      iVar19 = 0;
      uVar12 = Math_FloatToUInt64();
      iVar16 = (int)uVar12;
      iVar14 = piVar9[8];
      cVar21 = '\0';
      uVar12 = Math_FloatToUInt64();
      DrawSprite((void *)*piVar9,param_1,(int)uVar12,iVar14,cVar21,iVar16,iVar19,cVar15);
    }
    else {
      iVar14 = *(int *)(*piVar9 + 0x10);
      local_30 = (double)CONCAT44(*(undefined4 *)(*piVar9 + 0x14),(undefined4)local_30);
      uVar12 = Math_FloatToUInt64();
      local_28[0] = (int)uVar12 * iVar14;
      local_28[1] = 0;
      local_28[3] = local_30._4_4_;
      local_28[2] = iVar14;
      SexyWidget_DrawImage2
                (param_1,*(undefined4 *)(*piVar9 + 8),(float)*(double *)(piVar9 + 6),
                 (float)piVar9[8],local_28);
    }
  }
  *(undefined4 *)((int)this + 0x218) = *(undefined4 *)((int)this + 0x214);
  SexyWidget_Translate(param_1,0x140,0);
  while (iVar14 = *(int *)(*(int *)((int)this + 0x218) + 4), iVar14 != 0) {
    *(int *)((int)this + 0x218) = iVar14;
    if (*(int *)((int)this + 0x220) == 0) {
      iVar14 = 0;
    }
    else {
      iVar14 = **(int **)((int)this + 0x218);
    }
    if (*(char *)(iVar14 + 0x55) != '\0') {
      if (*(int *)((int)this + 0x220) == 0) {
        (*(code *)_DAT_00000000[1])(param_1);
      }
      else {
        (**(code **)(*(int *)**(undefined4 **)((int)this + 0x218) + 4))(param_1);
      }
    }
  }
  SexyWidget_Translate(param_1,-0x140,0);
  uVar5 = Compression_GetCompressedSize(*(int *)((int)this + 0x5c));
  if ((char)uVar5 == '\0') {
    iVar14 = *(int *)((int)this + 0x5c);
    if (_DAT_0052a0c0 < *(double *)(iVar14 + 0xb28)) {
      cVar15 = '\0';
      iVar17 = 0;
      iVar19 = 0;
      cVar21 = '\0';
      iVar16 = 0xb4;
      uVar12 = Math_FloatToUInt64();
      DrawSprite(*(void **)(iVar14 + 0x6c0),param_1,(int)uVar12,iVar16,cVar21,iVar19,iVar17,cVar15);
      cVar15 = '\0';
      iVar19 = 0;
      iVar16 = 0;
      cVar21 = '\0';
      iVar14 = 0xb4;
      uVar12 = Math_FloatToUInt64();
      DrawSprite(*(void **)(*(int *)((int)this + 0x5c) + 0x6c0),param_1,(int)uVar12 + 0x3c0,iVar14,
                 cVar21,iVar16,iVar19,cVar15);
    }
  }
  else if (_DAT_0052a0c0 < *(double *)(*(int *)((int)this + 0x5c) + 0xb28)) {
    Graphics_ProcessImageBlend
              (param_1,*(int *)(*(int *)(*(int *)((int)this + 0x5c) + 0x6c0) + 8),
               *(float *)((int)this + 0x78),180.0);
    Graphics_ProcessImageBlend
              (param_1,*(int *)(*(int *)(*(int *)((int)this + 0x5c) + 0x6c0) + 8),
               *(float *)((int)this + 0x78) + _DAT_0052c760,180.0);
  }
  if ((*(int *)((int)this + 0x31c) != 0) &&
     (dVar1 = *(double *)(*(int *)((int)this + 0x5c) + 0xb28),
     (NAN(dVar1) || NAN(_DAT_0052a0c0)) == (dVar1 == _DAT_0052a0c0))) {
    uVar5 = Compression_GetCompressedSize(*(int *)((int)this + 0x5c));
    piVar9 = *(int **)((int)this + 0x31c);
    if ((char)uVar5 == '\0') {
      cVar15 = '\0';
      iVar19 = 0;
      uVar12 = Math_FloatToUInt64();
      iVar16 = (int)uVar12;
      iVar14 = piVar9[8];
      cVar21 = '\0';
      uVar12 = Math_FloatToUInt64();
      DrawSprite((void *)*piVar9,param_1,(int)uVar12,iVar14,cVar21,iVar16,iVar19,cVar15);
    }
    else {
      iVar14 = *(int *)(*piVar9 + 0x10);
      local_30 = (double)CONCAT44(*(undefined4 *)(*piVar9 + 0x14),(undefined4)local_30);
      uVar12 = Math_FloatToUInt64();
      local_28[0] = (int)uVar12 * iVar14;
      local_28[1] = 0;
      local_28[3] = local_30._4_4_;
      local_28[2] = iVar14;
      SexyWidget_DrawImage2
                (param_1,*(undefined4 *)(*piVar9 + 8),(float)*(double *)(piVar9 + 6),
                 (float)piVar9[8],local_28);
    }
  }
  SexyWidget_Translate(param_1,0x140,0);
  *(undefined4 *)((int)this + 0x268) = *(undefined4 *)((int)this + 0x264);
  while (iVar14 = *(int *)(*(int *)((int)this + 0x268) + 4), iVar14 != 0) {
    *(int *)((int)this + 0x268) = iVar14;
    if (*(int *)((int)this + 0x270) == 0) {
      Settings_ProcessAntiAliasingOptions((void *)0x0,param_1);
    }
    else {
      Settings_ProcessAntiAliasingOptions((void *)**(undefined4 **)((int)this + 0x268),param_1);
    }
  }
  SexyWidget_Translate(param_1,-0x140,0);
  if ((NAN(*(double *)((int)this + 0x88)) || NAN(_DAT_0052a0c0)) ==
      (*(double *)((int)this + 0x88) == _DAT_0052a0c0)) {
    SexyWidget_SetColorizeFlag2(param_1,1);
    uVar12 = Math_FloatToUInt64();
    puVar4 = (undefined4 *)CreateColor(local_28,0xff,(int)uVar12,(int)uVar12,0xff);
    SexyWidget_SetRectangle(param_1,puVar4);
  }
  uVar5 = Compression_GetCompressedSize(*(int *)((int)this + 0x5c));
  if ((char)uVar5 == '\0') {
    cVar15 = '\0';
    iVar19 = 0;
    iVar16 = 0;
    cVar21 = '\0';
    iVar14 = 0xb4;
    uVar12 = Math_FloatToUInt64();
    DrawSprite(*(void **)(*(int *)((int)this + 0x5c) + 0x6bc),param_1,(int)uVar12,iVar14,cVar21,
               iVar16,iVar19,cVar15);
    cVar15 = '\0';
    iVar19 = 0;
    iVar16 = 0;
    cVar21 = '\0';
    iVar14 = 0xb4;
    uVar12 = Math_FloatToUInt64();
    DrawSprite(*(void **)(*(int *)((int)this + 0x5c) + 0x6bc),param_1,(int)uVar12 + 0x3c0,iVar14,
               cVar21,iVar16,iVar19,cVar15);
  }
  else {
    Graphics_ProcessImageBlend
              (param_1,*(int *)(*(int *)(*(int *)((int)this + 0x5c) + 0x6bc) + 8),
               *(float *)((int)this + 0x74),180.0);
    Graphics_ProcessImageBlend
              (param_1,*(int *)(*(int *)(*(int *)((int)this + 0x5c) + 0x6bc) + 8),
               *(float *)((int)this + 0x74) + _DAT_0052c760,180.0);
  }
  if ((*(int *)((int)this + 0x318) != 0) &&
     (dVar1 = *(double *)(*(int *)((int)this + 0x5c) + 0xb28),
     (NAN(dVar1) || NAN(_DAT_0052a0c0)) == (dVar1 == _DAT_0052a0c0))) {
    uVar5 = Compression_GetCompressedSize(*(int *)((int)this + 0x5c));
    piVar9 = *(int **)((int)this + 0x318);
    if ((char)uVar5 == '\0') {
      cVar15 = '\0';
      iVar19 = 0;
      uVar12 = Math_FloatToUInt64();
      iVar16 = (int)uVar12;
      iVar14 = piVar9[8];
      cVar21 = '\0';
      uVar12 = Math_FloatToUInt64();
      DrawSprite((void *)*piVar9,param_1,(int)uVar12,iVar14,cVar21,iVar16,iVar19,cVar15);
    }
    else {
      iVar14 = *(int *)(*piVar9 + 0x10);
      local_30 = (double)CONCAT44(*(undefined4 *)(*piVar9 + 0x14),(undefined4)local_30);
      uVar12 = Math_FloatToUInt64();
      local_28[0] = (int)uVar12 * iVar14;
      local_28[1] = 0;
      local_28[3] = local_30._4_4_;
      local_28[2] = iVar14;
      SexyWidget_DrawImage2
                (param_1,*(undefined4 *)(*piVar9 + 8),(float)*(double *)(piVar9 + 6),
                 (float)piVar9[8],local_28);
    }
  }
  SexyWidget_SetColorizeFlag2(param_1,0);
  if ((NAN(*(double *)((int)this + 0x88)) || NAN(_DAT_0052a0c0)) ==
      (*(double *)((int)this + 0x88) == _DAT_0052a0c0)) {
    SexyWidget_SetColorizeFlag2(param_1,1);
    uVar12 = Math_FloatToUInt64();
    puVar4 = (undefined4 *)CreateColor(local_28,0xff,(int)uVar12,(int)uVar12,0xff);
    SexyWidget_SetRectangle(param_1,puVar4);
  }
  if ((*(int *)((int)this + 0x1c4) < 0) && (*(char *)((int)this + 0x327) == '\0')) {
    DrawSprite(*(void **)(*(int *)((int)this + 0x5c) + 0x82c),param_1,
               *(int *)((int)this + 0x1c4) + 0x280,0x15e,'\0',0,0,'\0');
    iVar14 = (*(int *)((int)this + 0x184) - *(int *)((int)this + 0x17c)) / 5000;
    if ((iVar14 < 5) && (-1 < iVar14)) {
      DrawSprite(*(void **)(*(int *)((int)this + 0x5c) + 0x830),param_1,
                 *(int *)((int)this + 0x1c4) + 0x28a,0x174,'\0',iVar14,0,'\0');
    }
  }
  cVar15 = '\0';
  iVar19 = 0;
  iVar16 = 0;
  cVar21 = '\0';
  iVar14 = 0x1a4;
  uVar12 = Math_FloatToUInt64();
  DrawSprite(*(void **)(*(int *)((int)this + 0x5c) + 0x6c8),param_1,(int)uVar12,iVar14,cVar21,iVar16
             ,iVar19,cVar15);
  cVar15 = '\0';
  iVar19 = 0;
  iVar16 = 0;
  cVar21 = '\0';
  iVar14 = 0x1a4;
  uVar12 = Math_FloatToUInt64();
  DrawSprite(*(void **)(*(int *)((int)this + 0x5c) + 0x6c8),param_1,(int)uVar12,iVar14,cVar21,iVar16
             ,iVar19,cVar15);
  SexyAppFramework_ProcessWindowMessages(this,param_1,0);
  SexyWidget_Translate(param_1,0x140,0);
  if (*(double *)((int)this + 400) < _DAT_0052c578 !=
      (NAN(*(double *)((int)this + 400)) || NAN(_DAT_0052c578))) {
    cVar15 = '\0';
    iVar19 = 0;
    iVar16 = 0;
    cVar21 = '\x01';
    iVar14 = 0x195;
    uVar12 = Math_FloatToUInt64();
    DrawSprite(*(void **)(*(int *)((int)this + 0x5c) + 0x748),param_1,(int)uVar12,iVar14,cVar21,
               iVar16,iVar19,cVar15);
    Graphics_SetProjection(param_1,*(undefined4 *)(*(int *)((int)this + 0x5c) + 0x930));
    puVar4 = (undefined4 *)CreateColor(local_28,0xff,0xff,0xff,0xff);
    SexyWidget_SetRectangle(param_1,puVar4);
    local_8c = 0xf;
    local_90 = 0;
    local_a0 = local_a0 & 0xffffff00;
    iVar14 = *(int *)((int)this + 0x198) * 0x14;
    p_Var6 = (_String_base *)("?NUKE n GO" + iVar14 + 1);
    do {
      _Var2 = *p_Var6;
      p_Var6 = p_Var6 + 1;
    } while (_Var2 != (_String_base)0x0);
    String_Assign(local_a4,(_String_base *)("?NUKE n GO" + iVar14 + 1),
                  (int)p_Var6 - (int)("?NUKE n GO" + iVar14 + 2));
    local_8 = 0;
    local_44 = 0;
    local_54 = local_54 & 0xffffff00;
    local_40 = 0xf;
    iVar14 = *(int *)((int)this + 0x198) * 0x14;
    p_Var6 = (_String_base *)("?NUKE n GO" + iVar14 + 1);
    do {
      _Var2 = *p_Var6;
      p_Var6 = p_Var6 + 1;
    } while (_Var2 != (_String_base)0x0);
    String_Assign(local_58,(_String_base *)("?NUKE n GO" + iVar14 + 1),
                  (int)p_Var6 - (int)("?NUKE n GO" + iVar14 + 2));
    puVar10 = local_a4;
    local_8 = CONCAT31(local_8._1_3_,1);
    iVar14 = SexyWidget_CallInterface((int)param_1);
    uVar12 = Math_FloatToUInt64();
    SexyWidget_DrawWithInterface(param_1,local_58,(int)uVar12 - iVar14 / 2,puVar10);
    if (0xf < local_40) {
                    /* WARNING: Subroutine does not return */
      System_ShutdownHandler(extraout_ECX,local_54);
    }
    local_40 = 0xf;
    local_44 = 0;
    local_54 = local_54 & 0xffffff00;
    local_8 = 0xffffffff;
    if (0xf < local_8c) {
                    /* WARNING: Subroutine does not return */
      System_ShutdownHandler(extraout_ECX,extraout_EDX);
    }
    cVar15 = '\0';
    iVar19 = 0;
    iVar16 = 0;
    cVar21 = '\x01';
    iVar14 = 0x15e;
    uVar12 = Math_FloatToUInt64();
    DrawSprite(*(void **)(*(int *)((int)this + 0x5c) + 0x74c),param_1,(int)uVar12 + -0x87,iVar14,
               cVar21,iVar16,iVar19,cVar15);
  }
  *(undefined4 *)((int)this + 600) = *(undefined4 *)((int)this + 0x254);
  while (iVar14 = *(int *)(*(int *)((int)this + 600) + 4), iVar14 != 0) {
    *(int *)((int)this + 600) = iVar14;
    if (*(int *)((int)this + 0x260) == 0) {
      pdVar7 = (double *)0x0;
    }
    else {
      pdVar7 = (double *)**(undefined4 **)((int)this + 600);
    }
    if (pdVar7[1] - *pdVar7 < _DAT_0052c758 != (NAN(pdVar7[1] - *pdVar7) || NAN(_DAT_0052c758))) {
      local_28[0] = 0;
      local_28[1] = 0;
      uVar12 = Math_FloatToUInt64();
      local_28[3] = 0x11;
      local_28[2] = (int)uVar12;
      uVar13 = Math_FloatToUInt64();
      local_68 = (int)uVar13;
      local_64 = 0x1c7;
      local_60 = (double)CONCAT44(0x11,(int)uVar12);
      Graphics_SetImageAlpha
                (param_1,*(undefined4 *)(*(int *)(*(int *)((int)this + 0x5c) + 0x744) + 8),
                 (int)&local_68,local_28);
    }
  }
  *(undefined4 *)((int)this + 0x228) = *(undefined4 *)((int)this + 0x224);
  SexyWidget_SetColorizeFlag2(param_1,1);
  while (iVar14 = *(int *)(*(int *)((int)this + 0x228) + 4), iVar14 != 0) {
    *(int *)((int)this + 0x228) = iVar14;
    if (*(int *)((int)this + 0x230) == 0) {
      iVar14 = 0;
    }
    else {
      iVar14 = **(int **)((int)this + 0x228);
    }
    if (*(int *)(iVar14 + 8) < 0x200) {
      puVar4 = (undefined4 *)CreateColor(local_28,0xff,0xff,0xff,*(int *)(iVar14 + 8) / 2);
    }
    else {
      puVar4 = (undefined4 *)SexyWidget_ApplyMatrix(&local_68,0xff,0xff,0xff);
    }
    SexyWidget_SetRectangle(param_1,puVar4);
    iVar14 = *(int *)(iVar14 + 0xc);
    cVar15 = '\0';
    iVar19 = 0;
    cVar21 = '\x01';
    iVar16 = 0x1cc;
    uVar12 = Math_FloatToUInt64();
    DrawSprite(*(void **)(*(int *)((int)this + 0x5c) + 0x6f0),param_1,(int)uVar12,iVar16,cVar21,
               iVar14,iVar19,cVar15);
  }
  *(undefined4 *)((int)this + 0x2d8) = *(undefined4 *)((int)this + 0x2d4);
  SexyWidget_SetDrawMode(param_1,1);
  while (iVar14 = *(int *)(*(int *)((int)this + 0x2d8) + 4), iVar14 != 0) {
    *(int *)((int)this + 0x2d8) = iVar14;
    if (*(int *)((int)this + 0x2e0) == 0) {
      iVar14 = 0;
    }
    else {
      iVar14 = **(int **)((int)this + 0x2d8);
    }
    iVar16 = *(int *)(iVar14 + 8);
    if (0xff < iVar16) {
      iVar16 = 0xff;
    }
    iVar19 = iVar16 * 2 + -0xff;
    if (iVar19 < 0) {
      iVar19 = 0;
    }
    if (*(int *)(iVar14 + 0xc) == 0) {
      piVar9 = local_28;
      iVar17 = iVar16;
    }
    else {
      piVar9 = &local_68;
      iVar17 = iVar19;
      iVar19 = iVar16;
    }
    puVar4 = (undefined4 *)SexyWidget_ApplyMatrix(piVar9,iVar17,iVar19,iVar16);
    SexyWidget_SetRectangle(param_1,puVar4);
    iVar14 = *(int *)(iVar14 + 0xc);
    cVar15 = '\0';
    iVar19 = 0;
    cVar21 = '\x01';
    iVar16 = 0x1cc;
    uVar12 = Math_FloatToUInt64();
    DrawSprite(*(void **)(*(int *)((int)this + 0x5c) + 0x8a4),param_1,(int)uVar12,iVar16,cVar21,
               iVar14,iVar19,cVar15);
  }
  SexyWidget_SetDrawMode(param_1,0);
  SexyWidget_SetColorizeFlag2(param_1,0);
  *(undefined4 *)((int)this + 0x1f8) = *(undefined4 *)((int)this + 500);
  while (iVar14 = *(int *)(*(int *)((int)this + 0x1f8) + 4), iVar14 != 0) {
    *(int *)((int)this + 0x1f8) = iVar14;
    if (*(int *)((int)this + 0x200) == 0) {
      (*(code *)_DAT_00000000[1])(param_1);
    }
    else {
      (**(code **)(*(int *)**(undefined4 **)((int)this + 0x1f8) + 4))(param_1);
    }
  }
  if (*(int *)((int)this + 0x80) == 0) {
    uVar12 = Math_FloatToUInt64();
    iVar16 = (int)uVar12;
    iVar14 = *(int *)((int)this + 0x98);
    uVar12 = Math_FloatToUInt64();
    Tank_RenderWithPowerUps(*(void **)((int)this + 0x5c),param_1,(int)uVar12,iVar14,iVar16);
  }
  *(undefined4 *)((int)this + 0x288) = *(undefined4 *)((int)this + 0x284);
  while (iVar14 = *(int *)(*(int *)((int)this + 0x288) + 4), iVar14 != 0) {
    *(int *)((int)this + 0x288) = iVar14;
    cVar15 = '\0';
    iVar19 = 0;
    iVar16 = 0;
    cVar21 = '\x01';
    uVar12 = Math_FloatToUInt64();
    iVar14 = (int)uVar12;
    uVar12 = Math_FloatToUInt64();
    DrawSprite(*(void **)(*(int *)((int)this + 0x5c) + 0x778),param_1,(int)uVar12,iVar14,cVar21,
               iVar16,iVar19,cVar15);
  }
  if (*(double *)((int)this + 400) < _DAT_0052c578 !=
      (NAN(*(double *)((int)this + 400)) || NAN(_DAT_0052c578))) {
    cVar15 = '\0';
    iVar19 = 0;
    iVar16 = 0;
    cVar21 = '\x01';
    iVar14 = 0x1c7;
    uVar12 = Math_FloatToUInt64();
    DrawSprite(*(void **)(*(int *)((int)this + 0x5c) + 0x750),param_1,(int)uVar12 + -0x41,iVar14,
               cVar21,iVar16,iVar19,cVar15);
    cVar15 = '\0';
    iVar19 = 0;
    iVar16 = 0;
    cVar21 = '\x01';
    iVar14 = 0x1c7;
    uVar12 = Math_FloatToUInt64();
    DrawSprite(*(void **)(*(int *)((int)this + 0x5c) + 0x750),param_1,(int)uVar12 + 0x37,iVar14,
               cVar21,iVar16,iVar19,cVar15);
  }
  if (_DAT_0052a0c0 < *(double *)((int)this + 0x148)) {
    SexyWidget_SetDrawMode(param_1,1);
    uVar12 = Math_FloatToUInt64();
    uVar5 = (undefined4)uVar12;
    puVar4 = (undefined4 *)CreateColor(local_28,uVar5,uVar5,uVar5,0xff);
    SexyWidget_SetRectangle(param_1,puVar4);
    cVar15 = '\0';
    iVar19 = 0;
    uVar12 = Math_FloatToUInt64();
    iVar14 = (int)uVar12;
    iVar16 = *(int *)((int)this + 0x98) + 2;
    cVar21 = '\x01';
    uVar12 = Math_FloatToUInt64();
    DrawSprite(*(void **)(*(int *)((int)this + 0x5c) + 0x70c),param_1,(int)uVar12,iVar16,cVar21,
               iVar14,iVar19,cVar15);
    SexyWidget_SetDrawMode(param_1,0);
  }
  ParticleEffects_Render((void *)((int)this + 0x2e8),param_1);
  *(undefined4 *)((int)this + 0x208) = *(undefined4 *)((int)this + 0x204);
  while (iVar14 = *(int *)(*(int *)((int)this + 0x208) + 4), iVar14 != 0) {
    *(int *)((int)this + 0x208) = iVar14;
    if (*(int *)((int)this + 0x210) == 0) {
      iVar14 = 0;
    }
    else {
      iVar14 = **(int **)((int)this + 0x208);
    }
    uVar5 = Compression_GetCompressedSize(*(int *)((int)this + 0x5c));
    Graphics_SwapBuffers(param_1,(char)uVar5 == '\0');
    uVar12 = Math_FloatToUInt64();
    local_28[2] = 0xa0;
    local_28[3] = 0xa0;
    local_28[1] = 0;
    local_30 = (double)CONCAT44(*(undefined4 *)(iVar14 + 0x20),(undefined4)local_30);
    local_28[0] = (int)uVar12 * 0xa0;
    uVar12 = Math_FloatToUInt64();
    local_68 = (int)uVar12;
    local_3c = *(int *)(iVar14 + 0x24);
    uVar12 = Math_FloatToUInt64();
    local_64 = (undefined4)uVar12;
    local_60 = (double)CONCAT44(local_3c,local_30._4_4_);
    Graphics_SetImageAlpha
              (param_1,*(undefined4 *)(*(int *)(*(int *)((int)this + 0x5c) + 0x81c) + 8),
               (int)&local_68,local_28);
  }
  *(undefined4 *)((int)this + 0x248) = *(undefined4 *)((int)this + 0x244);
  while (iVar14 = *(int *)(*(int *)((int)this + 0x248) + 4), iVar14 != 0) {
    *(int *)((int)this + 0x248) = iVar14;
    if (*(int *)((int)this + 0x250) == 0) {
      Projectile_Render((void *)0x0,param_1);
    }
    else {
      Projectile_Render((void *)**(undefined4 **)((int)this + 0x248),param_1);
    }
  }
  *(undefined4 *)((int)this + 0x278) = *(undefined4 *)((int)this + 0x274);
  while (iVar14 = *(int *)(*(int *)((int)this + 0x278) + 4), iVar14 != 0) {
    *(int *)((int)this + 0x278) = iVar14;
    if (*(int *)((int)this + 0x280) == 0) {
      Enemy_Render((void *)0x0,param_1);
    }
    else {
      Enemy_Render((void *)**(undefined4 **)((int)this + 0x278),param_1);
    }
  }
  TextEffect_Render(*(void **)((int)this + 0x2fc),param_1);
  if ((0x32 < *(int *)((int)this + 0xb4)) && (*(int *)((int)this + 0xb4) < 100)) {
    SexyWidget_SetDrawMode(param_1,1);
    puVar4 = local_88;
    iVar14 = 4;
    do {
      *puVar4 = 0;
      puVar4[1] = 0;
      puVar4 = puVar4 + 2;
      iVar14 = iVar14 + -1;
    } while (iVar14 != 0);
    iVar14 = 2;
    do {
      local_18 = *(double *)((int)this + 0x150) + _DAT_0052c530;
      iVar16 = (*(int *)(*(int *)((int)this + 0x5c) + 0x988) + 1) * iVar14;
      local_38 = (double)iVar16;
      fcos((float10)local_18);
      fVar11 = (float10)fsin((float10)local_18);
      local_60 = (double)(fVar11 * (float10)iVar16);
      fcos((float10)*(double *)((int)this + 0x150));
      uVar12 = Math_FloatToUInt64();
      fVar11 = (float10)fsin((float10)*(double *)((int)this + 0x150));
      local_18 = (double)CONCAT44((int)uVar12,(undefined4)local_18);
      local_30 = (double)fVar11;
      local_38 = (double)(*(int *)((int)this + 0x98) + -0xc);
      uVar12 = Math_FloatToUInt64();
      local_3c = (int)uVar12;
      uVar12 = Math_FloatToUInt64();
      iVar16 = (int)uVar12;
      uVar12 = Math_FloatToUInt64();
      local_30 = (double)CONCAT44((int)uVar12,(undefined4)local_30);
      uVar12 = Math_FloatToUInt64();
      local_b4 = (undefined4)uVar12;
      local_38 = (double)local_3c;
      uVar12 = Math_FloatToUInt64();
      local_88[1] = (undefined4)uVar12;
      local_88[0] = local_b4;
      uVar12 = Math_FloatToUInt64();
      local_ac = (undefined4)uVar12;
      uVar12 = Math_FloatToUInt64();
      local_88[3] = (undefined4)uVar12;
      local_88[2] = local_ac;
      uVar12 = Math_FloatToUInt64();
      local_bc = (undefined4)uVar12;
      local_38 = (double)local_30._4_4_;
      uVar12 = Math_FloatToUInt64();
      local_74 = (undefined4)uVar12;
      local_88[4] = local_bc;
      uVar12 = Math_FloatToUInt64();
      local_28[2] = (int)uVar12;
      uVar12 = Math_FloatToUInt64();
      local_6c = (undefined4)uVar12;
      local_70 = local_28[2];
      if (iVar14 == 2) {
        uVar20 = 0x40;
        uVar18 = 0x80;
        uVar5 = 0x20;
        puVar10 = local_98;
      }
      else {
        uVar20 = 0xff;
        uVar18 = 0xff;
        uVar5 = 0xff;
        puVar10 = local_4c;
      }
      puVar4 = (undefined4 *)SexyWidget_ApplyMatrix(puVar10,uVar5,uVar18,uVar20);
      SexyWidget_SetRectangle(param_1,puVar4);
      Polygon_Rasterize(param_1,(int)local_88,4,'\0');
      iVar14 = iVar14 + -1;
    } while (0 < iVar14);
    fsin((float10)*(double *)((int)this + 0x150));
    iVar19 = *(int *)((int)this + 0xb4) % 10;
    cVar15 = '\0';
    iVar17 = 0;
    cVar21 = '\x01';
    local_18 = (double)CONCAT44(*(int *)((int)this + 0x98) + -0xc,(undefined4)local_18);
    uVar12 = Math_FloatToUInt64();
    iVar14 = (int)uVar12;
    fcos((float10)*(double *)((int)this + 0x150));
    uVar12 = Math_FloatToUInt64();
    DrawSprite(*(void **)(*(int *)((int)this + 0x5c) + 0x75c),param_1,(int)uVar12,iVar14,cVar21,
               iVar19,iVar17,cVar15);
    if ((((*(double *)((int)this + 0x158) < _DAT_0052c740 !=
           (NAN(*(double *)((int)this + 0x158)) || NAN(_DAT_0052c740))) && (-0x140 < iVar16)) &&
        (iVar16 < 0x140)) && (0 < local_3c)) {
      iVar14 = *(int *)(*(int *)((int)this + 0x5c) + 0x414) % 0x28;
      DrawSprite(*(void **)(*(int *)((int)this + 0x5c) + 0x870),param_1,iVar16,local_30._4_4_,'\x01'
                 ,(int)(iVar14 + (iVar14 >> 0x1f & 3U)) >> 2,0,'\0');
    }
    SexyWidget_SetDrawMode(param_1,0);
  }
  if (*(int *)((int)this + 0x130) != 0) {
    fsin((float10)*(double *)((int)this + 0x150));
    cVar15 = '\0';
    iVar14 = *(int *)((int)this + 300) + (*(int *)((int)this + 300) >> 0x1f & 3U);
    iVar19 = 0;
    iVar16 = (int)(CONCAT44(iVar14 >> 0x1f,iVar14 >> 2) % 5);
    cVar21 = '\x01';
    uVar12 = Math_FloatToUInt64();
    iVar14 = (int)uVar12;
    fcos((float10)*(double *)((int)this + 0x150));
    uVar12 = Math_FloatToUInt64();
    DrawSprite(*(void **)(*(int *)((int)this + 0x5c) + 0x788),param_1,(int)uVar12,iVar14,cVar21,
               iVar16,iVar19,cVar15);
    local_18 = (double)(0x14 - (*(int *)((int)this + 300) * 2) % 0x14);
    if (local_18 < *(double *)((int)this + 0x158) != (local_18 == *(double *)((int)this + 0x158))) {
      do {
        cVar15 = '\0';
        iVar19 = 0;
        uVar12 = Math_FloatToUInt64();
        fsin((float10)*(double *)((int)this + 0x150));
        iVar16 = (int)((longlong)
                       ((ulonglong)(uint)((int)uVar12 >> 0x1f) << 0x20 | uVar12 & 0xffffffff) % 5);
        cVar21 = '\x01';
        uVar12 = Math_FloatToUInt64();
        iVar14 = (int)uVar12;
        fcos((float10)*(double *)((int)this + 0x150));
        uVar12 = Math_FloatToUInt64();
        DrawSprite(*(void **)(*(int *)((int)this + 0x5c) + 0x788),param_1,(int)uVar12,iVar14,cVar21,
                   iVar16,iVar19,cVar15);
        local_18 = local_18 + _DAT_0052c5a8;
      } while (local_18 < *(double *)((int)this + 0x158) !=
               (local_18 == *(double *)((int)this + 0x158)));
    }
    SexyWidget_SetDrawMode(param_1,1);
    local_18 = 0.0;
    if (_DAT_0052a0c0 < *(double *)((int)this + 0x158) !=
        (_DAT_0052a0c0 == *(double *)((int)this + 0x158))) {
      do {
        fsin((float10)*(double *)((int)this + 0x150));
        cVar15 = '\0';
        iVar19 = 0;
        iVar16 = 0;
        cVar21 = '\x01';
        uVar12 = Math_FloatToUInt64();
        iVar14 = (int)uVar12;
        fcos((float10)*(double *)((int)this + 0x150));
        uVar12 = Math_FloatToUInt64();
        DrawSprite(*(void **)(*(int *)((int)this + 0x5c) + 0x784),param_1,(int)uVar12,iVar14,cVar21,
                   iVar16,iVar19,cVar15);
        local_18 = local_18 + _DAT_0052c638;
      } while (local_18 < *(double *)((int)this + 0x158) !=
               (local_18 == *(double *)((int)this + 0x158)));
    }
    local_18 = (double)(0x32 - (*(int *)((int)this + 300) * 2) % 0x32);
    if (local_18 < *(double *)((int)this + 0x158) != (local_18 == *(double *)((int)this + 0x158))) {
      do {
        cVar15 = '\0';
        iVar19 = 0;
        uVar12 = Math_FloatToUInt64();
        fsin((float10)*(double *)((int)this + 0x150));
        iVar16 = (int)((longlong)
                       ((ulonglong)(uint)((int)uVar12 >> 0x1f) << 0x20 | uVar12 & 0xffffffff) % 5);
        cVar21 = '\x01';
        uVar12 = Math_FloatToUInt64();
        iVar14 = (int)uVar12;
        fcos((float10)*(double *)((int)this + 0x150));
        uVar12 = Math_FloatToUInt64();
        DrawSprite(*(void **)(*(int *)((int)this + 0x5c) + 0x78c),param_1,(int)uVar12,iVar14,cVar21,
                   iVar16,iVar19,cVar15);
        local_18 = local_18 + _DAT_0052a0a8;
      } while (local_18 < *(double *)((int)this + 0x158) !=
               (local_18 == *(double *)((int)this + 0x158)));
    }
    fsin((float10)*(double *)((int)this + 0x150));
    cVar15 = '\0';
    iVar14 = *(int *)((int)this + 300) + (*(int *)((int)this + 300) >> 0x1f & 3U);
    iVar19 = 0;
    iVar16 = (int)(CONCAT44(iVar14 >> 0x1f,iVar14 >> 2) % 5);
    cVar21 = '\x01';
    uVar12 = Math_FloatToUInt64();
    iVar14 = (int)uVar12;
    fcos((float10)*(double *)((int)this + 0x150));
    uVar12 = Math_FloatToUInt64();
    DrawSprite(*(void **)(*(int *)((int)this + 0x5c) + 0x78c),param_1,(int)uVar12,iVar14,cVar21,
               iVar16,iVar19,cVar15);
    SexyWidget_SetDrawMode(param_1,0);
  }
  *(undefined4 *)((int)this + 0x2a8) = *(undefined4 *)((int)this + 0x2a4);
  SexyWidget_SetDrawMode(param_1,1);
  SexyWidget_SetColorizeFlag2(param_1,1);
  while (iVar14 = *(int *)(*(int *)((int)this + 0x2a8) + 4), iVar14 != 0) {
    *(int *)((int)this + 0x2a8) = iVar14;
    if (*(int *)((int)this + 0x2b0) == 0) {
      iVar14 = 0;
    }
    else {
      iVar14 = **(int **)((int)this + 0x2a8);
    }
    uVar5 = *(undefined4 *)(iVar14 + 0x20);
    puVar4 = (undefined4 *)CreateColor(local_4c,uVar5,uVar5,uVar5,0xff);
    SexyWidget_SetRectangle(param_1,puVar4);
    iVar14 = *(int *)(iVar14 + 0x24);
    cVar15 = '\0';
    iVar19 = 0;
    cVar21 = '\x01';
    uVar12 = Math_FloatToUInt64();
    iVar16 = (int)uVar12;
    uVar12 = Math_FloatToUInt64();
    DrawSprite(*(void **)(*(int *)((int)this + 0x5c) + 0x7a8),param_1,(int)uVar12,iVar16,cVar21,
               iVar14,iVar19,cVar15);
  }
  SexyWidget_SetColorizeFlag2(param_1,0);
  SexyWidget_SetDrawMode(param_1,0);
  *(undefined4 *)((int)this + 0x238) = *(undefined4 *)((int)this + 0x234);
  while (iVar14 = *(int *)(*(int *)((int)this + 0x238) + 4), iVar14 != 0) {
    *(int *)((int)this + 0x238) = iVar14;
    if (*(int *)((int)this + 0x240) == 0) {
      (*(code *)*_DAT_00000000)(param_1);
    }
    else {
      (*(code *)**(undefined4 **)**(undefined4 **)((int)this + 0x238))(param_1);
    }
  }
  *(undefined4 *)((int)this + 0x218) = *(undefined4 *)((int)this + 0x214);
  while (iVar14 = *(int *)(*(int *)((int)this + 0x218) + 4), iVar14 != 0) {
    *(int *)((int)this + 0x218) = iVar14;
    if (*(int *)((int)this + 0x220) == 0) {
      iVar14 = 0;
    }
    else {
      iVar14 = **(int **)((int)this + 0x218);
    }
    if (*(char *)(iVar14 + 0x55) == '\0') {
      if (*(int *)((int)this + 0x220) == 0) {
        (*(code *)_DAT_00000000[1])(param_1);
      }
      else {
        (**(code **)(*(int *)**(undefined4 **)((int)this + 0x218) + 4))(param_1);
      }
    }
  }
  *(undefined4 *)((int)this + 0x1e8) = *(undefined4 *)((int)this + 0x1e4);
  while (iVar14 = *(int *)(*(int *)((int)this + 0x1e8) + 4), iVar14 != 0) {
    *(int *)((int)this + 0x1e8) = iVar14;
    if (*(int *)((int)this + 0x1f0) == 0) {
      iVar14 = 0;
    }
    else {
      iVar14 = **(int **)((int)this + 0x1e8);
    }
    iVar16 = *(int *)(iVar14 + 0x3c);
    iVar19 = *(int *)(iVar14 + 0x38);
    cVar15 = '\0';
    cVar21 = '\x01';
    uVar12 = Math_FloatToUInt64();
    iVar17 = (int)uVar12;
    uVar12 = Math_FloatToUInt64();
    DrawSprite(*(void **)(iVar14 + 0x34),param_1,(int)uVar12,iVar17,cVar21,iVar19,iVar16,cVar15);
  }
  *(undefined4 *)((int)this + 0x298) = *(undefined4 *)((int)this + 0x294);
  SexyWidget_SetDrawMode(param_1,1);
  while (iVar14 = *(int *)(*(int *)((int)this + 0x298) + 4), iVar14 != 0) {
    *(int *)((int)this + 0x298) = iVar14;
    cVar15 = '\0';
    iVar19 = 0;
    uVar12 = Math_FloatToUInt64();
    iVar14 = (int)uVar12;
    cVar21 = '\x01';
    uVar12 = Math_FloatToUInt64();
    iVar16 = (int)uVar12;
    uVar12 = Math_FloatToUInt64();
    DrawSprite(*(void **)(*(int *)((int)this + 0x5c) + 0x700),param_1,(int)uVar12,iVar16,cVar21,
               iVar14,iVar19,cVar15);
  }
  SexyWidget_SetDrawMode(param_1,0);
  if ((NAN(*(double *)((int)this + 0x88)) || NAN(_DAT_0052a0c0)) ==
      (*(double *)((int)this + 0x88) == _DAT_0052a0c0)) {
    SexyWidget_Translate(param_1,-0x140,0);
    SexyWidget_SetDrawMode(param_1,1);
    uVar20 = 0xff;
    uVar18 = 0;
    uVar12 = Math_FloatToUInt64();
    uVar5 = (undefined4)uVar12;
    uVar12 = Math_FloatToUInt64();
    puVar4 = (undefined4 *)CreateColor(local_4c,(int)uVar12,uVar5,uVar18,uVar20);
    SexyWidget_SetRectangle(param_1,puVar4);
    Graphics_FillRect(param_1,0,0,0x280,0x1e0);
    SexyWidget_SetDrawMode(param_1,0);
    SexyWidget_Translate(param_1,0x140,0);
  }
  if (*(int *)((int)this + 0x84) != 0) {
    SexyWidget_Translate(param_1,-0x140,0);
    SexyWidget_SetDrawMode(param_1,1);
    uVar5 = *(undefined4 *)((int)this + 0x84);
    puVar4 = (undefined4 *)CreateColor(local_4c,uVar5,uVar5,uVar5,0xff);
    SexyWidget_SetRectangle(param_1,puVar4);
    Graphics_FillRect(param_1,0,0,0x280,0x1e0);
    SexyWidget_SetDrawMode(param_1,0);
    SexyWidget_Translate(param_1,0x140,0);
  }
  if ((*(int *)((int)this + 0x1c8) != 0) && (*(int *)((int)this + 0x1c8) < 0x19)) {
    SexyWidget_SetDrawMode(param_1,1);
    local_28[2] = 200;
    local_28[0] = 0;
    local_28[1] = 0;
    local_28[3] = 0x96;
    fVar11 = (float10)fsin((float10)*(int *)((int)this + 0x1c8) * (float10)_DAT_0052c730);
    local_38 = (double)((float10)_DAT_0052c720 *
                       (fVar11 * (float10)_DAT_0052c728 + (float10)_DAT_0052c590));
    uVar12 = Math_FloatToUInt64();
    uVar13 = Math_FloatToUInt64();
    local_68 = (int)uVar13;
    local_64 = (int)uVar12;
    uVar12 = Math_FloatToUInt64();
    local_60 = (double)CONCAT44(local_60._4_4_,(int)uVar12);
    uVar12 = Math_FloatToUInt64();
    local_60 = (double)CONCAT44((int)uVar12,(undefined4)local_60);
    Graphics_SetImageAlpha
              (param_1,*(undefined4 *)(*(int *)(*(int *)((int)this + 0x5c) + 0x834) + 8),
               (int)&local_68,local_28);
    iVar14 = (0x19 - *(int *)((int)this + 0x1c8)) * 10;
    puVar4 = (undefined4 *)SexyWidget_ApplyMatrix(local_4c,iVar14,iVar14,iVar14);
    SexyWidget_SetRectangle(param_1,puVar4);
    Graphics_FillRect(param_1,0xfffffec0,0,0x280,0x1e0);
    SexyWidget_SetDrawMode(param_1,0);
  }
  if (*(void **)((int)this + 0x30c) != (void *)0x0) {
    Boss_RenderGraphics(*(void **)((int)this + 0x30c),param_1);
  }
  iVar14 = *(int *)((int)this + 0x5c);
  if (*(int *)(iVar14 + 0x968) == 0) {
    if ((*(int *)((int)this + 0x1dc) != 0) && (10 < *(int *)((int)this + 0x1dc) % 0x1e)) {
      puVar4 = (undefined4 *)SexyWidget_ApplyMatrix(local_4c,0xff,0,0);
      SexyWidget_SetRectangle(param_1,puVar4);
      Graphics_SetProjection(param_1,*(undefined4 *)(*(int *)((int)this + 0x5c) + 0x940));
      local_40 = 0xf;
      local_44 = 0;
      local_54 = local_54 & 0xffffff00;
      pcVar3 = "NO NUKES - COLLECT";
      do {
        pcVar8 = pcVar3;
        pcVar3 = pcVar8 + 1;
      } while (*pcVar8 != '\0');
      String_Assign(local_58,(_String_base *)"NO NUKES - COLLECT",(uint)(pcVar8 + -0x52c6f8));
      local_8 = 2;
      SexyWidget_DrawWithInterface(param_1,local_58,0xfffffecf,0x37);
      local_8 = 0xffffffff;
      if (0xf < local_40) {
                    /* WARNING: Subroutine does not return */
        System_ShutdownHandler(extraout_ECX_00,local_54);
      }
      DrawSprite(*(void **)(*(int *)((int)this + 0x5c) + 0x6fc),param_1,-0x78,0x32,'\x01',0,0,'\0');
    }
  }
  else if (((*(int *)((int)this + 0x17c) <= *(int *)((int)this + 0x184)) ||
           (*(char *)((int)this + 0x327) != '\0')) && (iVar16 = 0, 0 < *(int *)(iVar14 + 0x968))) {
    param_1 = (undefined4 *)0xfffffed4;
    do {
      DrawSprite(*(void **)(iVar14 + 0x6fc),this_00,(int)param_1,0x32,'\x01',0,0,'\0');
      iVar14 = *(int *)((int)this + 0x5c);
      iVar16 = iVar16 + 1;
      param_1 = (undefined4 *)((int)param_1 + 0x1e);
    } while (iVar16 < *(int *)(iVar14 + 0x968));
  }
  SexyWidget_Translate(this_00,-0x140,0);
  if ((*(int *)((int)this + 0x2e4) != 0) && (*(char *)((int)this + 0x1e0) == '\0')) {
    uVar12 = Math_FloatToUInt64();
    iVar14 = (int)uVar12;
    if (iVar14 < 0) {
      iVar14 = 0;
    }
    puVar4 = (undefined4 *)SexyWidget_ApplyMatrix(local_4c,0xff,0xff,0xff);
    SexyWidget_SetRectangle(this_00,puVar4);
    Graphics_SetProjection(this_00,*(undefined4 *)(*(int *)((int)this + 0x5c) + 0x940));
    local_40 = 0xf;
    local_44 = 0;
    local_54 = local_54 & 0xffffff00;
    pcVar3 = "BOSS";
    do {
      pcVar8 = pcVar3;
      pcVar3 = pcVar8 + 1;
    } while (*pcVar8 != '\0');
    String_Assign(local_58,(_String_base *)&DAT_0052c6f0,(uint)(pcVar8 + -0x52c6f0));
                    /* WARNING: Load size is inaccurate */
    local_8 = 3;
    (**(code **)(*this + 0x94))(this_00,local_58,0xd7,0x32,0xffffffff,1,1,0,0xffffffff);
    local_8 = 0xffffffff;
    if (0xf < local_40) {
                    /* WARNING: Subroutine does not return */
      System_ShutdownHandler(local_54,extraout_EDX_00);
    }
    if (*(char *)(*(int *)((int)this + 0x2e4) + 0x48) == '\0') {
      puVar4 = (undefined4 *)CreateColor(local_4c,0xff,0xff,0xff,0x50);
    }
    else {
      uVar18 = 0;
      uVar5 = 0;
      fcos((float10)(*(int *)((int)this + 0x4c) % 0x1f) * (float10)_DAT_0052c5a0);
      uVar12 = Math_FloatToUInt64();
      puVar4 = (undefined4 *)SexyWidget_ApplyMatrix(local_4c,(int)uVar12,uVar5,uVar18);
    }
    SexyWidget_SetRectangle(this_00,puVar4);
    Graphics_FillRect(this_00,0xdc,0x25,iVar14,0xf);
    if (*(char *)(*(int *)((int)this + 0x2e4) + 0x48) == '\0') {
      uVar5 = 0x50;
      puVar10 = local_c4;
    }
    else {
      uVar5 = 0xff;
      puVar10 = local_4c;
    }
    puVar4 = (undefined4 *)CreateColor(puVar10,0,0,0,uVar5);
    SexyWidget_SetRectangle(this_00,puVar4);
    Graphics_FillRect(this_00,iVar14 + 0xdc,0x25,200 - iVar14,0xf);
  }
  SexyWidget_Translate(this_00,0x140,0);
  *(undefined4 *)((int)this + 0x2c8) = *(undefined4 *)((int)this + 0x2c4);
  while (iVar14 = *(int *)(*(int *)((int)this + 0x2c8) + 4), iVar14 != 0) {
    *(int *)((int)this + 0x2c8) = iVar14;
    if (*(int *)((int)this + 0x2d0) == 0) {
      DataStructure_InitializeStack((void *)0x0,this_00);
    }
    else {
      DataStructure_InitializeStack((void *)**(undefined4 **)((int)this + 0x2c8),this_00);
    }
  }
  ExceptionList = local_10;
  return;
}


