/*
 * Function: Game_HandleUserInput
 * Address: 0044bf20
 * Category: core
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void Game_HandleUserInput(void)

{
  char cVar1;
  uint in_EAX;
  int iVar2;
  BOOL BVar3;
  int extraout_ECX;
  uint uVar4;
  undefined4 local_c;
  uint local_8;
  
  cVar1 = Registry_CloseKey(DAT_0056da10);
  if ((cVar1 == '\0') && (*(char *)(extraout_ECX + 0x2ff) != '\0')) {
    if (10000 < in_EAX - DAT_0056da64) {
      local_8 = 0;
      DAT_0056da64 = in_EAX;
      SystemParametersInfoA(0xe,0,&local_8,0);
      SystemParametersInfoA(0x10,0,&DAT_00566180,0);
      iVar2 = local_8 - 2;
      if (iVar2 < 1) {
        iVar2 = 1;
      }
      DAT_0056617c = iVar2 * 1000;
      if (DAT_00566180 == 0) {
        DAT_0056da24 = '\0';
      }
    }
    if (DAT_0056da20 != (code *)0x0) {
      local_c = 8;
      iVar2 = (*DAT_0056da20)(&local_c);
      if (iVar2 != 0) {
        if (in_EAX < local_8) {
          local_8 = in_EAX;
        }
        *(uint *)(DAT_0056da10 + 0x408) = local_8;
      }
    }
    if (DAT_00566180 != 0) {
      uVar4 = in_EAX - *(int *)(DAT_0056da10 + 0x408);
      if (DAT_0056da24 == '\0') {
        if (DAT_0056617c < uVar4) {
          DAT_0056da24 = '\x01';
        }
      }
      else {
        local_8 = 0;
        BVar3 = SystemParametersInfoA(0x72,0,&local_8,0);
        if (((BVar3 == 0) || (local_8 == 0)) && (uVar4 < DAT_0056617c)) {
          DAT_0056da24 = 0;
          UI_Widget_ValidateRender(*(int *)(DAT_0056da10 + 0x2dc));
          return;
        }
      }
    }
  }
  return;
}


