/*
 * Function: GameState_ProcessVictory
 * Address: 0043c170
 * Category: core
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


undefined4 * __thiscall GameState_ProcessVictory(void *this,byte param_1)

{
  int extraout_ECX;
  uint extraout_EDX;
  
  GameState_ResetLevel((undefined4 *)this);
  if ((param_1 & 1) != 0) {
                    /* WARNING: Subroutine does not return */
    System_ShutdownHandler(extraout_ECX,extraout_EDX);
  }
  return (undefined4 *)this;
}


