/*
 * Function: ImageDecoder_ApplyFilters
 * Address: 004cd830
 * Category: core
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __cdecl ImageDecoder_ApplyFilters(uint param_1)

{
  ulonglong uVar1;
  
  uVar1 = Math_FloatToUInt64();
  Renderer_BeginScene(&stack0x0000000c,(int)uVar1);
  ImageDecoder_ProcessHeader(param_1,(byte *)&DAT_00567d0c,&stack0x0000000c,4);
  return;
}


