/*
 * Function: MemoryCopy_Backward_96ByteObjects_Wrapper
 * Address: 004025d0
 * Category: core
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


undefined4 * __cdecl
MemoryCopy_Backward_96ByteObjects_Wrapper
          (undefined4 *param_1,undefined4 *param_2,undefined4 *param_3,undefined4 *param_4)

{
  MemoryCopy_Backward_96ByteObjects(param_1,param_2,param_3,param_4);
  return param_1;
}


