/*
 * Function: MemoryCopy_Forward_40ByteObjects_Wrapper
 * Address: 00408390
 * Category: core
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __cdecl
MemoryCopy_Forward_40ByteObjects_Wrapper
          (undefined4 *param_1,undefined4 *param_2,undefined4 *param_3)

{
  MemoryCopy_Forward_40ByteObjects(param_1,param_2,param_3);
  return;
}


