/*
 * Function: Particle_ApplyPhysics
 * Address: 00489d30
 * Category: core
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __thiscall
Particle_ApplyPhysics
          (void *this,int *param_1,int param_2,int param_3,int *param_4,uint *param_5,int param_6)

{
  undefined4 uVar1;
  uint extraout_EDX;
  uint extraout_EDX_00;
  uint extraout_EDX_01;
  uint uVar2;
  
                    /* WARNING: Load size is inaccurate */
  (**(code **)(*this + 0x50))();
  uVar1 = Texture_IsReady((int)this);
  if ((char)uVar1 != '\0') {
    Player_DrawVehicle(*(void **)(*(int *)((int)this + 0x48) + 0x30),param_1,(float)param_2,
                       (float)param_3,param_4,param_5,param_6,'\0');
    return;
  }
  if (param_6 == 0) {
                    /* WARNING: Load size is inaccurate */
    (**(code **)(*this + 0x94))(param_1,param_2,param_3,param_4,param_5);
    uVar2 = extraout_EDX_01;
  }
  else {
    uVar2 = extraout_EDX;
    if (param_6 == 1) {
                    /* WARNING: Load size is inaccurate */
      (**(code **)(*this + 0x98))(param_1,param_2,param_3,param_4,param_5);
      System_HandleShutdown2((int)this,extraout_EDX_00);
      return;
    }
  }
  System_HandleShutdown2((int)this,uVar2);
  return;
}


