/*
 * Function: SexyAppFramework_CleanupResources
 * Address: 004111a0
 * Category: core
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __fastcall SexyAppFramework_CleanupResources(int param_1)

{
  int iVar1;
  double *pdVar2;
  uint uVar3;
  ulonglong uVar4;
  
  *(undefined4 *)(param_1 + 0x208) = *(undefined4 *)(param_1 + 0x204);
  do {
    iVar1 = *(int *)(*(int *)(param_1 + 0x208) + 4);
    if (iVar1 == 0) {
      return;
    }
    *(int *)(param_1 + 0x208) = iVar1;
    if (*(int *)(param_1 + 0x210) == 0) {
      pdVar2 = (double *)0x0;
    }
    else {
      pdVar2 = (double *)**(undefined4 **)(param_1 + 0x208);
    }
    *pdVar2 = pdVar2[2] + *pdVar2;
    pdVar2[1] = pdVar2[1] + pdVar2[3];
    pdVar2[2] = pdVar2[2] * _DAT_0052c570;
    pdVar2[3] = pdVar2[3] * _DAT_0052c570;
    pdVar2[5] = pdVar2[6] + pdVar2[5];
    uVar4 = Math_FloatToUInt64();
  } while (((int)uVar4 < 0x14) ||
          (iVar1 = *(int *)(param_1 + 0x208), iVar1 == *(int *)(param_1 + 0x204)));
  if (iVar1 == *(int *)(param_1 + 0x20c)) {
    *(undefined4 *)(param_1 + 0x20c) = *(undefined4 *)(iVar1 + 8);
  }
  uVar3 = *(uint *)(iVar1 + 8);
  *(undefined4 *)(uVar3 + 4) = *(undefined4 *)(iVar1 + 4);
  iVar1 = *(int *)(*(int *)(param_1 + 0x208) + 4);
  if (iVar1 != 0) {
    uVar3 = *(uint *)(*(int *)(param_1 + 0x208) + 8);
    *(uint *)(iVar1 + 8) = uVar3;
  }
  if (**(int **)(param_1 + 0x208) != 0) {
                    /* WARNING: Subroutine does not return */
    System_ShutdownHandler(iVar1,uVar3);
  }
                    /* WARNING: Subroutine does not return */
  System_ShutdownHandler(iVar1,uVar3);
}


