/*
 * Function: Powerup_GunPowerUpdate
 * Address: 00447e00
 * Category: powerups
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


undefined4 * __thiscall
Powerup_GunPowerUpdate
          (void *this,int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4,
          undefined4 param_5,undefined4 param_6,undefined4 param_7,undefined4 param_8,
          undefined4 param_9,undefined1 param_10)

{
  undefined4 uVar1;
  int iVar2;
  void *local_10;
  undefined4 uStack_c;
  undefined4 local_8;
  
  local_8 = 0xffffffff;
  uStack_c = 0x512f78;
  local_10 = ExceptionList;
  ExceptionList = &local_10;
  String_Replace(this,param_1);
  *(undefined4 *)((int)this + 0x10) = param_2;
  *(undefined4 *)((int)this + 0x14) = param_3;
  *(undefined4 *)((int)this + 0x18) = param_4;
  *(undefined4 *)((int)this + 0x1c) = param_5;
  *(undefined4 *)((int)this + 0x20) = param_6;
  local_8 = 0;
  *(undefined ***)this = &PTR_List_GetCount_00531138;
  *(undefined4 *)((int)this + 0x24) = param_7;
  *(undefined4 *)((int)this + 0x28) = param_8;
  *(undefined4 *)((int)this + 0x2c) = param_9;
  iVar2 = Collision_HandleEnemyHit();
  *(double *)((int)this + 0x30) = (double)(iVar2 % 5);
  uVar1 = *(undefined4 *)(*(int *)(*(int *)((int)this + 0x58) + 0x5c) + 0x840);
  *(undefined4 *)((int)this + 8) = 0;
  *(undefined4 *)((int)this + 0x5c) = uVar1;
  *(undefined4 *)((int)this + 0x48) = 0;
  *(undefined4 *)((int)this + 0x4c) = 0x40340000;
  *(undefined1 *)((int)this + 0x68) = param_10;
  ExceptionList = local_10;
  return (undefined4 *)this;
}


