/*
 * Function: PowerUp_UpdateSystem
 * Address: 00488ec0
 * Category: powerups
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall PowerUp_UpdateSystem(undefined4 param_1)

{
  bool bVar1;
  undefined4 *puVar2;
  int iVar3;
  void *pvVar4;
  int *piVar5;
  uint *puVar6;
  int extraout_ECX;
  undefined4 *puVar7;
  undefined4 *puVar8;
  int *piVar9;
  int iVar10;
  undefined4 *puVar11;
  ulonglong uVar12;
  undefined4 local_10c4 [1028];
  undefined4 local_b4 [22];
  undefined4 local_5c;
  undefined4 local_58;
  double local_54;
  int local_4c;
  int local_48;
  int local_3c;
  undefined4 local_34;
  undefined4 *puVar13;
  char cVar14;
  int iVar15;
  undefined4 *puVar16;
  int iVar17;
  uint uVar18;
  void *local_10;
  undefined4 uStack_c;
  undefined4 local_8;
  
  local_8 = 0xffffffff;
  uStack_c = 0x514fa1;
  local_10 = ExceptionList;
  ExceptionList = &local_10;
  System_LoadLibrary(param_1);
  if (*(char *)(*(int *)(extraout_ECX + 0x14) + 4) != '\0') {
    piVar5 = *(int **)(extraout_ECX + 0x34);
    if (piVar5 == (int *)0x0) {
      piVar9 = (int *)0x0;
    }
    else {
      piVar9 = (int *)*piVar5;
    }
    local_48 = extraout_ECX;
    Database_OptimizePerformance
              ((void *)(extraout_ECX + 0x30),(int *)&stack0xffffffe0,piVar9,piVar5);
    *(undefined4 *)(extraout_ECX + 4) = 0;
    *(undefined4 *)(extraout_ECX + 8) = 0;
    *(undefined4 *)(extraout_ECX + 0xc) = 0;
    *(undefined4 *)(extraout_ECX + 0x10) = 0;
    puVar7 = *(undefined4 **)(*(int *)(extraout_ECX + 0x14) + 0x124);
    if (puVar7 == (undefined4 *)0x0) {
      puVar7 = (undefined4 *)0x0;
    }
    else {
      puVar7 = (undefined4 *)*puVar7;
    }
    iVar10 = extraout_ECX;
    if (puVar7 != *(undefined4 **)(*(int *)(extraout_ECX + 0x14) + 0x124)) {
      do {
        puVar13 = puVar7;
        if (((int)puVar7[0x4818] <= *(int *)(iVar10 + 0x18)) &&
           ((*(int *)(iVar10 + 0x18) <= (int)puVar7[0x4819] || (puVar7[0x4819] == -1)))) {
          bVar1 = true;
          for (uVar18 = 0;
              (puVar7[4] != 0 && (uVar18 < (uint)((int)(puVar7[5] - puVar7[4]) / 0x1c)));
              uVar18 = uVar18 + 1) {
            pvVar4 = *(void **)(iVar10 + 0x24);
            puVar13 = &local_58;
            _local_34 = (double)CONCAT44(0x488fd0,local_34);
            puVar2 = (undefined4 *)
                     System_CheckResourceLimits
                               (puVar13,*(void **)(iVar10 + 0x20),pvVar4,(int)&stack0xffffffd8);
            if ((void *)*puVar2 == pvVar4) {
              bVar1 = false;
            }
          }
          for (uVar18 = 0;
              (*(int *)(iVar10 + 0x20) != 0 &&
              (uVar18 < (uint)((*(int *)(iVar10 + 0x24) - *(int *)(iVar10 + 0x20)) / 0x1c)));
              uVar18 = uVar18 + 1) {
            pvVar4 = (void *)puVar7[9];
            puVar13 = &local_5c;
            _local_34 = (double)CONCAT44(0x489045,local_34);
            puVar2 = (undefined4 *)
                     System_CheckResourceLimits
                               (puVar13,(void *)puVar7[8],pvVar4,(int)&stack0xffffffd8);
            if ((void *)*puVar2 != pvVar4) {
              bVar1 = false;
            }
          }
          if (bVar1) {
            iVar3 = Graphics_ValidatePixelFormat(local_10c4);
            local_8 = 0;
            iVar17 = *(int *)(iVar10 + 0x34);
            puVar13 = (undefined4 *)0x489090;
            puVar2 = Exception_HandleCriticalError(iVar17,*(undefined4 *)(iVar17 + 4),iVar3);
            cVar14 = '\0';
            System_GetTicks((void *)(iVar10 + 0x30),1);
            *(undefined4 **)(iVar17 + 4) = puVar2;
            *(undefined4 **)puVar2[1] = puVar2;
            local_8 = 0xffffffff;
            Graphics_SetRenderMode(local_10c4);
            iVar17 = *(int *)(*(int *)(iVar10 + 0x34) + 4);
            *(undefined4 **)(iVar17 + 0xc) = puVar7 + 2;
            _local_34 = *(double *)(iVar10 + 0x40);
            local_54 = 1.0;
            if (((*(int *)(iVar10 + 0x40) == 0) && (*(int *)(iVar10 + 0x44) == 0x3ff00000)) &&
               ((puVar7[0x481a] == 0 || (*(int *)(iVar10 + 0x18) == puVar7[0x481a])))) {
              *(undefined4 *)(iVar17 + 0x10) = puVar7[0x4813];
              *(undefined1 *)(iVar17 + 0x14) = 0;
              puVar2 = (undefined4 *)(iVar17 + 0x18);
              puVar7 = puVar7 + 0xb;
              iVar17 = 0x100;
              do {
                *puVar2 = *puVar7;
                puVar2[1] = puVar7[1];
                puVar2[2] = puVar7[2];
                puVar2[3] = puVar7[3];
                puVar7 = puVar7 + 0x48;
                puVar2 = puVar2 + 4;
                iVar17 = iVar17 + -1;
              } while (iVar17 != 0);
            }
            else {
              if (puVar7[0x481a] != 0) {
                local_54 = (double)(int)puVar7[0x481a];
                _local_34 = (double)*(int *)(iVar10 + 0x18) * *(double *)(iVar10 + 0x40);
              }
              pvVar4 = operator_new(0x48);
              local_8 = 1;
              if (pvVar4 == (void *)0x0) {
                piVar5 = (int *)0x0;
              }
              else {
                piVar5 = SexyFramework_DrawWidget(pvVar4,*(int *)(*(int *)(iVar10 + 0x14) + 0xc));
              }
              piVar9 = (int *)(iVar17 + 0x28);
              local_8 = 0xffffffff;
              iVar3 = 0;
              iVar10 = 0;
              local_4c = 0x20;
              do {
                uVar12 = Math_FloatToUInt64();
                local_3c = (int)uVar12;
                uVar12 = Math_FloatToUInt64();
                iVar15 = (int)uVar12;
                piVar9[-4] = iVar3;
                piVar9[-3] = 0;
                piVar9[-2] = local_3c;
                piVar9[-1] = iVar15;
                if (iVar10 < iVar15) {
                  iVar10 = iVar15;
                }
                iVar3 = iVar3 + local_3c;
                uVar12 = Math_FloatToUInt64();
                local_3c = (int)uVar12;
                uVar12 = Math_FloatToUInt64();
                iVar15 = (int)uVar12;
                *piVar9 = iVar3;
                piVar9[1] = 0;
                piVar9[2] = local_3c;
                piVar9[3] = iVar15;
                if (iVar10 < iVar15) {
                  iVar10 = iVar15;
                }
                iVar3 = iVar3 + local_3c;
                uVar12 = Math_FloatToUInt64();
                local_3c = (int)uVar12;
                uVar12 = Math_FloatToUInt64();
                iVar15 = (int)uVar12;
                piVar9[4] = iVar3;
                piVar9[5] = 0;
                piVar9[6] = local_3c;
                piVar9[7] = iVar15;
                if (iVar10 < iVar15) {
                  iVar10 = iVar15;
                }
                iVar3 = iVar3 + local_3c;
                uVar12 = Math_FloatToUInt64();
                local_3c = (int)uVar12;
                uVar12 = Math_FloatToUInt64();
                iVar15 = (int)uVar12;
                piVar9[8] = iVar3;
                piVar9[9] = 0;
                piVar9[10] = local_3c;
                piVar9[0xb] = iVar15;
                if (iVar10 < iVar15) {
                  iVar10 = iVar15;
                }
                iVar3 = iVar3 + local_3c;
                uVar12 = Math_FloatToUInt64();
                local_3c = (int)uVar12;
                uVar12 = Math_FloatToUInt64();
                iVar15 = (int)uVar12;
                piVar9[0xc] = iVar3;
                piVar9[0xd] = 0;
                piVar9[0xe] = local_3c;
                piVar9[0xf] = iVar15;
                if (iVar10 < iVar15) {
                  iVar10 = iVar15;
                }
                iVar3 = iVar3 + local_3c;
                uVar12 = Math_FloatToUInt64();
                local_3c = (int)uVar12;
                uVar12 = Math_FloatToUInt64();
                iVar15 = (int)uVar12;
                piVar9[0x10] = iVar3;
                piVar9[0x11] = 0;
                piVar9[0x12] = local_3c;
                piVar9[0x13] = iVar15;
                if (iVar10 < iVar15) {
                  iVar10 = iVar15;
                }
                iVar3 = iVar3 + local_3c;
                uVar12 = Math_FloatToUInt64();
                local_3c = (int)uVar12;
                uVar12 = Math_FloatToUInt64();
                iVar15 = (int)uVar12;
                piVar9[0x14] = iVar3;
                piVar9[0x15] = 0;
                piVar9[0x16] = local_3c;
                piVar9[0x17] = iVar15;
                if (iVar10 < iVar15) {
                  iVar10 = iVar15;
                }
                iVar3 = iVar3 + local_3c;
                Math_FloatToUInt64();
                iVar15 = 0x48939c;
                uVar12 = Math_FloatToUInt64();
                piVar9[0x18] = iVar3;
                piVar9[0x19] = 0;
                piVar9[0x1a] = (int)uVar12;
                piVar9[0x1b] = iVar15;
                if (iVar10 < iVar15) {
                  iVar10 = iVar15;
                }
                iVar3 = iVar3 + (int)uVar12;
                piVar9 = piVar9 + 0x20;
                local_4c = local_4c + -1;
              } while (local_4c != 0);
              *(int **)(iVar17 + 0x10) = piVar5;
              *(undefined1 *)(iVar17 + 0x14) = 1;
              (**(code **)(*piVar5 + 0x60))();
              puVar13 = (undefined4 *)0x489401;
              Graphics_InitializeSurface(local_b4,piVar5);
              puVar11 = (undefined4 *)(iVar17 + 0x18);
              puVar8 = puVar13 + 2;
              local_8 = 2;
              puVar7 = puVar13 + 0xb;
              puVar2 = (undefined4 *)0x100;
              puVar16 = puVar8;
              do {
                iVar10 = puVar8[0x4811];
                if (iVar10 != 0) {
                  _local_34 = (double)CONCAT44(iVar10,0x489439);
                  puVar13 = puVar11;
                  puVar2 = puVar7;
                  puVar8 = puVar16;
                  Graphics_SetImageAlpha(local_b4,iVar10,(int)puVar11,puVar7);
                  puVar16 = puVar8;
                }
                cVar14 = (char)((uint)iVar3 >> 0x18);
                puVar7 = puVar7 + 0x48;
                puVar11 = puVar11 + 4;
                puVar2 = (undefined4 *)((int)puVar2 + -1);
              } while (puVar2 != (undefined4 *)0x0);
              if (*(char *)(local_48 + 0x48) != '\0') {
                iVar10 = piVar5[2] * piVar5[1];
                puVar6 = (uint *)(**(code **)(*piVar5 + 100))();
                if (0 < iVar10) {
                  do {
                    *puVar6 = *puVar6 | 0xffffff;
                    puVar6 = puVar6 + 1;
                    iVar10 = iVar10 + -1;
                  } while (iVar10 != 0);
                }
              }
              (**(code **)(*piVar5 + 0x70))();
              local_8 = 0xffffffff;
              Graphics_ClearClipRect(local_b4);
              iVar10 = local_48;
            }
            uVar12 = Math_FloatToUInt64();
            if (*(int *)(iVar10 + 4) < (int)uVar12) {
              *(int *)(iVar10 + 4) = (int)uVar12;
            }
            uVar12 = Math_FloatToUInt64();
            if (*(int *)(iVar10 + 0xc) < (int)uVar12) {
              *(int *)(iVar10 + 0xc) = (int)uVar12;
            }
            uVar12 = Math_FloatToUInt64();
            if ((cVar14 != '\0') || ((int)uVar12 < *(int *)(iVar10 + 8))) {
              *(int *)(iVar10 + 8) = (int)uVar12;
            }
            uVar12 = Math_FloatToUInt64();
            if ((cVar14 != '\0') || (*(int *)(iVar10 + 0x10) < (int)uVar12)) {
              *(int *)(iVar10 + 0x10) = (int)uVar12;
            }
          }
        }
        puVar7 = (undefined4 *)*puVar13;
      } while (puVar7 != *(undefined4 **)(*(int *)(iVar10 + 0x14) + 0x124));
    }
  }
  ExceptionList = local_10;
  return;
}


