/*
 * Function: PowerUp_ProcessThunderstrike
 * Address: 00402f60
 * Category: powerups
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


_String_base * __fastcall
PowerUp_ProcessThunderstrike
          (_String_base *param_1,uint param_2,_String_base *param_3,uint param_4,uint param_5)

{
  bool bVar1;
  _String_base *p_Var2;
  uint uVar3;
  uint extraout_EDX;
  _String_base *p_Var4;
  _String_base *p_Var5;
  
  p_Var5 = param_3;
  if (*(uint *)(param_3 + 0x14) < param_4) {
    std::_String_base::_Xran(param_1);
    param_2 = extraout_EDX;
  }
  param_3 = (_String_base *)(*(int *)(param_3 + 0x14) - param_4);
  if (param_5 < param_3) {
    param_3 = (_String_base *)param_5;
  }
  if (param_1 != p_Var5) {
    bVar1 = Level_ProcessWaveSpawning(param_1,param_2,(uint)param_3,'\x01');
    if (bVar1) {
      if (*(uint *)(p_Var5 + 0x18) < 0x10) {
        p_Var5 = p_Var5 + 4;
      }
      else {
        p_Var5 = *(_String_base **)(p_Var5 + 4);
      }
      p_Var2 = param_1 + 4;
      p_Var4 = p_Var2;
      if (0xf < *(uint *)(param_1 + 0x18)) {
        p_Var4 = *(_String_base **)p_Var2;
      }
      p_Var5 = p_Var5 + param_4;
      for (uVar3 = (uint)param_3 >> 2; uVar3 != 0; uVar3 = uVar3 - 1) {
        *(undefined4 *)p_Var4 = *(undefined4 *)p_Var5;
        p_Var5 = p_Var5 + 4;
        p_Var4 = p_Var4 + 4;
      }
      for (uVar3 = (uint)param_3 & 3; uVar3 != 0; uVar3 = uVar3 - 1) {
        *p_Var4 = *p_Var5;
        p_Var5 = p_Var5 + 1;
        p_Var4 = p_Var4 + 1;
      }
      *(_String_base **)(param_1 + 0x14) = param_3;
      if (0xf < *(uint *)(param_1 + 0x18)) {
        p_Var2 = *(_String_base **)p_Var2;
      }
      p_Var2[(int)param_3] = (_String_base)0x0;
    }
    return param_1;
  }
  PowerUp_ProcessFlakCannon(param_1,(uint)(param_3 + param_4),0xffffffff);
  PowerUp_ProcessFlakCannon(param_1,0,param_4);
  return param_1;
}


