/*
 * Function: PowerUp_ProcessSpreadShot
 * Address: 0042e840
 * Category: powerups
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall PowerUp_ProcessSpreadShot(int param_1)

{
  *(undefined4 *)(param_1 + 0x78) = 4;
  (**(code **)(**(int **)(param_1 + 0x7c) + 0xb8))(0,0);
  return;
}


