/*
 * Function: Powerup_RapidFireUpdate
 * Address: 00447cf0
 * Category: weapons
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall Powerup_RapidFireUpdate(undefined4 *param_1)

{
  *param_1 = &PTR_List_Find_00531118;
  String_Copy(param_1);
  return;
}


