/*
 * Function: Projectile_Render
 * Address: 0042bf90
 * Category: weapons
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __thiscall Projectile_Render(void *this,void *param_1)

{
  undefined4 *puVar1;
  undefined1 local_14 [16];
  
                    /* WARNING: Load size is inaccurate */
  Graphics_SetProjection(param_1,*(undefined4 *)(*this + 0x93c));
  puVar1 = (undefined4 *)
           CreateColor(local_14,*(undefined4 *)((int)this + 0x3c),*(undefined4 *)((int)this + 0x40),
                       *(undefined4 *)((int)this + 0x44),*(undefined4 *)((int)this + 0x24));
  SexyWidget_SetRectangle(param_1,puVar1);
  SexyWidget_DrawWithInterface
            (param_1,(int)this + 8,*(undefined4 *)((int)this + 0x28),
             *(int *)((int)this + 0x24) / 2 + -0x80 + *(int *)((int)this + 0x2c));
  return;
}


