/*
 * Function: Level_InitializeFrigistan
 * Address: 00496d60
 * Category: levels
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall Level_InitializeFrigistan(int param_1)

{
  *(undefined4 *)(param_1 + 0x18) = 0;
  return;
}


