/*
 * Function: Level_ProcessProgression
 * Address: 004138e0
 * Category: levels
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __fastcall Level_ProcessProgression(int param_1)

{
  int iVar1;
  uint uVar2;
  int extraout_ECX;
  uint extraout_EDX;
  
  Boss_AttackSystem(*(int **)(param_1 + 0x300));
  if (*(int *)(*(int *)(param_1 + 0x300) + 0xc) == 1) {
    SmartLinkedList_ClearAll((int *)(param_1 + 0x214));
    LinkedList_ClearBasic((int *)(param_1 + 0x1e4));
  }
  if (0x14 < *(int *)(*(int *)(param_1 + 0x300) + 0xc)) {
    *(undefined4 *)(param_1 + 0x1f8) = *(undefined4 *)(param_1 + 500);
    while (iVar1 = *(int *)(*(int *)(param_1 + 0x1f8) + 4), iVar1 != 0) {
      *(int *)(param_1 + 0x1f8) = iVar1;
      if (*(int *)(param_1 + 0x200) == 0) {
        (**(code **)(_DAT_00000000 + 0x10))();
      }
      else {
        (**(code **)(*(int *)**(undefined4 **)(param_1 + 0x1f8) + 0x10))();
      }
    }
    SmartLinkedList_ClearAll((int *)(param_1 + 500));
    *(undefined4 *)(param_1 + 0x2e4) = 0;
    *(undefined4 *)(param_1 + 0x84) = 0xfe;
    *(undefined4 *)(param_1 + 0x88) = 0;
    *(undefined4 *)(param_1 + 0x8c) = 0x406fe000;
    *(int *)(param_1 + 0x1e8) = *(int *)(param_1 + 0x1e4);
    while (iVar1 = *(int *)(*(int *)(param_1 + 0x1e8) + 4), iVar1 != 0) {
      *(int *)(param_1 + 0x1e8) = iVar1;
      if (*(int *)(param_1 + 0x1f0) == 0) {
        iVar1 = 0;
      }
      else {
        iVar1 = **(int **)(param_1 + 0x1e8);
      }
      if (*(char *)(iVar1 + 0x30) != '\0') {
        LinkedList_PopNode((int *)(param_1 + 0x1e4));
      }
    }
    SmartLinkedList_ClearAll((int *)(param_1 + 0x214));
    (**(code **)(**(int **)(param_1 + 0x5c) + 0xb8))(0x10,0);
    if (*(int **)(param_1 + 0x300) != (int *)0x0) {
      Audio_PlaySoundEffect(*(int **)(param_1 + 0x300));
                    /* WARNING: Subroutine does not return */
      System_ShutdownHandler(extraout_ECX,extraout_EDX);
    }
    *(undefined4 *)(param_1 + 0x300) = 0;
    *(undefined4 *)(param_1 + 400) = 0;
    *(int *)(param_1 + 0x17c) = *(int *)(param_1 + 0x17c) + 1;
    *(undefined4 *)(param_1 + 0x194) = 0x407e0000;
    uVar2 = Collision_HandleEnemyHit();
    uVar2 = uVar2 & 0x80000003;
    if ((int)uVar2 < 0) {
      uVar2 = (uVar2 - 1 | 0xfffffffc) + 1;
    }
    *(uint *)(param_1 + 0x198) = uVar2;
  }
  return;
}


