/*
 * Function: Survival_ExecuteWaveSpawning
 * Address: 0040a820
 * Category: levels
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void * __cdecl Survival_ExecuteWaveSpawning(int param_1,int param_2,void *param_3)

{
  void *pvStack_10;
  undefined4 uStack_c;
  undefined1 local_8;
  undefined3 uStack_7;
  
  uStack_c = 0x50fb61;
  pvStack_10 = ExceptionList;
  uStack_7 = 0;
  ExceptionList = &pvStack_10;
  for (; param_1 != param_2; param_1 = param_1 + 0x10) {
    local_8 = 1;
    if (param_3 != (void *)0x0) {
      Wave_ProcessSpawning(param_3,param_1);
    }
    param_3 = (void *)((int)param_3 + 0x10);
  }
  ExceptionList = pvStack_10;
  return param_3;
}


