/*
 * Function: Wave_ProcessLevel17
 * Address: 00434950
 * Category: levels
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


undefined4 * __thiscall Wave_ProcessLevel17(void *this,int param_1)

{
  undefined4 uVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  uint uVar5;
  bool bVar6;
  void *local_10;
  undefined4 uStack_c;
  undefined4 local_8;
  
  local_8 = 0xffffffff;
  uStack_c = 0x511fe8;
  local_10 = ExceptionList;
  ExceptionList = &local_10;
  Boss_HelicopterTurretSystem(this,param_1);
  *(undefined ***)this = &PTR_UI_ProcessMenuNavigation_00530470;
  *(undefined4 *)((int)this + 0x74) = 0;
  *(undefined4 *)((int)this + 0x70) = 200;
  *(undefined4 *)((int)this + 0x58) = *(undefined4 *)(*(int *)((int)this + 0x50) + 0x1228);
  local_8 = 0;
  *(undefined4 *)((int)this + 0x5c) = *(undefined4 *)(*(int *)((int)this + 0x50) + 0x122c);
  uVar1 = *(undefined4 *)(*(int *)(*(int *)((int)this + 0x4c) + 0x5c) + 0x8e4);
  *(undefined4 *)((int)this + 0x78) = 0;
  *(undefined4 *)((int)this + 0x60) = uVar1;
  *(undefined4 *)((int)this + 0x7c) = 0;
  iVar2 = Boss_ProcessEyebot((int)this);
  iVar3 = Collision_HandleEnemyHit();
  iVar4 = Boss_ProcessEyebot((int)this);
  *(undefined4 *)((int)this + 0x18) = 0;
  *(undefined4 *)((int)this + 0x1c) = 0;
  *(undefined4 *)((int)this + 0x20) = 0;
  *(undefined4 *)((int)this + 0x24) = 0;
  *(undefined4 *)((int)this + 0x28) = 0;
  *(undefined4 *)((int)this + 0x2c) = 0;
  *(double *)((int)this + 0x10) = (double)(iVar3 % (0xe6 - iVar2) + 0x32 + iVar4 / 2);
  uVar1 = *(undefined4 *)(*(int *)((int)this + 0x50) + 0x121c);
  *(undefined4 *)((int)this + 0x80) = 0;
  *(undefined4 *)((int)this + 100) = uVar1;
  *(undefined4 *)((int)this + 0x84) = 0;
  *(undefined4 *)((int)this + 0x88) = 0;
  uVar5 = Collision_HandleEnemyHit();
  uVar5 = uVar5 & 0x80000001;
  bVar6 = uVar5 == 0;
  if ((int)uVar5 < 0) {
    bVar6 = (uVar5 - 1 | 0xfffffffe) == 0xffffffff;
  }
  if (bVar6) {
    iVar2 = Boss_ProcessApeKommieKong((int)this);
    iVar2 = -0x140 - iVar2 / 2;
  }
  else {
    iVar2 = Boss_ProcessApeKommieKong((int)this);
    iVar2 = iVar2 / 2 + 0x140;
  }
  *(double *)((int)this + 8) = (double)iVar2;
  *(int *)(*(int *)((int)this + 0x4c) + 0x7c) =
       *(int *)(*(int *)((int)this + 0x4c) + 0x7c) + *(int *)(*(int *)((int)this + 0x50) + 0x1220);
  ExceptionList = local_10;
  return (undefined4 *)this;
}


