/*
 * Function: D3D_ValidateRenderTarget
 * Address: 00482bf0
 * Category: graphics
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __cdecl D3D_ValidateRenderTarget(int param_1,_String_base *param_2)

{
  _String_base _Var1;
  char *pcVar2;
  _String_base *p_Var3;
  char *pcVar4;
  int iVar5;
  uint extraout_EDX;
  uint unaff_retaddr;
  undefined4 *in_stack_ffffffa8;
  undefined4 *in_stack_ffffffac;
  undefined1 local_4c [4];
  int local_48;
  uint local_34;
  _String_base local_30 [4];
  undefined1 local_2c;
  undefined4 local_1c;
  undefined4 local_18;
  uint local_14;
  void *local_10;
  undefined1 *puStack_c;
  int local_8;
  
  local_8 = -1;
  puStack_c = &LAB_005148f0;
  local_10 = ExceptionList;
  local_14 = DAT_00569f5c ^ unaff_retaddr;
  if (param_1 < 0) {
    local_18 = 0xf;
    local_1c = 0;
    local_2c = 0;
    pcVar2 = "DXError - ";
    do {
      pcVar4 = pcVar2;
      pcVar2 = pcVar4 + 1;
    } while (*pcVar4 != '\0');
    ExceptionList = &local_10;
    String_Assign(local_30,(_String_base *)"DXError - ",(uint)(pcVar4 + -0x53339c));
    local_8 = 0;
    p_Var3 = param_2;
    do {
      _Var1 = *p_Var3;
      p_Var3 = p_Var3 + 1;
    } while (_Var1 != (_String_base)0x0);
    Enemy_ProcessSatelliteLogic(local_30,param_2,(int)p_Var3 - (int)(param_2 + 1));
    pcVar2 = ": ";
    do {
      pcVar4 = pcVar2;
      pcVar2 = pcVar4 + 1;
    } while (*pcVar4 != '\0');
    Enemy_ProcessSatelliteLogic(local_30,(_String_base *)&DAT_005331fc,(uint)(pcVar4 + -0x5331fc));
    iVar5 = Image_Clone(local_4c,param_1);
    local_8._0_1_ = 1;
    Enemy_UpdateAI(local_30,iVar5,0,0xffffffff);
    local_8 = (uint)local_8._1_3_ << 8;
    if (0xf < local_34) {
                    /* WARNING: Subroutine does not return */
      System_ShutdownHandler(local_48,extraout_EDX);
    }
    Database_CacheResults(&stack0xffffffa8,local_30);
    CRuntime_CxxThrowException(&stack0xffffffa8,&DAT_00556c00);
  }
  ExceptionList = local_10;
  Exception_SetMessage((void *)(local_14 ^ unaff_retaddr),in_stack_ffffffa8,in_stack_ffffffac);
  return;
}


