/*
 * Function: D3DRenderer_DrawTexturedQuad
 * Address: 00484ba0
 * Category: graphics
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __thiscall
D3DRenderer_DrawTexturedQuad
          (void *this,_String_base *param_1,_String_base *param_2,float param_3,float param_4,
          int param_5,int param_6,int param_7,int param_8,undefined4 param_9)

{
  int iVar1;
  _String_base *p_Var2;
  float local_94;
  float local_90;
  undefined4 local_8c;
  undefined4 local_88;
  undefined4 local_84;
  undefined4 local_80;
  undefined4 local_7c;
  undefined4 local_78;
  float local_74;
  float local_70;
  undefined4 local_6c;
  undefined4 local_68;
  undefined4 local_64;
  undefined4 local_60;
  undefined4 local_5c;
  float local_58;
  float local_54;
  float local_50;
  undefined4 local_4c;
  undefined4 local_48;
  undefined4 local_44;
  undefined4 local_40;
  float local_3c;
  undefined4 local_38;
  float local_34;
  float local_30;
  undefined4 local_2c;
  undefined4 local_28;
  undefined4 local_24;
  undefined4 local_20;
  float local_1c;
  float local_18;
  float local_14;
  float local_10;
  float local_c;
  float local_8;
  
  local_14 = (float)param_7;
  local_8 = (float)param_7 * _DAT_00533448;
  local_c = (float)param_8;
  local_10 = (float)param_8 * _DAT_00533448;
  if (DAT_0056e35a == '\0') {
    D3D_TranslateMatrix(this,param_2,param_5,param_6,param_7,param_8);
  }
  else {
    D3D_ScaleMatrix(this,param_2,param_5,param_6,param_7,param_8);
  }
  local_94 = param_3 - _DAT_005332ec;
  local_58 = local_10;
  local_90 = param_4 - _DAT_005332ec;
  local_70 = local_c + local_90;
  local_84 = param_9;
  local_64 = param_9;
  local_44 = param_9;
  local_24 = param_9;
  local_54 = local_14 + local_94;
  local_3c = local_8;
  local_8c = 0;
  local_88 = 0x3f800000;
  local_80 = 0;
  local_7c = 0;
  local_78 = 0;
  local_6c = 0;
  local_68 = 0x3f800000;
  local_60 = 0;
  local_5c = 0;
  local_4c = 0;
  local_48 = 0x3f800000;
  local_40 = 0;
  local_38 = 0;
  local_2c = 0;
  local_28 = 0x3f800000;
  local_20 = 0;
  local_1c = local_8;
  local_18 = local_10;
  p_Var2 = param_1;
  local_74 = local_94;
  local_50 = local_90;
  local_34 = local_54;
  local_30 = local_70;
  iVar1 = (**(code **)(*(int *)param_1 + 0x8c))(param_1,0,param_2,"SetTexture theTexture");
  D3D_ValidateRenderTarget(iVar1,p_Var2);
  p_Var2 = param_1;
  iVar1 = (**(code **)(*(int *)param_1 + 100))(param_1,5,0x1c4,&local_94,4,1,"DrawPrimitive");
  D3D_ValidateRenderTarget(iVar1,p_Var2);
  iVar1 = (**(code **)(*(int *)param_1 + 0x8c))(param_1,0,0,"SetTexture NULL");
  D3D_ValidateRenderTarget(iVar1,param_1);
  return;
}


