/*
 * Function: Graphics_SetViewport
 * Address: 0047f410
 * Category: graphics
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall Graphics_SetViewport(int *param_1)

{
  int *piVar1;
  int iVar2;
  byte *pbVar3;
  uint uVar4;
  
  piVar1 = (int *)*param_1;
  if (piVar1 == (int *)0x0) goto LAB_0047f454;
  uVar4 = *(uint *)piVar1[8];
  if (uVar4 == 0) {
LAB_0047f443:
    uVar4 = (**(code **)(*piVar1 + 0x14))();
  }
  else {
    iVar2 = *(int *)piVar1[0xc];
    if (iVar2 + uVar4 <= uVar4) goto LAB_0047f443;
    *(int *)piVar1[0xc] = iVar2 + -1;
    pbVar3 = *(byte **)piVar1[8];
    *(byte **)piVar1[8] = pbVar3 + 1;
    uVar4 = (uint)*pbVar3;
  }
  if (uVar4 != 0xffffffff) {
    *(undefined1 *)(param_1 + 1) = 0;
    return;
  }
LAB_0047f454:
  *param_1 = 0;
  *(undefined1 *)(param_1 + 1) = 1;
  return;
}


