/*
 * Function: Graphics_Present
 * Address: 004e4de0
 * Category: graphics
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall Graphics_Present(int param_1,uint param_2,undefined4 *param_3)

{
  int iVar1;
  
  if (param_3 == (undefined4 *)0x0) {
    return;
  }
  if (param_3[3] != 0) {
                    /* WARNING: Subroutine does not return */
    System_ShutdownHandler(param_1,param_2);
  }
  if (param_3[5] != 0) {
                    /* WARNING: Subroutine does not return */
    System_ShutdownHandler(param_1,param_2);
  }
  for (iVar1 = 6; iVar1 != 0; iVar1 = iVar1 + -1) {
    *param_3 = 0;
    param_3 = param_3 + 1;
  }
                    /* WARNING: Subroutine does not return */
  System_ShutdownHandler(0,param_2);
}


