/*
 * Function: Graphics_SetRenderTarget
 * Address: 00478bb0
 * Category: graphics
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


int __thiscall Graphics_SetRenderTarget(void *this,int param_1)

{
  int extraout_EDX;
  
  *(undefined ***)this = &PTR_Graphics_CreateSurface_00532f78;
  *(undefined4 *)((int)this + 4) = *(undefined4 *)(param_1 + 4);
  *(undefined4 *)((int)this + 8) = *(undefined4 *)(param_1 + 8);
  *(undefined4 *)((int)this + 0xc) = *(undefined4 *)(param_1 + 0xc);
  *(undefined4 *)((int)this + 0x10) = *(undefined4 *)(param_1 + 0x10);
  *(undefined4 *)((int)this + 0x14) = *(undefined4 *)(param_1 + 0x14);
  *(undefined4 *)((int)this + 0x18) = *(undefined4 *)(param_1 + 0x18);
  *(undefined4 *)((int)this + 0x1c) = *(undefined4 *)(param_1 + 0x1c);
  *(undefined4 *)((int)this + 0x20) = *(undefined4 *)(param_1 + 0x20);
  *(undefined4 *)((int)this + 0x24) = *(undefined4 *)(param_1 + 0x24);
  *(undefined4 *)((int)this + 0x28) = *(undefined4 *)(param_1 + 0x28);
  *(undefined4 *)((int)this + 0x2c) = *(undefined4 *)(param_1 + 0x2c);
  SexyWidget_SetMatrix((undefined4 *)((int)this + 0x30));
  *(undefined4 *)(extraout_EDX + 0x40) = *(undefined4 *)(param_1 + 0x40);
  *(undefined4 *)(extraout_EDX + 0x44) = *(undefined4 *)(param_1 + 0x44);
  *(undefined1 *)(extraout_EDX + 0x48) = *(undefined1 *)(param_1 + 0x48);
  *(undefined1 *)(extraout_EDX + 0x49) = *(undefined1 *)(param_1 + 0x49);
  return extraout_EDX;
}


