/*
 * Function: Graphics_ProcessTextureBlend
 * Address: 00476580
 * Category: graphics
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


int __fastcall Graphics_ProcessTextureBlend(int *param_1)

{
  ushort uVar1;
  uint uVar2;
  char cVar3;
  int iVar4;
  void *pvVar5;
  ushort *puVar6;
  ushort *puVar7;
  uint *puVar8;
  uint *puVar9;
  uint *local_14;
  int local_10;
  int local_c;
  uint *local_8;
  
  if (param_1[6] == 0) {
    if (param_1[0x13] == 0) {
      iVar4 = MemoryImage_GetPixelData((int)param_1);
      return iVar4;
    }
    if (((char)param_1[0x14] != '\0') || (cVar3 = (**(code **)(*param_1 + 0x9c))(), cVar3 == '\0'))
    {
      return 0;
    }
    pvVar5 = operator_new(param_1[2] * param_1[1] * 4 + 4);
    param_1[6] = (int)pvVar5;
    *(undefined4 *)((int)pvVar5 + param_1[2] * param_1[1] * 4) = 0x4beefade;
    if (param_1[0x2c] == 0x10) {
      puVar6 = (ushort *)param_1[0x20];
      local_8 = (uint *)param_1[6];
      local_14 = (uint *)0x0;
      if (0 < param_1[2]) {
        do {
          local_c = 0;
          puVar7 = puVar6;
          if (0 < param_1[1]) {
            do {
              uVar1 = *puVar7;
              iVar4 = param_1[0x12];
              puVar7 = puVar7 + 1;
              *local_8 = (((uint)(uVar1 >> ((byte)*(undefined4 *)(iVar4 + 0x20) & 0x1f)) <<
                           (8U - (char)*(undefined4 *)(iVar4 + 0x14) & 0x1f) | 0xffffff00) << 8 |
                         (uint)(uVar1 >> ((byte)*(undefined4 *)(iVar4 + 0x24) & 0x1f)) <<
                         (8U - (char)*(undefined4 *)(iVar4 + 0x18) & 0x1f) & 0xff) << 8 |
                         (uint)(uVar1 >> ((byte)*(undefined4 *)(iVar4 + 0x28) & 0x1f)) <<
                         (8U - (char)*(undefined4 *)(iVar4 + 0x1c) & 0x1f) & 0xff;
              local_8 = local_8 + 1;
              local_c = local_c + 1;
            } while (local_c < param_1[1]);
          }
          puVar6 = puVar6 + param_1[0x1b] / 2;
          local_14 = (uint *)((int)local_14 + 1);
        } while ((int)local_14 < param_1[2]);
        (**(code **)(*param_1 + 0xa0))();
        return param_1[6];
      }
    }
    else if (param_1[0x2c] == 0x20) {
      local_14 = (uint *)param_1[6];
      puVar8 = (uint *)param_1[0x20];
      local_8 = (uint *)0x0;
      if (0 < param_1[2]) {
        do {
          local_10 = 0;
          puVar9 = puVar8;
          if (0 < param_1[1]) {
            do {
              uVar2 = *puVar9;
              iVar4 = param_1[0x12];
              puVar9 = puVar9 + 1;
              *local_14 = (((uVar2 >> ((byte)*(undefined4 *)(iVar4 + 0x20) & 0x1f)) <<
                            (8U - (char)*(undefined4 *)(iVar4 + 0x14) & 0x1f) | 0xffffff00) << 8 |
                          (uVar2 >> ((byte)*(undefined4 *)(iVar4 + 0x24) & 0x1f)) <<
                          (8U - (char)*(undefined4 *)(iVar4 + 0x18) & 0x1f) & 0xff) << 8 |
                          (uVar2 >> ((byte)*(undefined4 *)(iVar4 + 0x28) & 0x1f)) <<
                          (8U - (char)*(undefined4 *)(iVar4 + 0x1c) & 0x1f) & 0xff;
              local_14 = local_14 + 1;
              local_10 = local_10 + 1;
            } while (local_10 < param_1[1]);
          }
          puVar8 = puVar8 + ((int)(param_1[0x1b] + (param_1[0x1b] >> 0x1f & 3U)) >> 2);
          local_8 = (uint *)((int)local_8 + 1);
        } while ((int)local_8 < param_1[2]);
      }
    }
    (**(code **)(*param_1 + 0xa0))();
  }
  return param_1[6];
}


