/*
 * Function: Graphics_ProcessImageTransform
 * Address: 00479130
 * Category: graphics
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __thiscall
Graphics_ProcessImageTransform
          (void *this,int param_1,undefined4 param_2,undefined4 param_3,int *param_4)

{
  int iVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  undefined4 *puVar5;
  int extraout_EDX;
  ulonglong uVar6;
  ulonglong uVar7;
  int local_24;
  int local_20;
  int local_1c;
  int local_18;
  int local_14;
  int local_10;
  int local_c;
  int local_8;
  
  uVar6 = Math_FloatToUInt64();
  uVar7 = Math_FloatToUInt64();
  iVar1 = *param_4;
  iVar3 = SexyWidget_GetWidth(param_1);
  if (iVar1 + extraout_EDX <= iVar3) {
    iVar3 = param_4[3];
    iVar2 = param_4[1];
    iVar4 = SexyWidget_GetHeight(param_1);
    if (iVar3 + iVar2 <= iVar4) {
      local_14 = (int)uVar6;
      local_10 = (int)uVar7;
      local_8 = iVar3;
      Collision_CalculateIntersection(&local_14,&local_24,(int *)((int)this + 0x10));
      local_14 = (iVar1 - (int)uVar6) + local_24;
      local_10 = (iVar2 - (int)uVar7) + local_20;
      local_c = local_1c;
      local_8 = local_18;
      if ((0 < local_1c) && (0 < local_18)) {
        puVar5 = (undefined4 *)((int)this + 0x20);
        if (*(char *)((int)this + 0x48) == '\0') {
          puVar5 = &DAT_005a2378;
        }
        (**(code **)(**(int **)((int)this + 4) + 0x1c))
                  (param_1,local_24,local_20,&local_14,puVar5,*(undefined4 *)((int)this + 0x44));
      }
    }
  }
  return;
}


