/*
 * Function: Graphics_BindTextureUnit
 * Address: 00476490
 * Category: graphics
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall Graphics_BindTextureUnit(int param_1,uint param_2,int param_3,int param_4)

{
  void *pvVar1;
  
  System_HandleShutdown(param_1,param_2);
  if ((0 < param_3) && (0 < param_4)) {
    pvVar1 = operator_new(param_3 * param_4 * 4);
    *(void **)(param_1 + 4) = pvVar1;
    *(int *)(param_1 + 8) = param_3;
    *(int *)(param_1 + 0xc) = param_4;
  }
  return;
}


