/*
 * Function: Graphics_DrawFilledRect
 * Address: 00478d70
 * Category: graphics
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __thiscall Graphics_DrawFilledRect(void *this,int param_1,int param_2,int param_3,int param_4)

{
  int iVar1;
  ulonglong uVar2;
  ulonglong uVar3;
  int local_34;
  int local_30;
  int local_2c;
  int local_28;
  int local_24;
  int local_20;
  int local_1c;
  int local_18;
  int local_14;
  int local_10;
  int local_c;
  int local_8;
  
  if (*(int *)((int)this + 0x2c) != 0) {
    uVar2 = Math_FloatToUInt64();
    local_34 = (int)uVar2;
    uVar3 = Math_FloatToUInt64();
    local_30 = (int)uVar3;
    local_2c = param_3;
    iVar1 = param_3 + 1;
    local_8 = param_4 + 1;
    local_28 = param_4;
    local_14 = (int)uVar2;
    local_10 = local_30;
    local_c = iVar1;
    Collision_CalculateIntersection(&local_14,&local_24,(int *)((int)this + 0x10));
    if ((((local_14 == local_24) && (local_10 == local_20)) && (iVar1 == local_1c)) &&
       (local_8 == local_18)) {
      (**(code **)(**(int **)((int)this + 4) + 0xc))
                (&local_34,(int)this + 0x20,*(undefined4 *)((int)this + 0x44));
      return;
    }
    Graphics_FillRect(this,param_1,param_2,iVar1,1);
    Graphics_FillRect(this,param_1,param_2 + param_4,iVar1,1);
    Graphics_FillRect(this,param_1,param_2 + 1,1,param_4 + -1);
    Graphics_FillRect(this,param_1 + param_3,param_2 + 1,1,param_4 + -1);
  }
  return;
}


