/*
 * Function: Graphics_ProcessRenderQueue
 * Address: 00471cf0
 * Category: graphics
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __thiscall Graphics_ProcessRenderQueue(void *this,undefined4 param_1)

{
  *(undefined4 *)((int)this + 0x18) = param_1;
  *(undefined1 *)((int)this + 0x2c) = 0;
  return;
}


