/*
 * Function: ParticleSystem_Render
 * Address: 00429f50
 * Category: graphics
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __thiscall ParticleSystem_Render(void *this,void *param_1)

{
  SexyWidget_ProcessEffects(this,param_1);
  SexyWidget_GetColor(param_1,*(int **)((int)this + 0x144));
  if (*(int **)((int)this + 0x148) != (int *)0x0) {
    SexyWidget_GetColor(param_1,*(int **)((int)this + 0x148));
  }
  if (*(int **)((int)this + 0x14c) != (int *)0x0) {
    SexyWidget_GetColor(param_1,*(int **)((int)this + 0x14c));
  }
  if (*(int **)((int)this + 0x140) != (int *)0x0) {
    SexyWidget_GetColor(param_1,*(int **)((int)this + 0x140));
  }
  SexyWidget_GetColor(param_1,*(int **)((int)this + 0x150));
  SexyWidget_GetColor(param_1,*(int **)((int)this + 0x154));
  SexyWidget_GetColor(param_1,*(int **)((int)this + 0x124));
  SexyWidget_GetColor(param_1,*(int **)((int)this + 0x128));
  SexyWidget_GetColor(param_1,*(int **)((int)this + 300));
  SexyWidget_GetColor(param_1,*(int **)((int)this + 0x130));
  SexyWidget_GetColor(param_1,*(int **)((int)this + 0x134));
  SexyWidget_GetColor(param_1,*(int **)((int)this + 0x138));
  SexyWidget_GetColor(param_1,*(int **)((int)this + 0x13c));
  return;
}


