/*
 * Function: Renderer_Scale
 * Address: 004ccb10
 * Category: graphics
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall
Renderer_Scale(int param_1,byte *param_2,void *param_3,byte *param_4,byte *param_5,
              undefined4 param_6,int param_7)

{
  uint uVar1;
  undefined4 *puVar2;
  int extraout_ECX;
  uint extraout_ECX_00;
  uint uVar3;
  uint extraout_ECX_01;
  int iVar4;
  int extraout_ECX_02;
  int extraout_ECX_03;
  int extraout_ECX_04;
  int iVar5;
  int extraout_ECX_05;
  byte *extraout_EDX;
  byte *extraout_EDX_00;
  byte *extraout_EDX_01;
  uint extraout_EDX_02;
  uint extraout_EDX_03;
  uint extraout_EDX_04;
  byte *pbVar6;
  byte *pbVar7;
  undefined4 *puVar8;
  size_t sVar9;
  byte *pbVar10;
  undefined8 uVar11;
  uint unaff_retaddr;
  char *pcVar12;
  undefined4 *in_stack_ffffffa0;
  undefined4 *in_stack_ffffffa4;
  byte *local_24;
  int *local_20;
  size_t local_1c;
  uint local_18;
  int local_14;
  byte *local_10;
  byte local_9;
  uint local_8;
  
  local_8 = DAT_00569f5c ^ unaff_retaddr;
  pbVar6 = (byte *)0x0;
  local_10 = (byte *)0x0;
  local_14 = 0;
  local_18 = 0;
  if (param_4 != (byte *)0x0) {
    uVar11 = Renderer_Translate(&local_24,param_3,param_4,(int *)&local_24);
    param_2 = (byte *)((ulonglong)uVar11 >> 0x20);
    iVar5 = (int)uVar11;
    param_1 = extraout_ECX;
    if (iVar5 != 0) {
      if (((param_5 == (byte *)0x0) || (*param_5 == 0)) || (param_7 == -1)) {
        Renderer_Rotate(extraout_ECX,param_2,param_3,local_24,param_5,0);
        CPU_Instruction13(extraout_ECX_05,extraout_EDX_04,(int)param_3,(int)local_24);
        Exception_SetMessage((void *)(local_8 ^ unaff_retaddr),in_stack_ffffffa0,in_stack_ffffffa4);
        return;
      }
      CPU_Instruction13(extraout_ECX,(uint)local_24,(int)param_3,(int)local_24);
      if (0 < param_7) {
        Exception_Release(&stack0xffffffa0,"Unknown zTXt compression type %d");
        CPU_Instruction21(&stack0xffffffa0,extraout_EDX,(uint)param_3,&stack0xffffffa0);
        param_7 = 0;
      }
      local_20 = (int *)((int)param_3 + 0x74);
      *(undefined4 *)((int)param_3 + 0x78) = param_6;
      *local_20 = (int)param_5;
      sVar9 = 0x10;
      *(undefined4 *)((int)param_3 + 0x84) = *(undefined4 *)((int)param_3 + 0xb0);
      *(undefined4 *)((int)param_3 + 0x80) = *(undefined4 *)((int)param_3 + 0xac);
      local_1c = 0x10;
      do {
        uVar1 = PNG_WriteIEND(local_20,0);
        if (uVar1 != 0) {
          pcVar12 = *(char **)((int)param_3 + 0x8c);
          if (pcVar12 == (char *)0x0) {
            pcVar12 = "zlib error";
          }
          CPU_Instruction20(extraout_ECX_00,extraout_EDX_00,(int)param_3,pcVar12);
        }
        if (*(int *)((int)param_3 + 0x84) == 0) {
          if (*(int *)((int)param_3 + 0x78) == 0) break;
          if ((int)local_18 <= local_14) {
            local_24 = (byte *)(local_18 << 2);
            local_18 = local_14 + 4;
            if (pbVar6 == (byte *)0x0) {
              pbVar6 = (byte *)CPU_Instruction12((int)param_3,sVar9);
              local_10 = pbVar6;
            }
            else {
              local_10 = (byte *)CPU_Instruction12((int)param_3,sVar9);
              pbVar7 = pbVar6;
              pbVar10 = local_10;
              for (uVar1 = (uint)local_24 >> 2; uVar1 != 0; uVar1 = uVar1 - 1) {
                *(undefined4 *)pbVar10 = *(undefined4 *)pbVar7;
                pbVar7 = pbVar7 + 4;
                pbVar10 = pbVar10 + 4;
              }
              for (uVar1 = (uint)local_24 & 3; uVar1 != 0; uVar1 = uVar1 - 1) {
                *pbVar10 = *pbVar7;
                pbVar7 = pbVar7 + 1;
                pbVar10 = pbVar10 + 1;
              }
              CPU_Instruction13(0,(uint)local_24,(int)param_3,(int)pbVar6);
              pbVar6 = local_10;
              sVar9 = local_1c;
            }
          }
          puVar2 = (undefined4 *)CPU_Instruction12((int)param_3,*(size_t *)((int)param_3 + 0xb0));
          *(undefined4 **)(pbVar6 + (sVar9 - 0x10)) = puVar2;
          uVar1 = *(uint *)((int)param_3 + 0xb0);
          puVar8 = *(undefined4 **)((int)param_3 + 0xac);
          for (uVar3 = uVar1 >> 2; uVar3 != 0; uVar3 = uVar3 - 1) {
            *puVar2 = *puVar8;
            puVar8 = puVar8 + 1;
            puVar2 = puVar2 + 1;
          }
          for (uVar1 = uVar1 & 3; uVar1 != 0; uVar1 = uVar1 - 1) {
            *(undefined1 *)puVar2 = *(undefined1 *)puVar8;
            puVar8 = (undefined4 *)((int)puVar8 + 1);
            puVar2 = (undefined4 *)((int)puVar2 + 1);
          }
          local_14 = local_14 + 1;
          sVar9 = local_1c + 4;
          *(undefined4 *)((int)param_3 + 0x84) = *(undefined4 *)((int)param_3 + 0xb0);
          *(undefined4 *)((int)param_3 + 0x80) = *(undefined4 *)((int)param_3 + 0xac);
          pbVar6 = local_10;
          local_1c = sVar9;
        }
      } while (*(int *)((int)param_3 + 0x78) != 0);
      sVar9 = local_14 * 4 + 0x10;
      local_1c = sVar9;
      do {
        while( true ) {
          local_24 = (byte *)PNG_WriteIEND(local_20,4);
          if ((local_24 != (byte *)0x0) && (local_24 != (byte *)0x1)) {
            pcVar12 = *(char **)((int)param_3 + 0x8c);
            if (pcVar12 == (char *)0x0) {
              pcVar12 = "zlib error";
            }
            CPU_Instruction20(extraout_ECX_01,extraout_EDX_01,(int)param_3,pcVar12);
          }
          uVar1 = local_18;
          if ((*(int *)((int)param_3 + 0x84) != 0) || (local_24 != (byte *)0x0)) break;
          if ((int)local_18 <= local_14) {
            uVar3 = local_18 << 2;
            local_18 = local_14 + 4;
            if (pbVar6 == (byte *)0x0) {
              pbVar6 = (byte *)CPU_Instruction12((int)param_3,sVar9);
              local_10 = pbVar6;
            }
            else {
              local_24 = pbVar6;
              local_10 = (byte *)CPU_Instruction12((int)param_3,sVar9);
              pbVar7 = local_10;
              for (uVar1 = uVar1 & 0x3fffffff; uVar1 != 0; uVar1 = uVar1 - 1) {
                *(undefined4 *)pbVar7 = *(undefined4 *)pbVar6;
                pbVar6 = pbVar6 + 4;
                pbVar7 = pbVar7 + 4;
              }
              for (iVar4 = 0; iVar4 != 0; iVar4 = iVar4 + -1) {
                *pbVar7 = *pbVar6;
                pbVar6 = pbVar6 + 1;
                pbVar7 = pbVar7 + 1;
              }
              CPU_Instruction13(0,uVar3,(int)param_3,(int)local_24);
              pbVar6 = local_10;
              sVar9 = local_1c;
            }
          }
          puVar2 = (undefined4 *)CPU_Instruction12((int)param_3,*(size_t *)((int)param_3 + 0xb0));
          *(undefined4 **)(pbVar6 + (sVar9 - 0x10)) = puVar2;
          uVar1 = *(uint *)((int)param_3 + 0xb0);
          puVar8 = *(undefined4 **)((int)param_3 + 0xac);
          for (uVar3 = uVar1 >> 2; uVar3 != 0; uVar3 = uVar3 - 1) {
            *puVar2 = *puVar8;
            puVar8 = puVar8 + 1;
            puVar2 = puVar2 + 1;
          }
          for (uVar1 = uVar1 & 3; uVar1 != 0; uVar1 = uVar1 - 1) {
            *(undefined1 *)puVar2 = *(undefined1 *)puVar8;
            puVar8 = (undefined4 *)((int)puVar8 + 1);
            puVar2 = (undefined4 *)((int)puVar2 + 1);
          }
          local_14 = local_14 + 1;
          sVar9 = local_1c + 4;
          *(undefined4 *)((int)param_3 + 0x84) = *(undefined4 *)((int)param_3 + 0xb0);
          *(undefined4 *)((int)param_3 + 0x80) = *(undefined4 *)((int)param_3 + 0xac);
          pbVar6 = local_10;
          local_1c = sVar9;
        }
      } while (local_24 != (byte *)0x1);
      uVar1 = *(uint *)((int)param_3 + 0xb0);
      iVar4 = uVar1 * local_14;
      if (*(uint *)((int)param_3 + 0x84) < uVar1) {
        iVar4 = iVar4 + (uVar1 - *(uint *)((int)param_3 + 0x84));
      }
      Renderer_SetViewport((uint)param_3,(byte *)&DAT_00567d5c,iVar5 + 2 + iVar4);
      Renderer_SetProjection((uint)param_3,param_4,iVar5 + 1);
      local_9 = (byte)param_7;
      Renderer_SetProjection((uint)param_3,&local_9,1);
      iVar5 = extraout_ECX_02;
      uVar1 = extraout_EDX_02;
      if (0 < local_14) {
        iVar4 = 0;
        do {
          Renderer_SetProjection
                    ((uint)param_3,*(byte **)(pbVar6 + iVar4 * 4),*(uint *)((int)param_3 + 0xb0));
          CPU_Instruction13(extraout_ECX_03,*(uint *)(pbVar6 + iVar4 * 4),(int)param_3,
                            *(uint *)(pbVar6 + iVar4 * 4));
          iVar4 = iVar4 + 1;
          iVar5 = extraout_ECX_04;
          uVar1 = extraout_EDX_03;
        } while (iVar4 < local_14);
      }
      if (local_18 != 0) {
        CPU_Instruction13(iVar5,uVar1,(int)param_3,(int)pbVar6);
      }
      if (*(uint *)((int)param_3 + 0x84) < *(uint *)((int)param_3 + 0xb0)) {
        Renderer_SetProjection
                  ((uint)param_3,*(byte **)((int)param_3 + 0xac),
                   *(uint *)((int)param_3 + 0xb0) - *(uint *)((int)param_3 + 0x84));
      }
      Renderer_SetModelView((uint)param_3);
      PNG_CompressData((int)local_20);
      goto LAB_004ccefe;
    }
  }
  CPU_Instruction21(param_1,param_2,(uint)param_3,"Empty keyword in zTXt chunk");
LAB_004ccefe:
  Exception_SetMessage((void *)(local_8 ^ unaff_retaddr),in_stack_ffffffa0,in_stack_ffffffa4);
  return;
}


