/*
 * Function: Renderer_ProcessAlphaBlending
 * Address: 004152b0
 * Category: graphics
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __fastcall Renderer_ProcessAlphaBlending(undefined4 *param_1,uint param_2)

{
  void *local_10;
  undefined *puStack_c;
  undefined4 local_8;
  
  puStack_c = &DAT_005102e8;
  local_10 = ExceptionList;
  ExceptionList = &local_10;
  *param_1 = &PTR_Renderer_ProcessTexturing_0053154c;
  local_8 = 0;
  Renderer_ProcessDepthBuffer((int)param_1,param_2);
  *param_1 = &PTR_SexyWidget_UpdateProperties_0053129c;
  ExceptionList = local_10;
  return;
}


