/*
 * Function: Renderer_ProcessTexturing
 * Address: 00415280
 * Category: graphics
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


undefined4 * __fastcall Renderer_ProcessTexturing(undefined4 *param_1,uint param_2,byte param_3)

{
  int extraout_ECX;
  uint extraout_EDX;
  
  Renderer_ProcessAlphaBlending(param_1,param_2);
  if ((param_3 & 1) != 0) {
                    /* WARNING: Subroutine does not return */
    System_ShutdownHandler(extraout_ECX,extraout_EDX);
  }
  return param_1;
}


