/*
 * Function: Resource_UnloadSprites
 * Address: 0043f6f0
 * Category: graphics
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


void __thiscall Resource_UnloadSprites(void *this,void *param_1)

{
  int iVar1;
  undefined4 *puVar2;
  int iVar3;
  uint uVar4;
  ulonglong uVar5;
  char cVar6;
  int iVar7;
  char cVar8;
  undefined1 local_14 [16];
  
  if (*(int *)(*(int *)((int)this + 0x4c) + 0x184) <= *(int *)(*(int *)((int)this + 0x4c) + 0x17c))
  {
    if (*(int *)((int)this + 0x34) != 0) {
      SexyWidget_SetColorizeFlag2(param_1,1);
      iVar1 = 0xff - *(int *)((int)this + 0x34);
      puVar2 = (undefined4 *)CreateColor(local_14,0xff,iVar1,iVar1,0xff);
      SexyWidget_SetRectangle(param_1,puVar2);
    }
    cVar8 = '\0';
    uVar4 = (uint)*(byte *)((int)this + 0x30);
    uVar5 = Math_FloatToUInt64();
    iVar1 = (int)uVar5;
    cVar6 = '\x01';
    uVar5 = Math_FloatToUInt64();
    iVar3 = (int)uVar5;
    uVar5 = Math_FloatToUInt64();
    DrawSprite(*(void **)((int)this + 0x60),param_1,(int)uVar5,iVar3,cVar6,iVar1,uVar4,cVar8);
    cVar8 = '\0';
    iVar7 = 0;
    uVar5 = Math_FloatToUInt64();
    iVar1 = (int)uVar5;
    cVar6 = '\x01';
    uVar5 = Math_FloatToUInt64();
    iVar3 = (int)uVar5;
    uVar5 = Math_FloatToUInt64();
    DrawSprite(*(void **)((int)this + 0x70),param_1,(int)uVar5,iVar3,cVar6,iVar1,iVar7,cVar8);
    cVar8 = '\0';
    iVar7 = 0;
    uVar5 = Math_FloatToUInt64();
    iVar1 = (int)uVar5;
    cVar6 = '\x01';
    uVar5 = Math_FloatToUInt64();
    iVar3 = (int)uVar5;
    uVar5 = Math_FloatToUInt64();
    DrawSprite(*(void **)((int)this + 0x70),param_1,(int)uVar5,iVar3,cVar6,iVar1,iVar7,cVar8);
    SexyWidget_SetColorizeFlag2(param_1,0);
  }
  return;
}


