/*
 * Function: SexyFramework_DrawWidget
 * Address: 00487440
 * Category: graphics
 * Generated by Ghidra Bulk Exporter
 */

#include "../heavy_weapon_deluxe.h"


undefined4 * __thiscall SexyFramework_DrawWidget(void *this,int param_1)

{
  void *local_10;
  undefined *puStack_c;
  undefined4 local_8;
  
  local_8 = 0xffffffff;
  puStack_c = &DAT_00514db8;
  local_10 = ExceptionList;
  ExceptionList = &local_10;
  Game_ParticleSystem_Constructor((undefined4 *)this);
  local_8 = 0;
  *(undefined ***)this = &PTR_PowerUp_DrawSystem_005338ac;
  *(int *)((int)this + 0x44) = param_1;
  *(undefined4 *)((int)this + 0x18) = 0;
  *(undefined4 *)((int)this + 0x28) = 0;
  *(undefined4 *)((int)this + 0x2c) = 0;
  *(undefined4 *)((int)this + 0x34) = 0;
  *(undefined4 *)((int)this + 0x38) = 0;
  *(undefined4 *)((int)this + 0x3c) = 0;
  *(undefined1 *)((int)this + 0x31) = 0;
  *(undefined1 *)((int)this + 0x32) = 0;
  *(undefined1 *)((int)this + 0x40) = 0;
  *(undefined1 *)((int)this + 0x30) = 0;
  *(undefined1 *)((int)this + 0x33) = 0;
  *(undefined4 *)((int)this + 0x20) = 0;
  *(undefined4 *)((int)this + 0x24) = 0;
  *(undefined4 *)((int)this + 0x1c) = 0;
  STL_String_AssignmentOperator(param_1);
  ExceptionList = local_10;
  return (undefined4 *)this;
}


